lab_3
Dovgalyuk/Algorithms pull request #1008
Opened 2024-11-07 17:56 UTC by Roman375757752

Я же правильно понял задание, то что- 
4          // Число вершин
0 1 0 0    // Рёбра из вершины 0
0 0 1 1    // Рёбра из вершины 1
1 0 0 1    // Рёбра из вершины 2
0 1 0 0    // Рёбра из вершины 3
И то есть у нас соединение выглядит так: 
![Screenshot_29](https://github.com/user-attachments/assets/e87a6a82-66c5-4c0b-bd90-afe26f6873c3)

2024-11-08 06:04 UTC, Dovgalyuk commented
Картинка неправильная. Стоит почитать про матрицу смежности.

2024-12-16 19:03 UTC, Roman375757752 commented
![image](https://github.com/user-attachments/assets/439387a5-1bf0-4682-95f7-35a5f841cea3)
Извините, такой рисунок?

2024-12-17 06:40 UTC, Dovgalyuk commented
Да, рисунок такой.

2024-12-19 05:31 UTC, Roman375757752 commented
Спасибо.

2024-12-19 06:11 UTC, Dovgalyuk requested changes

2024-12-19 06:11 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +    for (int i = 0; i < num_vertices; i++) output << vector_get(distances, i) << endl;
Можно это записать в else предыдущего условия. А уже после всего ветвления освобождать память, чтобы не дублировать эти строчки.

2024-12-19 06:11 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +    queue->data.push_back(data);  // Добавляем элемент в конец очереди
Должен быть кольцевой буфер. Чтобы освободившиеся в начале массива элементы заполнялись новыми из хвоста очереди.

2024-12-20 06:11 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +    queue->rear = 0;
rear можно вычислить из front и size.

2024-12-23 09:09 UTC, Dovgalyuk commented
Принято.

2024-12-23 09:09 UTC, closed without merging