Lab4
Dovgalyuk/Algorithms pull request #1009
Opened 2024-11-07 18:39 UTC by bvaleksch

![Screenshot from 2024-11-07 21-29-44](https://github.com/user-attachments/assets/74da1287-2c5c-4569-8570-e1dc4c87ad43)
![Screenshot from 2024-11-07 21-34-48](https://github.com/user-attachments/assets/dfea5acb-f670-4bd3-ad7d-60c49ec37397)

2024-11-08 06:22 UTC, Dovgalyuk requested changes

2024-11-08 06:22 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +	Vector<edge*> edges;
В задании были списки смежности, от этого массива нужно избавиться.

2024-11-08 06:22 UTC, Dovgalyuk commented on Lab4CPP/lab4.cpp
> +int find(Vector<int> &vec, int ind)
Эффективная реализация должна ещё обновлять корневой узел для всех пройденных вершин.
Обычно она делается с помощью рекурсии.

2024-11-11 08:04 UTC, Dovgalyuk requested changes

2024-11-11 08:04 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +			vertices[ind]->index = ind;
Вершины перемешиваются, но при получении конкретной везде используется просто индекс в массиве. Тогда зачем у вершины есть индекс? Стоит его удалить.

2024-11-11 08:17 UTC, bvaleksch commented on LibraryCPPTemplate/graph.h
> +			vertices[ind]->index = ind;
void delete_edge(edge *e)
{
	if (!e)
		throw std::invalid_argument("[delete_edge] The pointer is nullptr");

	remove_edge(e->from->index, e->id);
	remove_edge(e->to->index, e->id);

	delete e;
}
	
Индекс мне нужен, при удалении ребра

2024-11-12 05:48 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +			vertices[ind]->index = ind;
Можно просто список для вершины переместить прямо в структуру с ней.

2024-11-13 11:39 UTC, Dovgalyuk commented
Принято.

* Разработать интерфейс (набор функций) для ассоциативного массива, который хранит пары (ключ)строка -> (значение)строка. Поддерживаемые операции: добавить пару ключ-значение, найти значение по ключу, удалить значение по ключу.
* Реализовать контейнер на основе хэш-таблицы с открытой адресацией, реализующий разработанный интерфейс. Таблица должна поддерживать расширение при большой доле заполненных ячеек.
* Создать тест для проверки работы контейнера. Программа должна включать в себя нагрузочное тестирование для исключения ошибок, приводящих к сложности работы O(N*N) при поиске, удалении или добавлении значений.
* Написать генератор входных данных различного объема для этого контейнера.
* Сравнить скорость выполнения операции добавления в контейнер содержимого файла со стандартным контейнером std::unordered_map при различных объемах данных. Построить график зависимости времени работы от объёма входных данных и оценить характер зависимости.
* Добавить тест в CMakeLists.txt, который запускает разработанную программу.

2024-11-13 11:39 UTC, closed without merging