Lab3
Dovgalyuk/Algorithms pull request #1016
Opened 2024-11-07 21:44 UTC by nikitagrmv

2024-11-08 06:15 UTC, Dovgalyuk requested changes

2024-11-08 06:15 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +            lbr[current.x][current.y] = 'x';
Лучше помечать клетку во время добавления в очередь, потому что иначе в очереди будут одновременно находиться одни и те же координаты, занимая лишнюю память.

2024-11-08 06:15 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +    ifstream input_file("input.txt");
Имена файлов нужно получать из аргументов командной строки.

2024-11-08 06:15 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        list->tail = new_item;
Эта строчка дублируется.

2024-11-08 06:15 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    size_t size;
Размер списку не нужен.

2024-11-10 22:09 UTC, nikitagrmv commented on LibraryCPP/list.cpp
> +        list->tail = new_item;
Не очень понимаю, какая именно строчка дублируется. В этом фрагменте после проверки на пустоту обновляется указатель на начало списка, а затем указатель на конец списка. Так как изначально список пустой, head и tail указывают на один и тот же элемент, который добавляется и является единственным.

2024-11-11 07:55 UTC, Dovgalyuk requested changes

2024-11-11 07:55 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +                (lbr[new_x][new_y] == '.' || lbr[new_x][new_y] == 'X')) {
А как здесь он может дойти до 'X'?

2024-11-11 07:55 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        list->tail = new_item;
tail одинаково записывается в обеих частях ветвления.

2024-11-12 06:48 UTC, Dovgalyuk commented
Принято.

* Разработать программный интерфейс модуля (заголовки функций) библиотеки LibraryCPPTemplate для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины,
получить пометки всех вершин в виде вектора.
* Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
* Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде матрицы смежности в контейнере Vector библиотеки LibraryCPPTemplate.
* Разработать и добавить в проект LibraryCPPTemplate программу, тестирующую работу библиотеки для графа.
* Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать в нем количество компонентов связности с помощью обхода в глубину.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

2024-11-12 06:48 UTC, closed without merging