lab3
Dovgalyuk/Algorithms pull request #1022
Opened 2024-11-09 14:01 UTC by Ilya-Vdovskiy

2024-11-11 05:46 UTC, Dovgalyuk requested changes

2024-11-11 05:46 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    ListItem* newItem = new ListItem;
Что будет с этим указателем, если head==nullptr?

2024-11-12 05:44 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    if (!list->head) {
Может ли это условие сработать?

2024-11-12 12:17 UTC, Ilya-Vdovskiy commented on LibraryCPP/list.cpp
> +    if (!list->head) {
ну если у нас на вход придет пустой лист, то сработает и вызовется функция которая поставит элемент как новую голову. Сделал как дополнительную проверку на всякий случай

2024-11-13 12:06 UTC, Ilya-Vdovskiy commented on LibraryCPP/list.cpp
> +    if (!list->head) {
понял, исправил

2024-11-14 06:15 UTC, Dovgalyuk commented
Принято.

* Разработать программный интерфейс модуля (заголовки функций) библиотеки LibraryCPPTemplate для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины,
получить пометки всех вершин в виде вектора.
* Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
* Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List библиотеки LibraryCPPTemplate.
* Разработать и добавить в проект LibraryCPPTemplate программу, тестирующую работу библиотеки для графа.
* Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать в нем количество компонентов связности с помощью обхода в глубину.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

2024-11-14 06:15 UTC, closed without merging