zadanie4
Dovgalyuk/Algorithms pull request #103
Opened 2020-11-30 14:59 UTC by sergeychaliy2

2020-12-01 06:22 UTC, Dovgalyuk commented
Опять много временных файлов.

2020-12-01 12:24 UTC, Dovgalyuk requested changes

2020-12-01 12:24 UTC, Dovgalyuk commented on TestArrayCPP/main.cpp
> +			if ((x + 1) < numRow && (x + 1) >= 0 && !visited[x + 1][y] &&
Вряд ли при инкременте могло получиться меньше 0.

2020-12-01 12:24 UTC, Dovgalyuk commented on TestArrayCPP/main.cpp
> +			while (path[x][y] != 2) {
Восстановление пути стоит вынести из основного цикла. К тому же, тут оно ещё и может выполниться многократно.

2020-12-02 07:38 UTC, Dovgalyuk requested changes

2020-12-02 07:38 UTC, Dovgalyuk commented on TestArrayCPP/main.cpp
> +			if ((x - 1) < numRow && (x - 1) >= 0 && !visited[x - 1][y] &&
При вычитании нет смысла сравнивать на переполнение вверх.

2020-12-03 06:12 UTC, Dovgalyuk commented
Осталось привести очередь в порядок.

2020-12-03 09:36 UTC, Dovgalyuk commented
Там есть комментарий.

Ещё много общего кода, который можно было бы вынести в функции.

2020-12-03 10:03 UTC, sergeychaliy2 commented
> Там есть комментарий.
> 
> Ещё много общего кода, который можно было бы вынести в функции.

2020-12-03 10:03 UTC, sergeychaliy2 commented
Я что то нажал нечаяно

2020-12-04 06:26 UTC, Dovgalyuk commented
Улучшить надо реализацию очереди.

2020-12-04 11:00 UTC, Dovgalyuk requested changes

2020-12-04 11:00 UTC, Dovgalyuk commented on LibraryCPP/queue.h
> +	moveBetweenStacks(s1, s2);	//Переносим все элементы во 2 стек
Переносить нужно только если стек 2 опустел.

2020-12-07 05:53 UTC, Dovgalyuk requested changes

2020-12-07 05:53 UTC, Dovgalyuk commented on LibraryCPP/queue.h
> +		if (s1.empty())
И вот это не совсем верно.

2020-12-07 10:45 UTC, Dovgalyuk commented
1. Разработать интерфейс (набор функций) для контейнера для хранения множества значений строк с возможностью быстрого поиска. Поддерживаемые операции: добавить значение, найти значение, удалить значение.
    2. Реализовать контейнер на основе АВЛ-дерева.
    3. Реализовать функцию проверки баланса АВЛ-дерева и в отладочном режиме вызывать ее после каждого добавления/удаления.
    4. Написать генератор входных данных различного объема для этого контейнера. Сравнить скорость выполнения операции добавления в контейнер содержимого файла для АВЛ-дерева и для std::set при различных объемах данных.

2020-12-07 10:45 UTC, closed without merging