Lab4
Dovgalyuk/Algorithms pull request #1032
Opened 2024-11-11 10:48 UTC by tolstosup

2024-11-12 06:29 UTC, Dovgalyuk requested changes

2024-11-12 06:29 UTC, Dovgalyuk commented on Lab4CPP/lab4.cpp
> +std::pair<unsigned int, Vector<std::string>> find_min_path(Graph<std::string, unsigned int> graph, size_t start, size_t end) {
Граф стоит передавать по ссылке.

2024-11-12 06:29 UTC, Dovgalyuk commented on Lab4CPP/lab4.cpp
> +    Graph<std::string, unsigned int> graph;
Объявление типа многократно повторяется, стоит сделать typedef.

2024-11-12 06:29 UTC, Dovgalyuk commented on Lab4CPP/lab4.cpp
> +                queue.push({ new_distance, neighbor_i });
В очередь вершины могут попадать повторно, но нет проверки, чтобы уже обработанные вершины не обрабатывались снова.

2024-11-12 06:29 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +#include "Edge.h"
А зачем в отдельные файлы выносить Vertex и Edge?

2024-11-12 06:29 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +    Vertex<V_type> add_vertex();
Стоит возвращать ссылку, а не копию структуры.

2024-11-12 06:29 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +    Vector<Vector<unsigned int>> get_matrix();
Тут стоит константную ссылку возвращать.

2024-11-12 06:29 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +    Vector<Edge<V_type, E_type>> edges;
Есть же матрица смежности. Рёбра и должны быть в ней.

2024-11-14 07:27 UTC, Dovgalyuk requested changes

2024-11-14 07:27 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +#define MATRIX Vector<Vector<Vector<Edge<E>>>>
Почему три вектора?

2024-11-14 07:27 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +    return matrix[a][b][edge_index].mark;
Между парой вершин может быть только одно ребро. И оно может отсутствовать.

2024-11-15 04:31 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +        return mark == E();
Пользователь может не согласиться, что это значение отвечает за отсутствие ребра.
Лучше в матрице хранить указатели на рёбра. И нулевой указатель будет означать отсутствие ребра.

2024-11-18 09:11 UTC, Dovgalyuk requested changes

2024-11-18 09:11 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +Vertex<V>& GRAPH::add_vertex() {
А нельзя просто следующую функцию вызвать?

2024-11-18 09:11 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +            matrix[i].push(nullptr);
resize разве не подойдёт?

2024-11-18 09:11 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +Vertex<V> GRAPH::add_vertex(V vertex_mark) {
Лучше ссылку возвращать (можно константную), а не копию.

2024-11-18 09:11 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +Edge<E>* GRAPH::delete_edge(size_t a, size_t b) {
Какой смысл в возвращаемом значении?

2024-11-18 09:11 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +    matrix[a][b] = new Edge<E>(edge_mark);
А если там уже что-то было?

2024-11-18 17:14 UTC, tolstosup commented on LibraryCPPTemplate/graph.h
> +            matrix[i].push(nullptr);
При использовании resize новые выделенные ячейки не инициализируются нулевыми указателями, при этом во время добавления нового ребра обрабатывается случай, когда между вершинами уже существует связь (значение данной ячейки матрицы смежности не равно нулевому указателю), поэтому при добавление нового ребра между вершинами, при заранее известном, что связи между ними нет, выбрасывается исключение о том, что вершины уже связаны.

2024-11-19 05:26 UTC, Dovgalyuk commented
Принято.

* Разработать интерфейс (набор функций) для контейнера для хранения множества значений строк с возможностью быстрого поиска. Поддерживаемые операции: добавить значение, найти значение, удалить значение.
* Реализовать контейнер на основе красно-чёрного дерева, реализующий разработанный интерфейс.
* Создать тест для проверки работы контейнера. Программа должна включать в себя нагрузочное тестирование для исключения ошибок, приводящих к сложности работы O(N*N) при поиске, удалении или добавлении значений.
* Написать генератор входных данных различного объема для этого контейнера.
* Сравнить скорость выполнения операции добавления в контейнер содержимого файла со стандартным контейнером std::set при различных объемах данных. Построить график зависимости времени работы от объёма входных данных и оценить характер зависимости.
* Добавить тест в CMakeLists.txt, который запускает разработанную программу.

2024-11-19 05:26 UTC, closed without merging