Баринов Дмитрий Задание 3
Dovgalyuk/Algorithms pull request #104
Opened 2020-12-01 17:21 UTC by Golden3oloto

Был реализован контейнер vector. На основе этого контейнера была написана очередь. С помощью этой очереди было сделано задание 3 на обход в ширину ориентированного графа.

2020-12-02 07:46 UTC, Dovgalyuk requested changes

2020-12-02 07:46 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +    }
Нужно реализовать кольцевой буфер, чтобы операция remove работала бы за время O(1).

2020-12-02 13:24 UTC, Golden3oloto commented on LibraryCPP/queue.cpp
> +    }
Переделал. Только я создал переменные не begin и end, а begin и size, потому что так проще.

2020-12-03 06:17 UTC, Dovgalyuk requested changes

2020-12-03 06:17 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +        vector_set(queue->vector, 0, data);
Мне кажется, здесь нужен begin.
Тогда обе строчки vector_set можно объединить.

2020-12-03 06:17 UTC, Dovgalyuk commented on LibraryCPP/vector.h
> +};
Определение структуры должно быть спрятано в cpp.

2020-12-03 08:06 UTC, Golden3oloto commented on LibraryCPP/queue.cpp
> +        vector_set(queue->vector, 0, data);
В первой строчки берётся остаток от деления на размер вектора, а строчка в условии else выполняется, когда размер вектора равен нулю. Я их смог объединил используя только тернарный оператор.

2020-12-03 08:09 UTC, Golden3oloto commented on LibraryCPP/vector.h
> +};
Сделал, только использование указателя на тип неполного класса не допускается, и мне пришлось в Queue создать ещё одну переменную - vector_size.

2020-12-03 09:39 UTC, Dovgalyuk requested changes

2020-12-03 09:39 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +    size_t vector_size;
почему бы не использовать функцию vector_size(vector)?

2020-12-03 09:39 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +    queue->queue_size++;
Да, я перепутал верхнее условие. Тогда раньше было нормально.

2020-12-03 11:23 UTC, Golden3oloto commented on LibraryCPP/queue.cpp
> +    size_t vector_size;
Да, простите, совсем забыл. Исправил.

2020-12-03 11:23 UTC, Golden3oloto commented on LibraryCPP/queue.cpp
> +    queue->queue_size++;
Вернул к тому, что было.

2020-12-03 11:35 UTC, Dovgalyuk commented
1. Разработать интерфейс (набор функций) для ассоциативного массива, который хранит пары (ключ)строка -> (значение)строка. Поддерживаемые операции: добавить пару ключ-значение, найти значение по ключу, удалить значение по ключу.
    2. Реализовать ассоциативный массив на основе splay tree.
    3. Написать генератор входных данных различного объема для этого контейнера. Сравнить скорость выполнения операций добавления в контейнер и поиска содержимого файла для splay tree и для std::map при различных объемах данных.
    4. Построить зависимость высоты дерева от времени при последовательном выполнении множества операций поиска

2020-12-03 11:35 UTC, closed without merging