Lab1..
Dovgalyuk/Algorithms pull request #1041
Opened 2024-11-11 15:36 UTC by SaNiokIV

2024-11-12 06:47 UTC, Dovgalyuk requested changes

2024-11-12 06:47 UTC, Dovgalyuk commented on LAB1CPP/LAB1.cpp
> +        result += array_element;
Нужно найти сумму цифр, а просто чисел.

2024-11-13 11:59 UTC, SaNiokIV commented
поменял task1 на нахождение суммы цифр

2024-11-13 12:00 UTC, SaNiokIV commented on LAB1CPP/LAB1.cpp
> +        result += array_element;
поменял task1

2024-11-14 06:13 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Вычислить значение корректного арифметического выражения, использующего операции сложения, вычитания, умножения и деления. Программа должна учитывать приоритет операторов умножения и деления и использовать стек для хранения промежуточных результатов. Операндами в выражении являются неотрицательные целые числа.

Входные данные
```
1+2*3-1
```
Выходные данные
```
6
```

Входные данные
```
1*(2+3)
```
Выходные данные
```
5
```

2024-11-14 06:13 UTC, closed without merging