Lab2 Иванов Никита Александрович 3093
Dovgalyuk/Algorithms pull request #1042
Opened 2024-11-11 15:48 UTC by qwxxx

2024-11-11 16:10 UTC, qwxxx commented
https://github.com/Dovgalyuk/Algorithms/pull/919#issuecomment-2376023138 - ссылка на задание второй лабораторной работы

2024-11-12 07:07 UTC, Dovgalyuk commented
А где тесты для списка и стека?

2024-11-12 09:39 UTC, qwxxx commented
> А где тесты для списка и стека?

добавил

2024-11-13 11:10 UTC, Dovgalyuk requested changes

2024-11-13 11:10 UTC, Dovgalyuk commented on Lab2CPP/lab2.h
> +static std::vector<std::string> COMMANDS_WITH_VARS = {"bipush", "iload", "istore"};
Это в заголовочном файле не нужно, можно убрать в cpp.

2024-11-13 11:10 UTC, Dovgalyuk commented on LibraryCPPClass/list.cpp
> +    }
Тут получится список элементов в другом порядке.

2024-11-14 06:33 UTC, Dovgalyuk commented on LibraryCPPClass/list.cpp
> +    }
Здесь осталась ошибка.

2024-11-15 04:28 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной - «#» или пустым пространством – «.».
Стартовая позиция обозначается как X, финишные позиции цифрами от 0 до 9.
Написать программу, которая выводит цифру, ближайшую к стартовой позиции.
За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди.

Входные данные
```
######
#...X#
#.#.##
#3.4.#
######
```
Выходные данные
```
4
```

2024-11-15 04:28 UTC, closed without merging