Lab3
Dovgalyuk/Algorithms pull request #1043
Opened 2024-11-11 17:02 UTC by Dethord-hub

2024-11-11 17:41 UTC, Dethord-hub commented
Полностью перепишу оба модуля, только сейчас понял, что наворотил там много ошибок + поменяю тест на vector(минимально поменяю), т.к. он не проходит, хотя тест на queue проходит без проблем (проверял локально)

2024-11-13 12:15 UTC, Dovgalyuk requested changes

2024-11-13 12:15 UTC, Dovgalyuk commented on LibraryC/queue.c
> +  vector_resize(queue->vector, queue->back + 1);
Нужен кольцевой буфер. В этот момент уже могли освободиться ячейки в начале массива, новый элемент должен занять первую из них.

2024-11-15 04:42 UTC, Dovgalyuk commented on LibraryC/queue.c
> +    vector_resize(queue->vector, new_capacity);
Это не сработает, если хвост очереди находится в середине массива.

2024-11-18 09:18 UTC, Dovgalyuk requested changes

2024-11-18 09:18 UTC, Dovgalyuk commented on LibraryC/queue.c
> +        vector_set(queue->vector, new_front++, vector_get(queue->vector, i));
В начале массива сейчас хвост очереди, а тут мы его портим.

2024-11-18 09:18 UTC, Dovgalyuk commented on LibraryC/queue.c
> +  if (queue->size == 0) {
Стоит постараться и избавиться от этой ветки, чтобы такой вариант покрывался другими частями кода.

2024-11-18 09:20 UTC, Dethord-hub commented on LibraryC/queue.c
> +  if (queue->size == 0) {
Можно, пожалуйста, чуть подробнее? Вы имеете ввиду то, чтобы добавить этот функционал, условно говоря, в какую-нибудь другую функцию?

2024-11-18 09:20 UTC, Dethord-hub commented on LibraryC/queue.c
> +        vector_set(queue->vector, new_front++, vector_get(queue->vector, i));
Исправим!

2024-11-19 04:17 UTC, Dovgalyuk commented on LibraryC/queue.c
> +      vector_resize(queue->vector, new_capacity);
А сразу нельзя было создать temp нужного размера, а потом заменить им vector?

2024-11-19 08:07 UTC, Dethord-hub commented on LibraryC/queue.c
> +      vector_resize(queue->vector, new_capacity);
Если я правильно вас понял, то сейчас там выполняются лишние операция копирования, сейчас скину исправление

2024-11-20 06:13 UTC, Dovgalyuk commented
Принято.

* Разработать программный интерфейс модуля (заголовки функций) библиотеки LibraryCPPTemplate для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины,
получить пометки всех вершин в виде вектора.
* Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
* Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List библиотеки LibraryCPPTemplate.
* Разработать и добавить в проект LibraryCPPTemplate программу, тестирующую работу библиотеки для графа.
* Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать для него алгоритмом Флойда самый длинный из кратчайших путей.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

2024-11-20 06:13 UTC, closed without merging