lab_1
Dovgalyuk/Algorithms pull request #1053
Opened 2024-11-12 00:31 UTC by exg0n

2024-11-12 07:21 UTC, Dovgalyuk commented
Должен работать ещё тест для массива.

2024-11-12 22:20 UTC, exg0n commented
Добавил тест в cmakelist, указал в качестве аргумента при вызове программы другой файл "input2.txt". В нём описал ещё один набор тестовых данных. Надеюсь, я вас правильно понял.

2024-11-13 11:54 UTC, Dovgalyuk commented
В работе нужно реализовать контейнер Array. Для него или включить предлагаемый тест, либо написать собственный.

2024-11-14 06:26 UTC, Dovgalyuk requested changes

2024-11-14 06:26 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +            sum += array_get(arr, i);
Сумму считать нужно в отдельном цикле, потому что в первом позиции минимума и максимума ещё не найдены.

2024-11-15 05:12 UTC, Dovgalyuk commented
> у меня не получается отправить пул реквест, пишет ошибку "merging is blcked", почитал, говорят, что нужно вносить изменения по каким-то правилам
> 
> честно, не понимаю, что нужно сделать ![Снимок экрана 2024-11-15 012106](https://private-user-images.githubusercontent.com/105127448/386387467-d8037257-8849-4d6e-8980-3a4ec031fb22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NDc3OTcsIm5iZiI6MTczMTY0NzQ5NywicGF0aCI6Ii8xMDUxMjc0NDgvMzg2Mzg3NDY3LWQ4MDM3MjU3LTg4NDktNGQ2ZS04OTgwLTNhNGVjMDMxZmIyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwNTExMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWZhOWE1MzM0MDI2ODkzNzY4YTE1NTBiMjVhYzU2MGNjOWVhNzhkYTRiMmZjMGE1MjA4OTFjMTI2YWFjZjM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QHh04i92eF-9rhbtKjwh5W460gsZl8q2akzLT4UTsn0)

Так и должно быть.
Надо смотреть только на прохождение тестов.

2024-11-15 05:13 UTC, Dovgalyuk commented
А сейчас нужно из репозитория удалить временные файлы.

2024-11-18 09:32 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

В ускорителе по прямой движутся частицы. Положительно заряженные частицы движутся вправо, отрицательно заряженные влево с одинаковой скоростью. При столкновении двух частиц обе они исчезают не влияя на все остальные. Вывести пары начальных координат частиц, которые столкнутся между собой. Во входном файле сначала записано число N, а затем идет описание частиц: начальная координата и заряд. Описания частиц в файле упорядочены по координате.

Входные данные
```
5
1 -
4 +
8 -
9 +
10 -
```
Выходные данные
```
4 8
9 10
```

2024-11-18 09:32 UTC, closed without merging