Lab2
Dovgalyuk/Algorithms pull request #1056
Opened 2024-11-12 01:31 UTC by y3oooh

2024-11-12 07:28 UTC, Dovgalyuk requested changes

2024-11-12 07:28 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +    string filename = "input.txt";
Имя файла нужно брать из аргументов командной строки.

2024-11-13 11:56 UTC, Dovgalyuk commented on LibraryCPP/Tests/list.cpp
> +    /*list_insert_after(list, list_first(list), 4);
Почему этого не должно быть в тестовой программе?

2024-11-14 06:22 UTC, Dovgalyuk commented on LibraryCPP/Tests/list.cpp
> +    /*list_insert_after(list, list_first(list), 4);
В каком месте жалуется? Функцию надо вернуть.

2024-11-14 07:57 UTC, y3oooh commented
Теперь при сборке появляется ошибка... \Algorithms\LibraryCPP\list.cpp(59,35): warning C4100: list: неиспользованный формальный параметр

2024-11-14 08:05 UTC, y3oooh commented
Закомментировала и пересобрала, теперь вылезает ошибка как раз таки в тестах листа \Algorithms\LibraryCPP\Tests\list.cpp(24,5): error C3861: list_insert_after: идентификатор не найден
А ошибка про неиспользованный формальный параметр пропала

2024-11-14 08:08 UTC, y3oooh commented
Не увидела, что в файле .h функция была закомментирована...но теперь вылезает ошибка list.obj : error LNK2019: ссылка на неразрешенный внешний символ "struct ListItem * __cdecl list_insert_after(struct List *,struct ListItem *,int)" (?list_ 
insert_after@@YAPEAUListItem@@PEAUList@@PEAU1@H@Z) в функции main.

2024-11-14 08:16 UTC, y3oooh commented
Закомментировала функцию в тестах, сборка прошла, но теперь ошибка при запуске в следующей функции, потому что из-за комментирования немного поломалась логика
Ошибка: 1/1 Test #1: TestListCPP ......................***Failed    0.01 sec
list_erase error

2024-11-14 08:22 UTC, y3oooh commented
Теперь всё работает корректно, как сборка и запуск тестов, так и сама программа, поэтому я не особо понимаю, как сделать так, чтобы и сборка работала и функция вернулась...

2024-11-15 04:24 UTC, Dovgalyuk commented
Был какой-то момент, когда всё компилировалось, но не работали тесты.
Стоит к нему вернуться, чтобы разобраться, что не так в реализации функций.

2024-11-18 01:18 UTC, y3oooh commented
добрый день, изменила немного реализацию функций (увидела, где не использовались параметры...), поэтому вернула все тесты в исходный вид и теперь по идее всё работает и используется

2024-11-18 10:31 UTC, Dovgalyuk requested changes

2024-11-18 10:31 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    if (list->head == item) list->head = item;
Какой в этом смысл?

2024-11-18 10:31 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    if (list->head == item && item_delete->next == nullptr) list->head = item;
Тоже непонятно.

2024-11-18 11:36 UTC, y3oooh commented
добрый день, данные условия были добавлены, чтобы исправить ошибку "неиспользованный формальный параметр", но не сразу додумалась что можно просто его (параметр) убрать... так что лишние условия убрала

2024-11-19 04:23 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Во входном файле записано количество вершин и матрица смежности ориентированного графа. Вывести в выходной файл список расстояний от первой вершины до всех остальных. Для вычисления расстояний использовать поиск в ширину.

Входные данные
```
4
0 1 0 0
0 0 1 1
1 0 0 1
0 1 0 0
```
Выходные данные
```
0
1
2
2
```

2024-11-19 04:23 UTC, closed without merging