Lab_2
Dovgalyuk/Algorithms pull request #1057
Opened 2024-11-12 05:03 UTC by wXwSmilewXw

Вроде Good <(￣︶￣)>

2024-11-12 08:23 UTC, wXwSmilewXw commented
> Тесты какие-то не те.

Полчаса сидел, так и не понял о каких тестах идет речь, объясните, пожалуйста

2024-11-13 00:32 UTC, wXwSmilewXw commented
Исправил, жду дальнейших указаний w(°ｏ°)w

2024-11-13 12:06 UTC, Dovgalyuk requested changes

2024-11-17 03:41 UTC, wXwSmilewXw commented
Finally done!
 (◕‿◕)

2024-11-18 09:53 UTC, Dovgalyuk requested changes

2024-11-18 09:53 UTC, Dovgalyuk commented on LibraryC/vector.h
> +} Vector;
Определение структуры должно быть в .c, а не в .h.

2024-11-18 09:53 UTC, Dovgalyuk commented on LibraryC/vector.c
> +    if (index >= vector->capacity || index >= vector->size) {
Достаточно проверять >= size.

2024-11-18 09:53 UTC, Dovgalyuk commented on LibraryC/vector.c
> +        vector->size = index + 1; // Обновляем размер вектора, если это необходимо
Это забота функции resize.

2024-11-18 16:38 UTC, wXwSmilewXw commented
Поправил, что дальше?

2024-11-19 05:20 UTC, Dovgalyuk requested changes

2024-11-19 05:20 UTC, Dovgalyuk commented on LibraryC/vector.c
> +    vector->data[vector->size++] = value; // Добавление элемента и увеличение размера
Все эти манипуляции и проверки size можно убрать, просто сделав resize(size + 1)

2024-11-19 05:54 UTC, wXwSmilewXw commented on LibraryC/vector.c
> +    vector->data[vector->size++] = value; // Добавление элемента и увеличение размера
В текущем коде осуществляется проверка на заполнение вектора, чтобы избежать выделения памяти без необходимости. Если vector->size уже больше или равно vector->capacity, вызывается vector_resize.  Если убрать проверку, как Вы предложили, и просто вызывать vector_resize(vector, vector->size + 1), это приведет к тому, что при каждом добавлении элемента выделяется новая память, даже если еще есть неиспользуемая емкость. Лучше сохранить текущую логику, так как она гарантирует, что выделение памяти произойдет только при необходимости, что более эффективно.

2024-11-20 05:32 UTC, Dovgalyuk commented on LibraryC/vector.c
> +    vector->data[vector->size++] = value; // Добавление элемента и увеличение размера
resize не должен выделять памяти, если хватает capacity.

2024-11-21 03:50 UTC, wXwSmilewXw commented on LibraryC/vector.c
> +    vector->data[vector->size++] = value; // Добавление элемента и увеличение размера
Объясните, пожалуйста, я попробовал сделать так как Вы сказали, но вылетает timeout (Что логично, т.к. мое условие предотвращало ненужный вызов функции resize) или я не так Вас понял? Можете сказать, что конкретно удалить и что дописать, а то я не понимаю, что конкретно у меня не правильно (╥_╥)

2024-11-21 08:40 UTC, Dovgalyuk commented on LibraryC/vector.c
> +    vector->data[vector->size++] = value; // Добавление элемента и увеличение размера
Это условие можно проверять внутри функции resize. Если capacity хватает, то перевыделять память не надо, можно просто поменять видимый размер size.

2024-11-22 04:12 UTC, wXwSmilewXw commented
Сегодня к 8-9 постараюсь выложить ＼(〇_ｏ)／

2024-11-22 05:51 UTC, wXwSmilewXw commented
Я до сих пор не понимаю чем так плохо условие, но перепробовав множество вариантов, без него выходит какая-то ерунда

2024-11-25 02:52 UTC, wXwSmilewXw commented
Done! (￣ヘ￣)

2024-11-27 04:56 UTC, Dovgalyuk commented
Что-то сломалось.

2024-11-27 21:05 UTC, wXwSmilewXw commented
Исправил ＼(￣▽￣)／

2024-11-28 06:00 UTC, Dovgalyuk requested changes

2024-11-28 06:01 UTC, Dovgalyuk commented on LibraryC/vector.c
> +        vector_resize(vector, vector->size); // Увеличиваем размер вектора до необходимого
Тут нужно было передать index + 1

2024-11-28 06:03 UTC, wXwSmilewXw commented on LibraryC/vector.c
> +        vector_resize(vector, vector->size); // Увеличиваем размер вектора до необходимого
Не знаю почему так, но у меня if и так убран 
![изображение](https://github.com/user-attachments/assets/d4590736-bd79-48be-a391-ce05b5508f3b)

2024-11-28 06:10 UTC, wXwSmilewXw commented on Lab1C/lab2.c
> +    if (strcmp(command, "PUSH") == 0 && reg_char >= 'A' && reg_char < 'A' + REGISTERS) {
Добавил проверку на пустую строку

2024-11-28 06:11 UTC, wXwSmilewXw commented
Поправил код и добавил проверку, что дальше?

2024-11-29 04:31 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и очередь на основе этого списка (модуль queue).
* Решить задачу, используя реализованную очередь.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Задан ориентированный граф виде матрицы смежности. Написать программу для определения длины кратчайшего пути от одной вершины для другой. В первой строке входного файла записано количество вершин, номер стартовой вершины и номер финишной. В последующих строках идет описание матрицы смежности. Значения 0 в матрице обозначают отсутствие ребра. В выходной файл выводится длина кратчайшего пути. Если решения не существует – выводится IMPOSSIBLE. Программа должна использовать поиск в ширину на основе очереди.

Входные данные
```
4 1 4
0 1 1 0
0 0 0 0
0 1 0 1
0 0 1 0
```
Выходные данные
```
2
```

2024-11-29 04:31 UTC, closed without merging