lab2
Dovgalyuk/Algorithms pull request #1059
Opened 2024-11-12 14:01 UTC by frostikkkk

2024-11-13 11:21 UTC, Dovgalyuk requested changes

2024-11-13 11:21 UTC, Dovgalyuk commented on Lab2CPP/lab2.h
> +void to_lowercase(std::string& str);
Это не нужно в заголовочном файле.

2024-11-13 12:26 UTC, frostikkkk commented on Lab2CPP/lab2.h
> +void to_lowercase(std::string& str);
Исправил.

2024-11-14 06:50 UTC, Dovgalyuk commented on Lab2CPP/lab2.h
> +void to_lowercase(std::string& str);
Всё так и осталось.

2024-11-14 07:56 UTC, frostikkkk commented on Lab2CPP/lab2.h
> +void to_lowercase(std::string& str);
Теперь вроде все хорошо.

2024-11-15 04:21 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и очередь на основе этого списка (модуль queue).
* Решить задачу, используя реализованную очередь.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной - «#» или пустым пространством – «.». Стартовая позиция обозначается как X. Написать программу, считающую количество клеток, до которых можно найти из начальной, а также выводящую лабиринт с достижимыми клетками, отмеченными символом «x». За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди.

Входные данные
```
######
#...X#
#.####
#....#
######
```
Выходные данные
```
9
######
#xxxx#
#x####
#xxxx#
######
```

2024-11-15 04:21 UTC, closed without merging