Выполнено индивидуальное задание 5
Dovgalyuk/Algorithms pull request #106
Opened 2020-12-09 18:46 UTC by SomeBytes-lab

```
1. Разработать программный интерфейс модуля (заголовки функций) для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
2. Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
3. Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде матрицы смежности в контейнере Array той же библиотеки.
4. Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать в нем длины кратчайших путей от одной вершины до всех остальных с помощью алгоритма Дейкстры. 
```

2020-12-10 07:37 UTC, Dovgalyuk requested changes

2020-12-10 07:37 UTC, Dovgalyuk commented on Task/main.cpp
> +   bool isVisited[graphSize];
Что-то из этого (или даже можно совместить) можно хранить в пометках для вершин прямо в графе.

2020-12-10 07:37 UTC, Dovgalyuk commented on Task/main.cpp
> +            currentVertex = i, minDist = distance[i];
Так лучше не писать, это запутывает читателя.

2020-12-10 07:37 UTC, Dovgalyuk commented on LibraryCPP/graph.cpp
> +         array_set(newAdjacencyMatrix, i, 0), k++;
Можно избавиться от k, если брать остаток от деления.
Мне кажется, так нагляднее.

2020-12-10 07:37 UTC, Dovgalyuk commented on Task/main.cpp
> +         if (currentWeight && currentWeight + distance[currentVertex] < distance[i])
Почему бы здесь не применить итератор. Он же как раз для обхода соседей нужен.

2020-12-11 07:31 UTC, Dovgalyuk requested changes

2020-12-11 07:31 UTC, Dovgalyuk commented on Task/main.cpp
> +      for (int i = 0; i < edgeCount; i++)
Пересчитывать не стоит, лучше идти в цикле до признака "вершины кончились".

2020-12-11 07:31 UTC, Dovgalyuk commented on Task/main.cpp
> +   Iterator* iter = iterator_create(graph, startVertex);
А почему это всегда одна и та же вершина?

2020-12-11 13:11 UTC, SomeBytes-lab commented on Task/main.cpp
> +   Iterator* iter = iterator_create(graph, startVertex);
В конце цикла while выбирается новая вершина

2020-12-11 13:35 UTC, Dovgalyuk commented on Task/main.cpp
> +   Iterator* iter = iterator_create(graph, startVertex);
В том цикле мы должны обходить все связи от currentVertex, а не какие попало.

2020-12-11 13:35 UTC, Dovgalyuk commented on Task/main.cpp
> +   Iterator* iter = iterator_create(graph, startVertex);
а, там есть selectVertex

2020-12-11 13:39 UTC, Dovgalyuk commented
Последнее задание:

Разработать архиватор для кодирования и раскодирования файла с помощью кода Хаффмана.
Код архивации/разархивации оформить в виде библиотеки, в которую передается ссылка на объекты istream/ostream для возможности работы с произвольными файлами и буферами через этот интерфейс.
При кодировании использовать собственную реализацию очереди с приоритетами.

2020-12-11 13:39 UTC, closed without merging