Lab2
Dovgalyuk/Algorithms pull request #1061
Opened 2024-11-12 18:22 UTC by Nickolay-Varuhin

2024-11-13 11:49 UTC, Dovgalyuk requested changes

2024-11-13 11:49 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +           (opening == L'\u201C' && closing == L'\u201D') ||
Нужны ASCII-символы, а не какие-то из других кодировок.

2024-11-13 11:49 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +        } else if (ch == L')' || ch == L']' || ch == L'}' || ch == L'\u2018' || ch == L'\u2019') {
Как должно здесь сработать условие с кавычкой?

2024-11-13 20:59 UTC, Nickolay-Varuhin commented on Lab2CPP/lab2.cpp
> +           (opening == L'\u201C' && closing == L'\u201D') ||
Здравствуйте, я поменял на кодировку ASCII и добавил проверку на закрытие кавычек

2024-11-13 21:00 UTC, Nickolay-Varuhin commented on Lab2CPP/lab2.cpp
> +        } else if (ch == L')' || ch == L']' || ch == L'}' || ch == L'\u2018' || ch == L'\u2019') {
спасибо, что указали на ошибку, из-за которой у меня открывающиеся и закрывающиеся одинарные и двойные кавычки находились не на своих местах при проверке

2024-11-14 06:55 UTC, Dovgalyuk requested changes

2024-11-14 06:55 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +    bool inQuotes = false; // Флаг для отслеживания кавычек
Это делается с помощью стека, как и скобки.

2024-11-15 05:02 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +}
Стоит проверить, что выдаётся для теста, который уже есть в проекте.

2024-11-19 05:52 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +}
Вот ещё тест:
```
"''"
```

2024-11-19 06:03 UTC, Nickolay-Varuhin commented on Lab2CPP/lab2.cpp
> +}
Здравствуйте, я нашёл ошибку, отправил исправленный код

2024-11-20 05:44 UTC, Dovgalyuk requested changes

2024-11-20 05:44 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +                    if (!isMatchingPair(opening, ch)) {
Совпадение же проверено выше.

2024-11-21 06:44 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной – «#» или пустым пространством – «.». Стартовая позиция обозначается как X, финишная как Y. Написать программу, находящую минимальный путь от стартовой до финишной клетки, если это возможно. За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди. Если решения нет, вывести IMPOSSIBLE.

Входные данные
```
######
#...X#
#.####
#...Y#
######
```
Выходные данные
```
######
#xxxX#
#x####
#xxxY#
######
```

Входные данные
```
######
#...X#
######
#...Y#
######
```
Выходные данные
```
IMPOSSIBLE
```

2024-11-21 06:44 UTC, closed without merging