Lab2
Dovgalyuk/Algorithms pull request #1068
Opened 2024-11-13 22:27 UTC by g3ntle-man

2024-11-13 22:32 UTC, g3ntle-man commented on LibraryCPP/stack.h
> +};
Павел Михалойлович, здравствуйте!

При решении 2-й лабы возник вопрос:
В задании написано: "Реализовать ... двусвязный список и стэк на **основе этого списка** ...". Я так и сделал, создав структуру Stack, в которой инициализирован list.

2024-11-13 22:36 UTC, g3ntle-man commented
Сам вопрос: будет ли это считаться правильно в случае с лабой, или нужно как-то доработать этот момент?

2024-11-13 22:43 UTC, g3ntle-man commented on LibraryCPP/stack.h
> +};
Павел Михалойлович, здравствуйте!

При решении 2-й лабы возник вопрос:
В задании написано: "Реализовать ... двусвязный список и стэк на **основе этого списка** ...". Я так и сделал, создав структуру Stack, в которой инициализирован list.

2024-11-13 22:43 UTC, g3ntle-man commented on Lab1CPP/lab2.cpp
> +    stack->list->tail;
Если реализовывать таким способом (по заданию) стэк, то я буду иметь доступ к полю tail, хотя стэк имеет доступ только к полю head (в зависимости от порядка добавления в list)

2024-11-13 22:43 UTC, g3ntle-man commented on Lab1CPP/lab2.cpp
> +    stack->list->tail;
Сам вопрос: если реализовывать таким способом (по заданию) стэк, то я буду иметь доступ к полю tail, хотя стэк имеет доступ только к полю head (в зависимости от порядка добавления в list)

2024-11-14 07:20 UTC, Dovgalyuk commented on Lab1CPP/lab2.cpp
> +    stack->list->tail;
Для того, чтобы сделать стек, можно добавлять данные в начало списка. А при удалении - удалять голову списка.

2024-11-14 15:35 UTC, g3ntle-man commented
Павел Михайлович, работу сделал. Проверьте пожалуйста

2024-11-15 04:55 UTC, Dovgalyuk requested changes

2024-11-15 04:55 UTC, Dovgalyuk commented on Lab1CPP/lab2.cpp
> +            stack_push(stack, value);
Аргументом push может быть так же и регистр.

2024-11-15 04:55 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        list->tail = new_item;
От tail можно избавиться, он не нужен для работы списка в данном случае.

2024-11-15 04:55 UTC, Dovgalyuk commented on LibraryCPP/list.h
> +    ListItem *prev;
Определение структур должно быть в cpp, а не в h.

2024-11-15 04:55 UTC, Dovgalyuk commented on LibraryCPP/stack.h
> +};
Структура Stack тоже должна быть описана в cpp.

2024-11-15 07:29 UTC, g3ntle-man commented
Павел Михайлович, здравствуйте. 

Исправил ошибки. Надеюсь правильно понял про аргумент push, т.к. иначе идей, для чего он работает с регистрами, нет

2024-11-18 09:26 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

На шахматной доске построен лабиринт и задана позиция шахматного коня.
Найти кратчайший путь коня в целевую точку.

Позиция коня обозначена бувой 'K', выход буквой 'E', а препятствие символом '#'.
Вывести такую же доску с клетками, пронумерованными в порядке их посещения.

Входные данные
```
K.######
..#E....
..#.....
..#.###.
..#.....
.....###
.#####..
##......
```
Выходные данные
```
0.######
..#2....
.1#.....
..#.###.
..#.....
.....###
.#####..
##......
```

2024-11-18 09:26 UTC, closed without merging