<test>
Dovgalyuk/Algorithms pull request #1079
Opened 2024-11-17 20:45 UTC by xlurr

2024-11-18 10:01 UTC, Dovgalyuk requested changes

2024-11-18 10:01 UTC, Dovgalyuk commented on Lab1CPP/lab1.cpp
> +	std::vector<int> arr = readFile(input);
Нужно использовать собственный масси Array.

2024-11-18 11:59 UTC, xlurr commented on Lab1CPP/lab1.cpp
> +	std::vector<int> arr = readFile(input);
Прошу прощения, запамятовал что нужен array. Переделал.

2024-11-19 04:27 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library двусвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Написать программу, проверяющую правильность расстановки двух видов кавычек (“ и ‘) и скобок () в строке.  Программа должна выводить YES для правильной последовательности и NO для неправильной.

Входные данные
```
"ab(c 'de' f)gt"
```
Выходные данные
```
YES
```

Входные данные
```
"adjsk 'z' frr')
```
Выходные данные
```
NO
```

2024-11-19 04:27 UTC, closed without merging