Zadanie5
Dovgalyuk/Algorithms pull request #108
Opened 2020-12-13 09:23 UTC by sergeychaliy2

.

2020-12-14 05:50 UTC, Dovgalyuk commented
1. Нужны результаты измерения времени работы для нового контейнера и для set.

2. Не хватает функции, которая обходила бы дерево и перепроверяла баланс. А также теста с ней с добавлением и удалением большого объема данных.

2020-12-16 05:30 UTC, Dovgalyuk requested changes

2020-12-16 05:30 UTC, Dovgalyuk commented on container/main.cpp
> +	string *str = new string;
Нельзя просто использовать string str; ?

2020-12-17 06:05 UTC, Dovgalyuk requested changes

2020-12-17 06:05 UTC, Dovgalyuk commented on container/main.cpp
> +	string*str=new string;
Тут тоже new.

2020-12-17 06:05 UTC, Dovgalyuk commented on container/main.cpp
> +	string *str = new string;
И тут new.

2020-12-17 06:06 UTC, Dovgalyuk commented
И по-прежнему:

Нужны результаты измерения времени работы для нового контейнера и для set.

Не хватает функции, которая обходила бы дерево и перепроверяла баланс.

2020-12-17 07:24 UTC, Dovgalyuk commented
Не хватает функции, которая обходила бы дерево и перепроверяла баланс.

2020-12-18 08:00 UTC, sergeychaliy2 commented
У нас пересчет проходит вызовом функции countHeight() в функциях balanceAVLTree(), turnLeft(), turnRight(). при проходе по узлам дерева.

2020-12-21 07:43 UTC, Dovgalyuk commented
countHeight() берет готовую высоту. Нужно проверять всё дерево и выдавать ошибку, если что-то не сходится.

2020-12-22 10:36 UTC, Dovgalyuk commented
Нужна отдельная функция для полного обхода и пересчета высоты.
Обычные функции работы с деревом при этом портить не надо.
Эту тестовую функцию нужно вызывать только когда выполняются тесты - добавление или удаление множества элементов.

2020-12-23 06:31 UTC, Dovgalyuk commented
Так лучше. Осталось проверить, что left и right не отличаются больше, чем на 1.

2020-12-24 07:02 UTC, Dovgalyuk commented
1. Разработать программный интерфейс модуля (заголовки функций) для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
    2. Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
    3. Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List той же библиотеки.
    4. Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать в нем длины кратчайших путей от одной вершины до всех остальных с помощью алгоритма Дейкстры.

2020-12-24 07:02 UTC, closed without merging