Lab1
Dovgalyuk/Algorithms pull request #1081
Opened 2024-11-17 22:17 UTC by Skipeptp

2024-11-18 10:04 UTC, Dovgalyuk requested changes

2024-11-18 10:04 UTC, Dovgalyuk commented on Lab1CPP/lab1.cpp
> +        for (size_t j = 0; j < 5; ++j) {
Можно только обновлять сумму по сравнению с предыдущей итерацией. Вычитать один старый элемент и добавлять один новый.

2024-11-18 10:04 UTC, Dovgalyuk commented on Lab1CPP/input.txt
> +1 2 3 4
Странный тест для поиска максимальной суммы пяти элементов.

2024-11-18 13:02 UTC, Skipeptp commented on Lab1CPP/input.txt
> +1 2 3 4
Здравствуйте, я изменил указанные недостатки в работе.

2024-11-19 04:29 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library двусвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Во входном файле записана последовательность тегов в формате HTML. Каждый тег расположен на отдельной строке. Используя стек, проверить правильность этой последовательности. Вывести в выходной файл YES, если последовательность корректна и NO, если нет.

Входные данные
```
<HTML>
<Body>
</body>
</HTML>
```
Выходные данные
```
YES
```

Входные данные
```
<HTML>
</body>
```
Выходные данные
```
NO
```

2024-11-19 04:29 UTC, closed without merging