Lab5
Dovgalyuk/Algorithms pull request #1088
Opened 2024-11-18 17:27 UTC by bvaleksch

Моя реализация
![my_hash_table](https://github.com/user-attachments/assets/9f313851-8bde-4778-92ef-337f55ca3a36)
 
Стандартная
![std_hash_table](https://github.com/user-attachments/assets/e887bc3b-583e-47eb-a795-646c0647b2bb)

2024-11-19 06:08 UTC, Dovgalyuk requested changes

2024-11-19 06:08 UTC, Dovgalyuk commented on LibraryCPP/hash_table.cpp
> +	size_t cnt = 0;
Незначительная оптимизация, усложняющая код.
Исходная таблица почти полная, сэкономить мало что получится.

2024-11-19 06:08 UTC, Dovgalyuk commented on Lab5CPP/lab5.cpp
> +        assert(hashTable.get("key" + std::to_string(i)) == "value" + std::to_string(i));
assert при релизной сборке удаляется.

2024-11-20 06:09 UTC, Dovgalyuk commented on Lab5CPP/lab5.cpp
> +        (void) hashTable.get(keys[i]);
Надо было оставить сравнение. Мне кажется, другие баги в реализации тут бы проявились.

2024-11-20 07:22 UTC, bvaleksch commented on Lab5CPP/lab5.cpp
> +        (void) hashTable.get(keys[i]);
Хорошо добавлю сравнение. Просто я думал, что за корректную работу модулей отвечают тесты. Задача же этой программы просто замерить время

2024-11-21 06:12 UTC, Dovgalyuk requested changes

2024-11-21 06:12 UTC, Dovgalyuk commented on LibraryCPP/hash_table.cpp
> +void HashTable::insert(std::string key, std::string value)
Везде строки передаются по значению, хотя вполне можно использовать константные ссылки.

2024-11-21 06:12 UTC, Dovgalyuk commented on LibraryCPP/hash_table.cpp
> +	if (((count+1)/size) >= load_factor) {
Здесь целочисленное деление, так что непонятно, как вообще что-то работает.

2024-11-21 06:12 UTC, Dovgalyuk commented on LibraryCPP/hash_table.cpp
> +	for (size_t ind = 0; ind < size; ind++) {
Тут нет перехода через ноль. В результате функция может вернуть индекс, равный размеру массива.

2024-11-21 15:07 UTC, bvaleksch commented on LibraryCPP/hash_table.cpp
> +	for (size_t ind = 0; ind < size; ind++) {
Здесь я не совсем понял, в какой ситуации возможен данный случай. Индекс, возвращаемый функцией, всегда принадлежит диапазону [0; size - 1] и может быть получен только тремя способами: из основного цикла do-while, из вспомогательного цикла for, либо напрямую как get_start_index(key). В первом случае индекс вычисляется как (index + k * step) % size, что гарантирует его нахождение в пределах [0; size - 1]. Во втором случае цикл явно перебирает индексы от 0 до size - 1, возвращая первый элемент, чей тип не равен Type::Value. Третий случай — возврат значения get_start_index(key) — теоретически возможен, если массив полностью состоит из Type::Value, но на практике исключён благодаря проверке load_factor, при достижение которого массив расширяется. Однако даже если бы этот случай был возможен, get_start_index(key) вычисляется как my_hash1(key) % size, а значит, результат всё равно был бы в пределах [0; size - 1]. Таким образом, возвращаемое значение всегда находится диапазоне [0; size - 1]

2024-11-22 06:39 UTC, Dovgalyuk commented on LibraryCPP/hash_table.cpp
> +	for (size_t ind = 0; ind < size; ind++) {
Может быть пустые элементы собрались в начале массива, и поиск во втором цикле до правой границы не найдёт ни одного пустого.

2024-11-22 07:16 UTC, bvaleksch commented on LibraryCPP/hash_table.cpp
> +	for (size_t ind = 0; ind < size; ind++) {
Если все пустые(Delete / None) элементы действительно собраны в начале массива, то второй цикл просто вернет индекс первого пустого элемента (в данном случае 0), что соответствует ожидаемому поведению

2024-11-25 05:21 UTC, Dovgalyuk commented on LibraryCPP/hash_table.cpp
> +	for (size_t ind = 0; ind < size; ind++) {
Точно, я не заметил, что он идёт не с последнего индекса, а с нуля.

2024-11-25 05:21 UTC, Dovgalyuk commented
Принято.

2024-11-25 05:21 UTC, closed without merging

2024-11-25 07:25 UTC, bvaleksch commented
Запрос на шестую лабораторную

2024-11-26 05:53 UTC, Dovgalyuk commented
Задано алгебраическое выражение, составленное из неотрицательных целых чисел и знаков операций +, - и *. Требуется так расставить в этом выражении скобки, чтобы его значение стало максимально возможным.

Входные данные
```
1+2-3*4
```
Выходные данные
```
0
((1+2)-3)*4
```

* Решить задачу с помощью переборного алгоритма
* Доработать переборный алгоритм с использованием принципов динамического программирования
* Сравнить время работы обеих программ на входных данных различного объема
* Оценить по графику и по программе асимптотическую сложность обоих вариантов решения