Lab2
Dovgalyuk/Algorithms pull request #1092
Opened 2024-11-19 11:22 UTC by sudo-odner

Лабораторная №2 Ильин Данила Александрович, гр.3091

https://github.com/Dovgalyuk/Algorithms/pull/913#issuecomment-2400377389

2024-11-20 06:13 UTC, Dovgalyuk commented
Решение не собирается.

2024-11-21 06:33 UTC, Dovgalyuk commented
А очередь с вектором откуда взялись?

2024-11-21 09:04 UTC, sudo-odner commented
Я с первой лабораторной заранее всю библиотеку написал. Что бы потом просто сделать задание.

2024-11-22 06:30 UTC, Dovgalyuk requested changes

2024-11-25 05:30 UTC, Dovgalyuk requested changes

2024-11-25 05:30 UTC, Dovgalyuk commented on LibraryCPPClass/list.cpp
> +List::Item *List::erase_first() {
А нужно ли тут менять _listLast?

2024-11-25 06:05 UTC, sudo-odner commented on LibraryCPPClass/list.cpp
> +List::Item *List::erase_first() {
Нет, менять не нужно. Мы удаляем с начало, а не с конца. Если мы удалим последний элемент, то ссылка на него будет null.

FirstItem <-> MiddleItem <-> EndItem

Delete first

MiddleItem(Now first) <-> EndItem

Delete first

EndItem(Now first and End element)

Delete first

Начало и конец ссылаются на пустую ссылку

2024-11-26 05:24 UTC, Dovgalyuk commented on LibraryCPPClass/list.cpp
> +List::Item *List::erase_first() {
А если единственный элемент удаляется?

2024-11-26 07:19 UTC, sudo-odner commented on LibraryCPPClass/list.cpp
> +List::Item *List::erase_first() {
Если удаляется единственный элемент, то голова и конец головы будут ссылаться на nullptr. Пока не будет добавлен новый элемент

2024-11-27 04:29 UTC, Dovgalyuk commented on LibraryCPPClass/list.cpp
> +List::Item *List::erase_first() {
А где перезаписывается _listLast, когда удаляется последний элемент?

2024-11-27 13:07 UTC, sudo-odner commented on LibraryCPPClass/list.cpp
> +List::Item *List::erase_first() {
_listLast перезаписывется/записывается в случаях:

**1. При добавлении элемента.**
Если голова == nullptr, то тогда делаем его _listLast(последним элементом) и _list(головой)
```
// Inserts new list item into the beginning
List::Item *List::insert(Data data) {
    Item *newItem = new Item(data);
    if (_list != nullptr) {
        _list->_prev = newItem;
        newItem->_next = _list;
    } else {
        _listLast = newItem;
    }
    _list = newItem;

    return newItem;
}
```
**2. Добавление после определенного элемента** 
Если следующий элемент == nullptr, тогда добавляем новый элемент после него и делаем его _listLast(последним элементом)
```
// Inserts new list item after the specified item
List::Item *List::insert_after(Item *item, Data data) {
    if (item == nullptr) return nullptr;

    Item *newItem = new Item(data);
    newItem->_next = item->next();
    newItem->_prev = item;

    newItem->prev()->_next = newItem;
    if (newItem->next() == nullptr) {
        _listLast = newItem;
    } else {
        newItem->next()->_prev = newItem;
    }

    return newItem;
}
```
**3. При удалении после**
Если следующий элемент == nullptr,  тогда делаем предыдущий элемент _listLast (Если предудущий == nullptr, тогда и _listLast == nullptr)
```
// Deletes the list item following the specified one.
// Returns pointer to the item next to the deleted one.
// Should be O(1)
List::Item *List::erase_next(Item *item) {
    if (item == nullptr || item->next() == nullptr) return nullptr;

    Item *itemDelete = item->next();
    if (itemDelete->next() == nullptr) {
        _listLast = item;
    }
    item->_next = itemDelete->next();

    delete itemDelete;
    return item->next();
}
```

2024-11-27 13:09 UTC, sudo-odner commented on LibraryCPPClass/list.cpp
> +List::Item *List::erase_first() {
Если удалиться последний элемент, то _list == nullptr и _listLast == nullptr. Но при добавлении нового элемента, в пустой _list - создастся _list и _listLast

2024-11-27 13:36 UTC, sudo-odner commented on LibraryCPPClass/list.cpp
> +List::Item *List::erase_first() {
**_Раскрытый ответ на вопрос "А нужно ли тут менять \_listLast?":_**
В данной реализации _list и _listLast являются ссылкой на Item. При удалении элемента с начала мы постепенно дойдем до конца массива, где поледний элемент записан в _list и _listLast. Удалив последний элемент в массиве _list и _listLast будут ссылаться на ничто и будут равны nullptr.

**Возможные вопросы:**

_Тогда когда мы добавляем ссылку на элемент в \_listLast? Где запись в \_listLast?_
> Когда добавляем, добавляем после, удаляем после.
> 1. При добавление в пустой массив, наш первый элемент будет и началом и концом. Поэтому мы проверяем если у нас голова == nullptr, если - да то просто у головы меняем ссылку на предыдущий элемент на новый Item, если - нет то добавляем в _list и в _listLast
> 2. При добавляем после, мы можем столкнуться, что добавим в конец списка. Поэтому мы проверяем, если элемент после которого мы хотим добавить новый элемент ссылается на nullptr, то обновляем наш последний элемент на _listLast
> 3. При удалении после, мы можем столкнуться с тем, что удаляемый элемент будет _listLast. Поэтому, если так оно и есть, то предыдущий станет _listLast.

_У тебя в реализации нет проверки Item с \_listLast. Ты делаешь проверку, что следующий элемент nullptr, исходя из этого даелаешь запись в \_listLast. Почему так?_
> Верно, можно было бы сверять элемент по "== _listLast" вместо "->next() == nullptr". Но данные реализации идентичны и несут одинаковую логику.

2024-11-28 05:40 UTC, Dovgalyuk commented on LibraryCPPClass/list.cpp
> +List::Item *List::erase_first() {
Тем временем, проблема всё ещё присутствует.

2024-11-28 12:39 UTC, sudo-odner commented on LibraryCPPClass/list.cpp
> +List::Item *List::erase_first() {
_listLast - это ссылка на на последний элемент, как и _list. При удалении его он ссылается на ничто и является nullptr

2024-11-28 12:42 UTC, sudo-odner commented on LibraryCPPClass/list.cpp
> +List::Item *List::erase_first() {
При удалении последнего элемента, _list и _listLast будут ссылаться на удаленный элемент == nullptr. Элемент удалился и на него нет ссылки -> nullptr. Поэтому явного присваивания nullptr нет смысла.

2024-11-29 04:49 UTC, Dovgalyuk commented on LibraryCPPClass/list.cpp
> +        _list = nullptr;
Эта строчка не нужна.
И оба ветвления можно объединить через if-else, так как проверяются противоположные условия.

2024-12-03 15:18 UTC, Dovgalyuk commented on LibraryCPPClass/list.cpp
> +        _list = nullptr;
Присваивание всё ещё не нужно.

2024-12-09 10:39 UTC, sudo-odner commented
Добрый день. Можно узнать статус моей лабораторной, что бы приступить к выполнению последующий, как можно быстрей

2024-12-09 14:42 UTC, Dovgalyuk commented
Я же оставлял комментарий к последним изменениям. Ещё надо немного доделать.

2024-12-11 06:59 UTC, sudo-odner commented
if-else я исправил. Что именно нужно изменить?

2024-12-11 07:14 UTC, sudo-odner commented
Здравствуйте, мне для допуска на сессию нужно сдать 3 лабораторные. Хотел бы в следуйщий понедельник, когда у нас в университете пары. На них дописать 2 лабу и написать 3. В последствии их защитить.

2024-12-11 16:43 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной – «#» или пустым пространством – «.». Стартовая позиция обозначается как X, финишная как Y. Написать программу, находящую минимальный путь от стартовой до финишной клетки, если это возможно. За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди. Если решения нет, вывести IMPOSSIBLE.

Входные данные
```
######
#...X#
#.####
#...Y#
######
```
Выходные данные
```
######
#xxxX#
#x####
#xxxY#
######
```

Входные данные
```
######
#...X#
######
#...Y#
######
```
Выходные данные
```
IMPOSSIBLE
```

2024-12-11 16:43 UTC, closed without merging