Lab1
Dovgalyuk/Algorithms pull request #1093
Opened 2024-11-19 12:25 UTC by kitheok

2024-11-20 06:21 UTC, Dovgalyuk requested changes

2024-11-20 06:21 UTC, Dovgalyuk commented on Lab1CPP/lab1.cpp
> +    ifstream input_1("input_1.txt");
Имя файла нужно брать из аргументов, передаваемых программе при запуске.

2024-11-20 08:16 UTC, kitheok commented on Lab1CPP/lab1.cpp
> +    ifstream input_1("input_1.txt");
Добавила изменения

2024-11-21 06:31 UTC, Dovgalyuk commented
Программа должна работать корректно, если будет запущена с именем файла, отличающимся от input.txt.

2024-11-21 08:36 UTC, kitheok commented
Исправлено

2024-11-22 06:07 UTC, Dovgalyuk requested changes

2024-11-22 06:07 UTC, Dovgalyuk commented on Lab1CPP/lab1.cpp
> +#include "../LibraryCPP/array.h"
Путь прописан в CMakeLists.txt, тут он не нужен.

2024-11-25 05:19 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
* Решить задачу, используя реализованный стек.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Преобразовать арифметическое выражение в ассемблерные опреации работы со стеком и регистрами.
Используются команды PUSH (занести в стек), POP (извлечь из стека в регистр), ADD (сложить),
SUB (вычесть), MUL (перемножить). Достаточно использовать два регистра A и B.

Входные данные
```
1+2*3
```
Выходные данные
```
PUSH 1
PUSH 2
PUSH 3
POP A
POP B
MUL A, B
PUSH A
POP A
POP B
ADD A, B
PUSH A
```

Входные данные
```
(1+2)*3
```
Выходные данные
```
PUSH 1
PUSH 2
POP A
POP B
ADD A, B
PUSH A
PUSH 3
POP A
POP B
MUL A, B
PUSH A
```

2024-11-25 05:19 UTC, closed without merging