Lab2
Dovgalyuk/Algorithms pull request #1099
Opened 2024-11-19 20:11 UTC by diforc

2024-11-19 21:23 UTC, diforc commented
Павел Михайлович здравствуйте, не могу понять почему у меня не проходит тест, выдавая ошибку утечки памяти в стеке и списке, хотя посмотрев несколько раз я не могу увидеть где происходит утечка, вроде функции stack/list_delete работают корректно, и в самом файле программы lab2.cpp память под стек освобождается

2024-11-20 07:01 UTC, Dovgalyuk commented
Не удаляется стек, если не открылся входной файл.

2024-11-21 06:23 UTC, Dovgalyuk requested changes

2024-11-21 12:32 UTC, diforc commented
Павел Михайлович, здравствуйте!

Изменил структуру Command, добавив аргумент строки, по которой происходит проверка на равенство с регистрами, для команды push, чтобы копировалось значение регистра, а затем использовалось в добавлении значения регистра в стек, также для команды push добавил проверку на то, является ли строка после самой команды числовым значением(если она не является регистром), чтобы копировалось число.

Помимо этого добавил проверку условия для команды pop, чтобы считываемая строка после самой команды была равна хотя бы одному из регистров.

2024-11-22 06:37 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +			if (command.rg == "A" || command.rg == "B" || command.rg == "C" || command.rg == "D") {
Эта проверка не нужна, потому что повторяется ниже в цепочке проверок.

2024-11-22 07:09 UTC, diforc commented
Павел Михайлович, здравствуйте!

Изменил проверку, убрав лишнюю, проверьте пожалуйста.

2024-11-25 05:17 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +			if (command.rg == "A" || command.rg == "B" || command.rg == "C" || command.rg == "D") {
Осталось.

2024-11-25 19:34 UTC, diforc commented on Lab2CPP/lab2.cpp
> +			if (command.rg == "A" || command.rg == "B" || command.rg == "C" || command.rg == "D") {
Изменил условие проверки, как вы мне сегодня сказали, проверьте пожалуйста.

2024-11-26 06:08 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной - «#» или пустым пространством – «.». Стартовая позиция обозначается как X. Написать программу, считающую количество клеток, до которых можно найти из начальной, а также выводящую лабиринт с достижимыми клетками, отмеченными символом «x». За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди.

Входные данные
```
######
#...X#
#.####
#....#
######
```
Выходные данные
```
9
######
#xxxx#
#x####
#xxxx#
######
```

2024-11-26 06:08 UTC, closed without merging