Lab2
Dovgalyuk/Algorithms pull request #1101
Opened 2024-11-20 16:08 UTC by tolik124

2024-12-02 14:30 UTC, Dovgalyuk commented
Пока что тесты не проходят.

2024-12-06 04:59 UTC, Dovgalyuk commented
Должны быть ещё тесты для списка и для стека.

2024-12-09 14:33 UTC, Dovgalyuk commented
Временные файлы из репозитория нужно удалить.

2024-12-09 19:29 UTC, tolik124 commented
какие временные файлы?

2024-12-10 05:35 UTC, Dovgalyuk commented
Algorithms.lnk, CMakeCache.txt. Может ещё что-то не заметил.

2024-12-11 13:15 UTC, tolik124 commented
Hard.waiTTTing⌛

2024-12-11 16:47 UTC, Dovgalyuk requested changes

2024-12-12 06:57 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Во входном файле заданы два числа a, b и последовательность целых чисел. За один просмотр файла с этой последовательностью переписать ее элементы в выходной файл так, чтобы сначала шли числа меньшие заданного числа a, затем все числа из отрезка [a, b], а затем – все остальные. Взаимный порядок чисел в каждой из групп должен быть сохранен. Входной файл содержит числа a, b и последовательность, которую нужно переписать. При реализации программы использовать очередь.

Входные данные
```
1 2
0 -1 1 5 6 2 1 7 -2
```
Выходные данные
```
0 -1 -2 1 2 1 5 6 7
```

2024-12-12 06:57 UTC, closed without merging