Lab5
Dovgalyuk/Algorithms pull request #1103
Opened 2024-11-20 19:46 UTC by ssezmar

Реализован фильтр Блума на основе массива int. Занимает больше, чем мог бы если бы имел бы массив из bool или же еще лучше bitset, но по заданию необходимо предусмотреть возможность удаления элементов.

---

Формулы по которым я считаю предположительное количество ячеек моего массива и количество хэш-функций:

$$m = \frac{-n \cdot \ln(p)}{(\ln(2))^2}$$

$$k = \frac{n}{m} \cdot \ln(2)$$

---
График для фильтра Блума

![filter](https://github.com/user-attachments/assets/82b772a2-62a1-4a6b-8ce5-597a7d898b75)

---
График для unordered set

![unordered_set](https://github.com/user-attachments/assets/21aafc66-ec7a-4425-995e-a1bcc140e35b)

---
График ложных срабатываний

![filter2](https://github.com/user-attachments/assets/045fd6b8-a666-419a-b73e-127f00be4ac9)

2024-11-21 08:49 UTC, Dovgalyuk requested changes

2024-11-21 08:49 UTC, Dovgalyuk commented on Lab5/lab5.cpp
> +    for (size_t i = 0; i < num / 2; ++i) {
Почему только половина удаляется?

2024-11-21 19:46 UTC, ssezmar commented on Lab5/lab5.cpp
> +    for (size_t i = 0; i < num / 2; ++i) {
Случайно забыл убрать...

2024-11-21 19:48 UTC, ssezmar commented
Вот обновлённые графики

---

Фильтр Блума

![blum_v2](https://github.com/user-attachments/assets/ff43c548-7c38-48c6-96ee-10ae42ee287a)

---

unordered_set

![set_v2](https://github.com/user-attachments/assets/6c3c2f14-52a2-4c58-bbec-0b27bc8c66f6)

---

Ложные срабатывания

![blum_v2_l](https://github.com/user-attachments/assets/f965762e-dae8-46fc-9ee3-2275d2addc0a)

2024-11-22 07:21 UTC, Dovgalyuk commented
Принято.

2024-11-22 07:21 UTC, closed without merging