Lab1
Dovgalyuk/Algorithms pull request #1106
Opened 2024-11-21 01:05 UTC by andreev-s-k

2024-11-21 08:10 UTC, Dovgalyuk requested changes

2024-11-21 08:10 UTC, Dovgalyuk commented on Lab1CPP/lab1.cpp
> +    std::ifstream input("input.txt");
Имя файла нужно брать из аргументов командной строки.

2024-11-21 08:10 UTC, Dovgalyuk commented on Lab1CPP/lab1.cpp
> +    }
А где заполнение хвоста массива нулями?

2024-11-22 00:40 UTC, andreev-s-k commented
теперь имя файла берется из аргументов. А по поводу заполнения нулями хвоста массива, я это делаю на строчке 69.

2024-11-22 07:52 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
* Решить задачу, используя реализованный стек.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Во входном файле записана последовательность операций со стеком JAVA-машины.
Упрощённая JAVA-машина может оперировать стеком и четырьмя локальными переменными с номерами от 0 до 3.
Выполнить операции и напечатать финальное состояние стека и переменных.

Список операций, которые должны поддерживаться:
* bipush число - занести число в стек
* pop - вытолкнуть верхнее значение со стека
* imul - умножение
* iand - побитовое "и"
* ior - побитовое "или"
* ixor - операция "исключающее или"
* iadd - сложение
* isub - вычитание
* iload_0, iload_1, iload_2, iload_3 - занести в стек значение соответствующей переменной
* istore_0, istore_1, istore_2, istore_3 - записать значение с вершины стека в соответствующую переменную
* swap - меняет местами два верхних значения в стеке

Все арифметические операции берут операнды с вершины стека, а затем записывают в стек результат вычислений.

Входные данные
```
bipush 1
bipush 2
bipush 3
iadd
istore_0
```
Выходные данные
```
stack:
1
vars:
5
0
0
0
```

2024-11-22 07:52 UTC, closed without merging