Lab2
Dovgalyuk/Algorithms pull request #1108
Opened 2024-11-21 02:16 UTC by voxnord

2024-11-21 08:37 UTC, Dovgalyuk requested changes

2024-11-21 08:37 UTC, Dovgalyuk commented on LAB2CPPCLASS/lab2.cpp
> +        cmd.type = typeCommand::PUSH;
PUSH должен поддерживать и регистры.

2024-11-21 08:37 UTC, Dovgalyuk commented on LibraryCPPClass/list.cpp
> +                current->set_next(new Item(item->data()));
Чем это отличается от кода в конструкторе копирования?

2024-11-22 05:01 UTC, voxnord commented on LibraryCPPClass/list.cpp
> +                current->set_next(new Item(item->data()));
В операторе присваивания приходится каждый раз проходить весь новый список до конца

2024-11-22 07:54 UTC, Dovgalyuk requested changes

2024-11-22 07:54 UTC, Dovgalyuk commented on LAB2CPPCLASS/lab2.cpp
> +            cmd.value = value[0];
А если добавится такое же число, как код какой-то буквы.

2024-12-18 06:16 UTC, Dovgalyuk commented on LAB2CPPCLASS/lab2.cpp
> +            cmd.value = value[0];
Как отработает команда PUSH 65?

2024-12-19 06:03 UTC, Dovgalyuk commented
Проблема осталась.

2024-12-20 06:27 UTC, Dovgalyuk commented on LAB2CPPCLASS/lab2.cpp
> +                if (cmd.value >= 0 && cmd.value <= 3)
А если будет просто команда PUSH 2?

2024-12-23 09:01 UTC, Dovgalyuk commented
Проблема остаётся.

2024-12-26 06:21 UTC, closed without merging