lab_2
Dovgalyuk/Algorithms pull request #1112
Opened 2024-11-21 19:04 UTC by exg0n

в задании не описан случай, когда две разнозаряженные частицы появляются в одинаковых координатах
например
7 -
7 +
как нужно обрабатывать этот случай?

2024-11-22 07:23 UTC, Dovgalyuk commented
> в задании не описан случай, когда две разнозаряженные частицы появляются в одинаковых координатах например 7 - 7 + как нужно обрабатывать этот случай?

Можно не учитывать.

2024-11-22 07:48 UTC, exg0n commented
А с работой что? Принята? Не принята? Может доделать что то нужно?

2024-11-25 05:25 UTC, Dovgalyuk requested changes

2024-11-25 05:25 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +    Stack *particle_charge = stack_create();
Этот стек не нужен. Ведь можно добавлять только положительные частицы. А отрицательные либо сталкиваются с ними, либо улетают.

2024-11-26 06:05 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +        while (stack_empty(particle_start_coordinates) && input_charge == '-')
Есть же внешний цикл. Зачем ещё один внутри?

2024-11-27 04:52 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Написать программу с использованием очереди, которая складывает два длинных числа. Числа имеют одинаковое количество цифр и записаны во входном файле в следующем формате: на первой строке количество цифр в числе, на последующих – цифры первого числа (по одной на строку), а затем – цифры второго. Разряды числа поступают в порядке от наименее значимых к наиболее значимым. В выходной файл должен быть выведен результат сложения.

Входные данные
```
2
9
9
1
1
```
Выходные данные
```
0
1
1
```

2024-11-27 04:52 UTC, closed without merging