lab 4
Dovgalyuk/Algorithms pull request #1130
Opened 2024-11-25 17:47 UTC by ms-anastasiia

2024-11-25 21:30 UTC, ms-anastasiia commented
![graph](https://github.com/user-attachments/assets/07943eec-bd7a-42bf-bfe9-ce1338cbe908)
![graphMST](https://github.com/user-attachments/assets/91a31438-f57c-40c7-b8c5-6f67f654629f)
тест

2024-11-25 21:38 UTC, ms-anastasiia commented
![Снимок экрана 2024-11-26 003600](https://github.com/user-attachments/assets/17ed5e19-71b6-4b02-ab4c-14b1503f6260)
![Снимок экрана 2024-11-26 003744](https://github.com/user-attachments/assets/68394908-356e-4346-9de1-63eb13f6c2df)
тест

2024-11-26 06:23 UTC, Dovgalyuk requested changes

2024-11-26 06:23 UTC, Dovgalyuk commented on Lab4CPP/lab4.cpp
> +			if (graph.get_Edge(u, v) != nullptr && !inMST[v]) {
Тут должен быть итератор по соседям вершины u.

2024-11-26 06:23 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +template<typename Data>
Должно быть два типа для пометок.
Например, у вершин может быть строка (название города), а у рёбер число (длина пути).

2024-11-26 06:23 UTC, Dovgalyuk commented on LibraryCPPTemplate/Tests/CMakeLists.txt
> +
Надо ещё тест для вектора включить.

2024-12-02 14:10 UTC, Dovgalyuk requested changes

2024-12-02 14:10 UTC, Dovgalyuk commented on Lab4CPP/lab4.cpp
> +template<typename V, typename E>
Либо функция не должна быть шаблоном, либо все массивы и переменные внутри должны иметь подходящие типы.

2024-12-03 14:56 UTC, Dovgalyuk commented
Принято.

* Разработать интерфейс (набор функций) для ассоциативного массива, который хранит пары (ключ)строка -> (значение)строка. Поддерживаемые операции: добавить пару ключ-значение, найти значение по ключу, удалить значение по ключу.
* Реализовать контейнер на основе АВЛ-дерева, реализующий разработанный интерфейс.
* Создать тест для проверки работы контейнера. Программа должна включать в себя нагрузочное тестирование для исключения ошибок, приводящих к сложности работы O(N*N) при поиске, удалении или добавлении значений.
* Написать генератор входных данных различного объема для этого контейнера.
* Сравнить скорость выполнения операции добавления в контейнер содержимого файла со стандартным контейнером std::map при различных объемах данных. Построить график зависимости времени работы от объёма входных данных и оценить характер зависимости.
* Добавить тест в CMakeLists.txt, который запускает разработанную программу.

2024-12-03 14:56 UTC, closed without merging