Lab1
Dovgalyuk/Algorithms pull request #1131
Opened 2024-11-25 20:13 UTC by nikolaievanin

2024-11-26 06:09 UTC, Dovgalyuk commented
Не собирается (см. вкладку Checks)

2024-11-29 04:59 UTC, Dovgalyuk commented
Всё ещё не собирается.

2024-12-03 15:22 UTC, Dovgalyuk requested changes

2024-12-03 15:22 UTC, Dovgalyuk commented on Lab1CPP/labb.cpp
> +        string filename2 = "input2.txt"; // Имя файла для второй задачи
Файлы надо брать из аргументов командной строки.

2024-12-06 04:56 UTC, Dovgalyuk commented
Ничего не изменилось.

2024-12-06 21:04 UTC, nikolaievanin commented
Я сейчас изменил код

2024-12-09 07:40 UTC, nikolaievanin commented
Павел Михайлович, добрый день. Я вне изменения. Теперь должно быть все нормально

2024-12-09 14:39 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
* Решить задачу, используя реализованный стек.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Написать программу, работу процессора со стеком. Процессор имеет 4 регистра, обозначенных буквами A, B, C, D. Во входном файле присутствуют операции PUSH и POP. Операция PUSH может иметь в качестве параметра число или регистр. Операция POP в качестве параметра имеет регистр и считывает в него значение с вершины стека.

Также процессор поддерживает арифметические операции со стеком: ADD, MUL, SUB.
Каждая такая операция извлекает из стека два операнда и заносит результат в регистр.

После выполнения последовательности операций программа должна распечатать содержимое регистров.

Входные данные
```
PUSH 1
POP B
```
Выходные данные
```
A = 0
B = 1
C = 0
D = 0
```

Входные данные
```
PUSH 1
PUSH 2
POP B
POP C
PUSH C
POP D
```
Выходные данные
```
A = 0
B = 2
C = 1
D = 1
```

Входные данные
```
PUSH 1
PUSH 2
ADD B
```
Выходные данные
```
A = 0
B = 3
C = 0
D = 0
```

2024-12-09 14:39 UTC, closed without merging