lab_3
Dovgalyuk/Algorithms pull request #1136
Opened 2024-11-27 14:13 UTC by exg0n

2024-11-28 05:47 UTC, Dovgalyuk requested changes

2024-11-28 05:47 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +        std::cerr << "output file error " << argv[2] << std::endl;
Зачем имя входного файла здесь?

2024-11-28 23:11 UTC, exg0n commented on Lab1C/lab1.cpp
> +        std::cerr << "output file error " << argv[2] << std::endl;
В прошлый раз забыл изменить код, оставил argv[2], которого уже не было. Убрал в прошлый раз, так как не понимал, почему программа не билдится. В этот раз пути для ввода и вывода данных передаются через агрументы.

argv[1] - путь к входному файлу
argv[2] - путь к выходному файлу

2024-11-29 05:01 UTC, Dovgalyuk requested changes

2024-11-29 05:01 UTC, Dovgalyuk commented on Lab1C/CMakeLists.txt
> +add_test(NAME TestLab1C COMMAND Lab1C ${CMAKE_CURRENT_SOURCE_DIR}/input.txt ${CMAKE_CURRENT_SOURCE_DIR}/output.txt)
output нужно создавать не в каталоге с исходным кодом.

2024-11-29 05:01 UTC, Dovgalyuk commented on Lab1C/output.txt
Этот файл стоит удалить.

2024-12-02 14:16 UTC, Dovgalyuk commented
Принято.

Следующее задание после защиты.

2024-12-02 14:16 UTC, closed without merging