Lab3
Dovgalyuk/Algorithms pull request #1139
Opened 2024-11-27 20:05 UTC by Nickolay-Varuhin

2024-11-28 05:55 UTC, Dovgalyuk requested changes

2024-11-28 05:55 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +bool poiskpos(const vector<string>& labirint, int stroka, int stolbik) {
Для vector<string> стоит объявить именованный тип.

2024-11-28 05:55 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +}
Стоит проверить ещё такой пример:
```
#######
#X....#
#.....#
#.....#
#.....#
#....Y#
#######
```

2024-11-28 05:55 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +    size_t kon;
Конец очереди можно легко найти, зная начало и размер.

2024-11-29 04:50 UTC, Dovgalyuk commented
Надо не просто тест добавить, а посмотреть, что выдаётся. Соответствует ли это заданию.

2024-12-02 14:38 UTC, closed without merging

2024-12-02 16:04 UTC, Nickolay-Varuhin commented
Здравствуйте, я забыл что у меня был открыт пул реквест, этот после закрытия не открывается, поэтому создам новый