Лабораторная 1 Манилов Тимур
Dovgalyuk/Algorithms pull request #114
Opened 2020-12-24 19:39 UTC by NewExample

2020-12-25 08:44 UTC, Dovgalyuk requested changes

2020-12-25 08:44 UTC, Dovgalyuk commented on LibraryMy/Individual.cpp
> +            if (array_get(arr, i) == array_get(arr, j) && i != j)
Можно ли избавиться от условия i!=j?

2021-01-05 14:46 UTC, NewExample commented
Здравствуйте, я внёс изменения)

2021-01-06 09:28 UTC, Dovgalyuk requested changes

2021-01-06 09:28 UTC, Dovgalyuk commented on LibraryMy/Individual.cpp
> +        for (int j = 0; j < N && i != j; j++)
Что будет выводиться для массива 1 1 1 1 ?

2021-01-07 10:28 UTC, NewExample commented
Здравствуйте, а можете  отослать задание 2 и 3 чтобы я их начал делать

2021-01-09 08:36 UTC, Dovgalyuk commented
1. Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
    2. Решить задачу, используя реализованный стек.
Написать программу, которая с помощью стека проверяет правильность последовательности из скобок вида (), [] и {}. Правильной считается последовательность, где каждой открывающей соответствует ровно одна закрывающая скобка и наоборот. 
В выходной файл напечатать YES, если последовательность правильная и NO, если неправильная.

Вход
`([])`
Выход
YES

Вход
`(]`
Выход
NO

2021-01-09 08:36 UTC, closed without merging