Lab5
Dovgalyuk/Algorithms pull request #1140
Opened 2024-11-28 15:04 UTC by tolstosup

Красный график - insert
Синий график - find 
Зеленый график - remove

Моя реализация
![mySet](https://github.com/user-attachments/assets/93d9f9ef-2779-4adf-a021-b0665b91f77c)
Стандартная реализация 
![stdSet](https://github.com/user-attachments/assets/dcc415d6-ba82-43f5-816c-80bf8ef5192c)

2024-11-29 05:22 UTC, Dovgalyuk requested changes

2024-11-29 05:22 UTC, Dovgalyuk commented on Lab5/lab5.cpp
> +        set.insert(std::to_string(i));
Стоит вынести to_string отсюда, сгенерировав их заранее, чтобы лишние факторы не портили график.

2024-11-29 05:22 UTC, Dovgalyuk commented on LibraryCPPClass/Set.cpp
> +Node* Set::min_node(Node*& node)
Зачем node передавать по ссылке?

2024-11-29 05:22 UTC, Dovgalyuk commented on LibraryCPPClass/Set.cpp
> +void Set::insert(std::string key)
Лучше передавать key по константной ссылке.

2024-11-29 05:22 UTC, Dovgalyuk commented on LibraryCPPClass/Set.cpp
> +void Set::balance_after_insert(Node*& node)
Тут не нужна передача параметра по ссылке.

2024-11-29 05:22 UTC, Dovgalyuk commented on LibraryCPPClass/Set.cpp
> +void Set::rotate_left(Node*& node)
Передача параметра по ссылке не нужна.

2024-11-29 05:22 UTC, Dovgalyuk commented on LibraryCPPClass/Tests/SetTest.cpp
> +        set.find(std::to_string(i));
Нужно проверить, что find вернул правильное значение.
Также и добавить тест на ошибочный поиск.

2024-12-02 14:05 UTC, Dovgalyuk requested changes

2024-12-02 14:05 UTC, Dovgalyuk commented on LibraryCPPClass/Set.cpp
> +void Set::transplant(Node*& root, Node*& u, Node*& v)
По ссылке надо передавать только root.

2024-12-03 15:06 UTC, Dovgalyuk commented
Принято.

2024-12-03 15:06 UTC, closed without merging

2024-12-03 15:11 UTC, tolstosup commented
Здравствуйте! Прошу Вас выдать задание для шестой лабораторной работы.

2024-12-04 13:22 UTC, Dovgalyuk commented
Только после защиты.

2024-12-16 11:23 UTC, Dovgalyuk commented
* Разработать контейнер, реализующий структуру данных «двоичная куча».
* Использовать его для реализации алгоритма Дейкстры.
* Сравнить производительность кучи со стандартным контейнером std::priority_queue для разных объемов входных данных.