lab 5
Dovgalyuk/Algorithms pull request #1154
Opened 2024-12-05 17:12 UTC by ms-anastasiia

2024-12-05 18:01 UTC, ms-anastasiia commented
Задание
![Снимок экрана 2024-12-05 210029](https://github.com/user-attachments/assets/256b1c64-952b-4057-ab15-ebb4a88c5e5d)

2024-12-05 18:04 UTC, ms-anastasiia commented
Графики
![Снимок экрана 2024-12-05 185724](https://github.com/user-attachments/assets/c25648b0-94ad-4ce8-a15b-87630b0ae278)
![Снимок экрана 2024-12-05 185624](https://github.com/user-attachments/assets/60a95ab9-7de5-4c18-ab12-985feb63c4b7)

2024-12-06 05:13 UTC, Dovgalyuk requested changes

2024-12-06 05:13 UTC, Dovgalyuk commented on Lab5CPP/lab5.cpp
> +        array.find(key);
Стоит ещё проверять, нашёлся ли элемент.
Будет дополнительное тестирование.

2024-12-06 05:13 UTC, Dovgalyuk commented on LibraryCPPClass/Tests/Map.cpp
> +}
Не хватает тестов для неуспешного поиска.

2024-12-06 05:13 UTC, Dovgalyuk commented on LibraryCPPClass/Tests/Map.cpp
> +        assert(arr.find("key" + std::to_string(i)) == "value" + std::to_string(i));
assert может удалиться в release-сборке.

2024-12-06 05:13 UTC, Dovgalyuk commented on LibraryCPPClass/Tests/Map.cpp
> +        std::cerr << e.what() << std::endl;
не хватает return 1

2024-12-09 14:31 UTC, Dovgalyuk commented
Принято.

2024-12-09 14:31 UTC, closed without merging