lab1
Dovgalyuk/Algorithms pull request #1165
Opened 2024-12-10 08:20 UTC by Arichteabiscuit

2024-12-10 08:23 UTC, Arichteabiscuit commented
Наконец-то получилось все сделать. Получается, нужно запулить к себе в репозиторий, а потом закрыть старый пул реквест и создать новый. Вроде разобрался, спасибо за терпение.

2024-12-11 16:24 UTC, Dovgalyuk commented
Нужно удалить из репозитория временные файлы (директория out).

2024-12-12 13:49 UTC, Arichteabiscuit commented
удалить все содержимое out?

2024-12-13 07:29 UTC, Dovgalyuk commented
Ну да.

2024-12-16 09:16 UTC, Dovgalyuk requested changes

2024-12-16 09:16 UTC, Dovgalyuk commented on lab1/lab1.cpp
> +    std::cout << std::endl;
В задании сказано, что найденные индексы нужно сохранить в новом массиве.

2024-12-17 06:37 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
* Решить задачу, используя реализованный стек.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Дано выражение в обратной польской записи. Используя стек, написать программу, которая проверяет выражение на наличие ошибок. Ошибкой считается деление на 0 (ZERO), выполнение операции, когда в стеке меньше двух элементов (UNDERFLOW), наличие больше одного элемента в стеке после завершения работы программы (OVERFLOW).

Входные данные
```
1 2 + 3
```
Выходные данные
```
OVERFLOW
```

Входные данные
```
10 9 - +
```
Выходные данные
```
UNDERFLOW
```

2024-12-17 06:37 UTC, closed without merging