Lab4
Dovgalyuk/Algorithms pull request #1169
Opened 2024-12-11 21:13 UTC by Dan-GH-str

- Разработать программный интерфейс модуля (заголовки функций) библиотеки LibraryCPPTemplate для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины,
- получить пометки всех вершин в виде вектора.
- Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
- Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде матрицы смежности в контейнере Vector библиотеки LibraryCPPTemplate.
- Разработать и добавить в проект LibraryCPPTemplate программу, тестирующую работу библиотеки для графа.
- Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать для него минимальное покрывающее дерево алгоритмом Крускала. Использовать систему непересекающихся множеств для поддеревьев в процессе работы алгоритма.
- Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

В решении для алгоритма Крускала я использовал следующий граф:

![graph](https://github.com/user-attachments/assets/aa023ccb-58a6-499f-b3c6-9f3273ed90a9)

Красным цветом отмечены рёбра получившегося минимального покрывающего дерева.

2024-12-12 07:14 UTC, Dovgalyuk requested changes

2024-12-12 07:14 UTC, Dovgalyuk commented on Lab4CPPTemplate/Kruskal.cpp
> +        for (size_t j = 1; j < vertices_count; j++) {
Нужно использовать итератор соседей, а не цикл по всем вершинам.

2024-12-12 07:14 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +    Vector<Vector<Edge>> get_adjacency_matrix() const {
Матрицу обычно не надо отдавать наружу. Достаточно метода "получить ребро".

2024-12-12 07:14 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +            while (index < graph.vertices_count && graph.adjacency_matrix.get(vertex).get(index).label == E()) {
Почему метка со сначением по умолчанию, это отсутствующее ребро? Пользователь вполне может захотеть использовать такие метки (например, рёбра нулевой длины для int).

2024-12-13 08:04 UTC, Dovgalyuk requested changes

2024-12-13 08:04 UTC, Dovgalyuk commented on Lab4CPPTemplate/Kruskal.cpp
> +            if (i < j) {    // avoid duplicates in undirected graph
Это непонятно.

2024-12-13 08:04 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +    E get_edge_label(V from_label, V to_label) const {
Лучше константную ссылку возвращать, чтобы не было лишних копирований для сложных типов.

2024-12-13 08:04 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +    V get_vertex_label(size_t vertex) const {
Тут тоже можно вернуть константную ссылку.

2024-12-13 08:04 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +    Vector<V> get_vertices_labels() const {
Тоже можно не копировать.

2024-12-17 16:41 UTC, Dan-GH-str commented on Lab4CPPTemplate/Kruskal.cpp
> +            if (i < j) {    // avoid duplicates in undirected graph
Здесь i и j - порядковые номера вершин, которые не зависят от их названий.  И в данном случае они используются следующим образом: если порядковой номер (индекс) первой вершины больше порядкового номера второй вершины, значит наличие ребра между этими вершинами мы либо уже проверили, либо еще проверим в следующих итерациях. Причина такого явления - дублирование информации о ребре в матрице смежности для неориентированного графа. И так как для поиска всех рёбер я прохожу по этой матрице смежности, моя задача - избегать внесение дублирующихся рёбер в результирующий вектор.

Для наглядности я изобразил в прикреплённом рисунке элементы таблицы смежности, которые повторяются для неориентированного графа. В этом я случае, если мы уже выявили наличие ребра между 1 и 3 вершиной, то далее нет смысла проверять наличие ребра между 3 и 1 вершиной ( j > i ):

![8](https://github.com/user-attachments/assets/125d5dd3-83f0-4042-9fb1-8f1d909dad88)

Таким образом, мы проверяем только элементы, находящиеся выше проведенной диагонали, избегая дубликатов:

![1](https://github.com/user-attachments/assets/4875d0a1-d467-44d6-8461-fbd0767f8fe7)

2024-12-18 05:39 UTC, Dovgalyuk commented
Во всех последних исправлениях ссылка должна возвращаться константная. Хотя бы потому, что это делает константный метод.

2024-12-18 05:41 UTC, Dovgalyuk commented on Lab4CPPTemplate/Kruskal.cpp
> +                if (graph.has_edge(u, v)) {
А эта проверка зачем?

2024-12-18 20:20 UTC, Dan-GH-str commented on Lab4CPPTemplate/Kruskal.cpp
> +                if (graph.has_edge(u, v)) {
Здесь происходит проверка наличия ребра между вершиной с названием "u" и вершиной с названием "v". Если ребро присутствует - информация о нем передаётся в результирующий вектор рёбер "edges", который в конце концов должен содержать в себе информацию о всех рёбрах графа. Далее по алгоритму эта информация используется для составления минимального покрывающего дерева.

2024-12-19 05:59 UTC, Dovgalyuk commented on Lab4CPPTemplate/Kruskal.cpp
> +                if (graph.has_edge(u, v)) {
Тут же и так перебираются соседи, значит ребро существует.

2024-12-20 06:01 UTC, Dovgalyuk commented
Принято.

* Разработать интерфейс (набор функций) для ассоциативного массива, который хранит пары (ключ)строка -> (значение)строка. Поддерживаемые операции: добавить пару ключ-значение, найти значение по ключу, удалить значение по ключу.
* Реализовать контейнер на основе splay tree, реализующий разработанный интерфейс.
* Создать тест для проверки работы контейнера. Программа должна включать в себя нагрузочное тестирование для исключения ошибок, приводящих к сложности работы O(N*N) при поиске, удалении или добавлении значений.
* Написать генератор входных данных различного объема для этого контейнера.
* Сравнить скорость выполнения операции добавления в контейнер содержимого файла со стандартным контейнером std::map при различных объемах данных. Построить график зависимости времени работы от объёма входных данных и оценить характер зависимости.
* Добавить тест в CMakeLists.txt, который запускает разработанную программу.

2024-12-20 06:01 UTC, closed without merging