Lab4
Dovgalyuk/Algorithms pull request #1170
Opened 2024-12-12 13:19 UTC by EKATERINAelnova

2024-12-12 14:00 UTC, EKATERINAelnova commented
![graph](https://github.com/user-attachments/assets/2961854e-f622-4e7b-8b4f-0e2db904a726)

2024-12-13 07:55 UTC, Dovgalyuk requested changes

2024-12-13 07:55 UTC, Dovgalyuk commented on Lab4CPP/lab4.cpp
> +            return d;
Надо искать путь, а не длину пути.

2024-12-13 07:55 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +    void removeVertex(size_t vertex) {
А что будет со связями, которые ссылаются на номера вершин, которые больше, чем vertex?

2024-12-13 07:55 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +                insert(current->dataa);
Получится список в обратном порядке.

2024-12-13 07:55 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +    size_t size;
Списку не нужен размер.

2024-12-20 05:58 UTC, Dovgalyuk requested changes

2024-12-20 05:58 UTC, Dovgalyuk commented on Lab4CPP/lab4.cpp
> +vector<size_t> dijkstra(Graph<V, E>& graph, size_t start, size_t end) {
```vector<size_t>``` написано несколько раз

2024-12-20 05:58 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +            current = current->next();
Этот элемент уже удалён, у него нельзя получить next.

2024-12-20 05:58 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +    void removeVertex(size_t vertex) {
Этот вопрос остался.

2025-01-20 07:48 UTC, closed without merging