Lab3
Dovgalyuk/Algorithms pull request #1182
Opened 2024-12-16 04:08 UTC by kitheok

2024-12-16 11:13 UTC, Dovgalyuk requested changes

2024-12-16 11:13 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +    if (start.x < 0 || start.y < 0 || static_cast<size_t>(start.x) >= rows || static_cast<size_t>(start.y) >= cols) {
Не надо буквой x обозначать номер строки, это запутывает.

2024-12-16 11:13 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +}
Пример лабиринта:
```
#####
#X..#
#...#
#...#
#...#
#...#
#..Y#
#####
```

2024-12-18 20:49 UTC, kitheok commented on Lab3CPP/lab3.cpp
> +    if (start.x < 0 || start.y < 0 || static_cast<size_t>(start.x) >= rows || static_cast<size_t>(start.y) >= cols) {
Исправлено. Вместо x и y теперь row и col

2024-12-19 06:01 UTC, Dovgalyuk commented
Должен получаться кратчайший путь, а не все заполненные клетки.

2024-12-20 06:13 UTC, Dovgalyuk commented
Принято.

* Разработать программный интерфейс модуля (заголовки функций) библиотеки LibraryCPPTemplate для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины,
получить пометки всех вершин в виде вектора.
* Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
* Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List библиотеки LibraryCPPTemplate.
* Разработать и добавить в проект LibraryCPPTemplate программу, тестирующую работу библиотеки для графа.
* Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать в нем все кратчайшие пути между заданной парой вершин с помощью обхода в ширину.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

2024-12-20 06:13 UTC, closed without merging