Lab3
Dovgalyuk/Algorithms pull request #1183
Opened 2024-12-16 05:14 UTC by sudo-odner

Лабораторная №2 Ильин Данила Александрович, гр.3091

https://github.com/Dovgalyuk/Algorithms/pull/1092#issuecomment-2536517618

2024-12-16 11:17 UTC, Dovgalyuk commented on Lab3/lab3.cpp
> +    std::vector<Queue*> area;
Лабиринт не надо хранить в виде очередей. Либо один вектор, либо вектор векторов.

2024-12-16 11:19 UTC, Dovgalyuk commented on LibraryCPPClass/queue.cpp
> +        }
Сдвигать при каждом insert не нужно, очередь должна работать как кольцевой буфер.

2024-12-23 08:55 UTC, sudo-odner commented
Здравствуйте, когда мне можно будет задать практику?

2024-12-23 09:26 UTC, Dovgalyuk requested changes

2024-12-23 09:26 UTC, Dovgalyuk commented on Lab3/lab3.cpp
> +        for (std::vector<Data> areaY : area) {
Тут копируется строка, а потом очищается копия.
А вообще весь этот код не нужен, потому что у вектора есть деструктор.

2024-12-23 09:26 UTC, Dovgalyuk commented on Lab3/lab3.cpp
> +            std::vector<Data> areaY;
Для этого типа не помешает typedef.

2024-12-23 09:26 UTC, Dovgalyuk commented on Lab3/lab3.cpp
> +                    areaY.push_back(-2);
Тут не помешают именованные константы.

2024-12-23 09:26 UTC, Dovgalyuk commented on Lab3/lab3.cpp
> +            int directions[4][2] = {{-1, 0}, {1, 0}, {0, -1}, {0, 1}};
Этот массив повторяется.

2024-12-23 09:26 UTC, Dovgalyuk commented on LibraryCPPClass/queue.cpp
> +            _queue->set(idx_front, bufData);
Как-то многовато пересылок. Что здесь происходит?

2024-12-23 09:26 UTC, Dovgalyuk commented on LibraryCPPClass/queue.cpp
> +    _back = 0;
_back можно вычислить, зная _front и _size.

2025-01-12 13:15 UTC, sudo-odner commented on LibraryCPPClass/queue.cpp
> +            _queue->set(idx_front, bufData);
Если у нас кольцевой массив достиг максимума, в то время когда мы пытаемся добавить еще один элемент, мы нормализуем его. 
1. Мы сдвигаем front в начало (меняем местами front и первый элемент)
2. Пересоздаем массив (увеличиваем его cap в 2 раза)
3. Добавляем новый элемент (после back)
Это позволяет безопасно добавить новый элемент в расширенный массив в ситуации когда front в середине. С нормализацией добавление в переполненый цикловой массив выглядит так:
[data, front, back, data] -> [front, data, data, back] -> [front, data, data, back, empty, empty, empty, empty]

2025-01-12 13:23 UTC, sudo-odner commented
Исправил, написал пояснение к предпоследнему недочету

2025-01-20 06:24 UTC, Dovgalyuk commented
Принято, но насчёт Queue::insert всё ещё есть сомнения.

2025-01-20 06:24 UTC, closed without merging