4lab
Dovgalyuk/Algorithms pull request #1184
Opened 2024-12-16 10:45 UTC by Dethord-hub

2024-12-17 06:34 UTC, Dovgalyuk requested changes

2024-12-17 06:34 UTC, Dovgalyuk commented on Lab4CPP/lab4.cpp
> +vector<vector<int>> floydWarshall(const Graph<int, int>& g) {
Не хватает typedef для повторяющихся типов.

2024-12-17 06:34 UTC, Dovgalyuk commented on back
А эти файлы откуда?

2024-12-17 06:34 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +        }
В итоге список получится перевёрнутый.

2024-12-17 06:34 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +    std::vector<List<std::pair<size_t, EdgeType>>> adjacencyList_;
Вместо pair стоит завести собственную структуру.

2024-12-17 06:34 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +}
Не нужно ли изменить идентификаторы вершин в рёбрах после удаления одной вершины из середины графа?

2024-12-17 06:34 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +                adjacencyList_[i].erase_next(item);
Почему удаляется не item, а следующий элемент списка?

2024-12-17 06:34 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +            adjacencyList_[from].erase_next(item->prev());
А если нужно удалить первое в списке ребро?

2024-12-17 06:34 UTC, Dovgalyuk commented on LibraryCPPTemplate/Tests/graph.cpp
> +    assert(labels[4] == 5);
Нужно заменить assert на собственную реализацию, потому что стандартный удаляется в релизной сборке.

2024-12-17 06:47 UTC, Dethord-hub commented on back
Эти файлы остаются после 2 или 3 лабы, я их удалю, т.к. не совсем понимаю причину их появления...

2024-12-17 06:48 UTC, Dethord-hub commented on LibraryCPPTemplate/graph.h
> +}
Понял, исправим

2024-12-18 05:51 UTC, Dovgalyuk requested changes

2024-12-18 05:51 UTC, Dovgalyuk commented on Lab4CPP/lab4.cpp
> +vector<vector<int>> floydWarshall(const Graph<int, int>& g) {
Это осталось.

2024-12-18 05:51 UTC, Dovgalyuk commented on Lab4CPP/lab4.cpp
> +    readGraph(g, "input.txt");
Файл нужно открывать тот, что передан в качестве параметра.

2024-12-18 05:51 UTC, Dovgalyuk commented on LibraryCPPTemplate/Tests/graph.cpp
> +        std::cerr << "Тест провален: ребро (0, 1) не найдено" << std::endl;
Не хватает ненулевого кода возврата для программы.

2024-12-18 05:51 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +        std::pair<size_t, EdgeType> operator*() const {
Здесь всё ещё pair.

2024-12-18 05:51 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +            adjacencyList_[from].erase_next(item->prev());
Всё ещё не сработает для первого ребра.

2024-12-19 05:34 UTC, Dovgalyuk requested changes

2024-12-19 05:34 UTC, Dovgalyuk commented on Lab4CPP/lab4.cpp
> +vector<vector<int>> floydWarshall(const Graph<int, int>& g) {
Пока ещё осталось.

2024-12-19 05:34 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +                adjacencyList_[i].erase_next(item->prev());
Тут невозможно удалить первый элемент списка.

2024-12-19 05:34 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +        item = item->next();
Если item - первый элемент, то его уже не существует, и нельзя получить next.

2024-12-20 05:52 UTC, Dovgalyuk requested changes

2024-12-20 05:52 UTC, Dovgalyuk commented on Lab4CPP/lab4.cpp
> +void readGraph(Graph<Data, Data>& g, const string& filename) {
Здесь написано ```Graph<Data, Data>``` и в 33 строчке то же самое. Этот тип можно объявить единожды.

2024-12-20 05:52 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +        item = item->next();
erase уже вернул следующий элемент

2025-01-20 07:49 UTC, closed without merging