Lab_3
Dovgalyuk/Algorithms pull request #1193
Opened 2024-12-20 11:52 UTC by tolik124

2024-12-23 09:05 UTC, Dovgalyuk requested changes

2024-12-23 09:05 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +    int arr[9];
В массив считывать содержимое файла не нужно.

2024-12-24 05:49 UTC, Dovgalyuk commented
Сборка не проходит.

2024-12-26 06:20 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +    std::vector<int> arr(9);
Лишние массивы ещё остались.

2025-01-10 18:52 UTC, tolik124 commented
Можно узнать насчет работы, принято или нет?

2025-01-20 06:19 UTC, Dovgalyuk commented
Не принято. Программа работает только для 9 элементов.

2025-01-20 06:19 UTC, closed without merging