Лабораторная работа 4
Dovgalyuk/Algorithms pull request #120
Opened 2021-01-02 01:00 UTC by Znoleg

Реализовал hash map на основе хэш таблицы. Т.к реализовал map, то и производительность сравнивается с std::unordered_map. Не сразу понял что надо реализовать сет, так что надеюсь, что сможете принять и мапку

2021-01-04 07:44 UTC, Dovgalyuk requested changes

2021-01-04 07:44 UTC, Dovgalyuk commented on LibraryCPPTemplate/IContainer.h
> +struct IContainer
Очень полезно в таких случаях (когда есть виртуальные функции) деструктор тоже делать виртуальным.

2021-01-04 07:44 UTC, Dovgalyuk commented on LibraryCPPTemplate/HashMap.h
> +			if (index == _nodes.size() - 1)
Почему бы не "заворачивать" обход по кругу, как с кольцевым буфером?

2021-01-04 07:44 UTC, Dovgalyuk commented on LibraryCPPTemplate/HashMap.h
> +			if (node->pair.key == key && node->status == NodeStatus::Empty)
Почему здесь empty?

2021-01-04 07:44 UTC, Dovgalyuk commented on LibraryIndividual/HashGenerator.cpp
> +		output << hash_map.Find(std::to_string(i));
Измерения сильно зависят от работы с диском. Надо сохранять результат в памяти, а потом отдельно записывать на диск, когда таймер уже остановлен.

2021-01-04 07:44 UTC, Dovgalyuk commented on LibraryIndividual/HashGenerator.cpp
> +	cout << "Unordered find time: " << static_cast<double>(end - start) / CLOCKS_PER_SEC << endl;
Ещё нужны результаты тестирования в зависимости от числа добавляемых записей.

2021-01-04 07:44 UTC, Dovgalyuk commented on LibraryCPPTemplate/HashMap.h
> +struct Pair
Вроде бы от этого типа нет пользы.

2021-01-06 09:25 UTC, Dovgalyuk commented
Также не хватает результатов тестирования на производительность.

2021-01-09 08:06 UTC, Dovgalyuk requested changes

2021-01-09 08:06 UTC, Dovgalyuk commented on LibraryCPPTemplate/HashMap.h
> +            if (condition(node, key)) return index;
Пропало условие остановки в случае пустой ячейки.

2021-01-09 08:06 UTC, Dovgalyuk commented on LibraryCPPTemplate/HashMap.h
> +        MyFunc* condition;
Лучше сразу функцию и передавать в качестве параметра.

2021-01-09 11:10 UTC, Znoleg commented on LibraryCPPTemplate/HashMap.h
> +            if (condition(node, key)) return index;
Не совсем понял о каком условии идёт речь. Сами условия не менялись, а только переместились в _conditions[]

2021-01-10 23:22 UTC, Znoleg commented on LibraryCPPTemplate/HashMap.h
> +            if (condition(node, key)) return index;
А можно получить лабораторную 5, если тут останутся недочёты, параллельно разбираясь с ними? Хотелось бы пятую успеть сделать

2021-01-11 09:37 UTC, Dovgalyuk commented on LibraryCPPTemplate/HashMap.h
> +            if (condition(node, key)) return index;
> Не совсем понял о каком условии идёт речь. Сами условия не менялись, а только переместились в _conditions[]

Если условие не сработало, поиск будет продолжен.
Хотя если встречена пустая ячейка, пора остановиться - ничего найти уже не удастся.

2021-01-11 09:38 UTC, Dovgalyuk commented on LibraryCPPTemplate/HashMap.h
> +        _conditions[0] = [](Node& node, string& key) {return node.status != NodeStatus::Full; }; // could do this in find_index() but doing it here gives us 0.001 boost :)
Теперь и сам массив можно выкинуть.

2021-01-12 07:00 UTC, Dovgalyuk commented
1. Разработать программный интерфейс модуля (заголовки функций) для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
    2. Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
    3. Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде матрицы смежности в контейнере Vector той же библиотеки.
    4. Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать в нем кратчайшие пути для заданной пары вершин с помощью алгоритма Дейкстры.

2021-01-12 07:00 UTC, closed without merging