list 6
Dovgalyuk/Algorithms pull request #123
Opened 2021-01-04 17:59 UTC by sergeychaliy2

2021-01-06 09:12 UTC, Dovgalyuk requested changes

2021-01-06 09:12 UTC, Dovgalyuk commented on grap/interface.h
> +	vector <unsigned int> vertexList;				//������ ������ �����
Все эти данные должны быть private.

2021-01-06 09:12 UTC, Dovgalyuk commented on grap/graph.cpp
> +		adjacencyList.erase(adjacencyList.begin() + posVert);
Память от списка тоже надо освобождать.

2021-01-06 09:12 UTC, Dovgalyuk commented on grap/minvertex/main.cpp
> +		cout << "����" << endl;
Ещё неплохо бы перевести интерфейс в UTF-8 или на английский, потому что так через гитхаб русский текст не читается.

2021-01-09 08:52 UTC, Dovgalyuk requested changes

2021-01-09 08:52 UTC, Dovgalyuk commented on grap/minvertex/main.cpp
> +		ListItem *item = NULL;
По-прежнему это не итератор.

2021-01-09 08:52 UTC, Dovgalyuk commented on grap/graph.cpp
> +		adjacencyList.erase(adjacencyList.begin() + posVert);
-

2021-01-11 09:11 UTC, Dovgalyuk commented
Остался недочёт с освобождением памяти.

2021-01-11 09:12 UTC, Dovgalyuk commented
И класс Interface занимается дублированием данных, его вообще стоит удалить.

2021-01-11 09:14 UTC, sergeychaliy2 commented
хорошо

2021-01-12 06:52 UTC, Dovgalyuk commented
Остался недочёт с освобождением памяти.

2021-01-15 09:02 UTC, closed without merging