Laba 2 vers1.0
Dovgalyuk/Algorithms pull request #124
Opened 2021-01-06 13:57 UTC by Werwolf2085

2021-01-09 08:22 UTC, Dovgalyuk requested changes

2021-01-09 08:22 UTC, Dovgalyuk commented on IndividualTask/main.cpp
> +    if (second_part.length() == 1 && map.find(second_part[0]) != map.end()){
Длину можно было бы и не проверять.

2021-01-09 08:22 UTC, Dovgalyuk commented on IndividualTask/main.cpp
> +        stack.push(strtol(second_part.data(), &end, 10));
Вместо data лучше использовать c_str, потому что data не обязательно содержит терминальный 0.

2021-01-09 08:22 UTC, Dovgalyuk commented on IndividualTask/main.cpp
> +    Stack<int> processor_stack = Stack<int>();
Раз уж мы ничего не делаем с числами, можно хранить сразу строки.

2021-01-09 20:23 UTC, Werwolf2085 commented
Здравствуйте
так а вы мне дадите следущее задание?
или не что то поменять надо
все же работает

2021-01-11 09:15 UTC, Dovgalyuk commented
1. Реализовать в проекте Library массив переменного размера (модуль vector) и очередь на основе этого массива (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
    2. Решить задачу, используя реализованную очередь.
Во входном файле записано количество вершин и матрица смежности ориентированного графа. Вывести в выходной файл список расстояний от первой вершины до всех остальных. Для вычисления расстояний использовать поиск в ширину.

Вход
```
4
0 1 0 0
0 0 1 1
1 0 0 1
0 1 0 0
```

Выход
```
0
1
2
2
```

2021-01-11 09:15 UTC, closed without merging