Лаб. 4 Алентьев. А
Dovgalyuk/Algorithms pull request #126
Opened 2021-01-07 15:55 UTC by TesaroTawer

![image](https://user-images.githubusercontent.com/60851441/103913650-d684ed00-5119-11eb-90d2-fac63fc48b20.png)

2021-01-09 08:45 UTC, Dovgalyuk requested changes

2021-01-09 08:45 UTC, Dovgalyuk commented on LibraryCPP/splay_tree.cpp
> +Node* find(Node* root,  const Key key)
А где же здесь splay?

2021-01-09 08:45 UTC, Dovgalyuk commented on LibraryCPP/splay_tree.h
> +void right_rotate(Node* root, Node* node);
Вроде бы эти функции не нужны в интерфейсе дерева.

2021-01-09 08:45 UTC, Dovgalyuk commented on IndividualTask4/main.cpp
> +    end = clock();
Можно попробовать все действия-измерения делать по два раза, чтобы убедиться, что никакой троттлинг не мешает.
Вроде такого: myset/set/myset/set

2021-01-09 11:35 UTC, TesaroTawer commented
![image](https://user-images.githubusercontent.com/60851441/104090446-ea4e6180-5287-11eb-929c-6d2053445c0b.png)

2021-01-11 08:28 UTC, Dovgalyuk commented
Про измерения я имел в виду немного не это, ну да ладно.

Следующее задание:

    1. Разработать программный интерфейс модуля (заголовки функций) для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
    2. Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
    3. Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List той же библиотеки.
    4. Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать для него минимальное покрывающее дерево алгоритмом Крускала.

2021-01-11 08:28 UTC, closed without merging