Задание 3
Dovgalyuk/Algorithms pull request #129
Opened 2021-01-09 06:44 UTC by Procrastin4tor

1. Реализован односвязный список (модуль list);
2. На основе списка реализована очередь (модуль queue);
3. Решена задача с использованием волнового алгоритма и очереди (IndividualTask3).

2021-01-09 09:16 UTC, Dovgalyuk requested changes

2021-01-09 09:16 UTC, Dovgalyuk commented on IndividualTask3/main.cpp
> +			if ((x - 1) >= 0 && (x - 1) < row && (path[x - 1][y] == path[x][y] - 1))
Разве x-1 может превысить row?

2021-01-11 08:24 UTC, Dovgalyuk commented
Может в этом файле найдётся ещё несколько избыточных условий?

2021-01-12 07:19 UTC, Dovgalyuk requested changes

2021-01-12 07:19 UTC, Dovgalyuk commented on IndividualTask3/main.cpp
> +			if (path[x - 1][y] == path[x][y] - 1)
А это условие не было избыточным, ведь при вычитании может получиться значение меньше нуля.

2021-01-12 07:43 UTC, Procrastin4tor commented on IndividualTask3/main.cpp
> +			if (path[x - 1][y] == path[x][y] - 1)
Всё верно, отправил вам,не сохранив изменения. Эти условия удалил по ошибке

2021-01-12 07:50 UTC, Dovgalyuk commented
Стоит проверить все условия. Переполнение в большую сторону тоже возможно.

2021-01-12 08:03 UTC, Dovgalyuk commented
Работа с массивами есть и в других местах.

2021-01-12 08:36 UTC, Dovgalyuk commented
1. Разработать интерфейс (набор функций) для ассоциативного массива, который хранит пары (ключ)строка -> (значение)строка. Поддерживаемые операции: добавить пару ключ-значение, найти значение по ключу, удалить значение по ключу.
    2. Реализовать ассоциативный массив на основе бинарного дерева поиска.
    3. Написать генератор входных данных различного объема для этого контейнера, измерить среднюю скорость добавления значений и поиска в нём.
    4. Доработать бинарное дерево, чтобы оно стало самобалансирующимся АВЛ-деревом. 
    5. Измерить скорость добавления значений и поиска в доработанном дереве.

2021-01-12 08:36 UTC, closed without merging