laba2 v1 Manilov Timur
Dovgalyuk/Algorithms pull request #132
Opened 2021-01-10 03:23 UTC by NewExample

laba2 v1

2021-01-11 09:06 UTC, Dovgalyuk requested changes

2021-01-11 09:06 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +//ListItem *list_erase(List *list, ListItem *item)
Эту функцию тоже нужно реализовать.

2021-01-11 09:06 UTC, Dovgalyuk commented on LibraryMy/Individual2.cpp
> +	else cout << "NO";
Как насчёт входной строки "[[["?

2021-01-11 09:06 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    delete list->head;
Нужно освободить память от всех элементов и от самой структуры list.

2021-01-11 19:43 UTC, NewExample commented on LibraryCPP/list.cpp
> +//ListItem *list_erase(List *list, ListItem *item)
У нас же односвязный список, в заголовочном написано что для односвязного функция невозможна

2021-01-12 07:21 UTC, Dovgalyuk commented on LibraryMy/Individual2.cpp
> +	else cout << "NO";
Вопрос остался.

2021-01-12 07:21 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    delete list->head;
Вопрос остался.

2021-01-12 07:23 UTC, Dovgalyuk commented
Нужно работать в том же пулреквесте, а не создавать новый.

2021-01-12 07:23 UTC, closed without merging