Fourth task
Dovgalyuk/Algorithms pull request #133
Opened 2021-01-10 21:30 UTC by 3minbb

2021-01-11 09:25 UTC, Dovgalyuk requested changes

2021-01-11 09:25 UTC, Dovgalyuk commented on LibraryCPP/queue.h
> +		}
vector будет бесконечно увеличиваться, даже если в его начале есть неиспользуемые элементы. Нужно реализовать кольцевой буфер.

2021-01-11 09:25 UTC, Dovgalyuk commented on LibraryCPP/vector.h
> +			new_size = size > Size * 2 ? size : Size * 2;
Чтобы видимый пользователю размер массива совпадал с тем, что он запрашивал, нужно хранить дополнительное поле, которое бы описывало количество реально используемых элементов вектора.

2021-01-11 09:25 UTC, Dovgalyuk commented on newtask/QueueTask.cpp
> +bool find_elem(Vector* vec, char to_check, size_t& index, size_t& element_count)
Почему бы не сделать массив из 26 элементов, где индекс - это буква? Тогда нужно будет просто обратиться к нему, а не искать в цикле совпадение.

2021-01-12 07:11 UTC, Dovgalyuk requested changes

2021-01-12 07:11 UTC, Dovgalyuk commented on newtask/QueueTask.cpp
> +const unsigned asciiDiff = 65;
Лучше 'A' вместо 65.

2021-01-12 07:11 UTC, Dovgalyuk commented on LibraryCPP/queue.h
>  	void Remove()
Теперь его сложность работы O(N).
Правильно будет сделать нормальный кольцевой буфер.

2021-01-12 07:11 UTC, Dovgalyuk commented on LibraryCPP/vector.h
> +	void Resize(size_t capacity)
resize должен менять size. Capacity - только, если размера не хватает.

2021-01-19 00:54 UTC, 3minbb commented
Исправил

2021-01-20 06:39 UTC, Dovgalyuk commented on LibraryCPP/queue.h
> +	if (!IsEmpty)
здесь, вероятно, потерялся вызов функции

2021-01-20 06:41 UTC, Dovgalyuk commented
1. Разработать интерфейс (набор функций) для ассоциативного массива, который хранит пары (ключ)строка -> (значение)строка. Поддерживаемые операции: добавить пару ключ-значение, найти значение по ключу, удалить значение по ключу.
    2. Реализовать ассоциативный массив на основе бинарного дерева поиска.
    3. Написать генератор входных данных различного объема для этого контейнера, измерить среднюю скорость добавления значений и поиска в нём.
    4. Доработать бинарное дерево, чтобы оно стало самобалансирующимся АВЛ-деревом. 
    5. Измерить скорость добавления значений и поиска в доработанном дереве.

2021-01-20 06:41 UTC, closed without merging

2021-01-21 05:51 UTC, 3minbb commented
А лабораторных, которые я сдал хватает на 4? Или нужно еще успеть до экзамена?

2021-01-21 06:58 UTC, Dovgalyuk commented
Нужно успеть что-то сделать ещё и по этой.