Lab 3 is ready
Dovgalyuk/Algorithms pull request #134
Opened 2021-01-10 23:16 UTC by Xhaver

2021-01-11 09:34 UTC, Dovgalyuk requested changes

2021-01-11 09:34 UTC, Dovgalyuk commented on PersonalExercise/Lab2.cpp
> +}
Нужно добавить уничтожение стека.

2021-01-11 09:34 UTC, Dovgalyuk commented on PersonalExercise/Lab2.cpp
> +	if (good) cout << "YES";
Стоит проверить тест "[[[".

2021-01-12 07:03 UTC, Dovgalyuk commented
In file included from LibraryCPPTemplate/array.cpp:1:
LibraryCPPTemplate/array.h:10:17: error: expected ‘)’ before ‘size’
   10 |     Array(size_t size);

2021-01-15 08:42 UTC, Dovgalyuk commented
LibraryCPPTemplate/array.h:16:14: error: ‘size_t’ is not a type
   16 |     Data get(size_t index) const;

2021-01-18 09:22 UTC, Dovgalyuk commented
Ошибка осталась.

2021-01-20 06:37 UTC, Dovgalyuk commented
Стоит попробовать собрать весь проект, как описано в readme, потому что ошибка всё ещё есть.

2021-01-20 23:23 UTC, Xhaver commented
> Стоит попробовать собрать весь проект, как описано в readme, потому что ошибка всё ещё есть.

Дело в том, что он собран и работает.
Поэтому приходится исправлять наугад.

2021-01-21 06:42 UTC, Dovgalyuk commented
Вот что ещё компилятор пишет:

array.h:1:1: note: ‘size_t’ is defined in header ‘<cstddef>’; did you forget to ‘#include <cstddef>’?
  +++ |+#include <cstddef>

2021-01-25 11:08 UTC, Dovgalyuk commented
```
LibraryCPP/array.h:11:21: error: ‘size_t’ was not declared in this scope
   11 | Array *array_create(size_t size);
```

2021-01-26 13:21 UTC, closed without merging