Индивидуальное задание 4
Dovgalyuk/Algorithms pull request #135
Opened 2021-01-11 06:20 UTC by Lapohuy

```
1. Разработать интерфейс (набор функций) для ассоциативного массива, который хранит пары (ключ)строка -> (значение)строка. Поддерживаемые операции: добавить пару ключ-значение, найти значение по ключу, удалить значение по ключу.
2. Реализовать ассоциативный массив на основе хэш-таблицы с открытой адресацией. Таблица должна поддерживать расширение при большой доле заполненных ячеек.
3. Написать генератор входных данных различного объема для этого контейнера. Сравнить скорость выполнения операции добавления в контейнер содержимого файла для хэш-таблицы и для std::unordered_map при различных объемах данных.
```

Создан ассоциативный массив на основе хэш-таблицы с открытой адресацией по методу линейного пробирования
![image](https://user-images.githubusercontent.com/61329224/104151466-2a2f5900-53ee-11eb-81c5-06793da9ca46.png)

2021-01-11 09:50 UTC, Dovgalyuk requested changes

2021-01-11 09:50 UTC, Dovgalyuk commented on LibraryCPP/hashtable.cpp
> +	int item_state; // giving state can be 0, 1 or 2
Вместо 012 лучше сделать именованные константы. Например, через enum.

2021-01-11 09:50 UTC, Dovgalyuk commented on LibraryCPP/map.cpp
> +		if ((get_key(map->table, hash) == key) && (get_state(map->table, hash) == 1))
Если попалась "совсем пустая" ячейка, то нужно останавливаться с неудачей.

2021-01-11 09:53 UTC, Lapohuy commented on LibraryCPP/hashtable.cpp
> +	int item_state; // giving state can be 0, 1 or 2
Принято. Я долго голову ломал, как присвоить ровно три значения, а об энаме как-то забыл. Сейчас пофикшу

2021-01-11 09:55 UTC, Lapohuy commented on LibraryCPP/map.cpp
> +		if ((get_key(map->table, hash) == key) && (get_state(map->table, hash) == 1))
Принято, сейчас поправлю

2021-01-11 10:59 UTC, Lapohuy commented
Гитхаб десктоп начал производить какие-то очень странные действия. Смотрите только фикс 4 лабы, пожалуйста. Оба замечания в нем учтены.

2021-01-12 06:57 UTC, Dovgalyuk commented
1. Разработать программный интерфейс модуля (заголовки функций) для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
    2. Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
    3. Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List той же библиотеки.
    4. Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать для него минимальное покрывающее дерево алгоритмом Прима.

2021-01-12 06:57 UTC, closed without merging