Laba3
Dovgalyuk/Algorithms pull request #138
Opened 2021-01-14 21:28 UTC by Werwolf2085

2021-01-15 08:57 UTC, Dovgalyuk requested changes

2021-01-15 08:57 UTC, Dovgalyuk commented on LibraryCPP/queue.h
> +    Vector<T>* _inner_vector;
Можно сделать просто переменной, указатель здесь не нужен.

2021-01-15 08:57 UTC, Dovgalyuk commented on LibraryCPP/queue.h
> +        _inner_vector->erase(0);
Так удаление будет работать за O(N).
Нужно реализовать кольцевой буфер.

2021-01-15 22:09 UTC, Werwolf2085 commented on LibraryCPP/queue.h
> +        _inner_vector->erase(0);
Первую ошибку я поправил
А вот второе переделывать очень долго, а времени мало, в задании просто про кольцевой буфер ничего не было сказано.

2021-01-18 09:18 UTC, Dovgalyuk commented on LibraryCPP/queue.h
> +        _inner_vector->erase(0);
Можно без кольцевого буфера. Только надо не тратить бесконечный объем памяти, а также обеспечить время работы операций порядка O(1).

2021-01-18 09:19 UTC, Dovgalyuk requested changes

2021-01-18 09:19 UTC, Dovgalyuk commented on LibraryCPP/queue.h
> -// Should be O(1) on average
Вот искомое требование.

2021-01-20 06:33 UTC, Dovgalyuk commented
Проект не компилируется по инструкции из readme

2021-01-25 10:43 UTC, closed without merging