Шиков Кирилл Дмитриевич 0091: Первое задание (Ремейк)
Dovgalyuk/Algorithms pull request #200
Opened 2021-09-09 06:35 UTC by NovolMob

2021-09-10 05:43 UTC, Dovgalyuk requested changes

2021-09-10 05:43 UTC, Dovgalyuk commented on Algorithms/First/test.cpp
> +#include "array.cpp"
Надо подключать заголовочный файл, а не cpp.

2021-09-10 05:43 UTC, Dovgalyuk commented on Algorithms/First/test.cpp
> +    return 0;
В конце надо уничтожать массив.

2021-09-10 10:20 UTC, NovolMob commented on Algorithms/First/test.cpp
> +    return 0;
Исправил

2021-09-10 10:21 UTC, NovolMob commented on Algorithms/First/test.cpp
> +#include "array.cpp"
Исправил

2021-09-13 04:24 UTC, Dovgalyuk commented
1. Реализовать в проекте Library двусвязный список (модуль list) и стек на основе этого списка (модуль stack).

2. Решить задачу, используя реализованный стек.

Во входном файле записана последовательность тегов в формате HTML. Каждый тег расположен на отдельной строке.
Используя стек, проверить правильность этой последовательности. Вывести в выходной файл YES, если последовательность корректна и NO, если нет.


Вход

```
<html>
<body>
</Body>
</HTML>
```

Выход
```
YES
```

Вход
```
<html>
</body>
```

Выход
```
NO
```

2021-09-13 04:24 UTC, closed without merging