Гуревич Кирилл Михайлович - 0092 - решение второй задачи
Dovgalyuk/Algorithms pull request #204
Opened 2021-09-10 15:50 UTC by Kirilliriks

Решение в папке Result, файл laboratorytwo.cpp

2021-09-13 06:35 UTC, Dovgalyuk requested changes

2021-09-13 06:35 UTC, Dovgalyuk commented on LibraryCPPTemplate/vector.h
> +            capacity = size;
Тут, вероятно, стоит просто менять length.

2021-09-13 06:35 UTC, Dovgalyuk commented on LibraryCPPTemplate/vector.h
> +    void resize(size_t size) {
Всё-таки стоит отделить reserve от resize и не вызывать reserve, если новый размер в пределах capacity.

2021-09-13 06:35 UTC, Dovgalyuk commented on LibraryCPPTemplate/stack.h
> +        this->reserve(this->length + 1);
Тут явно должен быть resize, а не reserve.

2021-09-13 06:35 UTC, Dovgalyuk commented on LibraryCPPTemplate/stack.h
> +        this->reserve(--this->length);
Здесь тоже resize.

2021-09-13 06:35 UTC, Dovgalyuk commented on LibraryCPPTemplate/stack.h
> +class Stack : public Vector<Data> {
Наследование не стоит делать публичным в такой ситуации. Иначе кто-то сможет использовать стек как вектор и сломать логику самого стека. Непосредственно для стека это вряд ли приведёт к проблемам, а в общем случае может.

2021-09-13 06:35 UTC, Dovgalyuk commented on Result/laboratorytwo.cpp
> +    Stack<std::string> operationStack;
Как-то не очень эффективно хранить отдельные символы в целых объектах-строках. Как-то надо обойти хранение всего в одном результирующем массиве. Например, организовать два стека.

2021-09-14 07:35 UTC, Kirilliriks commented
@Dovgalyuk причесал код

2021-09-15 05:52 UTC, Dovgalyuk requested changes

2021-09-15 05:52 UTC, Dovgalyuk commented on LibraryCPPTemplate/vector.h
> +            length = size;
И после этого снова пойдёт копирование.

2021-09-15 05:52 UTC, Dovgalyuk commented on LibraryCPPTemplate/vector.h
> +        if (length != 0)
Зачем проверка?

2021-09-15 05:52 UTC, Dovgalyuk commented on LibraryCPPTemplate/vector.h
> +        size_t copySize = size > length ? length : size;
Разве при уменьшении размера возможно копирование?

2021-09-15 05:52 UTC, Dovgalyuk commented on LibraryCPPTemplate/vector.h
> +        if (capacity > size && length < size) return;
Разве длина имеет значение здесь? Вообще, по идее, reserve может только увеличивать хранилище.

2021-09-15 05:53 UTC, closed without merging