lab1 Потапенко Егор 0092
Dovgalyuk/Algorithms pull request #205
Opened 2021-09-11 11:34 UTC by Shara1p

2021-09-13 06:16 UTC, Dovgalyuk requested changes

2021-09-13 06:16 UTC, Dovgalyuk commented on lab1/SomeCode.cpp
> +int decade = 10;
раз уж это константа, стоит явно об этом сказать с помощью const

2021-09-13 06:16 UTC, Dovgalyuk commented on lab1/SomeCode.cpp
> +int sum = 0;
эту переменную не стоит делать глобальной

2021-09-13 06:16 UTC, Dovgalyuk commented on lab1/SomeCode.cpp
> +int size = 0;
эта переменная не нужна в функции forecast, потому что можно использовать array_size

2021-09-13 06:16 UTC, Dovgalyuk commented on lab1/SomeCode.cpp
> +        for (j; j < size; j++) {
Можно сделать проще, если j будет просто увеличиваться. Для определения границ декад можно либо использовать дополнительный счётчик, либо остаток от деления j на 10.

2021-09-13 11:57 UTC, Shara1p commented on lab1/SomeCode.cpp
> +        for (j; j < size; j++) {
Все исправил

2021-09-14 06:20 UTC, Dovgalyuk requested changes

2021-09-14 06:20 UTC, Dovgalyuk commented on lab1/SomeCode.cpp
> +    size++;
Для чего нужна эта строчка?

2021-09-14 06:20 UTC, Dovgalyuk commented on lab1/SomeCode.cpp
> +        if ((j % 10) == 0) {
Сколько элементов будет обработано для первой декады?

2021-09-14 06:20 UTC, closed without merging

2021-09-14 06:40 UTC, Shara1p commented on lab1/SomeCode.cpp
> +    size++;
Почему то в последний элемент помещается мусор,  и если без этой строчки допустим ввести 30 элементов, то в 30 будет мусор и третья декада будет некорректно считаться, не понимаю почему так, наверное, из за цикла заполнения, сейчас посмотрю