Поправил недочеты
Dovgalyuk/Algorithms pull request #209
Opened 2021-09-14 06:45 UTC by Shara1p

удалено size++, поправлены циклы заполнения и подсчета декад (сделано включительно, теперь все работает корректно)

2021-09-15 05:55 UTC, Dovgalyuk requested changes

2021-09-15 05:55 UTC, Dovgalyuk commented on lab1/SomeCode.cpp
> +}
Что должна вывести программа для содержимого массива?
1 1 1 1 1 1 1 1 1 1 100 100 100 100 100 100 100 100 100 100

2021-09-20 08:20 UTC, Shara1p commented on lab1/SomeCode.cpp
> +}
1 декада: 1;
2 декада: 100;
третьей декады нет

2021-09-20 08:22 UTC, Shara1p commented on lab1/SomeCode.cpp
> +}
Что то не так в программе?

2021-09-21 05:25 UTC, Dovgalyuk commented on lab1/SomeCode.cpp
> +}
```
    for (int i = 0; i <= size; i++) {
        if (i < 10)
           array_set(arr, i, 1);
        else if (i < 20)
           array_set(arr, i, 100);
        else
           array_set(arr, i, 1 + rand() % 100);
    }
```
размер 20
```
decade 1: 11
decade 2: 96
```

2021-09-22 10:49 UTC, Shara1p commented on lab1/SomeCode.cpp
> +        if ((j + 1) % 10) == 0) {
Добавил в условной конструкции +, ошибку понял, в нашем случае декада это не 1 - 10, а 0 - 9

2021-09-29 06:03 UTC, Dovgalyuk requested changes

2021-09-29 06:03 UTC, Dovgalyuk commented on lab1/SomeCode.cpp
> +        if ((j + 1) % 10) == 0) {
Теперь и условие j==0 не нужно.

2021-09-29 06:03 UTC, Dovgalyuk commented on lab1/SomeCode.cpp
> +    for (int i = 0; i <= size; i++) {
Здесь происходит выход за границы массива.

2021-09-29 06:03 UTC, Dovgalyuk commented on lab1/SomeCode.cpp
> +    for (int j = 0; j <= array_size(arr); j++) {
И тут выход за границы массива.

2021-09-29 06:03 UTC, Dovgalyuk commented on lab1/SomeCode.cpp
> +        if ((j + 1) % 10) == 0) {
И если уж мы объявили константу, стоит ее здесь использовать.

2021-09-29 08:20 UTC, Shara1p commented on lab1/SomeCode.cpp
> +    for (int j = 0; j <= array_size(arr); j++) {
Все исправил

2021-09-30 06:36 UTC, Dovgalyuk commented
1. Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
    2. Решить задачу, используя реализованный стек.
Дано выражение в обратной польской записи. Используя стек, написать программу, которая проверяет выражение на наличие ошибок. Ошибкой считается деление на 0 (ZERO), выполнение операции, когда в стеке меньше двух элементов (UNDERFLOW), наличие больше одного элемента в стеке после завершения работы программы (OVERFLOW).

Вход
```
1
2
+
3
```

Выход
```
OVERFLOW
```


Вход
```
10
9
-
+
```

Выход
```
UNDERFLOW
```

2021-09-30 06:36 UTC, closed without merging