Гуревич Кирилл Михайлович - 0092 - решение третьей задачи
Dovgalyuk/Algorithms pull request #221
Opened 2021-09-16 14:37 UTC by Kirilliriks

Решение в папке Result, файл laboratorythree.cpp

2021-09-17 05:18 UTC, Dovgalyuk requested changes

2021-09-17 05:18 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +    Item *insert(Data data) {
Кажется для реализации этой функции можно попробовать применить вызов insert_after.

2021-09-17 05:18 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +    Item *lastItem;
От lastItem толку мало, а ошибки в коде функций есть.

2021-09-17 05:18 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +        if (item->next() != nullptr)
nextItem

2021-09-17 05:18 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +        if (item->prev() != nullptr)
Это условие как-то связано с первым условием в функции.

2021-09-17 05:18 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +class Queue : public List<Data>{
не надо делать наследование публичным в таких случаях, кто-то сможет вставить элемент в середину очереди

2021-09-17 05:18 UTC, Dovgalyuk commented on Result/laboratorythree.cpp
> +void checkTiles(std::vector<std::string>& map, Queue<Position> &positions, int &freeTilesCount) {
Для Queue<Position> стоит сделать typedef. Для map тоже.

2021-09-17 05:18 UTC, Dovgalyuk commented on Result/laboratorythree.cpp
> +            if (x == 0 && y == 0) continue; // Мне кажется что в учебных целях такой код читабельнее чем 4 if'а
Два варианта:
1.
const int dx[] = {-1, 1, 0, 0};
const int dy[] = {0, 0, -1, 1};

2.
std::abs(x) + std::abs(dy) == 1


Первый эффективнее, второй элегантнее.

2021-09-17 05:18 UTC, Dovgalyuk commented on Result/laboratorythree.cpp
> +                    map.at(newPosition.y).replace(newPosition.x, 1, "X");
квадратные скобки и присваивание будут читабельнее

2021-09-17 05:18 UTC, closed without merging

2021-09-20 06:34 UTC, Kirilliriks commented on LibraryCPPTemplate/queue.h
> +class Queue : public List<Data>{
Done

2021-09-20 06:35 UTC, Kirilliriks commented on LibraryCPPTemplate/list.h
> +    Item *lastItem;
Done

2021-09-20 06:35 UTC, Kirilliriks commented on LibraryCPPTemplate/list.h
> +        if (item->next() != nullptr)
Done

2021-09-20 06:35 UTC, Kirilliriks commented on LibraryCPPTemplate/list.h
> +        if (item->prev() != nullptr)
Done

2021-09-20 07:02 UTC, Kirilliriks commented on LibraryCPPTemplate/list.h
> +    Item *insert(Data data) {
К сожалению я не вижу способа сделать это, из-за особенностей insert_after(необходимо чтобы входящий параметр item != nullptr), вижу один способ решения это изменить логику метода insert_after

2021-09-20 07:05 UTC, Kirilliriks commented on Result/laboratorythree.cpp
> +void checkTiles(std::vector<std::string>& map, Queue<Position> &positions, int &freeTilesCount) {
Done

2021-09-20 07:12 UTC, Kirilliriks commented on Result/laboratorythree.cpp
> +            if (x == 0 && y == 0) continue; // Мне кажется что в учебных целях такой код читабельнее чем 4 if'а
Done, first variant was used

2021-09-20 07:12 UTC, Kirilliriks commented on Result/laboratorythree.cpp
> +                    map.at(newPosition.y).replace(newPosition.x, 1, "X");
Done