Лабораторная работа 1 от Курилова Романа 0091
Dovgalyuk/Algorithms pull request #222
Opened 2021-09-17 07:46 UTC by zyzic1001

2021-09-20 05:31 UTC, Dovgalyuk requested changes

2021-09-20 05:31 UTC, Dovgalyuk commented on HelpMeGod/laba1/NyPognali.cpp
> +	int *arrayCopy = new int[size];
Нужно обойтись без этого.

2021-09-20 05:31 UTC, Dovgalyuk commented on HelpMeGod/laba1/NyPognali.cpp
> +			check = 1;
Для таких случаев лучше использовать тип bool.

2021-09-20 05:31 UTC, Dovgalyuk commented on HelpMeGod/laba1/NyPognali.cpp
> +			array_set(array, i, array_get(array, i) - k1);
Надо вычитать не k1, а значение элемента с номером k1.

2021-09-20 05:55 UTC, zyzic1001 commented on HelpMeGod/laba1/NyPognali.cpp
> +	int *arrayCopy = new int[size];
В том смысле что вообще убрать arrayCopy, или как-то по-другому его выделять?

2021-09-21 05:06 UTC, Dovgalyuk commented on HelpMeGod/laba1/NyPognali.cpp
> +	int *arrayCopy = new int[size];
Да, лучше вообще убрать. А исходные значения вывести сразу на старте.

2021-09-21 05:06 UTC, zyzic1001 commented on HelpMeGod/laba1/NyPognali.cpp
> +	int *arrayCopy = new int[size];
Хорошо

2021-09-29 06:44 UTC, Dovgalyuk commented
CMake не смог собрать проект.

2021-09-30 13:08 UTC, zyzic1001 commented
Лично у меня всё собралось, в чём проблема не знаю. Могу показать работу в университете, когда вам удобно.

2021-10-01 05:55 UTC, Dovgalyuk commented
Стоит обратить внимание на регистр символов в названиях файлов и библиотек.

И остальные замечания по-прежнему остаются.

2021-10-01 06:45 UTC, zyzic1001 commented
Нашёл и исправил ошибку. Но можно поконкретнее, какие замечания остаются в силе?

2021-10-04 05:22 UTC, Dovgalyuk commented
Выше можно почитать, на два замечания нет ответов.

2021-10-04 05:53 UTC, zyzic1001 commented on HelpMeGod/laba1/NyPognali.cpp
> +			check = 1;
исправил

2021-10-04 05:53 UTC, zyzic1001 commented on HelpMeGod/laba1/NyPognali.cpp
> +			array_set(array, i, array_get(array, i) - k1);
исправил

2021-10-05 06:03 UTC, Dovgalyuk requested changes

2021-10-05 06:03 UTC, Dovgalyuk commented on HelpMeGod/laba1/NyPognali.cpp
> +			array_set(array, i, array_get(array, i) - k1);
не вижу исправления

2021-10-05 06:11 UTC, zyzic1001 commented on HelpMeGod/laba1/NyPognali.cpp
> +			array_set(array, i, array_get(array, i) - k1);
В начале subtractionk1k2 пользователь вводит номера элементов arrayя, которые хочет вычитать, потом k1 и k2 присваиваются значения элементов с номерами k1 и k2, после происходит вычитание

2021-10-05 06:20 UTC, Dovgalyuk commented
1. Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
    2. Решить задачу, используя реализованный стек.
Вычислить значение корректного арифметического выражения без скобок, использующего операции сложения, вычитания, умножения и деления. Программа должна учитывать приоритет операторов умножения и деления и использовать стек для хранения промежуточных результатов. Операндами в выражении являются неотрицательные целые числа.

Вход
```
1+2*3-1
```
Выход
6
Вход
```
1*2+3
```
Выход
5

2021-10-05 06:20 UTC, closed without merging