Гуревич Кирилл Михайлович - 0092 - решение третьей задачи (fixed:0)
Dovgalyuk/Algorithms pull request #225
Opened 2021-09-20 07:19 UTC by Kirilliriks

К сожалению пере открыть прошлый PR даже после коммита не получается.
С прошлого ревью не смог найти решение реализации метода _"insert"_ с помощью вызова метода _"insert_after"_ в прошлом PR изложил свои мысли, продублирую их тут:
**"К сожалению я не вижу способа сделать это, из-за особенностей insert_after(необходимо чтобы входящий параметр item != nullptr), вижу один способ решения это изменить логику метода insert_after"**

2021-09-21 05:05 UTC, Dovgalyuk requested changes

2021-09-21 05:05 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +        this->ins(data);
```List<Data>::insert(data)```
что-то в этом роде

2021-09-21 05:05 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +        return this->last()->data();
last() работает за O(N)
Можно в Queue хранить последний указатель, чтобы не усложнять List.

2021-09-23 12:33 UTC, Kirilliriks commented on LibraryCPPTemplate/queue.h
> +        return this->last()->data();
done

2021-09-23 12:33 UTC, Kirilliriks commented on LibraryCPPTemplate/queue.h
> +        this->ins(data);
done

2021-09-23 12:34 UTC, Kirilliriks commented
@Dovgalyuk все замечания исправлены.

2021-09-29 06:30 UTC, Dovgalyuk requested changes

2021-09-29 06:30 UTC, Dovgalyuk commented on Result/laboratorythree.cpp
> +#include "../LibraryCPPTemplate/queue.h"
Вот тут можно обходиться без путей, если прописать их в CMakeLists.txt

2021-09-30 08:36 UTC, Kirilliriks commented on Result/laboratorythree.cpp
> +#include "../LibraryCPPTemplate/queue.h"
Done. Я заодно решил и в прошлых решения (Электрической цепи и калькулятора) сделать аналогичной подключение хидера, однако в случае с LibraryCPP пришлось добавить в cmakelist.txt одну строку target_include_directories

2021-09-30 08:37 UTC, Kirilliriks commented
@Dovgalyuk сделал подключение без путей

2021-09-30 08:55 UTC, Kirilliriks commented
@Dovgalyuk сделал подключение без путей

2021-10-01 06:12 UTC, Dovgalyuk commented
1. Разработать программный интерфейс модуля (заголовки функций) для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
    2. Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
    3. Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде матрицы смежности в контейнере Array той же библиотеки.
    4. Разработать и добавить в проект программу, тестирующую работу библиотеки для графа.
    5. Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать в нем длины кратчайших путей от одной вершины до всех остальных с помощью алгоритма Дейкстры.

2021-10-01 06:12 UTC, closed without merging