Шиков Кирилл Дмитриевич 0091: Третье задание
Dovgalyuk/Algorithms pull request #226
Opened 2021-09-20 19:20 UTC by NovolMob

2021-09-21 05:21 UTC, Dovgalyuk requested changes

2021-09-21 05:21 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +    return (vector_size(queue->vector) - queue->offset) <= 0;
В каких случаях выражение внутри скобок будет отрицательным?

2021-09-21 05:21 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +            vector_set_data(queue->vector, new_data, new_size);
Залезать внутрь структур вектора не очень правильно. Лучше реализовать то же самое с помощью resize/get/set.

2021-09-21 05:21 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
>  #include "queue.h"
К тестам стоит добавить несколько разных сценариев по добавлению/извлечению элементов и проверки получающейся последовательности, потому что есть подозрение, что в некоторых случаях работать будет неправильно.

2021-09-21 19:10 UTC, NovolMob commented on LibraryCPP/queue.cpp
> +            vector_set_data(queue->vector, new_data, new_size);
Исправил

2021-09-21 19:10 UTC, NovolMob commented on LibraryCPP/queue.cpp
>  #include "queue.h"
Попробовал добавить

2021-09-21 19:11 UTC, NovolMob commented on LibraryCPP/queue.cpp
>  #include "queue.h"
Но я изменил алгоритм немного

2021-09-29 05:56 UTC, Dovgalyuk requested changes

2021-09-29 05:56 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +    queue->first = ++queue->first % vector_size(queue->vector);
так вообще писать нельзя, тут дважды изменяется переменная

2021-09-29 05:56 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +        first = ++first % this->size();
См. комментарий к другому модулю.
И зачем вообще делать обе реализации queue?

2021-09-29 05:56 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +    size_t length = 0;
Вот без length точно можно обойтись, потому что она легко вычисляется.
Есть ли от него какая-то другая польза?

2021-09-29 05:56 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +    void sort() {
этот метод должен быть private

2021-09-29 05:56 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +    }
Здесь есть утечка памяти.

2021-09-29 21:58 UTC, NovolMob commented on LibraryCPP/queue.cpp
> +    queue->first = ++queue->first % vector_size(queue->vector);
Исправил

2021-09-29 21:59 UTC, NovolMob commented on LibraryCPPTemplate/queue.h
> +        first = ++first % this->size();
Исправил. Сделал обе реализации для себя)

2021-09-29 21:59 UTC, NovolMob commented on LibraryCPPTemplate/queue.h
> +    void sort() {
Исправил

2021-09-29 21:59 UTC, NovolMob commented on LibraryCPPTemplate/queue.h
> +    }
Исправил

2021-09-29 22:02 UTC, NovolMob commented on LibraryCPPTemplate/queue.h
> +    size_t length = 0;
Я не смог придумать лёгкий способ вычисления. Если вы имеет ввиду last - first, то он не подойдёт, ведь не факт, что last всегда будет правее first.

2021-09-30 07:26 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +    size_t length = 0;
В одном случае правее, в другом левее. Можно использовать либо ветвление, либо остаток от деления.

2021-09-30 07:27 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +    }
Разве?

2021-09-30 11:53 UTC, NovolMob commented on LibraryCPPTemplate/queue.h
> +    size_t length = 0;
Но если будет например size = 6, last = 3, first = 4 - это значит что очередь пуста или заполнена? Или также например у меня будет size = 3, first = 0, last = 2 и я решу удалить три раза. После удаления данные те же, но как понял пустая у меня очередь и полная. Я не знаю как это проверить, поэтому я и сделал переменную, которая считает количество.

2021-09-30 11:54 UTC, NovolMob commented on LibraryCPPTemplate/queue.h
> +    size_t length = 0;
length показывает не размер, а сколько элементов есть в очереди

2021-09-30 11:57 UTC, NovolMob commented on LibraryCPPTemplate/queue.h
> +    size_t length = 0;
заменил length на amount

2021-09-30 12:23 UTC, NovolMob commented on LibraryCPPTemplate/queue.h
> +    }
ну теперь точно

2021-10-01 05:47 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +    size_t length = 0;
> Но если будет например size = 6, last = 3, first = 4 - это значит что очередь пуста или заполнена? Или также например у меня будет size = 3, first = 0, last = 2 и я решу удалить три раза. После удаления данные те же, но как понял пустая у меня очередь и полная. Я не знаю как это проверить, поэтому я и сделал переменную, которая считает количество.

Всё так, это единственное полезное применение длины. Другой вариант - не заполнять одну ячейку.

2021-10-01 05:53 UTC, Dovgalyuk requested changes

2021-10-01 05:53 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +        }
Точно надо копировать всё поэлементно?

2021-10-04 05:24 UTC, Dovgalyuk commented
1. Разработать программный интерфейс модуля (заголовки функций) для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
    2. Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
    3. Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде матрицы смежности в контейнере Vector той же библиотеки.
    4. Разработать и добавить в проект программу, тестирующую работу библиотеки для графа.
    5. Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать в нем кратчайшие пути для заданной пары вершин с помощью алгоритма Дейкстры.

2021-10-04 05:24 UTC, closed without merging