Лабораторная работа 1 от Радаева Кирилла 0091(Переделано)
Dovgalyuk/Algorithms pull request #227
Opened 2021-09-21 12:09 UTC by Golod-ru

Исправил все ошибки которые вы указали :\

2021-09-29 05:39 UTC, Dovgalyuk requested changes

2021-09-29 05:39 UTC, Dovgalyuk commented on laba/Lab1/lab1.cpp
> +void search(Array* array, int* max, int* min)
min и max можно же по значению передавать, а не по указателю

2021-09-29 05:39 UTC, Dovgalyuk commented on laba/Lab1/lab1.cpp
> +        cout << "There are no two-digit numbers" << endl;
а для второго вызова какое сообщение должно быть?

2021-09-29 05:39 UTC, Dovgalyuk commented on laba/Lab1/lab1.cpp
> +void select(int* max, int* min, int mark)
если уж делать такую функцию, то с циклом, который вычисляет нужные min и max в зависимости от параметра. А так выглядит, как ненужное усложнение, потому что min и max можно напрямую передать в search как константы.

2021-09-29 11:13 UTC, Golod-ru reviewed
Убрал функцию селект и немного доработал программу.

2021-09-30 06:42 UTC, Dovgalyuk commented
1. Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
    2. Решить задачу, используя реализованный стек.
Написать программу, которая с помощью стека проверяет правильность последовательности из скобок вида (), [] и {} и кавычек вида “” и ‘’. В выходной файл напечатать YES, если последовательность правильная и NO, если неправильная.

Вход
```
([]””)
```

Выход
YES

Вход
```
(“)”
```

Выход
NO

2021-09-30 06:42 UTC, closed without merging