0091 Васильев Дмитрий Задание №1fixed
Dovgalyuk/Algorithms pull request #229
Opened 2021-09-23 09:31 UTC by PodumaeshNicknameNePridumal

2021-09-29 06:18 UTC, Dovgalyuk requested changes

2021-09-29 06:18 UTC, Dovgalyuk commented on First/main.cpp
> +#include "../LibraryCPP/array.cpp"
Нужно подключать заголовочный файл. И без указания полного пути.

2021-09-29 11:29 UTC, PodumaeshNicknameNePridumal commented on First/main.cpp
> +#include "../LibraryCPP/array.cpp"
исправил

2021-09-30 06:49 UTC, Dovgalyuk commented
1. Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
    2. Решить задачу, используя реализованный стек.
Написать программу, имитирующую ввод с клавиатуры, имеющей буквы, цифры, пробелы, знаки препинания и клавишу «Backspace». Программа должна использовать стек. На вход программе подается последовательность нажатых клавиш в виде строки. Backspace обозначается символом # и означает, что последний введенный символ должен быть удален.

Вход
ABC#D

Выход
ABD

Вход
ABC###EFG

Выход
EFG

2021-09-30 06:49 UTC, closed without merging