Шиков Кирилл Дмитриевич 0091: Четвёртое задание
Dovgalyuk/Algorithms pull request #245
Opened 2021-10-06 21:25 UTC by NovolMob

2021-10-08 05:34 UTC, Dovgalyuk requested changes

2021-10-08 05:34 UTC, Dovgalyuk commented on LibraryCPPTemplate/directed_graph.h
> +    struct Iterator {
Это не очень полезный итератор (хотя и его можно оставить).
Полезный итератор должен перечислять всех соседей определённой вершины.

2021-10-08 05:34 UTC, Dovgalyuk commented on LibraryCPPTemplate/directed_graph.h
> +    explicit DirectedGraph(size_t vertex_amount): vertex_amount(vertex_amount), matrix(new Vector<Edge*>), vertices(new Vector<Vertex*>) {
А массив вершин пустой получится, хоть размер графа и задан?

2021-10-08 05:34 UTC, Dovgalyuk commented on LibraryCPPTemplate/directed_graph.h
> +    size_t add_vertex(Vertex* vertex) {
Во всех этих методах матрицу тоже надо модифицировать, чтобы можно было произвольно увеличивать и уменьшать граф.

2021-10-08 05:34 UTC, Dovgalyuk commented on LibraryCPPTemplate/directed_graph.h
> +    std::vector<int> get_near_vertices(size_t index) {
Вот это надо убрать и вместо такого метода сделать итератор.

2021-10-09 09:59 UTC, NovolMob commented on LibraryCPPTemplate/directed_graph.h
> +    struct Iterator {
Исправил

2021-10-09 09:59 UTC, NovolMob commented on LibraryCPPTemplate/directed_graph.h
> +    explicit DirectedGraph(size_t vertex_amount): vertex_amount(vertex_amount), matrix(new Vector<Edge*>), vertices(new Vector<Vertex*>) {
Исправил

2021-10-09 09:59 UTC, NovolMob commented on LibraryCPPTemplate/directed_graph.h
> +    size_t add_vertex(Vertex* vertex) {
Исправил

2021-10-09 09:59 UTC, NovolMob commented on LibraryCPPTemplate/directed_graph.h
> +    std::vector<int> get_near_vertices(size_t index) {
Исправил

2021-10-11 07:39 UTC, Dovgalyuk requested changes

2021-10-11 07:39 UTC, Dovgalyuk commented on LibraryCPPTemplate/directed_graph.h
> +        new_matrix->resize(pow(vertex_amount, 2));
pow не надо использовать для такого, она работает с вещественными числами

2021-10-11 07:39 UTC, Dovgalyuk commented on LibraryCPPTemplate/directed_graph.h
> +        int amount_vertex_in_old_matrix = sqrt(matrix->size());
А этот размер можно взять из массива для количества вершин.

2021-10-11 07:39 UTC, Dovgalyuk commented on Algorithms/Fourth/test.cpp
> +bool is_all(Data array[], size_t size, Data value) {
Вместо этого можно было бы завести счётчик итераций основного цикла.

2021-10-12 05:25 UTC, Dovgalyuk requested changes

2021-10-12 05:25 UTC, Dovgalyuk commented on LibraryCPPTemplate/directed_graph.h
> +        int amount_vertex_in_old_matrix = sqrt(matrix->size());
pow убрал, а sqrt оставил?

2021-10-12 05:25 UTC, Dovgalyuk commented on Algorithms/Fourth/test.cpp
> +    fill(costs, graph->get_vertex_amount(), INT_MAX);
costs стоит хранить в метках вершин

2021-10-12 05:25 UTC, Dovgalyuk commented on Algorithms/Fourth/test.cpp
> +    fill(was, graph->get_vertex_amount(), false);
Или was хранить в метках вершин. Или даже оба в виде структуры, раз уж у нас шаблон.

2021-10-12 06:47 UTC, NovolMob commented on LibraryCPPTemplate/directed_graph.h
> +        int amount_vertex_in_old_matrix = sqrt(matrix->size());
А как мне ещё брать корень? Здесь мне обязательно нужно количество вершин в матрице для итерации.

2021-10-12 07:16 UTC, NovolMob commented on LibraryCPPTemplate/directed_graph.h
> +        new_matrix->resize(pow(vertex_amount, 2));
Исправил

2021-10-12 07:26 UTC, NovolMob commented on LibraryCPPTemplate/directed_graph.h
> +        int amount_vertex_in_old_matrix = sqrt(matrix->size());
vertex_amount +- 1 я считаю не подойдёт, так как вдруг каким-то чудом будут добавляться вершины в обход методов, и здесь тогда будет ошибка

2021-10-13 06:20 UTC, NovolMob commented on LibraryCPPTemplate/directed_graph.h
> +        int amount_vertex_in_old_matrix = sqrt(matrix->size());
исправил

2021-10-14 05:43 UTC, Dovgalyuk commented
1. Разработать интерфейс (набор функций) для ассоциативного массива, который хранит пары (ключ)строка -> (значение)строка. Поддерживаемые операции: добавить пару ключ-значение, найти значение по ключу, удалить значение по ключу.
    2. Реализовать ассоциативный массив на основе АВЛ-дерева.
    3. Создать тест для проверки работы ассоциативного массива. Программа должна включать в себя нагрузочное тестирование для исключения ошибок, приводящих к сложности работы O(N^2) при поиске, удалении или добавлении.
    4. Реализовать функцию проверки баланса АВЛ-дерева и в тестовом режиме вызывать ее после каждого добавления/удаления.
    5. Написать генератор входных данных различного объема для этого контейнера. Сравнить скорость выполнения операции добавления в контейнер содержимого файла для АВЛ-дерева и для std::map при различных объемах данных.

2021-10-14 05:43 UTC, closed without merging