Вторая лаба от Курилова Романа 0091
Dovgalyuk/Algorithms pull request #254
Opened 2021-10-19 10:21 UTC by zyzic1001

2021-10-20 05:17 UTC, Dovgalyuk commented
Проект должен компилироваться.

2021-10-20 05:31 UTC, zyzic1001 commented
Можно уточнить, компилятору не нравиться функция pow из math.h?

2021-10-21 05:35 UTC, Dovgalyuk commented
Да, вероятно потому, что этот заголовочный файл не подключен.

2021-11-01 05:45 UTC, Dovgalyuk requested changes

2021-11-01 05:45 UTC, Dovgalyuk commented on HelpMeGod/laba2/NyPognali.cpp
> +                masdig[sizedig] = masdig[sizedig] + (primer[i + r] - '0') * step(kol - 1);
step выкинуть, masdig[sizedig] домножать на 10 каждый раз

2021-11-01 05:45 UTC, Dovgalyuk commented on HelpMeGod/laba2/NyPognali.cpp
> +        if (!isdigit(primer[i])) {
else?

2021-11-01 05:45 UTC, Dovgalyuk commented on HelpMeGod/laba2/NyPognali.cpp
> +                while (isdigit(primer[j])) {
Это же всё и так делается, здесь не нужно повторять.
Операция просто добавляется в стек.

2021-11-01 05:45 UTC, Dovgalyuk commented on HelpMeGod/laba2/NyPognali.cpp
> +    for (int i = 0; i < sizezna; i++) {
Вычисления доделываются в конце (если стек не пустой), либо если того требуют приоритеты (как описано выше). Смотреть вперёд, что там после операции, не нужно.

2021-11-01 07:46 UTC, zyzic1001 commented on HelpMeGod/laba2/NyPognali.cpp
> +                masdig[sizedig] = masdig[sizedig] + (primer[i + r] - '0') * step(kol - 1);
исправил

2021-11-01 07:47 UTC, zyzic1001 commented on HelpMeGod/laba2/NyPognali.cpp
> +        if (!isdigit(primer[i])) {
теперь else if

2021-11-01 08:03 UTC, zyzic1001 commented on HelpMeGod/laba2/NyPognali.cpp
> +                while (isdigit(primer[j])) {
Нужно. Если нам попалась операция умножения или деления, томы сразу считываем следующее число и берём из стека предыдущее, считаем и записываем результат в стек. Таким образом в стеке знаков операций не будет умножений и делений, вить если бы они были, то как нам их оттуда достать? а вдруг перед ними будут сложения и вычитания, куда нам их девать, чтоб добраться до операций высшего приоритета? Если записывать умножение и деление в стек к числам, то до них тоже фиг доберёшься через числа. В стеке даже нормально по элементам не пройтись, приходиться удалять те что на поверхности. Поэтому я и избавляюсь от умножения и деления сразу, а минус меняя на плюс и делая следующее за ним число отрицательным. Честно, я не знаю как сделать программу, которая вас устроит. Может я тупой и не догоняю ваши подсказки. Но данное вами задание программа выполняет.

2021-11-02 05:00 UTC, Dovgalyuk requested changes

2021-11-02 05:00 UTC, Dovgalyuk commented on HelpMeGod/laba2/NyPognali.cpp
> +                while (isdigit(primer[j])) {
Уже почти правильно.
С вычитанием и делением надо действовать так. Если на вершине стека одна из этих операций, а следом пришла операция с таким же приоритетом, то надо сначала выполнить ту, что в стеке, а потом добавить следующую.
Т.е. вперёд в обрабатываемой последовательности заглядывать не нужно никогда.

2021-11-02 05:01 UTC, Dovgalyuk commented on HelpMeGod/laba2/NyPognali.cpp
> +                while (isdigit(primer[j])) {
Кстати, это есть в том алгоритме, что я цитировал:

пока операция на вершине стека приоритетнее o1 ИЛИ операция на вершине стека левоассоциативная с приоритетом как у o1, то выталкиваем верхний элемент стека в выходную строку (то есть, делаем вычисления с верхними числами из стека чисел);

2021-11-02 05:53 UTC, zyzic1001 commented on HelpMeGod/laba2/NyPognali.cpp
> +                while (isdigit(primer[j])) {
Теперь, вроде, понял. Программа теперь не идёт вперёд обрабатываемой последовательности.

2021-11-03 04:57 UTC, Dovgalyuk approved these changes

2021-11-03 04:57 UTC, Dovgalyuk commented on HelpMeGod/laba2/NyPognali.cpp
> +                else if (stack_get(Stanly) == '-') {
Ну вот без этого можно было бы обойтись.

2021-11-03 05:01 UTC, Dovgalyuk commented
1. Реализовать в проекте Library очередь (модуль queue) на основе кольцевого двунаправленного списка (модуль list).
    2. Решить задачу, используя реализованную очередь.
Задан список двунаправленных дорог, соединяющих города и названия городов между которыми нужно найти кратчайший путь. Написать программу, находящую кратчайший путь с помоью поиска в ширину и вывести в выходной файл список городов, которые нужно посетить, чтобы добраться из начального города в конечный. 

Вход
```
City1 City2
City2 End
Start City1
Start End
```
Выход
```
Start City1 City2 End
```

В примере задано 3 дороги: City1-City2, City2-End, Start-City1. Последние 2 города в списке – начальный и конечный города в искомом пути.

2021-11-03 05:01 UTC, closed without merging