Шиков Кирилл Дмитриевич 0091: Пятое задание
Dovgalyuk/Algorithms pull request #259
Opened 2021-10-25 22:26 UTC by NovolMob

2021-10-31 22:45 UTC, NovolMob commented
В папке с задание(Fifth) лежит картинка с графиком.

2021-11-01 06:24 UTC, Dovgalyuk requested changes

2021-11-01 06:24 UTC, Dovgalyuk commented on Algorithms/Fifth/test.cpp
> +    readFileToMap(INPUT_FILE_NAME, map);
Чтение файла нужно исключить из замеров. Чтобы на время влияло только добавление или удаление из контейнера, а не скорость диска.

2021-11-02 05:06 UTC, Dovgalyuk commented
Последнее задание будет после защиты этого.

2021-11-19 08:01 UTC, Dovgalyuk commented
1. Разработать интерфейс модуля для работы со строками. Основные операции: создание, конкатенация, копирование, поиск подстроки, сравнение двух строк, изменение размера, получение указателя на массив символов
    2. Реализовать описанные функции
    3. Реализовать поиск с помощью алгоритма Кнута-Морриса-Пратта

2021-11-19 08:01 UTC, closed without merging