Гуревич Кирилл Михайлович - 0092 - решение пятой задачи
Dovgalyuk/Algorithms pull request #261
Opened 2021-10-28 10:50 UTC by Kirilliriks

Решение находиться в папке Result

2021-10-31 22:00 UTC, Kirilliriks commented
@Dovgalyuk всё исправил, график (в виде картинки) добавил в репозиторий

2021-11-01 06:17 UTC, Dovgalyuk requested changes

2021-11-01 06:17 UTC, Dovgalyuk commented on LibraryCPP/Tests/AVLTree.cpp
> +    }
Ещё с удалением такой же тест нужен.

2021-11-01 06:17 UTC, Dovgalyuk commented on LibraryCPP/AVLTree.cpp
> +    bool correct = balanceFactor(node) != 2 && balanceFactor(node) != -2;
Здесь нужно пересчитывать реальную высоту, вдруг поле height в результате преобразований стало некорректным.

2021-11-01 06:18 UTC, Dovgalyuk commented
1. Логарифмический масштаб оси x - это неудобно
2. Измеряется много всяких операций, а график только один
3. Количество вершин нужно сделать до 1000000

2021-11-01 07:51 UTC, Kirilliriks commented on LibraryCPP/Tests/AVLTree.cpp
> +    }
Done

2021-11-01 07:51 UTC, Kirilliriks commented on LibraryCPP/AVLTree.cpp
> +    bool correct = balanceFactor(node) != 2 && balanceFactor(node) != -2;
Done

2021-11-01 07:56 UTC, Kirilliriks commented
> 1. Логарифмический масштаб оси x - это неудобно
> 2. Измеряется много всяких операций, а график только один
> 3. Количество вершин нужно сделать до 1000000

Под операциями имеется ввиду отдельно операции добавления и удаления?

2021-11-01 09:00 UTC, Kirilliriks commented
@Dovgalyuk Исправлено

2021-11-02 05:10 UTC, Dovgalyuk commented
Последнее задание будет после защиты первых пяти.

2021-11-02 05:10 UTC, closed without merging