Лабораторная работа №2 Радаева Кирилла
Dovgalyuk/Algorithms pull request #265
Opened 2021-10-31 11:26 UTC by Golod-ru

2021-11-01 06:02 UTC, Dovgalyuk commented
проект должен компилироваться (см. вкладку checks)

2021-11-01 07:03 UTC, Golod-ru commented
Исправил

2021-11-02 05:19 UTC, Dovgalyuk requested changes

2021-11-02 05:19 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +    //vector_delete(stack->vec);
Вектор надо удалять тоже.

2021-11-02 05:19 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +    return vector_size(stack->vec) == 0 ? true : false;
Всю часть после ? можно убрать.

2021-11-02 05:19 UTC, Dovgalyuk commented on laba/lab2/Laba2v2.2.cpp
> +			if (c!=true)
Можно сразу проверять, что лежит на вершине, тогда b и c будут не нужны.

2021-11-02 05:19 UTC, Dovgalyuk commented on laba/lab2/Laba2v2.2.cpp
> +
Что будет, если на входе такая строка:
]

2021-11-02 15:11 UTC, Golod-ru commented
Исправил все, на что вы указали

2021-11-03 05:11 UTC, Dovgalyuk requested changes

2021-11-03 05:11 UTC, Dovgalyuk commented on laba/lab2/Laba2v2.2.cpp
> +		cheak(str, cha);
Ещё один тест:

()]

2021-11-03 13:30 UTC, Golod-ru commented
Теперь на тест ()] он выводит "NO"

2021-11-08 05:37 UTC, Dovgalyuk requested changes

2021-11-08 05:37 UTC, Dovgalyuk commented on laba/lab2/Laba2v2.2.cpp
> +	if (cha.size() % 2 != 0)
Не очень хорошая идея, стоит это убрать и подумать ещё.
Вот тест:
()]]

2021-11-09 09:22 UTC, Golod-ru commented
Переделал.

2021-11-10 05:31 UTC, Dovgalyuk commented
1. Реализовать в проекте Library очередь (модуль queue) на основе кольцевого двунаправленного списка (модуль list).
    2. Решить задачу, используя реализованную очередь.
В первой строке входного файла записаны числа N и M - высота и ширина прямоугольной доски. На ней расположены несколько клеток (координаты (от 1 до N и от 1 до M) которых записаны в следующих строках), покрашенные в цвет с интенсивностью 1. Далее делается несколько ходов. На каждом ходу все пустые клетки, граничащие с другими клетками с интенсивностью k, красятся в цвет k+1. Написать программу, использующую очередь, для определения за какое количество ходов будет покрашена вся доска.

Вход
3 3
1 1

Выход
5

2021-11-10 05:31 UTC, closed without merging