Вторая лабораторка Авдеев 0092
Dovgalyuk/Algorithms pull request #277
Opened 2021-11-08 14:17 UTC by gerundv

2021-11-08 14:22 UTC, gerundv commented
Добавлю по понятней, а то в комите криво перевелось, я не понял как сделать так, чтобы она приняла последовательность правильно, она её наполняет мусором и не хочет с ней работать, а с цифрами и буквами, она их в Dec переводит и, в принципе, работает, я написал как должна выглядеть программа для работы с последовательностью, не знаю как поправить, чтобы она её принимала.

2021-11-09 05:38 UTC, Dovgalyuk requested changes

2021-11-09 05:38 UTC, Dovgalyuk commented on LibraryCPP/2.cpp
> +    else std::cout << "unknown sequence";
Программа должна проверять корректность произвольной последовательности, введенной с клавиатуры или файла.

2021-11-09 05:38 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +    delete[] stack->vector;
Тут должен быть вызов vector_delete

2021-11-09 05:39 UTC, Dovgalyuk commented
Строку можно читать или через std::getline или std::cin >> s

2021-11-09 06:59 UTC, gerundv commented
он читает последовательность (")" . Или мне сделать посимвольное сравнение из стека? Просто тогда нужно Dec значениями сравнивать

2021-11-09 11:03 UTC, gerundv commented on LibraryCPP/2.cpp
> +    else if ((f.find("(")"")&&(f.length()==4)){
вот здесь он не может прочитать последовательность

2021-11-10 05:40 UTC, Dovgalyuk requested changes

2021-11-10 05:40 UTC, Dovgalyuk commented on LibraryCPP/2.cpp
> +    }
Вот нормальный цикл, обрабатывающий строку.
В нём нужно либо добавлять скобку в стек, если она открывающая.
Либо смотреть, лежит ли на вершине стека подходящая скобка, если на вход пришла закрывающая.

2021-11-10 11:22 UTC, gerundv commented on LibraryCPP/2.cpp
> +    }
не понимаю, как это связано с заданием? по заданию ведь нужны конкретные последовательности, а если смотреть по наличию последней скобки, то как оно связано?
задание ведь такое: Написать программу, которая с помощью стека проверяет правильность последовательности из скобок вида (), [] и {} и кавычек вида “” и ‘’. В выходной файл напечатать YES, если последовательность правильная и NO, если неправильная.
NO = (")"; YES = ([]"");
или я просто не понял задание и правильно последовательностью является люба, которая находится внутри скобок? и просто нужно сделать условием выбора наличие открывающей скобки в начале и закрывающей в конце?

2021-11-10 12:09 UTC, gerundv commented on LibraryCPP/2.cpp
> +    }
я правильно понял?

2021-11-10 12:27 UTC, gerundv commented on LibraryCPP/2.cpp
> +    }
дошло, скоро сделаю

2021-11-10 14:32 UTC, gerundv reviewed
вроде сделал правильно, единственный момент, последовательность (")" крашится когда включается условие строки 18

2021-11-11 05:38 UTC, Dovgalyuk requested changes

2021-11-11 05:38 UTC, Dovgalyuk commented on LibraryCPP/2.cpp
> +#include "stack.cpp"
Надо stack.h подключать.

2021-11-11 05:38 UTC, Dovgalyuk commented on LibraryCPP/2.cpp
> +        if ((b[b.length()-i] == '[') && (stack_get(stack)==']')){
Конечно было бы проще (и нагляднее) обрабатывать символы, начиная с первого и заканчивая последним.

2021-11-11 05:38 UTC, Dovgalyuk commented on LibraryCPP/2.cpp
> +            stack_pop(stack);
Для этих случаев нигде не проверяется, что стек не пустой.

2021-11-11 05:38 UTC, Dovgalyuk commented on LibraryCPP/2.cpp
> +            i++;
Зачем дополнительно пропускать символ?

2021-11-11 05:38 UTC, Dovgalyuk commented on LibraryCPP/2.cpp
> +        if ((b[b.length()-i] == '"') && (stack_get(stack)=='"')){
Все эти условия надо проверять так, чтобы срабатывало только одно, выстроив их в цепочку if-else-if-else

2021-11-11 08:32 UTC, gerundv reviewed
если подключать stack.h то ничего не будет работать

2021-11-12 05:26 UTC, Dovgalyuk commented
Нужно сделать cmakelists.txt по примеру тестов из проекта.
Там есть параметр, который описывает, где нужно брать заголовочные файлы.

2021-11-12 07:21 UTC, gerundv commented
![S9-av8514ME (1)](https://user-images.githubusercontent.com/72885722/141426591-6ca68c5c-c520-4d9f-b089-f8135a0be86a.jpg)

2021-11-12 07:22 UTC, gerundv commented
я просто не понимаю как

2021-11-12 08:07 UTC, gerundv commented
сделал для 2.cpp, для первой лабы делать? вы тогда ничего не сказали, если делать, то здесь же или иначе как-то?

2021-11-15 05:51 UTC, Dovgalyuk requested changes

2021-11-15 05:51 UTC, Dovgalyuk commented on LibraryCPP/2.cpp
> +        if ((b[i+1] == ']') && ( stack_get(stack)=='[')){
Не нужно в одной итерации обрабатывать два символа (b[i] и b[i+1]).
В каждой стоит просматривать только один символ b[i] и на основе его типа действовать.
К тому же, тут возникнет выход за границы массива из-за этого.

2021-11-15 05:51 UTC, Dovgalyuk commented on LibraryCPP/CMakeLists.txt
> +target_link_libraries(Second LibraryCPP)
Примерно так, только это должно быть не в самой библиотеке, а где-то снаружи.

2021-11-15 05:51 UTC, Dovgalyuk commented
> сделал для 2.cpp, для первой лабы делать? вы тогда ничего не сказали, если делать, то здесь же или иначе как-то?

Для первой не надо.

2021-11-15 07:59 UTC, gerundv commented
перенёс и сделал как для внешнего файла, если запускать программу через CMake Second_work то всё работает, а в файле 2.pp такая ошибка висит stack.h: No such file or directory
попробую сделать без выхода за пределы массива

2021-11-15 10:14 UTC, gerundv commented
вроде сделал как нужно, но не понимаю почему при последовательности (")" пишет YES, на бумаге все работает правильно

2021-11-16 04:36 UTC, Dovgalyuk requested changes

2021-11-16 04:36 UTC, Dovgalyuk commented on laboratory/Second/2.cpp
> +    for (int i= 0; i <= b.length();++i){
Элемент b[b.length()] не существует.

2021-11-16 04:36 UTC, Dovgalyuk commented on laboratory/Second/2.cpp
> +}
Вот ещё один тест:
[](

2021-11-16 04:36 UTC, Dovgalyuk commented on laboratory/Second/2.cpp
> +}
И ещё вот такой:
[)]

2021-11-17 05:59 UTC, Dovgalyuk requested changes

2021-11-17 05:59 UTC, Dovgalyuk commented on laboratory/Second/2.cpp
> +        if ((stack_empty(stack)) && (b[i] != 0)) stack_push(stack,b[i]);
b[i] не нужно проверять на 0, надо просто поменять ограничение в цикле

2021-11-17 05:59 UTC, Dovgalyuk commented on laboratory/Second/2.cpp
> +            if ((stack_empty(stack)) && (b[i+1] == 0)) break;
Это условие вообще выглядит ненужным.

2021-11-17 06:12 UTC, gerundv commented on laboratory/Second/2.cpp
> +            if ((stack_empty(stack)) && (b[i+1] == 0)) break;
если этого условия не будет, то в последовательности [)] он пропустит скобку и решит, что она правильная

2021-11-17 06:26 UTC, gerundv commented on laboratory/Second/2.cpp
> +            if ((stack_empty(stack)) && (b[i+1] == 0)) break;
если не будет условия 16-й строки, то он будет пропускать первые вхождения закрывающих скобок и кавычки, то-есть в последовательностях вроде [)] он увидит ), но не увидит ( и просто пропустит символ, и выведет YES

2021-11-17 06:29 UTC, gerundv commented on laboratory/Second/2.cpp
> +            if ((stack_empty(stack)) && (b[i+1] == 0)) break;
а если вы про 17-ю строку b[i+1] то оно нужно для последовательностей типа [](), иначе он просто выйдет из цикла после удаления [

2021-11-18 04:25 UTC, Dovgalyuk commented on laboratory/Second/2.cpp
> +            if ((stack_empty(stack)) && (b[i+1] == 0)) break;
Так можно всю 17 строку удалить.

2021-11-18 08:42 UTC, gerundv commented
получается так 6c1c118

2021-11-19 07:30 UTC, Dovgalyuk commented
1. Реализовать в проекте Library кольцевой список с фиктивным элементом (модуль list) и очередь на  его основе (модуль queue).
    2. Решить задачу, используя реализованную очередь.
Задано начальное вещество и список химических реакций, в которых оно превращается в другое вещество.  Написать программу, использующую поиск в ширину, и выводящую список веществ, которые можно получить из исходного

Вход
```
A
A->B
B->C
D->E
```
Выход
```
B
C
```

В примере из вещества A можно получить вещества B и C.

2021-11-19 07:30 UTC, closed without merging