lab2 finished by Vasilev Daniil
Dovgalyuk/Algorithms pull request #279
Opened 2021-11-09 15:56 UTC by ThisIsBacya

2021-11-10 06:18 UTC, Dovgalyuk commented
Тест для вектора не проходит.

2021-11-12 05:32 UTC, Dovgalyuk requested changes

2021-11-12 05:32 UTC, Dovgalyuk commented on LibraryCPPTemplate/stack.h
> +    Stack() : vector(new Vector<Data>())
Удалять вектор тоже где-то нужно.

2021-11-15 05:55 UTC, Dovgalyuk commented
Теперь не проходит тест для стека.

2021-11-16 04:41 UTC, Dovgalyuk requested changes

2021-11-16 04:41 UTC, Dovgalyuk commented on lab2/testStack.cpp
> +                _string = _string[5];
А зачем один символ хранить в строке?

2021-11-17 05:55 UTC, Dovgalyuk requested changes

2021-11-17 05:55 UTC, Dovgalyuk commented on lab2/testStack.cpp
> +                _string.erase(0,5);
Удалять символы из строк стоит только тогда, когда это действительно нужно, потому что это не быстрая операция.
Здесь же достаточно получить один символ из строки.

2021-11-17 07:12 UTC, ThisIsBacya commented on lab2/testStack.cpp
> +                _string.erase(0,5);
Я так пробовал, но это почему-то не работает.

2021-11-18 04:27 UTC, Dovgalyuk commented on lab2/testStack.cpp
> +                _string.erase(0,5);
Стоит разобраться.

2021-11-22 08:38 UTC, Dovgalyuk requested changes

2021-11-22 08:38 UTC, Dovgalyuk commented on lab2/testStack.cpp
> +    int A[1] = {0},
Зачем нужны массивы для хранения всего одного числа?

2021-11-23 06:18 UTC, Dovgalyuk requested changes

2021-11-23 06:18 UTC, Dovgalyuk commented on lab2/testStack.cpp
> +    return 0;
Будет ли работать для таких входных данных:
PUSH 101
POP A

2021-11-24 07:22 UTC, Dovgalyuk commented
1. Реализовать в проекте Library кольцевой список с фиктивным элементом (модуль list) и очередь на  его основе (модуль queue).
    2. Решить задачу, используя реализованную очередь.
В двух строках входного файла записаны две последовательности букв. Используя очередь, проверить, можно ли получить вторую строку вычеркиванием некоторого количества букв (возможно, нулевого) из первой. Из файла разрешается читать по одному символу за раз.

Вход
```
ABCD
ABC
```

Выход
```
YES
```

Вход
```
ABCD
AABC
```

Выход
```
NO
```

2021-11-24 07:22 UTC, closed without merging