Potapenko Egor lab2
Dovgalyuk/Algorithms pull request #283
Opened 2021-11-11 10:22 UTC by Shara1p

2021-11-11 10:29 UTC, Shara1p commented
Локально все проходит нормально, здесь почему то нет.

2021-11-11 10:41 UTC, Shara1p commented
Теперь все тесты проходят.

2021-11-12 05:47 UTC, Dovgalyuk requested changes

2021-11-12 05:47 UTC, Dovgalyuk commented on LibraryCPP/vector.cpp
> +            exit(0);
Почему нужно завершать программу, если в векторе хватает места для значений?

2021-11-12 05:47 UTC, Dovgalyuk commented on lab2/PolishMath.cpp
> +            number += polishMath;
Нужно упростить все ветвления и избавиться от переменной number. Например, может выполняться switch(number[0]), когда строка number пустая. А это некорректно.

2021-11-15 07:35 UTC, Shara1p commented on LibraryCPP/vector.cpp
> +            exit(0);
Только в таком случае выполняется тест на стек

2021-11-15 07:37 UTC, Shara1p commented on LibraryCPP/vector.cpp
> +            exit(0);
Хоть я и не улавливаю взаимосвязь прохождение теста стека на github и vector.cpp, но из за изменений в векторе зависит судьба теста стека, не понимаю почему так, локально такого нет

2021-11-15 07:41 UTC, Shara1p commented on LibraryCPP/vector.cpp
> +            exit(0);
Я уже все перепробовал и из за этого у меня депрессия

2021-11-16 04:31 UTC, Dovgalyuk requested changes

2021-11-16 04:31 UTC, Dovgalyuk commented on LibraryCPP/vector.cpp
> +            exit(0);
Если в векторе уже хватает памяти, то что остаётся сделать, чтобы увеличить его видимый пользователю размер?

2021-11-16 07:16 UTC, Shara1p commented on LibraryCPP/vector.cpp
> +            exit(0);
Решил попробовать вынести расширение, копирование и перенос данных в вектор в отдельные функции, теперь все тесты проходят, хотя вроде логика та же

2021-11-16 08:31 UTC, Shara1p commented on lab2/PolishMath.cpp
> +            number += polishMath;
Но как я избавлюсь от number, где то же нужно операции хранить, а в стеке им делать нечего по идее

2021-11-17 05:53 UTC, Dovgalyuk requested changes

2021-11-17 05:53 UTC, Dovgalyuk commented on LibraryCPP/vector.cpp
> +    delete[] vector;
вот тут нужен просто оператор delete

2021-11-17 05:53 UTC, Dovgalyuk commented on lab2/PolishMath.cpp
> +            number += polishMath;
number на каждой итерации очищается, то есть он не может отличаться от переменной polishMath

2021-11-17 05:53 UTC, Dovgalyuk commented
Ещё нужно добавить файлы CMakeLists.txt, чтобы решения задач тоже компилировались на сервере.

2021-11-17 08:18 UTC, Shara1p commented
> Ещё нужно добавить файлы CMakeLists.txt, чтобы решения задач тоже компилировались на сервере.

Все правки учтены

2021-11-18 05:01 UTC, Dovgalyuk approved these changes

2021-11-18 05:03 UTC, Dovgalyuk commented
1. Реализовать в проекте Library очередь (модуль queue) с использованием двух стеков (модуль stack).
    2. Решить задачу, используя реализованную очередь.
Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной – «#» или пустым пространством – «.». Стартовая позиция обозначается как X. Написать программу, считающую количество клеток, до которых можно найти из начальной, а также выводящую лабиринт с достижимыми клетками, отмеченными символом «x». За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди.

Вход
```
######
#...X#
#.####
#....#
######
```

Выход
```
9
######
#xxxx#
#x####
#xxxx#
######
```

2021-11-18 05:03 UTC, closed without merging