1 Лабораторная работа Морозов С.И
Dovgalyuk/Algorithms pull request #284
Opened 2021-11-11 10:41 UTC by MorozowSergey

2021-11-12 05:39 UTC, Dovgalyuk requested changes

2021-11-12 05:39 UTC, Dovgalyuk commented on LibraryC/stack.c
> +    int x;
Все ненужные изменения надо отменить.

2021-11-12 05:39 UTC, Dovgalyuk commented on results/lab1.cpp
> +#include "../LibraryCPP/array.cpp"
Подключать нужно заголовочный файл.

2021-11-12 05:39 UTC, Dovgalyuk commented on results/lab1.cpp
> +	cout << "Массив меняет знак: " << k << " раза" << endl;
Будет ли работать программа для такого теста:
-10 0 10

2021-11-15 05:56 UTC, Dovgalyuk commented
1. Мусор всё ещё есть (см. вкладку Files changed).
2. Подключать с помощью include надо заголовочный файл, а не cpp.

2021-11-15 10:51 UTC, MorozowSergey commented on LibraryC/stack.c
> +    int x;
Без этих изменений программа не компилируется. Выдает ошибку "Язык C требует, чтобы в struct или union был хотя бы один член."

2021-11-15 10:57 UTC, MorozowSergey commented on results/lab1.cpp
> +	cout << "Массив меняет знак: " << k << " раза" << endl;
Программа не будет работать поскольку значение элемента массива не может быть отрицательным. Сделал условие проверки.

2021-11-15 10:57 UTC, MorozowSergey commented on results/lab1.cpp
> +#include "../LibraryCPP/array.cpp"
Исправил

2021-11-15 11:22 UTC, MorozowSergey commented on results/lab1.cpp
> +#include "../LibraryCPP/array.cpp"
Когда подключаю заголовочный файл то программа начинает ругаться на неполный тип array.

2021-11-16 04:39 UTC, Dovgalyuk requested changes

2021-11-16 04:39 UTC, Dovgalyuk commented on results/lab1.cpp
> +	Array* array = new Array(n);
Так для этого и предусмотрена функция array_create

2021-11-16 04:39 UTC, Dovgalyuk commented on results/lab1.cpp
> +	cout << "Массив меняет знак: " << k << " раза" << endl;
Имелось в виду, что это содержимое массива (т.е. размер 3).

2021-11-17 05:38 UTC, Dovgalyuk requested changes

2021-11-17 05:38 UTC, Dovgalyuk commented on results/lab1.cpp
> +	cout << "Массив меняет знак: " << k << " раза" << endl;
Стоит ещё подумать.
Вот другой вариант:
5
10 0 0 0 -10

2021-11-17 08:23 UTC, closed without merging