Третья лаба от Курилова Романа 0091
Dovgalyuk/Algorithms pull request #288
Opened 2021-11-17 07:56 UTC by zyzic1001

2021-11-18 04:53 UTC, Dovgalyuk requested changes

2021-11-18 04:53 UTC, Dovgalyuk commented on HelpMeGod/laba3/NyPognali.cpp
> +        if (temp == i) {
Будет сильно нагляднее, если temp будет просто bool

2021-11-18 04:53 UTC, Dovgalyuk commented on HelpMeGod/laba3/NyPognali.cpp
> +bool bfs(int** graph, int n, int to, int* visited, list<int>& buffer, int* parents) {
Нужно убрать рекурсию и вместо buffer использовать собственную очередь.

2021-11-18 04:53 UTC, Dovgalyuk commented on HelpMeGod/laba3/NyPognali.cpp
> +        if (find(buffer.begin(), buffer.end(), i) != buffer.end())
Если visited выставлять прямо тут, то этот поиск не понадобится.

2021-11-18 04:53 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    ListItem* last = NULL;
Список же кольцевой, last можно легко находить и без хранения его в отдельной переменной.

2021-11-18 04:53 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +    queue->last = NULL;
Целесообразно расширить интерфейс списка, чтобы можно было получать последний элемент.

2021-11-18 04:53 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +    return (list_first(queue->lst) != NULL) ? false : true;
Стоит упростить это выражение.

2021-11-22 09:33 UTC, Dovgalyuk requested changes

2021-11-22 09:33 UTC, Dovgalyuk commented on HelpMeGod/laba3/NyPognali.cpp
> +            if (find(tempMas.begin(), tempMas.end(), i) != tempMas.end()) {
Надо избавиться от этого массива.
Просто по одной вершине доставать из очереди и обрабатывать. Перекладывать в другой массив не нужно.

2021-11-22 10:10 UTC, zyzic1001 commented
Исправил все прошлые ошибки и избавился от массива.

2021-11-22 10:55 UTC, zyzic1001 commented
Так же у меня появился вопрос по практическому заданию 7.2 "Коллизии". Как создать собственную хеш-функцию и запихнуть её во второй параметр шаблона unordered_set?

2021-11-23 06:08 UTC, Dovgalyuk commented
Вот здесь есть пример по хеш-функциям: https://en.cppreference.com/w/cpp/utility/hash
Но можно и иначе делать, явно передавая нужную функцию в шаблон.

2021-11-23 06:11 UTC, Dovgalyuk requested changes

2021-11-23 06:11 UTC, Dovgalyuk commented on HelpMeGod/laba3/NyPognali.cpp
> +    int from = queue_get(ochered);
Если немного переделать цикл и извлекать элемент в начале, а не в конце итерации, то эти действия перед его началом будут не нужны.

2021-11-23 06:11 UTC, Dovgalyuk commented on HelpMeGod/laba3/NyPognali.cpp
> +            for (int j = 0; j < sizeOchered; j++) {
Не нужно просматривать очередь, нужно просто добавить туда элемент.
Чтобы они не добавлялись по два раза, можно visited устанавливать в момент добавления в очередь.

2021-11-23 07:49 UTC, zyzic1001 commented on HelpMeGod/laba3/NyPognali.cpp
> +    int from = queue_get(ochered);
Переделал

2021-11-23 07:50 UTC, zyzic1001 commented on HelpMeGod/laba3/NyPognali.cpp
> +            for (int j = 0; j < sizeOchered; j++) {
Переделал

2021-11-24 07:14 UTC, Dovgalyuk commented
1. Разработать программный интерфейс модуля (заголовки функций) для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
    2. Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
    3. Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List той же библиотеки.
    4. Разработать и добавить в проект программу, тестирующую работу библиотеки для графа.
    5. Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать в нем длины кратчайших путей от одной вершины до всех остальных с помощью алгоритма Дейкстры.

2021-11-24 07:14 UTC, closed without merging

2021-11-26 09:56 UTC, zyzic1001 commented
Чуть-чуть не по теме вопрос, но что вы имели ввиду под фразой: "Напишите два варианта программы: с преобразованием хранимых в std::map слов и без него" в задаче 8.2 "Подсчёт слов" по практике?

2021-11-26 12:10 UTC, Dovgalyuk commented
Значит, что нужно реализовать функцию сравнения, игнорирующую регистр символов.