Третье задание Филимоненков Дмитрий 0091
Dovgalyuk/Algorithms pull request #292
Opened 2021-11-19 18:25 UTC by Philush

2021-11-22 08:42 UTC, Dovgalyuk requested changes

2021-11-22 08:42 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
>      ~List()
Список должен быть с фиктивным элементом, который упрощает реализацию операций добавления и удаления, но сам не хранит никаких данных.
Поэтому в конструкторе его необходимо создавать.

2021-11-23 05:57 UTC, Dovgalyuk commented
Проект не компилируется.

2021-11-24 07:59 UTC, Dovgalyuk requested changes

2021-11-24 07:59 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +                dummyElement->nextItem  = nullptr;
Этот элемент должен указывать сам на себя в случае пустого списка.
Поэтому стоит добавить также функцию empty, чтобы остальной код мог проверять пустоту не вдаваясь в детали реализации.

2021-11-24 08:04 UTC, Philush commented on LibraryCPPTemplate/list.h
> +                dummyElement->nextItem  = nullptr;
но если фиктивный элемент будет указывать сам на себя, то в методе first() придётся делать проверку, что случайно не вернуть фиктивный элемент

2021-11-25 05:28 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +                dummyElement->nextItem  = nullptr;
Да, придётся.

2021-11-26 12:08 UTC, Dovgalyuk requested changes

2021-11-26 12:08 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +        }
осталось удалить сам фиктивный элемент

2021-11-26 12:08 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +        newItem->nextItem = firstItem;
это всё можно получить от dummyElement, не нужно ветвлений и вызовов first()

2021-11-26 12:08 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +        newItem->nextItem = firstItem;
можно даже реализовать эту функцию через вызов insert_after

2021-11-26 12:08 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
>      Item *erase(Item *item)
выглядит излишне сложным

2021-11-26 12:08 UTC, Dovgalyuk commented on Tasks/Task3/task3.cpp
> +        for (int i = 0; i < size; ++i) {
можно обойтись без этого цикла, а просто в основном удалять по одному элементу

2021-11-29 06:02 UTC, Dovgalyuk requested changes

2021-11-29 06:02 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +        item->prevItem->nextItem = item->nextItem;
ещё нужно память очистить

2021-11-29 06:02 UTC, Dovgalyuk commented on Tasks/Task3/task3.cpp
> +        int length = ++lengths[id];
может быть lengths[id] + 1?

2021-11-30 05:42 UTC, Dovgalyuk commented
1. Разработать программный интерфейс модуля (заголовки функций) для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
    2. Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
    3. Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List той же библиотеки.
    4. Разработать и добавить в проект программу, тестирующую работу библиотеки для графа.
    5. Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать в нем количество компонентов связности с помощью обхода в глубину.

2021-11-30 05:42 UTC, closed without merging