Шиков Кирилл Дмитриевич 0091: Шестое задание
Dovgalyuk/Algorithms pull request #293
Opened 2021-11-19 22:42 UTC by NovolMob

2021-11-22 09:42 UTC, Dovgalyuk requested changes

2021-11-22 09:42 UTC, Dovgalyuk commented on LibraryCPPTemplate/string.h
> +    String(char* chars, int length): string(chars), capacity(length), length(length) {}
А если вызывающая сторона освободит массив?

2021-11-22 09:42 UTC, Dovgalyuk commented on LibraryCPPTemplate/string.h
> +    String(String& src): string(src.string), capacity(src.length), length(src.length) {}
Две строки будут указывать на один и тот же массив символов?

2021-11-22 09:42 UTC, Dovgalyuk commented on LibraryCPPTemplate/string.h
> +    void append(String secondString) {
Вот тут стоит сделать параметр константной ссылкой, чтобы избежать копирования.

2021-11-23 06:01 UTC, Dovgalyuk requested changes

2021-11-23 06:01 UTC, Dovgalyuk commented on LibraryCPPTemplate/string.h
> +            string = newString;
а как же удалить старую строку?

2021-11-23 06:01 UTC, Dovgalyuk commented on LibraryCPPTemplate/string.h
> +    int findString(String const &str, size_t pos = 0) {
Тут должен быть реализован алгоритм Кнута-Морриса-Пратта.
Ну и не помешает сделать тест для измерения его производительности.

2021-11-23 06:01 UTC, Dovgalyuk commented on LibraryCPPTemplate/string.h
> +        return length == secondString.length && findString(secondString) == 0;
для этого же есть compare

2021-11-23 22:55 UTC, NovolMob commented on LibraryCPPTemplate/string.h
> +        return length == secondString.length && findString(secondString) == 0;
Вообще эта функция была сделана для удобства пользователя, ведь compare возвращает от -1 до 1 и если строки совпадают, то вернулся бы 0, тогда пользователю для проверки необходимо сделать либо if( compare() == 0 ), либо if ( !compare() ), но это не так легко воспринимать, то есть читаемость кода уменьшается. Для решения проблемы был создан метод equal который вернёт true, если строки совпадаю, и false, если нет.

2021-11-23 22:56 UTC, NovolMob commented on LibraryCPPTemplate/string.h
> +    int findString(String const &str, size_t pos = 0) {
Тест я сделал, но построение графика, я думаю, не имеет смысла, значения получилось измерить только в микросекундах и они очень часто прыгают из-за нагрузки системы.

2021-11-24 08:18 UTC, Dovgalyuk requested changes

2021-11-24 08:18 UTC, Dovgalyuk commented on LibraryCPPTemplate/string.h
> +        return length == secondString.length && findString(secondString) == 0;
Речь о том, что ни к чему вызывать findString.

2021-11-24 08:18 UTC, Dovgalyuk commented on LibraryCPPTemplate/string.h
> +    int findString(String const &str, size_t pos = 0) {
Смысл в том, чтобы проверить корректность и убедиться, что сложность не O(N^2)

2021-11-25 05:31 UTC, Dovgalyuk commented
принято

2021-11-25 05:31 UTC, closed without merging