Третье задание Авдеев 0092
Dovgalyuk/Algorithms pull request #294
Opened 2021-11-23 08:43 UTC by gerundv

2021-11-24 07:18 UTC, Dovgalyuk requested changes

2021-11-24 07:18 UTC, Dovgalyuk commented on laboratory/CMakeLists.txt
> +add_subdirectory(Second)
Конфиг для третьей работы тоже нужен.

2021-11-24 07:18 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +    }
Это всё можно записать в одну строчку, просто вернув результат логического выражения.

2021-11-24 07:18 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
>      return new List;
В списке должен быть фиктивный элемент, который не хранит полезных данных, но позволяет упростить операции добавления и удаления.

2021-11-25 09:42 UTC, gerundv commented
сколько смотрел про фиктивный элемент так и не понял как его создать и вставить в список, хотя в голове какое-то представление сложилось, есть-ли в репозитории в каком-нибудь из уроков нормальное объяснение фиктивного элемента и его создания, или есть ли у вас ссылка на что-то похожее?

2021-11-25 09:46 UTC, gerundv commented
или создать его как элемент листа и считать его концом списка? @8f4dee4

2021-12-01 05:20 UTC, Dovgalyuk commented
> до меня что-то всё равно пока что не дошло как описать фиктивный элемент, но я понял, что он должен хранить указатель на prev(предыдущий), и чтобы next указывал на этот фиктивный элемент, верно? написал ещё саму программу для задачи

Да, если фиктивный элемент это X, то
X->prev - последний элемент списка
X->next - первый полезный элемент списка
Если список пустой, то X->prev == X->next == X

2021-12-01 05:22 UTC, Dovgalyuk commented
В задаче всё немного не так.
Нужно просматривать все варианты превращений веществ. Полученные в результате вещества тоже могут превращаться.

2021-12-07 13:15 UTC, gerundv commented
Как вариант. Я ещё не до конца разобрался, да и примеров в интернете немного, поэтому пока получается с ошибками. А с задачей - не понял как её нужно доработать, можно ещё примеров для проверок, чтобы стало понятней?

2021-12-08 05:58 UTC, Dovgalyuk commented
Примеры:
```
A
A->B
B->C
D->E
Ответ: B C

A
A->B
B->C
C->E
C->F
Ответ: B C E F

A
G->H
G->K
I->J
A->C
B->D
C->F
A->B
C->E
Ответ: B C D E F
```

2021-12-09 06:08 UTC, Dovgalyuk commented
Почти хорошо. Вот ещё тест:

A
A->B
B->A

2021-12-12 19:03 UTC, gerundv commented
Нужно ли что-то ещё в листе переделать?

2021-12-13 08:06 UTC, Dovgalyuk requested changes

2021-12-13 08:06 UTC, Dovgalyuk commented on laboratory/Third/3.cpp
> +                if (str.find(str[j])!=str.find(str[j+1]) + 1){
Сомнительная проверка.
Лучше помечать где-то отдельно те буквы, которые уже встречались. Тогда они и в выводе не будут повторяться, и бесконечных циклов не будет.

2021-12-14 05:19 UTC, gerundv commented
я вот не уверен нужна ли тут проверка для первого раза на наличие отмеченных значений, она работает и без неё, и потери памяти нету, там ведь пустая строка

2021-12-14 06:35 UTC, Dovgalyuk commented on laboratory/Third/3.cpp
> +                    if ((str[j+1]==str_save[i]) || (str[j+1]==basic))
Ну можно было basic добавить в str_save сразу.
А ещё лучше было бы сделать массив с индексом-буквой. Было бы эффективнее по времени.

2021-12-14 06:36 UTC, Dovgalyuk commented
1. Разработать программный интерфейс модуля (заголовки функций) для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
    2. Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
    3. Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде матрицы смежности в контейнере Array той же библиотеки.
    4. Разработать и добавить в проект программу, тестирующую работу библиотеки для графа.
    5. Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать для него минимальное покрывающее дерево алгоритмом Крускала.

2021-12-14 06:36 UTC, closed without merging