Гуревич Кирилл Михайлович - 0092 - решение шестой задачи
Dovgalyuk/Algorithms pull request #297
Opened 2021-11-24 13:54 UTC by Kirilliriks

Решение находиться в папке Result.
Я не до конца понял задачу и появилось несколько вопросов:
1) Правильно ли я справился с первой задачей? Вроде как я решил это с помощью перебора
2) Что значит доработать алгоритм с принципами динамического программирования? Я много гуглил но так и не нашёл что-то в чём могу быть уверенным
3) Какие границы у входных данных различного объёма?
4) Оценить по графику сложность обоих вариантов решения- с этим понятно, а вот оценить по программе немного непонятно что нужно конкретно сделать

2021-11-25 05:43 UTC, Dovgalyuk commented
1. Похоже на правду по описанию (в код я не вникал). Но можно сделать несколько проще: рекурсивная функция, которая считает максимум. Чтобы это сделать, она пробует каждую операцию делать последней (т.е. виртуально ставит скобки). А для подвыражений слева и справа вызывается рекурсивно. Правда иногда придётся искать минимум, а не максимум (например, для правой части вычитания).
2. Полученное решение иногда будет повторно вычислять одни и те же подзадачи (то есть подвыражения). Динамическое программирование - это принцип, по которому повторяющиеся подзадачи не вычисляются заново, а берутся уже готовые ответы (например, их можно хранить в массиве).
3. На 64 символах уже можно получить очень долго работающее решение.
4. Оценить временную сложность, анализируя алгоритм работы программы.

2021-11-25 14:00 UTC, Kirilliriks commented
@Dovgalyuk было сложно, но мне кажется я справился. Алгоритм не идеален, но нагляден и прост в изучении логики его работы. К репозиторию приложил скриншот графика времени выполнения работы графика без модификации и с модификацией по принципам динамического программирования.
Сложность работы программы оцениваю в O(n^3)

2021-11-26 11:36 UTC, Dovgalyuk commented
next_permutation это точно не вариант, у него же сложность O(N!)

2021-11-27 17:13 UTC, Kirilliriks commented
@Dovgalyuk переписал алгоритм

2021-11-29 11:51 UTC, Kirilliriks commented
@Dovgalyuk переписал алгоритм

2021-11-30 05:58 UTC, Dovgalyuk requested changes

2021-11-30 05:58 UTC, Dovgalyuk commented on Result/laboratoryfinal.cpp
> +            key.second = inputString.substr(leftIndex * 2, (rightIndex + 1) * 2 + 1 - leftIndex * 2);
для ключа достаточно индексы использовать, а не подстроку

2021-11-30 05:58 UTC, Dovgalyuk commented on Result/laboratoryfinal.cpp
> +                left = findMax(leftIndex, i - 1, dynamic);
findMin потерялось, вроде бы здесь оно должно иметь смысл

2021-11-30 05:58 UTC, Dovgalyuk commented on Result/laboratoryfinal.cpp
> +                right = findMax(i + 1, rightIndex, dynamic, (operation == '-'));
и тут новый findMin должен зависеть и от старого тоже

2021-11-30 12:28 UTC, Kirilliriks commented on Result/laboratoryfinal.cpp
> +            key.second = inputString.substr(leftIndex * 2, (rightIndex + 1) * 2 + 1 - leftIndex * 2);
Done.

2021-11-30 12:38 UTC, Kirilliriks commented
@Dovgalyuk исправлено

2021-12-01 05:50 UTC, Dovgalyuk commented
Принято. К защите нужно обдумать временную сложность.

2021-12-01 05:50 UTC, closed without merging