Lab 1 | Ivanov Nikolay 0092
Dovgalyuk/Algorithms pull request #298
Opened 2021-11-24 17:24 UTC by Nikolay0092

1. Реализовать контейнер-неизменяемый динамический массив array (на любом из языков)
2. Проверить работу соответствующей тестовой программы
3. В своей программе ввести целое число с клавиатуры, создать массив такой размерности и заполнить его случайными (подходящими под следующий пункт) числами.
4. Нечетные элементы массива уменьшить на m, а элементы с нечетными номерами
увеличить на n. m и n ввести с клавиатуры.

2021-11-25 05:47 UTC, Dovgalyuk requested changes

2021-11-25 05:47 UTC, Dovgalyuk commented on LibraryCPP/array.cpp
>      delete arr;
Надо освободить память не только от структуры, но и от самого массива элементов.

2021-11-25 05:47 UTC, Dovgalyuk commented on First/main.cpp
> +            array_set(array, i, array_get(array, i) - m);
Нужно не все элементы уменьшать на m.

2021-11-25 11:48 UTC, Nikolay0092 commented on First/main.cpp
> +            array_set(array, i, array_get(array, i) - m);
Там на м уменьшаются нечетные числа. Или я что-то не правильно понимаю?

2021-11-25 12:14 UTC, Nikolay0092 commented on First/main.cpp
> +            array_set(array, i, array_get(array, i) - m);
Вывод программы

input number 15
n input number 6
m input number 4
41 467 334 500 169 724 478 358 962 464 705 145 281 827 961
37 463 340 506 165 730 484 364 968 470 701 141 277 823 957

2021-11-26 11:45 UTC, Dovgalyuk commented
1. Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
    2. Решить задачу, используя реализованный стек.
Дано выражение в обратной польской записи. Используя стек, написать программу, которая проверяет выражение на наличие ошибок. Ошибкой считается деление на 0 (ZERO), выполнение операции, когда в стеке меньше двух элементов (UNDERFLOW), наличие больше одного элемента в стеке после завершения работы программы (OVERFLOW).

Вход
```
1
2
+
3
```
Выход
```
OVERFLOW
```

Вход
```
10
9
-
+
```
Выход
```
UNDERFLOW
```

2021-11-26 11:45 UTC, closed without merging