Алексеев Даниил Николаевич 0091 - laba2
Dovgalyuk/Algorithms pull request #299
Opened 2021-11-25 08:35 UTC by Lashy-Danya

2021-11-26 11:26 UTC, Dovgalyuk commented
Уже пора третье задание присылать.

2021-11-26 11:56 UTC, Lashy-Danya commented
А какое задание к третьему?

2021-11-26 12:14 UTC, Dovgalyuk commented
Не в ту колонку таблицы посмотрел, сейчас проверю это задание.

2021-11-26 12:17 UTC, Dovgalyuk requested changes

2021-11-26 12:17 UTC, Dovgalyuk commented on LibraryCPP/zadanie2.cpp
> +    int A[1] = {0}, B[1] = {0}, C[1] = {0}, D[1] = {0};
для чего здесь используются массивы?

2021-11-26 14:35 UTC, Lashy-Danya commented on LibraryCPP/zadanie2.cpp
> +    int A[1] = {0}, B[1] = {0}, C[1] = {0}, D[1] = {0};
Данные массивы используются для хранения значения каждого регистра. Конечно было бы разумнее написать единым массивом, например `int Registers[4] = {0, 0, 0, 0}`, где под нулевым индексом был бы A, потом B и т. д. Но я хотел такого вида запись (регистр = значение). То тогда нужно было использовать просто переменные  (с целочисленным типом данных) и присвоить им также нули.

2021-11-29 05:58 UTC, Dovgalyuk requested changes

2021-11-29 05:58 UTC, Dovgalyuk commented on LibraryCPP/CMakeLists.txt
> +target_link_libraries(TestSecondTask LibraryCPP)
Сборка заданий должна быть описана не внутри библиотеки, а где-то в собственном конфиге.

2021-11-29 06:33 UTC, Lashy-Danya commented on LibraryCPP/CMakeLists.txt
> +target_link_libraries(TestSecondTask LibraryCPP)
Изменил

2021-11-30 05:37 UTC, Dovgalyuk requested changes

2021-11-30 05:37 UTC, Dovgalyuk commented on Laba/zadanie2.cpp
> +    return 0;
как насчёт такого теста:
PUSH 101
POP A

2021-11-30 06:38 UTC, Lashy-Danya commented on Laba/zadanie2.cpp
> +    return 0;
Исправил, я не правильно получал число. Теперь делается с помощью метода строк ` substr`

2021-12-01 05:07 UTC, Dovgalyuk commented
1. Реализовать в проекте Library очередь (модуль queue) с использованием двух стеков (модуль stack).
    2. Решить задачу, используя реализованную очередь.
Во входном файле заданы два числа a, b и последовательность целых чисел. За один просмотр файла с этой последовательностью переписать ее элементы в выходной файл так, чтобы сначала шли числа меньшие заданного числа a, затем все числа из отрезка [a, b], а затем – все остальные. Взаимный порядок чисел в каждой из групп должен быть сохранен. Входной файл содержит числа a, b и последовательность, которую нужно переписать. При реализации программы использовать очередь.

Вход
1 2
0 -1 1 5 6 2 1 7 -2

Выход
0 -1 -2 1 2 1 5 6 7

2021-12-01 05:07 UTC, closed without merging