Лабораторная работа №3 Радаева Кирилла
Dovgalyuk/Algorithms pull request #300
Opened 2021-11-25 13:46 UTC by Golod-ru

2021-11-26 12:00 UTC, Dovgalyuk requested changes

2021-11-26 12:00 UTC, Dovgalyuk commented on laba/lab3/laba3.cpp
> +			if (mat[x][y] == index)
Не нужно искать в матрице эти клетки, координаты надо брать прямо из очереди.

2021-11-26 12:21 UTC, Golod-ru commented on laba/lab3/laba3.cpp
> +			if (mat[x][y] == index)
Так у меня в очереди находиться только значение этой клетки, а координат в ней нету.

2021-11-29 05:52 UTC, Dovgalyuk commented on laba/lab3/laba3.cpp
> +			if (mat[x][y] == index)
Вот координаты и надо хранить.

2021-12-01 05:25 UTC, Dovgalyuk requested changes

2021-12-01 05:25 UTC, Dovgalyuk commented on laba/lab3/laba3.cpp
> +	int index = queue_get(qu);
Можно его не хранить в очереди, а доставать из матрицы по координатам.

2021-12-01 05:25 UTC, Dovgalyuk commented
И ещё тест падает.

2021-12-01 10:44 UTC, Golod-ru commented
Исправил все, что вы сказали.

2021-12-03 06:26 UTC, Dovgalyuk commented
1. Разработать программный интерфейс модуля (заголовки функций) для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
    2. Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
    3. Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List той же библиотеки.
    4. Разработать и добавить в проект программу, тестирующую работу библиотеки для графа.
    5. Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать в нем кратчайший пути между заданной парой вершин с помощью обхода в ширину.

2021-12-03 06:26 UTC, closed without merging