2 Лабораторная работа Морозов С.И
Dovgalyuk/Algorithms pull request #302
Opened 2021-11-28 11:43 UTC by MorozowSergey

2021-11-28 11:51 UTC, MorozowSergey commented
Здравствуйте. Подскажите пожалуйста почему не прошли тесты?

2021-11-29 06:09 UTC, Dovgalyuk commented
Проект не собрался из-за того, что компилятор не смог выбрать правильную функцию tolower.

2021-11-30 05:50 UTC, Dovgalyuk requested changes

2021-11-30 05:50 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        list->head = elem;
Это действие выполняется в обеих ветках, можно его вынести.

2021-11-30 05:50 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    while (elem != NULL && elem != item )
Зачем нужен этот цикл?

2021-11-30 05:50 UTC, Dovgalyuk commented on results/lab2.cpp
> +}
Стек нужно ещё удалить.

2021-11-30 09:53 UTC, MorozowSergey commented on LibraryCPP/list.cpp
> +    while (elem != NULL && elem != item )
Проверяли является ли элемент head(головой).

2021-12-01 05:16 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    while (elem != NULL && elem != item )
Тогда нужно написать просто if.

2021-12-01 05:17 UTC, Dovgalyuk requested changes

2021-12-01 05:17 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        if (elem->next != NULL)
Эти действия есть в обеих ветках основного ветвления.

2021-12-01 11:58 UTC, MorozowSergey commented on LibraryCPP/list.cpp
> +        if (elem->next != NULL)
Извините, не понял о каких действиях идет речь. В теле основного If рассматривается ситуация, когда удаляется головной элемент листа. В этом случае  указатель на голову перемещается к следующему элементу. В теле else обрабатывается ситуация удаления из середины списка. При этом изменяются указатели соседних элементов.

2021-12-03 06:32 UTC, Dovgalyuk requested changes

2021-12-03 06:32 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        if (elem->next != NULL)
Речь о присваивании elem->next->prev
Оно так или иначе делается в обоих вариантах. И оба раза с одинаковой проверкой.

2021-12-06 05:55 UTC, Dovgalyuk commented
1. Реализовать в проекте Library массив переменного размера (модуль vector) и очередь на основе этого массива (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
    2. Решить задачу, используя реализованную очередь.
Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной – «#» или пустым пространством – «.». Стартовая позиция обозначается как X. Написать программу, считающую количество клеток, до которых можно найти из начальной, а также выводящую лабиринт с достижимыми клетками, отмеченными символом «x». За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди.

Вход
```
######
#...X#
#.####
#....#
######
```

Выход
```
9
######
#xxxx#
#x####
#xxxx#
######
```

2021-12-06 05:55 UTC, closed without merging