Potapenko Egor: Added solution on a third lab (lab3)
Dovgalyuk/Algorithms pull request #303
Opened 2021-11-30 08:55 UTC by Shara1p

2021-12-01 05:15 UTC, Dovgalyuk requested changes

2021-12-01 05:15 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +void queue_insert(Queue* queue, Data data)
Постоянно перемещать элементы не стоит.
Входящие элементы должны попадать в один стек, а исходящие извлекаться из другого.
И только если не хватает того, что надо извлечь, данные перемещаются из одного стека в другой.

2021-12-01 05:15 UTC, Dovgalyuk commented on lab3/Labirintum.cpp
> +enum labirintElements {X = 88, dot = 46, cage = 35,};
константы можно записывать так: X = 'X'

2021-12-01 05:15 UTC, Dovgalyuk commented on lab3/Labirintum.cpp
> +                startY = lastY;
Достаточно только переменных start. Текущие их значения должны получаться из очереди.
Тогда не нужна будет сложная логика их модификации.

2021-12-07 11:56 UTC, Shara1p commented on lab3/Labirintum.cpp
> +                startY = lastY;
А как я эти координаты положу в очередь, хорошо, можно просто их туда одним за другим положить, но потом будут  проблемы с доставанием, тк после доставания 1, нужно будет удалять его из очереди чтобы достать вторую координату. То есть не получится так: switch(labirint[queue_get(queue)][queue_get(queue)])

2021-12-08 05:55 UTC, Dovgalyuk commented on lab3/Labirintum.cpp
> +                startY = lastY;
Можно сделать две очереди, если в одной хранить не хочется.

2021-12-08 11:21 UTC, Shara1p commented on lab3/Labirintum.cpp
> +                startY = lastY;
Я не очень понимаю как мне без пременных last возвращаться к предыдущим значениям координат, если текущие не подходят

2021-12-09 05:35 UTC, Dovgalyuk commented on lab3/Labirintum.cpp
> +                startY = lastY;
Обход в ширину не требует никаких возвратов. Всегда обрабатывается конкретная клетка, полученная из очереди. Её соседи, в которых мы ещё не были, помещаются в очередь. Постепенно все клетки будут просмотрены и очередь опустеет.

2021-12-10 07:29 UTC, Shara1p commented on lab3/Labirintum.cpp
> +                startY = lastY;
Переделал, вроде сообразил наконец

2021-12-10 12:59 UTC, Dovgalyuk requested changes

2021-12-10 12:59 UTC, Dovgalyuk commented on lab3/Labirintum.cpp
> +                queue_insert(queueX, queue_get(queueX));
А зачем снова эту же клетку добавлять в очередь?

2021-12-10 12:59 UTC, Dovgalyuk commented on lab3/Labirintum.cpp
> +                queue_remove(queueX);
remove делается всегда, можно вынести из switch

2021-12-10 12:59 UTC, Dovgalyuk commented on lab3/Labirintum.cpp
> +        for (int i = 0; i < 4; i++) {
Этот цикл бесполезен. Можно без него, просто на каждой итерации извлекать из очереди элемент и обрабатывать его.

2021-12-13 08:38 UTC, Shara1p commented on lab3/Labirintum.cpp
> +                queue_insert(queueX, queue_get(queueX));
Я ее как бы из начала списка в конец перемещаю

2021-12-13 08:57 UTC, Shara1p commented on lab3/Labirintum.cpp
> +        for (int i = 0; i < 4; i++) {
Он нужен для ограничения, иначе выпадет исключение, выход за пределы вектора

2021-12-14 06:04 UTC, Dovgalyuk requested changes

2021-12-14 06:04 UTC, Dovgalyuk commented on lab3/Labirintum.cpp
> +        for (int i = 0; i < 4; i++) {
Значит где-то есть ошибка в реализации очереди. Код явно будет проще без этого цикла.

2021-12-14 06:04 UTC, Dovgalyuk commented on lab3/Labirintum.cpp
> +                queue_insert(queueX, queue_get(queueX));
Но зачем, если она уже обработана? Можно просто делать putCoordinates для этой клетки, не добавляя её заново.

2021-12-15 07:02 UTC, Dovgalyuk commented
Следующее задание будет после защиты.

2021-12-15 07:02 UTC, closed without merging

2021-12-17 11:13 UTC, Dovgalyuk commented
1. Разработать программный интерфейс модуля (заголовки функций) для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
    2. Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
    3. Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде матрицы смежности в контейнере Vector той же библиотеки.
    4. Разработать и добавить в проект программу, тестирующую работу библиотеки для графа.
    5. Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать для него минимальное покрывающее дерево алгоритмом Прима.

2022-01-12 10:07 UTC, Shara1p commented
Извините, а разве алгоритм Прима это не для неориентированных графов? Разве им можно пользоваться для ориентированных?