second lab
Dovgalyuk/Algorithms pull request #304
Opened 2021-11-30 18:28 UTC by veahcen

2021-12-01 05:30 UTC, Dovgalyuk requested changes

2021-12-01 05:30 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +        Item* prevItem = nullptr;
Если уж мы работаем с классами, то данные должны быть в приватной или защищённой секции.

2021-12-01 05:30 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +        Item *prev() { return prevItem; }
В задании был односвязный список.

2021-12-01 10:34 UTC, veahcen commented on LibraryCPPTemplate/list.h
> +        Item *prev() { return prevItem; }
// Not applicable for the singly linked lists.

2021-12-03 06:28 UTC, Dovgalyuk requested changes

2021-12-03 06:28 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +        Item *prev() { return prevItem; }
Методы с этим комментарием можно не реализовывать.

2021-12-06 06:39 UTC, Dovgalyuk commented
1. Реализовать в проекте Library массив переменного размера (модуль vector) и очередь на основе этого массива (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
    2. Решить задачу, используя реализованную очередь.
Во входном файле записано количество вершин и матрица смежности ориентированного графа. Вывести в выходной файл список расстояний от первой вершины до всех остальных. Для вычисления расстояний использовать поиск в ширину.

Вход
```
4
0 1 0 0
0 0 1 1
1 0 0 1
0 1 0 0
```

Выход
```
0
1
2
2
```

2021-12-06 06:39 UTC, closed without merging