Четвёртое задание Филимоненков Дмитрий 0091
Dovgalyuk/Algorithms pull request #306
Opened 2021-11-30 23:52 UTC by Philush

2021-12-01 05:42 UTC, Dovgalyuk requested changes

2021-12-01 05:42 UTC, Dovgalyuk commented on LibraryCPPTemplate/directed_graph.h
> +        Vertex* from;
Нет смысла хранить вершину "откуда", так как должны использоваться списки смежности, которые принадлежат конкретным вершинам.

2021-12-01 05:42 UTC, Dovgalyuk commented on LibraryCPPTemplate/Tests/directed_graph.cpp
> +    if (count != 5) {
После этого можно удаление вершин ещё потестировать.

2021-12-01 05:42 UTC, Dovgalyuk commented on LibraryCPPTemplate/directed_graph.h
> +        void operator ++(int i) {
Операторы ++ должны возвращать ссылку или значение объекта (в зависимости от оператора).

2021-12-01 05:42 UTC, Dovgalyuk commented on LibraryCPPTemplate/directed_graph.h
> +                founded = item;
Можно сразу делать return

2021-12-01 05:42 UTC, Dovgalyuk commented on LibraryCPPTemplate/directed_graph.h
> +            delete vertex;
А если другие рёбра ссылаются на эту вершину?

2021-12-01 20:28 UTC, Philush commented
Вопрос по поводу задания, поскольку у меня ориентированный граф, хотел бы уточнить, какие именно компоненты связности мне надо найти? сильные или слабые?

2021-12-03 06:34 UTC, Dovgalyuk commented
Сильные поинтереснее будут.

2021-12-07 05:16 UTC, Dovgalyuk commented
Принято. Следующее задание будет после защиты.

2021-12-07 05:16 UTC, closed without merging

2021-12-17 10:48 UTC, Dovgalyuk commented
1. Разработать интерфейс (набор функций) для ассоциативного массива, который хранит пары (ключ)строка -> (значение)строка. Поддерживаемые операции: добавить пару ключ-значение, найти значение по ключу, удалить значение по ключу.
    2. Реализовать ассоциативный массив на основе splay tree.
    3. Создать тест для проверки работы контейнера. Программа должна включать в себя нагрузочное тестирование для исключения ошибок, приводящих к сложности работы O(N2) при поиске, удалении или добавлении.
    4. Написать генератор входных данных различного объема для этого контейнера. Сравнить скорость выполнения операций добавления в контейнер и поиска содержимого файла для splay tree и для std::map при различных объемах данных.
    5. Построить зависимость высоты дерева от времени при последовательном выполнении множества операций поиска