0092 Шустров Василий lab #4
Dovgalyuk/Algorithms pull request #310
Opened 2021-12-02 16:38 UTC by Lostmindd

2021-12-03 06:44 UTC, Dovgalyuk requested changes

2021-12-03 06:44 UTC, Dovgalyuk commented on LibraryCPP/directed_graph.h
> +void add_vertex(struct directed_graph** graph); //add an vertex by copying the old array to the new array (where is 1 element more)
Надо как-то обойтись без указателя на указатель.

2021-12-03 06:44 UTC, Dovgalyuk commented on LibraryCPP/directed_graph.h
> +	edge* matrix;
Тут нужно использовать библиотеку Array, которая была реализована ранее.

2021-12-03 06:44 UTC, Dovgalyuk commented on LibraryCPP/directed_graph.h
> +	iterator* iter;
Этот указатель не нужен, пользователь же может запросить несколько итераторов.

2021-12-03 20:51 UTC, Lostmindd commented on LibraryCPP/directed_graph.h
> +	edge* matrix;
Получается библиотеку array нужно переделать под работу с шаблонами?

2021-12-05 16:31 UTC, Lostmindd commented on LibraryCPP/directed_graph.h
> +	edge* matrix;
сделал

2021-12-06 07:57 UTC, Dovgalyuk requested changes

2021-12-06 07:57 UTC, Dovgalyuk commented on LibraryCPP/directed_graph.h
> +#include "../LibraryCPPTemplate/array.h" //else it uses the wrong array.h
Надо путь прописать в конфиге.

2021-12-06 07:57 UTC, Dovgalyuk commented on LibraryCPP/directed_graph.h
> +	int vertexes_amount;
Полное описание структуры нужно унести в *.cpp, а здесь оставить только объявление struct directed_graph;

2021-12-06 07:57 UTC, Dovgalyuk commented on LibraryCPP/directed_graph.h
> +directed_graph::iterator* new_iterator(directed_graph* graph);
Итератор должен создаваться для конкретной вершины.

2021-12-06 07:57 UTC, Dovgalyuk commented on LibraryCPP/directed_graph.h
> +		int NextNeighborIndex(int vertex)
Тут параметр не нужен, итератор должен всегда работать с одной и той же вершиной.

2021-12-06 07:57 UTC, Dovgalyuk commented on SOLUTION/lab4.cpp
> +	auto iter = new_iterator(graph);
Надо ещё потом удалять его.

2021-12-06 07:57 UTC, Dovgalyuk commented on SOLUTION/lab4.cpp
> +			SearchInDepth(next, graph, &(*time), &(*considered_vertex));
&* ничего полезного в этом случае не делает.

2021-12-06 07:57 UTC, Dovgalyuk commented on SOLUTION/lab4.cpp
> +void SearchInDepth(int vertex, directed_graph* graph, int* time, bool** considered_vertex) //Search in depth with time
Последний массив можно передавать обычным указателем, указатель на указатель не нужен.

2021-12-07 20:23 UTC, Lostmindd commented on LibraryCPP/directed_graph.h
> +#include "../LibraryCPPTemplate/array.h" //else it uses the wrong array.h
подключил array.h из LibraryCPPTemplate в общую библиотеку, но #include всё равно берет не тот array.h (хоть и видит нужный  array.h).  + Если #include "array.h" будет подключать шаблонный array.h, то перестанет корректно работать array.cpp, в котором тоже прописано #include "array.h", но которому нужен обычный(не шаблонный) array.h .

2021-12-07 20:27 UTC, Lostmindd commented on LibraryCPP/directed_graph.h
> +	int vertexes_amount;
В таком случае не работает функция directed_graph::iterator* new_iterator (из directed_graph.h), т.к. она не знает о вложенной структуре iterator.

2021-12-08 06:09 UTC, Dovgalyuk commented on LibraryCPP/directed_graph.h
> +#include "../LibraryCPPTemplate/array.h" //else it uses the wrong array.h
Библиотеку трогать не нужно. Нужно настроить пути только в конфиге своего проекта.

2021-12-08 06:10 UTC, Dovgalyuk commented on LibraryCPP/directed_graph.h
> +#include "../LibraryCPPTemplate/array.h" //else it uses the wrong array.h
Понятно, тут смешаны библиотеки. Тогда пусть остаётся как есть.

2021-12-08 06:12 UTC, Dovgalyuk commented on LibraryCPP/directed_graph.h
> +	int vertexes_amount;
Можно сделать просто struct graph_iterator и объявить для него нужные функции. Не стоит смешивать функциональный и объектно-ориентированный стили в одной библиотеке.

2021-12-09 06:24 UTC, Dovgalyuk requested changes

2021-12-09 06:24 UTC, Dovgalyuk commented on LibraryCPP/directed_graph.h
> +#include "../LibraryCPPTemplate/array.h" //else it uses the wrong array.h
Полезный побочный эффект от сокрытия реализации - этот заголовочный файл больше не нужен.

2021-12-09 06:24 UTC, Dovgalyuk commented on LibraryCPP/directed_graph.cpp
> +	int GivenVertex = -1;
Это поле больше не используется.

2021-12-09 06:24 UTC, Dovgalyuk commented on SOLUTION/lab4.cpp
> +	delete iter;
Должна быть функция удаления, так как структура здесь не определена и теорерически у нее может быть какой-то деструктор.

2021-12-10 12:47 UTC, Dovgalyuk commented
1. Разработать интерфейс (набор функций) для ассоциативного массива, который хранит пары (ключ)строка -> (значение)строка. Поддерживаемые операции: добавить пару ключ-значение, найти значение по ключу, удалить значение по ключу.
    2. Реализовать ассоциативный массив на основе хэш-таблицы с открытой адресацией. Таблица должна поддерживать расширение при большой доле заполненных ячеек.
    3. Создать тест для проверки работы контейнера. Программа должна включать в себя нагрузочное тестирование для исключения ошибок, приводящих к сложности работы O(N2) при поиске, удалении или добавлении.
    4. Написать генератор входных данных различного объема для этого контейнера. Сравнить скорость выполнения операции добавления в контейнер содержимого файла для хэш-таблицы и для std::unordered_map при различных объемах данных.

2021-12-10 12:47 UTC, closed without merging