Храмов Арсений - labbb4
Dovgalyuk/Algorithms pull request #311
Opened 2021-12-02 21:44 UTC by Programmesto

2021-12-03 07:09 UTC, Dovgalyuk requested changes

2021-12-03 07:09 UTC, Dovgalyuk commented on LibraryCPPTemplate/d_graph.h
> +        if (vertices.size() == maxVerticesNumber) {
Граф должен уметь расширяться бесконечно.

2021-12-03 07:09 UTC, Dovgalyuk commented on Tasks/Task4.cpp
> +        used = {0,0,0,0,0};
А если в графе больше вершин?

2021-12-03 07:09 UTC, Dovgalyuk commented on Tasks/Task4.cpp
> +    bool thereIsNotUsedVertices() {
Можно обойтись без этой функции, если проверять, что vertexWithMinLabel возвращает корректный номер.

2021-12-06 22:36 UTC, Programmesto commented on LibraryCPPTemplate/d_graph.h
> +        }
Я использую стандартный std::vector, разве его деструктора будет недостаточно?

2021-12-07 05:39 UTC, Dovgalyuk commented on LibraryCPPTemplate/d_graph.h
> +        }
Достаточно.

2021-12-07 05:46 UTC, Dovgalyuk commented
1. Разработать интерфейс (набор функций) для контейнера для хранения множества значений строк с возможностью быстрого поиска. Поддерживаемые операции: добавить значение, найти значение, удалить значение.
    2. Реализовать контейнер на основе АВЛ-дерева.
    3. Создать тест для проверки работы контейнера. Программа должна включать в себя нагрузочное тестирование для исключения ошибок, приводящих к сложности работы O(N^2) при поиске, удалении или добавлении.
    4. Реализовать функцию проверки баланса АВЛ-дерева и в тестовом режиме вызывать ее после каждого добавления/удаления.
    5. Написать генератор входных данных различного объема для этого контейнера. Сравнить скорость выполнения операции добавления в контейнер содержимого файла для АВЛ-дерева и для std::set при различных объемах данных.

2021-12-07 05:46 UTC, closed without merging