Laba 1
Dovgalyuk/Algorithms pull request #313
Opened 2021-12-05 15:31 UTC by Varlenn

2021-12-06 06:42 UTC, Dovgalyuk commented
Проект должен успешно компилироваться (см. вкладку checks).

2021-12-07 05:27 UTC, Dovgalyuk requested changes

2021-12-07 05:27 UTC, Dovgalyuk commented on lab1/arr.cpp
> +}
Что будет при таком содержимом массива:
40 10 10

2021-12-07 17:32 UTC, Varlenn commented on lab1/arr.cpp
> +}
40, сейчас исправлю

2021-12-08 06:06 UTC, Dovgalyuk commented
1. Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
    2. Решить задачу, используя реализованный стек.
Дано корректное выражение в обратной польской записи. Используя стек, написать калькулятор, считающий значение этого выражения.

Вход
1
2
+
3
*
Выход
9

Вход
2
10
9
-
+
Выход
3

2021-12-08 06:06 UTC, closed without merging