lab3 finished
Dovgalyuk/Algorithms pull request #315
Opened 2021-12-05 17:58 UTC by ThisIsBacya

2021-12-06 06:48 UTC, Dovgalyuk requested changes

2021-12-06 06:48 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +    List() : firstItem(nullptr), lastItem(nullptr)
В кольцевом списке с фиктивным элементом всегда должен быть минимум один элемент (в котором нет полезных данных).
Указатели на первый и последний элемент нужно получать из него.

2021-12-06 06:48 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +    int size;
В списках не принято хранить размер, потому что теоретически мы можем работать с указателями на элементы не обращаясь к самому списку. Из-за этого размер может стать некорректным.

2021-12-06 06:48 UTC, Dovgalyuk commented on lab3/testQueue.cpp
> +                std::getline(in, str[i]);
Строки целиком читать не нужно, надо обрабатывать файл посимвольно.

2021-12-06 15:11 UTC, ThisIsBacya commented on LibraryCPPTemplate/list.h
> +    List() : firstItem(nullptr), lastItem(nullptr)
Это как?

2021-12-07 05:21 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +    List() : firstItem(nullptr), lastItem(nullptr)
https://studfile.net/preview/915308/page:18/

2021-12-09 06:05 UTC, Dovgalyuk requested changes

2021-12-09 06:05 UTC, Dovgalyuk commented on lab3/testQueue.cpp
> +    std::vector<char> stroka;
От этого массива надо избавиться.

2021-12-09 06:05 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +    Item* elem = new Item(0);
Достаточно иметь только этот указатель, а остальные находить на основе него.

2021-12-09 15:04 UTC, ThisIsBacya commented on lab3/testQueue.cpp
> +    std::vector<char> stroka;
Исправил библиотеки, но не понимаю, почему от вектора надо избавиться.

2021-12-10 12:31 UTC, Dovgalyuk requested changes

2021-12-10 12:31 UTC, Dovgalyuk commented on lab3/testQueue.cpp
> +    std::vector<char> stroka;
Читать из файла по одному символу.

2021-12-10 12:31 UTC, Dovgalyuk commented on lab3/testQueue.cpp
> +    for (int i = 0; i < 4; ++i) {
Символов может быть сколько угодно, а не 4.

2021-12-13 17:05 UTC, ThisIsBacya commented on lab3/testQueue.cpp
> +    for (int i = 0; i < 4; ++i) {
Как это можно сделать?

2021-12-14 06:27 UTC, Dovgalyuk commented on lab3/testQueue.cpp
> +    for (int i = 0; i < 4; ++i) {
Читать из файла по символу через in.get(), например.

2021-12-14 17:28 UTC, ThisIsBacya commented on lab3/testQueue.cpp
> +    for (int i = 0; i < 4; ++i) {
С первым фором разобрался, а второй почему-то он не хочет считывать до конца файла.
Что можно сделать?

2021-12-15 07:07 UTC, Dovgalyuk commented on lab3/testQueue.cpp
> +    for (int i = 0; i < 4; ++i) {
Можно использовать либо конструкцию while (in) { ... }, либо проверять на конец файла через in.eof()

2021-12-15 15:42 UTC, ThisIsBacya commented on lab3/testQueue.cpp
> +    for (int i = 0; i < 4; ++i) {
![изображение](https://user-images.githubusercontent.com/58570209/146217494-facb9589-4af6-47ab-b864-8115509caaec.png)

2021-12-15 15:44 UTC, ThisIsBacya commented on lab3/testQueue.cpp
> +    for (int i = 0; i < 4; ++i) {
Пробовал. Он откуда-то берет в конце еще одну букву, хотя в текстовом файле её, очевидно, нет.
![изображение](https://user-images.githubusercontent.com/58570209/146217609-6496733d-dab8-4a77-ad87-3249a7c3babf.png)
![изображение](https://user-images.githubusercontent.com/58570209/146217648-ad562267-27d7-41ec-a1c5-4fedeac6ccf8.png)

2021-12-16 05:39 UTC, Dovgalyuk commented on lab3/testQueue.cpp
> +    for (int i = 0; i < 4; ++i) {
Это из-за неудачно завершившегося ввода, просто возвращается последний символ. В этот момент можно и проверить флаг eof.

2021-12-17 11:27 UTC, Dovgalyuk commented on lab3/testQueue.cpp
> +        stroka.push_back(str);
Ну вот теперь осталось выкинуть переменную stroka и читать вторую часть ввода прямо в следующем цикле.

2021-12-21 07:56 UTC, Dovgalyuk commented on lab3/testQueue.cpp
> +        stroka.push_back(str);
Переписать программу, чтобы обойтись без переменной stroka.
Использовать посимвольное чтение непосредственно в следующем цикле.

2021-12-22 17:43 UTC, ThisIsBacya commented on lab3/testQueue.cpp
> +        stroka.push_back(str);
Это моя основная переменная, которая используется почти везде. Как мне избавиться от неё можно?

2021-12-23 05:45 UTC, Dovgalyuk commented on lab3/testQueue.cpp
> +        stroka.push_back(str);
Читать посимвольно в переменную типа char. Сразу же её использовать. В хранении всей строки нет необходимости.

2021-12-28 05:57 UTC, Dovgalyuk requested changes

2021-12-28 05:57 UTC, Dovgalyuk commented on lab3/testQueue.cpp
> +    }
Пример входных данных:
BCDA
A

2022-01-10 05:52 UTC, Dovgalyuk commented
Принято.

2022-01-10 05:52 UTC, closed without merging