Четвёртая лаба от Курилова Романа 0091
Dovgalyuk/Algorithms pull request #319
Opened 2021-12-07 09:37 UTC by zyzic1001

2021-12-08 05:54 UTC, Dovgalyuk requested changes

2021-12-08 05:54 UTC, Dovgalyuk commented on HelpMeGod/laba4/NyPognali.cpp
> +    int** massiveVershin = new int* [vershiniKol]; // 0)����� ��������; 1)���� �� ����; 2)��������� ��� ���
Вся информация о вершинах должна быть в самом графе.

2021-12-08 05:54 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +        List<Rebro*> neighbors;
Можно хранить просто Rebro, а не указатель на него. Тогда не придётся вручную его удалять. Сейчас из-за этого есть утечки памяти, так как рёбра не удаляются при удалении вершины из графа.

2021-12-08 05:54 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +        }
Цикл избыточно медленный из-за перебора рёбер.
Можно удалять просто всё последовательно. Если сначала удалить все рёбра, а потом все вершины, то даже некорректных указателей не будет храниться ни в какой момент.

2021-12-08 12:40 UTC, zyzic1001 commented on LibraryCPPTemplate/graph.h
> +        }
Теперь, вначале удаляются рёбра, потом вергины

2021-12-08 12:41 UTC, zyzic1001 commented on LibraryCPPTemplate/graph.h
> +        List<Rebro*> neighbors;
Раз в ~DirectedGraph у меня теперь вершины удаляются, я решил оставить их указателями

2021-12-08 12:43 UTC, zyzic1001 commented on HelpMeGod/laba4/NyPognali.cpp
> +    int** massiveVershin = new int* [vershiniKol]; // 0)����� ��������; 1)���� �� ����; 2)��������� ��� ���
Исправил. "Статус обработки" вершины я решил хранить в самих вершинах.

2021-12-09 05:57 UTC, Dovgalyuk requested changes

2021-12-09 05:57 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +                if (containsRebroBetweenVershina(getVershina(j), getVershina(i))) {
Не надо никаких проверок, надо просто удалять все рёбра подряд.

2021-12-09 05:57 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +            fromVershina->neighbors.erase(item);
Так объект "ребро" по-прежнему не удаляется.

2021-12-09 05:57 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +        List<Rebro*> neighbors;
Стоит внимательно всё проверить, потому что не всегда память очищается из-за этого.

2021-12-09 05:57 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +        VershinaData status;
Это же шаблон, не нужно делать дополнительное поле. Нужно параметром шаблона сделать структуру из двух полей.

2021-12-09 05:57 UTC, Dovgalyuk commented on HelpMeGod/laba4/NyPognali.cpp
> +    for (int i = 0; i < vershiniKol; i++) {
Вместо этого должен использоваться итератор по соседям.

2021-12-10 08:33 UTC, zyzic1001 commented on HelpMeGod/laba4/NyPognali.cpp
> +    for (int i = 0; i < vershiniKol; i++) {
Сделал.

2021-12-10 08:34 UTC, zyzic1001 commented on LibraryCPPTemplate/graph.h
> +                if (containsRebroBetweenVershina(getVershina(j), getVershina(i))) {
Исправил.

2021-12-10 08:35 UTC, zyzic1001 commented on LibraryCPPTemplate/graph.h
> +            fromVershina->neighbors.erase(item);
Вроде бы исправил. А то, если честно, не знаю как это проверить.

2021-12-10 08:37 UTC, zyzic1001 commented on LibraryCPPTemplate/graph.h
> +        VershinaData status;
Не совсем понял ваше объяснение, поэтому сделал назначение типов для data и status раздельным.

2021-12-10 13:02 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +        VershinaData status;
В качестве параметра шаблона VershinaData нужно передать собственный тип-структуру из двух полей.

2021-12-10 13:06 UTC, Dovgalyuk requested changes

2021-12-10 13:06 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +        }
А если всего пара рёбер? Проще обойти только списки.

2021-12-11 08:12 UTC, zyzic1001 commented on LibraryCPPTemplate/graph.h
> +        }
Вроде оптимизировал.

2021-12-13 07:09 UTC, Dovgalyuk requested changes

2021-12-13 07:09 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +template <typename VershinaData, typename VershinaStatus, typename RebroData> class DirectedGraph {
Второй параметр шаблона надо убрать.

2021-12-13 07:09 UTC, Dovgalyuk commented on HelpMeGod/laba4/NyPognali.cpp
> +    auto* graphTemp = new DirectedGraph<int, int, int>(vershiniKol);
А вместо int надо использовать что-то вроде Z, где Z это struct Z { int data; int status; };.

2021-12-13 08:04 UTC, zyzic1001 commented on LibraryCPPTemplate/graph.h
> +                removeRebro(*iteratorVershini, (*iteratorRebra)->to);
Исправил.

2021-12-13 08:04 UTC, zyzic1001 commented on LibraryCPPTemplate/graph.h
> +            vershini.erase(item);
Исправил.

2021-12-13 08:04 UTC, zyzic1001 commented on LibraryCPPTemplate/graph.h
> +template <typename VershinaData, typename VershinaStatus, typename RebroData> class DirectedGraph {
Сделал.

2021-12-13 08:05 UTC, zyzic1001 commented on HelpMeGod/laba4/NyPognali.cpp
> +    auto* graphTemp = new DirectedGraph<int, int, int>(vershiniKol);
Сделал.

2021-12-14 05:56 UTC, Dovgalyuk requested changes

2021-12-14 05:56 UTC, Dovgalyuk commented on HelpMeGod/laba4/NyPognali.cpp
> +int toTheNextVershina(int vershiniKol, int startVershina, int* workingVershina, bool* ending, DirectedGraph<Z, int>* graph) {
Только сейчас заметил, что тут выбирается не та вершина, что нужно.
Должна быть не первая попавшаяся, а вершина с кратчайшим расстоянием.

2021-12-14 05:56 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +            vershini.erase(item);
Вершина удаляется, а рёбра, которые хранятся в ней?

2021-12-14 05:56 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +            }
Теперь лишних циклов нет.
Но всё же без итератора обходить список было бы проще.

2021-12-14 06:49 UTC, zyzic1001 commented on HelpMeGod/laba4/NyPognali.cpp
> +int toTheNextVershina(int vershiniKol, int startVershina, int* workingVershina, bool* ending, DirectedGraph<Z, int>* graph) {
Исправил.

2021-12-14 06:49 UTC, zyzic1001 commented on LibraryCPPTemplate/graph.h
> +            vershini.erase(item);
Исправил.

2021-12-14 07:27 UTC, zyzic1001 commented on LibraryCPPTemplate/graph.h
> +            }
Сделал.

2021-12-15 07:01 UTC, Dovgalyuk commented
1. Разработать интерфейс (набор функций) для контейнера для хранения множества значений строк с возможностью быстрого поиска. Поддерживаемые операции: добавить значение, найти значение, удалить значение.
    2. Реализовать контейнер на основе хэш-таблицы с открытой адресацией. Таблица должна поддерживать расширение при большой доле заполненных ячеек.
    3. Создать тест для проверки работы контейнера. Программа должна включать в себя нагрузочное тестирование для исключения ошибок, приводящих к сложности работы O(N2) при поиске, удалении или добавлении.
    4. Написать генератор входных данных различного объема для этого контейнера. Сравнить скорость выполнения операции добавления в контейнер содержимого файла для хэш-таблицы и для std::unordered_set при различных объемах данных.

2021-12-15 07:01 UTC, closed without merging