Лабораторная работа №4 Радаева Кирилла
Dovgalyuk/Algorithms pull request #320
Opened 2021-12-08 14:27 UTC by Golod-ru

2021-12-09 06:01 UTC, Dovgalyuk requested changes

2021-12-09 06:01 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +#pragma once
Этот класс нужно переписать самостоятельно.

2021-12-15 07:05 UTC, Dovgalyuk requested changes

2021-12-15 07:05 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +    typedef typename List<Rebro*>::Item RItem;
Новый план:
Убрать указатели во всех списках, пусть в них хранятся сами структуры.

2021-12-29 15:56 UTC, Golod-ru commented on LibraryCPPTemplate/graph.h
> +    typedef typename List<Rebro*>::Item RItem;
Здравствуйте. Можете как то по другому объяснить что вы от меня требуете? У меня вообще ничего не получается :\

2022-01-10 06:23 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +    typedef typename List<Rebro*>::Item RItem;
Чтобы было вот так:
    typedef typename List<Rebro>::Item RItem;

2022-01-14 14:08 UTC, Golod-ru commented on LibraryCPPTemplate/graph.h
> +    typedef typename List<Rebro*>::Item RItem;
А можно узнать когда вы будете в институте? У меня опять не особо получается и хотелось бы чтобы вы посмотрели на работу в живую.

2022-01-17 05:43 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +    typedef typename List<Rebro*>::Item RItem;
Теперь только на экзамене. Лучше написать все вопросы сюда или в почту.

2022-01-24 05:37 UTC, closed without merging