lab2 Аниськин Артём 0092
Dovgalyuk/Algorithms pull request #321
Opened 2021-12-10 14:41 UTC by onisken

2021-12-13 06:06 UTC, Dovgalyuk requested changes

2021-12-13 06:06 UTC, Dovgalyuk commented on results/lab2.cpp
> +    Stack<int> stackMinus;
Достаточно одного стека. Так как частицы отсортированы по координате, можно обрабатывать их в порядке появления на входе.

2021-12-13 16:44 UTC, onisken commented on results/lab2.cpp
> +    Stack<int> stackMinus;
Исправлено

2021-12-13 16:45 UTC, onisken commented
@Dovgalyuk переделал работу алгоритма

2021-12-14 06:25 UTC, Dovgalyuk commented
1. Реализовать в проекте Library двусвязный список (модуль list) и очередь на основе этого списка (модуль queue).
    2. Решить задачу, используя реализованную очередь.
Задан неориентированный граф. Написать программу для определения кратчайшего пути от одной вершины для другой. В первой строке входного файла записано количество вершин, номер стартовой вершины и номер финишной. В последующих строках идут описания ребер, заданные номерами вершин, которые они соединяют. В выходной файл выводится последовательность вершин в кратчайшем пути. Если решения не существует – выводится IMPOSSIBLE. Программа должна использовать поиск в ширину на основе очереди.

Вход
```
4 1 2
1 3
1 4
3 2
4 3
```
Выход
```
1 3 2
```

2021-12-14 06:25 UTC, closed without merging