Лабораторная работа номер 2 (Зарманбетов Эмиль 0092)
Dovgalyuk/Algorithms pull request #322
Opened 2021-12-10 14:56 UTC by EkoRiri

2021-12-13 06:13 UTC, Dovgalyuk requested changes

2021-12-13 06:13 UTC, Dovgalyuk commented on Result/solvetwo.cpp
> +
Стек у процессора обычно один.
Операнд команды PUSH - значение, которое в этот стек надо поместить (число или регистр).
POP извлекает верхнее значение из стека в заданный регистр.

2021-12-13 15:30 UTC, EkoRiri commented on Result/solvetwo.cpp
> +
Исправлено

2021-12-13 15:31 UTC, EkoRiri commented
@Dovgalyuk  исправил

2021-12-14 06:22 UTC, Dovgalyuk commented
1. Реализовать в проекте Library очередь (модуль queue) с использованием двух стеков (модуль stack).
    2. Решить задачу, используя реализованную очередь.
Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной – «#» или пустым пространством – «.». Стартовая позиция обозначается как X, финишная как Y. Написать программу, находящую минимальный путь от стартовой до финишной клетки, если это возможно. За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди. Если решения нет, вывести IMPOSSIBLE.

Вход
```
######
#...X#
#.####
#...Y#
######
```
Выход
```
######
#xxxX#
#x####
#xxxY#
######
```

Вход
```
######
#...X#
######
#...Y#
######
```
Выход
```
IMPOSSIBLE
```

2021-12-14 06:22 UTC, closed without merging