lab 2 Иванов Николай
Dovgalyuk/Algorithms pull request #326
Opened 2021-12-15 10:26 UTC by Nikolay0092

1. Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
2. Решить задачу, используя реализованный стек.
Дано выражение в обратной польской записи. Используя стек, написать программу, которая проверяет выражение на наличие ошибок. Ошибкой считается деление на 0 (ZERO), выполнение операции, когда в стеке меньше двух элементов (UNDERFLOW), наличие больше одного элемента в стеке после завершения работы программы (OVERFLOW).

2021-12-16 05:27 UTC, Dovgalyuk requested changes

2021-12-16 05:27 UTC, Dovgalyuk commented on Second/main.cpp
> +    number.push(1);
Нужно обрабатывать данные из входного файла или введенные с клавиатуры.

2021-12-16 20:03 UTC, Nikolay0092 commented on Second/main.cpp
> +    number.push(1);
Исправил данную ошибку.

2021-12-17 10:58 UTC, Dovgalyuk commented
1. Реализовать в проекте Library массив переменного размера (модуль vector) и очередь на основе этого массива (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
    2. Решить задачу, используя реализованную очередь.
Во входном файле записано количество вершин и матрица смежности ориентированного графа. Вывести в выходной файл список расстояний от первой вершины до всех остальных. Для вычисления расстояний использовать поиск в ширину.

Вход
```
4
0 1 0 0
0 0 1 1
1 0 0 1
0 1 0 0
```
Выход
```
0
1
2
2
```

2021-12-17 10:58 UTC, closed without merging