lab3 Аниськин Артём 0092
Dovgalyuk/Algorithms pull request #327
Opened 2021-12-15 15:39 UTC by onisken

2021-12-16 05:37 UTC, Dovgalyuk requested changes

2021-12-16 05:37 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +    size_t size;
В списке не нужен size. Иногда в списках доступно присоединение произвольной последовательности, из-за чего size посчитать невозможно.

2021-12-16 05:37 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +        this->erase(item);
Удаление должно происходить с другого конца очереди, а не там, где только что было добавление.

2021-12-16 05:37 UTC, Dovgalyuk commented on results/lab3.cpp
> +    for (int i = 0; i < vertexQueue.size(); i++) {
Тут должен быть цикл "пока очередь не опустеет"

2021-12-16 05:37 UTC, Dovgalyuk commented on results/lab3.cpp
> +            newQueue.insert(vertexes[j]);
Добавлять вершины надо в ту же очередь, откуда они извлекаются. Тогда рекурсия не понадобится.

2021-12-16 07:46 UTC, onisken commented on LibraryCPPTemplate/list.h
> +    size_t size;
Исправлено

2021-12-16 07:52 UTC, onisken commented on LibraryCPPTemplate/queue.h
> +        this->erase(item);
Исправлено

2021-12-16 07:53 UTC, onisken commented on results/lab3.cpp
> +    for (int i = 0; i < vertexQueue.size(); i++) {
Исправлено

2021-12-16 07:53 UTC, onisken commented on results/lab3.cpp
> +            newQueue.insert(vertexes[j]);
Исправлено

2021-12-16 08:03 UTC, onisken commented
@Dovgalyuk исправил

2021-12-17 11:19 UTC, Dovgalyuk requested changes

2021-12-17 11:19 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +        this->erase(last);
Последний добавленный элемент будет удалён первым.

2021-12-17 11:19 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +        return this->getSize() == 0;
Нехорошо запрашивать размер у списка, потому что при этом придётся его весь обойти.

2021-12-17 11:19 UTC, Dovgalyuk commented on results/lab3.cpp
> +typedef Queue<Vertex> VertexQueue;
нет смысла хранить вес в очереди

2021-12-20 06:28 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +        this->erase(last);
Нет, в этом месте всё же верно. Остальные надо исправить.

2021-12-20 07:38 UTC, onisken commented on LibraryCPPTemplate/queue.h
> +        return this->getSize() == 0;
Исправлено

2021-12-20 07:44 UTC, onisken commented on results/lab3.cpp
> +typedef Queue<Vertex> VertexQueue;
Исправлено

2021-12-20 07:44 UTC, onisken commented
@Dovgalyuk  исправил все замечания

2021-12-21 07:50 UTC, Dovgalyuk requested changes

2021-12-21 07:50 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +    ~List() { }
Список должен очищаться в деструкторе.

2021-12-21 07:50 UTC, Dovgalyuk commented on results/lab3.cpp
> +void findPath(int size, int finishID, std::vector<bool> &links, IDQueue vertexQueue, std::vector<Vertex> &vertexes) {
У IDQueue нет корректного конструктора копирования, поэтому надо запретить конструктор копирования и передавать очередь по ссылке. Либо реализовать конструктор копирования.

2021-12-21 09:39 UTC, onisken commented on LibraryCPPTemplate/list.h
> +    ~List() { }
Исправлено

2021-12-21 09:39 UTC, onisken commented on results/lab3.cpp
> +void findPath(int size, int finishID, std::vector<bool> &links, IDQueue vertexQueue, std::vector<Vertex> &vertexes) {
Исправлено

2021-12-21 09:39 UTC, onisken commented
@Dovgalyuk исправлены замечания

2021-12-22 06:25 UTC, Dovgalyuk commented
1. Разработать программный интерфейс модуля (заголовки функций) для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
    2. Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
    3. Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List той же библиотеки.
    4. Разработать и добавить в проект программу, тестирующую работу библиотеки для графа.
    5. Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать для него все длины кратчайших путей алгоритмом Флойда.

2021-12-22 06:25 UTC, closed without merging