Лабораторная номер три (Зарманбетов Эмиль 0092)
Dovgalyuk/Algorithms pull request #328
Opened 2021-12-15 18:02 UTC by EkoRiri

2021-12-16 05:49 UTC, Dovgalyuk requested changes

2021-12-16 05:49 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +        stackData = tmpData;
Почти правильно. Только второй стек стоит держать постоянно.
В один добавлять, из другого извлекать. Если там кончились данные, то перенести из первого.

2021-12-18 12:25 UTC, EkoRiri commented on LibraryCPPTemplate/queue.h
> +        stackData = tmpData;
Переделано

2021-12-18 12:26 UTC, EkoRiri commented
@Dovgalyuk изменил работу алгоритма

2021-12-18 12:32 UTC, EkoRiri commented
@Dovgalyuk кое-что исправил

2021-12-20 05:57 UTC, Dovgalyuk requested changes

2021-12-20 05:57 UTC, Dovgalyuk commented on Result/solvethree.cpp
> +        newPosition.weight = checkPosition.weight + 1;
Вес всё равно хранится в карте, не надо таскать его ещё и через очередь.

2021-12-21 11:28 UTC, EkoRiri commented on Result/solvethree.cpp
> +        newPosition.weight = checkPosition.weight + 1;
Исправил

2021-12-21 11:29 UTC, EkoRiri commented
@Dovgalyuk исправил

2021-12-22 06:31 UTC, Dovgalyuk commented
1. Разработать программный интерфейс модуля (заголовки функций) для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
    2. Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
    3. Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List той же библиотеки.
    4. Разработать и добавить в проект программу, тестирующую работу библиотеки для графа.
    5. Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать для него минимальное покрывающее дерево алгоритмом Крускала.

2021-12-22 06:31 UTC, closed without merging