Лабораторная работа №2 Каримова Амина
Dovgalyuk/Algorithms pull request #329
Opened 2021-12-16 21:14 UTC by S-E-S-U

2021-12-17 11:46 UTC, Dovgalyuk requested changes

2021-12-17 11:46 UTC, Dovgalyuk commented on lab_solution/lab2.cpp
> +#include "../LibraryCPP/stack.h"
Нужно прописать этот путь в cmakelists, чтобы тут писать просто "stack.h"

2021-12-17 11:46 UTC, Dovgalyuk commented on lab_solution/lab2.cpp
> +                input.get(tag);
А зачем здесь читать файл, если он потом и так прочитается в заголовке цикла.

2021-12-17 15:51 UTC, S-E-S-U commented on lab_solution/lab2.cpp
> +                input.get(tag);
Исправила.

2021-12-20 05:45 UTC, Dovgalyuk commented on lab_solution/lab2.cpp
> +#include "../LibraryCPP/stack.h"
Это не исправлено.

2021-12-20 09:58 UTC, S-E-S-U commented on lab_solution/lab2.cpp
> +#include "../LibraryCPP/stack.h"
исправила...

2021-12-21 07:55 UTC, Dovgalyuk commented
1. Реализовать в проекте Library массив переменного размера (модуль vector) и очередь на основе этого массива (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
    2. Решить задачу, используя реализованную очередь.
Задано начальное вещество и список химических реакций, в которых оно превращается в другое вещество.  Написать программу, использующую поиск в ширину, и выводящую список веществ, которые можно получить из исходного

В примере из вещества A можно получить вещества B и C.
Вход
```
A
A->B
B->C
D->E
```
Выход
```
B
C
```

2021-12-21 07:55 UTC, closed without merging