0092 Шустров Василий lab5
Dovgalyuk/Algorithms pull request #332
Opened 2021-12-19 12:30 UTC by Lostmindd

Тест медленный получается, но я не знаю как ещё можно оптимизировать программу.

2021-12-20 07:01 UTC, Dovgalyuk requested changes

2021-12-20 07:01 UTC, Dovgalyuk commented on LibraryCPP/associative_array.cpp
> +void delete_pair(std::string key, associative_array* associative_arr)
Возможно медленно работает из-за этой функции. При удалении не надо всю таблицу пересчитывать. Но чтобы цепочки не разрывались, можно помечать ячейки как "свободна, но была занята раньше".

2021-12-20 16:15 UTC, Lostmindd commented on LibraryCPP/associative_array.cpp
> +		if (j > 12) p = 1;
Переделал немного. что касается хэш-функции:
1) Каждый 12 шаг сбрасываю значение p потому, что иначе p становиться большим и уходит в отрицательное значение. (и получается отриц. индекс массива).
2) Попробовал предложенную функцию и она точно также уходит в минус, вплоть до того, что нужно уменьшать порог обнуления p. По времени в нагрузочном тесте она примерно такая же, поэтому я решил её не вставлять
3) если же не возводить p каждый шаг в новую степень, то перестаёт учитываться порядок символов и получается много коллизий.

2021-12-20 17:27 UTC, Lostmindd commented on LibraryCPP/associative_array.cpp
> +void delete_pair(std::string key, associative_array* associative_arr)
Изменил -> тест замедлился с 2,40 до 3,40 sec.(+ в теории пострадала скорость поиска). 
Проверил по отдельности и стало понятно что основную нагрузку даёт добавление пары. 
Но не знаю как ещё можно её улучшить . (Пробовал вместо своей хэш-функции  использовать стандартную std::hash<std::string>, и скорость возрастала примерно на 30%).

2021-12-21 08:35 UTC, Dovgalyuk commented on LibraryCPP/associative_array.cpp
> +		if (j > 12) p = 1;
Как она может уходить в минус, если мы всегда берём остаток? Разве что символы какие-то из диапазона 128-255, а char у нас знаковый. Тогда надо привести код символа к unsigned char.

2021-12-21 08:37 UTC, Dovgalyuk commented on LibraryCPP/associative_array.cpp
> +void delete_pair(std::string key, associative_array* associative_arr)
При добавлении значит либо мы упускаем какую-то мелочь, либо возникает очень сильная кластеризация из-за того, что ячейки заполняются последовательно. Стоит попробовать другой порядок поиска новой свободной ячейки.

2021-12-21 08:38 UTC, Dovgalyuk commented on LibraryCPP/associative_array.cpp
> +				ArrayElement* arr_el = new ArrayElement;
Кстати, зачем создавать новый элемент, если можно перенести старый.

2021-12-21 12:13 UTC, Lostmindd commented on LibraryCPP/associative_array.cpp
> +		if (j > 12) p = 1;
Помогло исправление на unsigned long long. Просто знаковые типы при переполнении (а в нашем случае он рано или поздно переполняется, потому что каждый шаг мы возводим число в степень) могут непредвиденно уходить в минус. А функция как раз и уходила в минус из-за этой особенности (ещё при перемножении, ДО взятия остатка).

2021-12-21 21:24 UTC, Lostmindd commented on LibraryCPP/associative_array.cpp
> +void delete_pair(std::string key, associative_array* associative_arr)
переделал на двойное хеширование

2021-12-22 06:42 UTC, Dovgalyuk commented on LibraryCPP/associative_array.cpp
> +		if (j > 12) p = 1;
Это значит, что размер таблицы доходил до примерно 2*10^9/31 = 6*10^7. Как-то избыточно много для миллиона элементов. Стоит это проверить.

2021-12-22 06:44 UTC, Dovgalyuk commented on LibraryCPP/associative_array.cpp
> +		if (j > 12) p = 1;
А, так ещё и старая формула осталась.
Надо просто переделать на ту, что я предлагал.

2021-12-22 06:45 UTC, Dovgalyuk commented on LibraryCPP/associative_array.cpp
> +void delete_pair(std::string key, associative_array* associative_arr)
А время теста-то чего не уменьшилось?

2021-12-22 06:48 UTC, Dovgalyuk commented
Ну и результаты измерений производительности тоже стоит закоммитить.

2021-12-22 08:09 UTC, Lostmindd commented on LibraryCPP/associative_array.cpp
> +void delete_pair(std::string key, associative_array* associative_arr)
уменьшил ограничение времени для теста (если речь шла об этом)

2021-12-22 13:03 UTC, Lostmindd commented on LibraryCPP/associative_array.cpp
> +		if (j > 12) p = 1;
1) Переделал.
2) при миллионе элементов реальный размер таблицы (capacity) = 3 014 656.

2021-12-25 19:12 UTC, Lostmindd commented
Что-то ещё надо делать?

2021-12-27 05:48 UTC, Dovgalyuk requested changes

2021-12-27 05:49 UTC, Dovgalyuk commented
> Что-то ещё надо делать?

Комментарий с прошлого раза не отправился. Надо немного поменять измерения.

2021-12-28 06:03 UTC, Dovgalyuk requested changes

2021-12-28 06:03 UTC, Dovgalyuk commented on SOLUTION/lab5.cpp
> +		start = std::chrono::system_clock::now();
Только стоит отдельно запомнить последовательность, а потом добавлять её или в один контейнер, или в другой.
При этом измерять время всего цикла, чтобы не накапливать погрешность от сложения маленьких интервалов.

2022-01-10 06:53 UTC, Dovgalyuk commented
Принято.

2022-01-10 06:53 UTC, closed without merging