Лабораторная 4 Авдеев 0092
Dovgalyuk/Algorithms pull request #334
Opened 2021-12-19 19:41 UTC by gerundv

2021-12-20 06:35 UTC, Dovgalyuk requested changes

2021-12-20 06:35 UTC, Dovgalyuk commented on LibraryCPP/graph.h
> +
Стоит начинать функции с префикса graph_ чтобы было понятно, из какого они вообще модуля.
Ну и а автодополнением пользователю так будет проще.

2021-12-21 20:08 UTC, gerundv commented
Посмотрев похожее, мне, наверное, стоит в templates реализовать array и его использовать, структурным не понимаю как. И есть ли у вас ещё ссылки на тему графов? В репозитории ссылка только на общие факты о графах, в конце там говорилось про объяснение определенных графов, но продолжения видео я не нашёл.

2021-12-22 06:40 UTC, Dovgalyuk commented
Да, стоит добавить шаблонный array.
Ссылок про графы я больше не искал, только книги есть.

2021-12-28 13:21 UTC, gerundv commented
Чего-то я в конец запутался, чувствую что ничего не понял, как сел писать остово дерево, думаю теперь весь граф переписать уже по своему

2022-01-09 18:20 UTC, gerundv commented
Чувствую себя тупиком, потому что не могу сам разобраться и понять как написать граф. Посмотрел примеры написания матрицы смежности с контейнера Array у других ребят и мало что понял, как оно в теории работает понимаю, однако, своими силами написать у меня знаний о классах не хватает.

2022-01-13 17:08 UTC, gerundv commented
Как-то так, осталось додумать Крускала

2022-01-17 05:55 UTC, Dovgalyuk requested changes

2022-01-17 05:55 UTC, Dovgalyuk commented on laboratory/Fourth/4.cpp
> +    delete& graph,result;
и graph, и result - автоматические переменные, их не нужно отдельно удалять

2022-01-17 05:55 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +            Edges* edges;
Пусть матрица смежности хранится целиком в графе, как N*N ячеек, а не по отдельности в каждой вершине.

2022-01-21 05:03 UTC, Dovgalyuk requested changes

2022-01-21 05:03 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +    Edges* edges;
В задании сказано про контейнер Array.

2022-01-21 05:13 UTC, gerundv commented
А что конкретно не так?

2022-01-21 05:18 UTC, Dovgalyuk commented
Нужно использовать собственный контейнер, а не просто указатель на массив.

2022-01-21 06:50 UTC, gerundv commented
Вы, наверно, не заметили, но в начале Edges объявлен как массив array

2022-01-21 07:17 UTC, Dovgalyuk commented
Да, я смотрел на другой файл, который непонятно зачем присутствует в проекте.

2022-01-21 07:19 UTC, Dovgalyuk commented
Тогда пока принято, на защите будет много вопросов.

2022-01-21 07:19 UTC, closed without merging

2022-01-22 09:45 UTC, gerundv commented
У меня такая ситуация, у бабушки сегодня подтвердился тест на ковид (живу с ней), у меня будут брать тест в понедельник. Поэтому такой вопрос, будет ли третья пересдача и, если будет, то когда?

2022-01-24 05:32 UTC, Dovgalyuk commented
Не будет, но можно прийти на комиссию, которую будет проводить кафедра.

2022-01-24 05:33 UTC, gerundv commented
А могу ли я просто прийти, если я себя нормально чувствую?

2022-01-24 05:39 UTC, Dovgalyuk commented
Не стоит. Я смогу передать, что ты претендуешь на 4.

2022-01-24 05:40 UTC, gerundv commented
Понял, спасибо