lab4|Иванов Николай
Dovgalyuk/Algorithms pull request #340
Opened 2021-12-22 15:10 UTC by Nikolay0092

1. Разработать программный интерфейс модуля (заголовки функций) для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
2. Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
3. Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List той же библиотеки.
4. Разработать и добавить в проект программу, тестирующую работу библиотеки для графа.
5. Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать для него минимальное покрывающее дерево алгоритмом Прима.

2021-12-23 06:00 UTC, Dovgalyuk commented
Тест для графа надо включить.

2021-12-24 12:02 UTC, Dovgalyuk requested changes

2021-12-24 12:08 UTC, Dovgalyuk commented on Fourth/main.cpp
> +                        if (visited[i] != 0)
Хотя нет, сортировка тут лишняя. Но множество соседних с подграфом вершин поддерживать можно было бы.

2021-12-29 10:18 UTC, Nikolay0092 commented on Fourth/main.cpp
> +                        if (visited[i] != 0)
Если подключить проверку флага по j, через &&(и) программа отказывается работать, через ||(или) работает не корректно.

2021-12-29 10:35 UTC, Nikolay0092 commented on Fourth/main.cpp
> +        visited[0] = 1;
Исправлено

2022-01-10 06:21 UTC, Dovgalyuk requested changes

2022-01-10 06:21 UTC, Dovgalyuk commented on LibraryCPPTemplate/d_graph.h
> +        int label;
label не нужно выделять в виде поля. Data вполне может быть структурой с несколькими полями (weight и label, например).

2022-01-10 06:21 UTC, Dovgalyuk commented on Fourth/main.cpp
> +                            b = v = j;
b всегда совпадает с v и только запутывает код.

2022-01-10 06:21 UTC, Dovgalyuk commented on Fourth/main.cpp
> +                graph->getVertex(b)->setLabel(1);
А если метка уже была 1 у этой вершины?

2022-01-11 05:34 UTC, Dovgalyuk commented
Ещё два вопроса без ответа.

2022-01-17 05:34 UTC, Dovgalyuk requested changes

2022-01-17 05:34 UTC, Dovgalyuk commented on LibraryCPPTemplate/d_graph.h
> +        int label;
Теперь осталось вынести эту структуру и передавать её в качестве параметра шаблона.
Сам граф работает с ней просто как с Data.

2022-01-21 05:07 UTC, Dovgalyuk requested changes

2022-01-21 05:07 UTC, Dovgalyuk commented on LibraryCPPTemplate/d_graph.h
> +struct Data {
Эта структура должна быть описана не здесь, а в решении задачи. Сам граф только принимает параметр и работает с ним, не зная что внутри.

2022-01-24 05:25 UTC, Dovgalyuk commented
Принято.

2022-01-24 05:25 UTC, closed without merging