Lab3
Dovgalyuk/Algorithms pull request #342
Opened 2021-12-22 17:14 UTC by veahcen

2021-12-23 05:43 UTC, Dovgalyuk requested changes

2021-12-23 05:43 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +    size_t amount = 0;
Три поля хранить не нужно. Из любых двух третье можно вычислить.

2021-12-23 05:43 UTC, Dovgalyuk commented on laba3/text3.cpp
> +        bool was[count];
массив не инициализирован

2021-12-23 05:43 UTC, Dovgalyuk commented on laba3/text3.cpp
> +        std::cout << "error";
Вот такой пример:
```
5
0 1 0 0 0
0 0 1 1 0
1 0 0 1 0
0 1 0 0 1
0 0 0 0 0
```

2021-12-25 10:29 UTC, veahcen commented on LibraryCPPTemplate/queue.h
> +    size_t amount = 0;
Я не могу убрать ни одну из этих переменных, так как тут реализован кольцевой буфер. first и last перемещаются влево и вправо, они не зависят не от чего, поэтому их не высчитать. amount тоже не вычислить, бывают моменты, когда одно положение имеет два разных значения.

2021-12-27 05:45 UTC, Dovgalyuk requested changes

2021-12-27 05:45 UTC, Dovgalyuk commented on laba3/text3.cpp
> +        auto* queue = new Queue<std::vector<int>>;
Не надо в очереди хранить массив. Достаточно только номера вершин, которые мы будем обрабатывать.

2021-12-27 05:46 UTC, Dovgalyuk commented
Ещё проект не компилируется.

2022-01-10 05:56 UTC, Dovgalyuk commented
Сборка и тесты не могут выполниться из-за конфликтующих изменений.

2022-01-11 05:51 UTC, Dovgalyuk commented
Принято.

2022-01-11 05:51 UTC, closed without merging