Большаков Иван 0092, lab.1
Dovgalyuk/Algorithms pull request #345
Opened 2021-12-23 21:09 UTC by Bolshakov1

Исправил программу.

2021-12-24 11:48 UTC, Dovgalyuk requested changes

2021-12-24 11:48 UTC, Dovgalyuk commented on LibraryCPP/laba1.cpp
> +#include "array.cpp"
1. Нужно подключать заголовочный файл.
2. Программу с решением надо включить в сборочные конфиги.

2021-12-27 05:34 UTC, Dovgalyuk commented
Проект не собирается.

2021-12-27 11:59 UTC, Bolshakov1 commented
На данном моменте проект собирается, но все равно присутствует какая-то ошибка, не могу разобраться.

2021-12-27 15:31 UTC, Bolshakov1 commented
Исправил.

2021-12-28 05:47 UTC, Dovgalyuk commented
сборка не проходит

2021-12-28 06:17 UTC, closed without merging