Пятая лаба от Курилова Романа 0091
Dovgalyuk/Algorithms pull request #350
Opened 2021-12-28 06:53 UTC by zyzic1001

2022-01-10 06:51 UTC, Dovgalyuk requested changes

2022-01-10 06:51 UTC, Dovgalyuk commented on LibraryCPPTemplate/Tests/myContainer.cpp
> +    int size = 100;
Нужно добавлять 1000000 элементов, чтобы проверить производительность.

2022-01-10 06:51 UTC, Dovgalyuk commented on LibraryCPPTemplate/myContainer.h
> +template <typename hashData, typename Data> class container
Два параметра шаблона тут не нужны.
Только если для передачи собственной хэш-функции, а не типа hashData.

2022-01-10 06:51 UTC, Dovgalyuk commented on LibraryCPPTemplate/myContainer.h
> +    Item* firstItem = new Item("");
Нужна таблица, а не список для бьыстрой адресации.

2022-01-10 13:16 UTC, zyzic1001 commented on LibraryCPPTemplate/Tests/myContainer.cpp
> +    int size = 100;
Сделал

2022-01-10 13:16 UTC, zyzic1001 commented on LibraryCPPTemplate/myContainer.h
> +template <typename hashData, typename Data> class container
Переделал

2022-01-10 13:17 UTC, zyzic1001 commented on LibraryCPPTemplate/myContainer.h
> +    Item* firstItem = new Item("");
Ну, массив тоже в каком-то смысле таблица, так что буду считать это переделанным

2022-01-11 06:08 UTC, Dovgalyuk requested changes

2022-01-11 06:08 UTC, Dovgalyuk commented on LibraryCPPTemplate/myContainer.h
> +                    amountAndTableResize();
Тут возможна рекурсия insert->amountAndTableResize->insert из-за того, что поиск свободной ячейки не закольцован, а расширяет массив.

2022-01-11 06:08 UTC, Dovgalyuk commented on LibraryCPPTemplate/myContainer.h
> +    bool erase(string data)
Такая реализация может разорвать цепочку поиска.
Например, если из 1 2 3 удалить 2, то 3 мы дальше не сможем находить (в случае правильной реализации find).
Поэтому нужно помечать освободившиеся ячейки, чтобы через них можно было продолжать поиск.

2022-01-11 06:08 UTC, Dovgalyuk commented on LibraryCPPTemplate/myContainer.h
> +            if (table[index] != NULL) {
В противном случае надо останавливаться. Сейчас реализация поиска в среднем будет занимать O(N), что неприемлемо.

2022-01-11 15:09 UTC, zyzic1001 commented on LibraryCPPTemplate/myContainer.h
> +                    amountAndTableResize();
Исправил

2022-01-11 15:09 UTC, zyzic1001 commented on LibraryCPPTemplate/myContainer.h
> +    bool erase(string data)
Исправил

2022-01-11 15:10 UTC, zyzic1001 commented on LibraryCPPTemplate/myContainer.h
> +            if (table[index] != NULL) {
Исправил

2022-01-17 05:20 UTC, Dovgalyuk requested changes

2022-01-17 05:20 UTC, Dovgalyuk commented on LibraryCPPTemplate/myContainer.h
> +            if (table[i] != NULL) {
А если не null, но hash=0?

2022-01-17 05:20 UTC, Dovgalyuk commented on LibraryCPPTemplate/myContainer.h
> +        item->hash(hash<string>{}(data));
А где гарантии, что стандартная функция не вернет 0?
Нужно использовать свою, если уж 0 это специальное значение.

2022-01-17 10:17 UTC, zyzic1001 commented on LibraryCPPTemplate/myContainer.h
> +            if (table[i] != NULL) {
Исправил.

2022-01-17 10:18 UTC, zyzic1001 commented on LibraryCPPTemplate/myContainer.h
> +        item->hash(hash<string>{}(data));
Просто я не думал что функция hash может выдать 0 для string. Но теперь даю гарантию.

2022-01-19 05:27 UTC, Dovgalyuk requested changes

2022-01-19 05:27 UTC, Dovgalyuk commented on LibraryCPPTemplate/myContainer.h
> +                table[i] = NULL;
А память освободить?

2022-01-19 05:27 UTC, Dovgalyuk commented
Ещё нужны результаты измерения производительности.

2022-01-19 05:53 UTC, zyzic1001 commented on LibraryCPPTemplate/myContainer.h
> +                table[i] = NULL;
Исправил. Но что вы имеете в виду под результатами измерения производительности? А то у меня есть сравнение скоростей добавления элементов в мой контейнер и в std::unordered_set. Нужно что-то ещё?

2022-01-21 04:49 UTC, Dovgalyuk commented on LibraryCPPTemplate/myContainer.h
> +                table[i] = NULL;
Измерять для количества элементов от 1 до 10000000. Построить графики зависимости времени от числа элементов.

2022-01-22 09:10 UTC, zyzic1001 commented on LibraryCPPTemplate/myContainer.h
> +                table[i] = NULL;
![image](https://user-images.githubusercontent.com/78371726/150632129-6cb36126-3c43-41ee-8095-c516564873ff.png)
На графике слева время в секундах, снизу номера теста. На первом тесте у myContainer и UnorderedSet по 1-му елементу. На каждом последующем тесте количество элементов увеличивалось на 10000, вплоть до 500001 элементов. Да, это меньше, чем вы просили, но я решил пожалеть свой процессор.

2022-01-24 05:30 UTC, Dovgalyuk commented
Принято.

2022-01-24 05:30 UTC, closed without merging