Lab4: Realisation of directed graph
Dovgalyuk/Algorithms pull request #355
Opened 2022-01-05 12:01 UTC by Shara1p

Алгоритм Прима пока не сделал

2022-01-10 06:12 UTC, Dovgalyuk commented
Программа не компилируется.

2022-01-10 06:52 UTC, Shara1p commented
> 

Не могу разобраться почему, локально все проходит

2022-01-11 06:37 UTC, Dovgalyuk commented
Теперь другие ошибки.

2022-01-11 08:32 UTC, Shara1p commented
> Теперь другие ошибки.

Все исправил

2022-01-11 13:02 UTC, Shara1p commented
> Теперь другие ошибки.

Исправлено

2022-01-12 10:08 UTC, Shara1p commented
Извините, а разве алгоритм Прима это не для неориентированных графов? Разве им можно пользоваться для ориентированных?

2022-01-17 05:38 UTC, Dovgalyuk commented
Сборка не проходит.

2022-01-17 05:53 UTC, Shara1p commented
> Сборка не проходит.

Теперь все в порядке, забыл запушить 1 файл

2022-01-19 05:15 UTC, Dovgalyuk requested changes

2022-01-19 05:15 UTC, Dovgalyuk commented on LibraryCPP/graph.h
> +	Vertex* AddVertex(const int data);
должен быть способ получить одну вершину не копируя весь массив указателей на них целиком через GetVertices

2022-01-19 05:15 UTC, Dovgalyuk commented on LibraryCPP/graph.h
> +		Vertex* v = new Vertex(0, 0);
Довольно странно, что в ребре выделяется память под вершину.

2022-01-19 05:15 UTC, Dovgalyuk commented on LibraryCPP/graph.h
> +	std::unordered_map<Vertex*, std::unordered_set<Edge*>> edges;
Должны быть списки смежности, которые хранятся в собственном контейнере List.

2022-01-21 05:19 UTC, Dovgalyuk commented
Проект не собирается.

2022-01-21 08:10 UTC, Shara1p commented
> Проект не собирается.

Все исправил

2022-01-24 05:28 UTC, Dovgalyuk commented
1. Задание про граф, а тест для графа не проходит.
2. Выложено много мусора.

2022-01-24 05:28 UTC, closed without merging