lab4 Аниськин Артём 0092
Dovgalyuk/Algorithms pull request #357
Opened 2022-01-09 16:01 UTC by onisken

2022-01-10 06:10 UTC, Dovgalyuk requested changes

2022-01-10 06:10 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +        int weight;
Разумно этот тип тоже сделать параметром шаблона.

2022-01-10 06:10 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +    Vertex* addVertex(Vertex* data) {
Эта функция выглядит странно.

2022-01-10 06:10 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +            fromVertex->getEdge(toVertex)->setWeight(weightEdge);
Эта строчка есть в обеих ветках условного оператора.

2022-01-10 08:26 UTC, onisken commented on LibraryCPPTemplate/graph.h
> +        int weight;
Исправлено

2022-01-10 09:08 UTC, onisken commented on LibraryCPPTemplate/graph.h
> +            fromVertex->getEdge(toVertex)->setWeight(weightEdge);
Исправлено

2022-01-10 09:25 UTC, onisken commented on LibraryCPPTemplate/graph.h
> +    Vertex* addVertex(Vertex* data) {
Что нужно исправить в этой функции?

2022-01-10 09:56 UTC, onisken commented
@Dovgalyuk исправил замечания

2022-01-10 18:49 UTC, onisken commented on LibraryCPPTemplate/graph.h
> +    Vertex* addVertex(Vertex* data) {
Понял ошибку, исправил.

2022-01-11 06:24 UTC, Dovgalyuk commented
Принято.

2022-01-11 06:24 UTC, closed without merging