Алексеев Даниил Николаевич 0091 - lab5
Dovgalyuk/Algorithms pull request #360
Opened 2022-01-09 23:03 UTC by Lashy-Danya

2022-01-10 06:34 UTC, Dovgalyuk requested changes

2022-01-10 06:34 UTC, Dovgalyuk commented on Laba/zadanie5.cpp
> +		table->setData(string_generator());
В обоих случаях должны добавляться одинаковые строки, поэтому стоит их заранее где-то сохранить.
И предел измерений надо поднять хотя бы до 1000000.

2022-01-10 06:34 UTC, Dovgalyuk commented on LibraryCPPTemplate/Tests/hashTable.cpp
> +    int load_data = 1000;
Тут тоже стоит поднять предел до 1000000.

2022-01-10 06:34 UTC, Dovgalyuk commented on LibraryCPPTemplate/hashTable.h
> +                if (table[i]) {
if можно не писать

2022-01-10 06:34 UTC, Dovgalyuk commented on LibraryCPPTemplate/hashTable.h
> +            while (table[hash1] != nullptr && i < size_table) {
Такой цикл делается несколько раз, можно вынести его в отдельную функцию.

2022-01-10 15:57 UTC, Lashy-Danya commented
Поменял одну хеш-функцию (hash_1), так как  на вставку 1000000  элементов нужно было около двух минут

2022-01-10 23:37 UTC, Lashy-Danya commented
Вынес цикл в отдельную функцию, но пострадала скорость в итоге. Результаты на изображениях data_tabl_new и tabl_d_new. Может не правильно реализовал функцию. А если не выносить, то результаты на изображениях data_tabl и tabl_d

2022-01-11 06:36 UTC, Dovgalyuk commented
Принято.

2022-01-11 06:36 UTC, closed without merging