Решение четвёртой задачи - Зарманбетов Эмиль 0092
Dovgalyuk/Algorithms pull request #363
Opened 2022-01-10 08:51 UTC by EkoRiri

2022-01-11 06:21 UTC, Dovgalyuk commented
Проект не собирается.

2022-01-11 08:24 UTC, EkoRiri commented
@Dovgalyuk исправил

2022-01-17 05:14 UTC, Dovgalyuk requested changes

2022-01-17 05:14 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +        List<Edge*> edges = List<Edge*>();
Нет никакого смысла хранить указатели. Можно хранить сами структуры Edge в элементах списка.
В тех случаях, когда требуется именно адрес самого значения, можно использовать ссылки.

2022-01-19 12:08 UTC, EkoRiri commented on LibraryCPPTemplate/graph.h
> +        List<Edge*> edges = List<Edge*>();
Исправлено

2022-01-19 12:17 UTC, EkoRiri commented
@Dovgalyuk Готово

2022-01-21 05:00 UTC, Dovgalyuk requested changes

2022-01-21 05:00 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +            Edge nullEdge = Edge();
Нельзя возвращать ссылку на локальную переменную.
Нужно её сделать static хотя бы, тогда это будет ссылка на неизменную переменную, представляющую несуществующее ребро.

2022-01-21 05:19 UTC, EkoRiri commented
@Dovgalyuk Готово

2022-01-21 05:19 UTC, EkoRiri commented on LibraryCPPTemplate/graph.h
> +            Edge nullEdge = Edge();
Сделано

2022-01-24 05:22 UTC, Dovgalyuk commented
Принято.

2022-01-24 05:22 UTC, closed without merging