Тимофеев Владимир. Лабораторная работа №4.
Dovgalyuk/Algorithms pull request #364
Opened 2022-01-10 14:51 UTC by Vufik

2022-01-11 06:19 UTC, Dovgalyuk requested changes

2022-01-11 06:19 UTC, Dovgalyuk commented on LibraryCPPTemplate/d_graph.h
> +                if (it->check_weight(i)){
Матрица смежности должна быть отделена от меток, которые задаёт пользователь. Например, меткой вполне может быть строка. Или структура из числа и строки.

2022-01-11 09:07 UTC, Vufik commented on LibraryCPPTemplate/d_graph.h
> +                if (it->check_weight(i)){
Исправил

2022-01-17 05:26 UTC, Dovgalyuk requested changes

2022-01-17 05:26 UTC, Dovgalyuk commented on LibraryCPPTemplate/d_graph.h
> +            data = 0;
data может быть любого типа. Поэтому надо инициализировать значением по умолчанию, а не 0.

2022-01-17 07:55 UTC, Vufik commented on LibraryCPPTemplate/d_graph.h
> +            data = 0;
Исправил

2022-01-19 05:22 UTC, Dovgalyuk commented
Принято.

2022-01-19 05:22 UTC, closed without merging