4 задание Складник Любовь
Dovgalyuk/Algorithms pull request #366
Opened 2022-01-14 11:08 UTC by Lubov2609

2022-01-17 05:42 UTC, Dovgalyuk commented
Проект не компилируется.

2022-01-18 10:09 UTC, Lubov2609 commented
Проверила, переправила снова, у меня запускается

2022-01-19 05:28 UTC, Dovgalyuk commented
Стоит почитать описание ошибки сборки во вкладке checks.

2022-01-21 05:17 UTC, Dovgalyuk requested changes

2022-01-21 05:17 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +            Iterator it(graph, ownerIndex, current);
Постфиксный оператор должен возвращать предыдующее значение, а не следующее.

2022-01-21 05:17 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +            Iterator it(graph, current);
То же самое.

2022-01-21 05:17 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +                matrix->set(getIndex(i, j), matrix->get(getIndex(i + 1, j + 1)));
Похоже, что мы здесь будем затирать нулевую строку незавивимо от того, какую удаляем вершину.

2022-01-21 05:17 UTC, Dovgalyuk commented on lab4/Test.cpp
> +        if (vertex->data.first) continue;
Это можно делать сразу, не вычисляя новую стоимость.

2022-01-24 05:36 UTC, Dovgalyuk commented
1. Добавилось много мусора.
2. Проект не собирается.
3. Всё ещё остаются вопросы к итераторам.

2022-01-24 05:36 UTC, closed without merging

2022-01-24 11:53 UTC, Lubov2609 commented
Здравствуйте, во сколько и в какую аудиторию нам подходить?
группа 0091

пн, 24 янв. 2022 г., 08:36 Pavel Dovgalyuk ***@***.***>:

> Closed #366 <https://github.com/Dovgalyuk/Algorithms/pull/366>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Dovgalyuk/Algorithms/pull/366#event-5939771979>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AS4O4WYO3NJLNG6UFAR765TUXTQPBANCNFSM5L6QM3RA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-01-24 12:06 UTC, Dovgalyuk commented
9:00 1100(5)