First Lab
Dovgalyuk/Algorithms pull request #375
Opened 2022-09-07 14:45 UTC by diyliv

2022-09-07 14:46 UTC, diyliv commented
https://github.com/diyliv/Algorithms/tree/master/FirstLab

2022-09-08 05:00 UTC, Dovgalyuk commented
Смысл задания в том, чтобы не использовать встроенный массив для решения задачи, а реализовать библиотечный модуль, который предоставляет аналогичные функции.
Т.е. должен быть описан интерфейс массива (как в примерах в array.h). А потом реализован в отдельном модуле.

2022-09-08 15:20 UTC, diyliv commented
https://github.com/diyliv/Algorithms/tree/main/FirstLab

2022-09-09 05:10 UTC, Dovgalyuk commented
1. Я не вижу в array реализацию нужных методов
2. Очень много мусора в array
3. Как насчёт попробовать вызывать из программы на go реализацию контейнера на C++?

2022-09-10 09:49 UTC, diyliv commented
https://github.com/diyliv/Algorithms/tree/main/FirstLab

Фиксанул. Вызываю c++ код из гошки. (Так же реализовал контракт(array.h) в array.cpp)

2022-09-12 05:12 UTC, Dovgalyuk commented
Надо коммиты добавлять или в изначальную ветку, или создать новый pull request.
Так я буду видеть и изменения и тесты.

2022-09-12 05:17 UTC, Dovgalyuk commented
И нигде не нашёл, как подключается модуль array.

2022-09-12 07:43 UTC, diyliv commented
модуль подключается через import "C"

2022-09-13 06:43 UTC, Dovgalyuk commented
Array надо менять в одной из уже созданных библиотек, чтобы сразу прогонялись тесты. Сейчас они все падают.

2022-09-13 06:44 UTC, Dovgalyuk commented
Компиляцию своей программы было бы неплохо добавить в конфиг cmake, если получится.
Тогда можно будет наблюдать, что всё собирается, прямо на сервере, не скачивая исходники.

2022-09-13 09:59 UTC, diyliv commented
ок, попробую

2022-09-14 08:34 UTC, diyliv commented
добавил выполняемый файл

2022-09-14 13:57 UTC, diyliv commented
я если что добавил решение на плюсах.. не хотелось, но пришлось :)

2022-09-15 04:46 UTC, Dovgalyuk requested changes

2022-09-15 04:46 UTC, Dovgalyuk commented on FirstLab/firstlab.cpp
> +int ArrayProcessing(Array* ARR, int const &SIZE)
Размер передавать ни к чему, его можно прочитать из Array.

2022-09-15 04:46 UTC, Dovgalyuk commented on FirstLab/firstlab.cpp
> +		else if (array_get(ARR, i) >= max)
Условие "больше" тут уже не сработает, можно сделать код понятнее.

2022-09-15 04:46 UTC, Dovgalyuk commented on FirstLab/firstlab.cpp
> +	return max;
Что получится для такого массива?
10 3 4 5

2022-09-15 06:46 UTC, diyliv commented on FirstLab/firstlab.cpp
> +int ArrayProcessing(Array* ARR, int const &SIZE)
зачем мне получать размер через метод, когда я могу просто получить инт и это будет дешевле?

2022-09-15 18:48 UTC, diyliv commented on FirstLab/firstlab.cpp
> +		else if (array_get(ARR, i) >= max)
так не сработает или код сделать понятнее?
проверил, все норм

2022-09-15 18:49 UTC, diyliv commented on FirstLab/firstlab.cpp
> +	return max;
Введите длину массива: 4


10 3 4 5

Первая встреченная машина с макс скоростью и ее номер: 0

2022-09-16 06:28 UTC, Dovgalyuk commented on FirstLab/firstlab.cpp
> +int ArrayProcessing(Array* ARR, int const &SIZE)
Отделение кода от ненужных деталей, упрощение интерфейса. Этот алгоритм же универсален.

2022-09-16 06:29 UTC, Dovgalyuk commented on FirstLab/firstlab.cpp
> +		else if (array_get(ARR, i) >= max)
Не сработает, поэтому можно удалить без потери какого-либо поведения. И станет понятнее тому, кто этот код сопровождает.

2022-09-16 06:33 UTC, Dovgalyuk commented on FirstLab/firstlab.cpp
> +	return max;
Понял, ошибка не в этом. max инициализируется несуществующим значением, это неправильно.

2022-09-16 06:34 UTC, Dovgalyuk commented on FirstLab/firstlab.cpp
> +		else if (array_get(ARR, i) >= max)
Т.е. написать == вместо >=

2022-09-17 21:49 UTC, diyliv commented
фиксанул

2022-09-19 04:49 UTC, Dovgalyuk commented
Новый тест: 5 10 6 7

Остальные замечания тоже надо исправить.

2022-09-19 15:55 UTC, diyliv commented
фиксанул

2022-09-20 06:51 UTC, Dovgalyuk commented
Что-то не выложил, вероятно. Такой тест не проходит.

2022-09-20 07:31 UTC, diyliv commented
не, все добавил

2022-09-20 07:58 UTC, Dovgalyuk commented
Тогда это не может работать (и у меня не работает).

2022-09-20 11:10 UTC, diyliv commented
не понимаю о чем речь?
тесты же прошли все и билдится норм

2022-09-21 17:22 UTC, Dovgalyuk commented
Ну программа со входными данными 5 10 6 7 не работает.

2022-09-21 20:04 UTC, diyliv commented
почему?
Определить порядковый номер самого быстрого автомобиля.Если таких автомобилей несколько,то должен быть найден номер:
a) первого из них;
б) последнего из них. 

а) выводится индекс 1
б) не найдено 
что не так?

2022-09-22 17:28 UTC, Dovgalyuk commented
Должно быть так, но FirstLab/firstlab.cpp выводит не это.

2022-09-22 17:30 UTC, diyliv commented
как не это если я прогнал через нее эти значения?

2022-09-24 04:22 UTC, Dovgalyuk commented
выложи версию, которая не генерирует значения, а вводит с клавиатуры

2022-09-28 13:31 UTC, diyliv commented
uploaded

2022-09-29 06:41 UTC, Dovgalyuk commented
Это совсем другой код, тут ошибки уже нет.

2022-09-29 06:42 UTC, Dovgalyuk commented
* Реализовать в проекте Library двусвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

Написать программу, которая с помощью стека проверяет правильность последовательности из скобок вида (), [] и {}. Правильной считается последовательность, где каждой открывающей соответствует ровно одна закрывающая скобка и наоборот. 
В выходной файл напечатать YES, если последовательность правильная и NO, если неправильная.

Входные данные
```
([])
```
Выходные данные
```
YES
```

Входные данные
```
([)
```
Выходные данные
```
NO
```

2022-09-29 06:42 UTC, closed without merging