1 Task Галицкий Я.В. гр.1092
Dovgalyuk/Algorithms pull request #378
Opened 2022-09-09 06:26 UTC by IPOMPONI

Возникаю сложности с запуском и прохождением тестов.

2022-09-12 04:59 UTC, Dovgalyuk requested changes

2022-09-12 04:59 UTC, Dovgalyuk commented on LibraryCPP/array.cpp
> +    if (index < 0 || index >= array_size(arr))
size_t не может принимать отрицательные значения.

2022-09-12 04:59 UTC, Dovgalyuk commented on Lab1/1Task.cpp
> +		for ( int j = 0; j < i; j++)             // Проверка на одинаковые числа
Можно и без этого, тут разные числа необязательны.

2022-09-12 04:59 UTC, Dovgalyuk commented on Lab1/1Task.cpp
> +		if ((array_get(Parr, i) % 2 == 1) || ((array_get(Parr, i) % 2 == 1)) && ((array_get(Parr, i+1) % 2 == 1)))
Тут может быть выход за границы массива.

2022-09-12 04:59 UTC, Dovgalyuk commented on Lab1/1Task.cpp
> +	Array *Pbuf = array_create(SIZE);
Можно обойтись без дополнительного массива, ведь всегда используется только последнее значение.

2022-09-12 08:41 UTC, IPOMPONI commented
Исправил код.

2022-09-13 06:36 UTC, Dovgalyuk commented on Lab1/1Task.cpp
> +	cout << "\n\nНаибольший отрезок нечетных чисел в массиве: " << Maxlength << "\n\n";
Что будет, если все числа в массиве нечётные?

2022-09-13 07:18 UTC, IPOMPONI commented
Нашел ошибку, исправил код

2022-09-14 05:10 UTC, Dovgalyuk commented
Принято. Теперь нужно защитить работу на занятии.

Следующее задание:
* Реализовать в проекте Library двусвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

Преобразовать корректное арифметическое выражение, использующее операции сложения, вычитания, умножения и деления, в арифметическое выражение в обратной польской записи. Программа должна учитывать приоритет операторов умножения и деления и использовать стек. Операндами в выражении являются однобуквенные переменные.

Входные данные
```
A+B*C+D
```
Выходные данные
```
ABC*+D+
```

Входные данные
```
A*B+C
```
Выходные данные
```
AB*C+
```

Входные данные
```
A+B*(C+D)
```
Выходные данные
```
ABCD+*+
```

2022-09-14 05:10 UTC, closed without merging