Lab1(fix)
Dovgalyuk/Algorithms pull request #384
Opened 2022-09-11 13:17 UTC by Merk9ayt

2022-09-12 05:26 UTC, Dovgalyuk requested changes

2022-09-12 05:26 UTC, Dovgalyuk commented on LibraryCPP/array.cpp
> +    if (index < 0 || index >= array_size(arr))
size_t не может быть отрицательным.

2022-09-12 09:04 UTC, Merk9ayt commented on LibraryCPP/array.cpp
> +    if (index < 0 || index >= array_size(arr))
То есть нужно добавить проверку отрицательного значения вводимого числа?

2022-09-13 06:39 UTC, Dovgalyuk commented
Принято. Теперь работу нужно защитить.

Следующее задание:

# Реализовать в проекте Library двусвязный список (модуль list) и стек на основе этого списка (модуль stack).
# Решить задачу, используя реализованный стек.

Преобразовать арифметическое выражение в ассемблерные опреации работы со стеком и регистрами.
Используются команды PUSH (занести в стек), POP (извлечь из стека в регистр), ADD (сложить),
SUB (вычесть), MUL (перемножить). Достаточно использовать два регистра A и B.

Входные данные
```
1+2*3
```
Выходные данные
```
PUSH 1
PUSH 2
PUSH 3
POP A
POP B
MUL A, B
PUSH A
POP A
POP B
ADD A, B
PUSH A
```

Входные данные
```
(1+2)*3
```
Выходные данные
```
PUSH 1
PUSH 2
POP A
POP B
ADD A, B
PUSH A
PUSH 3
POP A
POP B
MUL A, B
PUSH A
```

2022-09-13 06:39 UTC, closed without merging

2022-09-13 14:55 UTC, Merk9ayt commented
В каком смысле защитить ? Нужно будет куда придти?

2022-09-14 05:12 UTC, Dovgalyuk commented
Во вторник в 9 часов в аудитории по расписанию.

2022-09-14 10:12 UTC, Merk9ayt commented
Во вторник у нас нету в среду есть, в следующую среду подойти?

2022-09-15 04:37 UTC, Dovgalyuk commented
Вторник - день для всех. Если с других занятий в этот день не уйти, тогда я подумаю, как сделать по-другому.

2022-09-16 09:06 UTC, Merk9ayt commented
Понял