lab1 Bespalov 1092
Dovgalyuk/Algorithms pull request #392
Opened 2022-09-23 15:32 UTC by GAZON17

2022-09-24 04:37 UTC, Dovgalyuk requested changes

2022-09-24 04:37 UTC, Dovgalyuk commented on Lab1/CMakeList.txt
> +target_link_libraries(Algorithms1 LibraryCPP)
Надо подключить этот файл в главный cmake-скрипт, чтобы компиляция проходила при тестировании на сервере.

2022-09-24 04:37 UTC, Dovgalyuk commented on Lab1/testttt.cpp
> +	task1(Numbers, k);
k передавать в функцию не нужно

2022-09-25 13:24 UTC, GAZON17 commented on Lab1/testttt.cpp
> +	task1(Numbers, k);
исправил

2022-09-25 13:25 UTC, GAZON17 commented on Lab1/CMakeList.txt
> +target_link_libraries(Algorithms1 LibraryCPP)
я ничего не понимаю с этим cmake

2022-09-26 07:05 UTC, Dovgalyuk commented on Lab1/CMakeList.txt
> +target_link_libraries(Algorithms1 LibraryCPP)
Можно просто сделать в основном скрипте add_subdirectory(Lab1)

2022-09-26 15:28 UTC, GAZON17 commented on Lab1/CMakeList.txt
> +target_link_libraries(Algorithms1 LibraryCPP)
добавил

2022-09-27 07:27 UTC, Dovgalyuk commented on Lab1/CMakeList.txt
> +target_link_libraries(Algorithms1 LibraryCPP)
Этот файл должен называться CMakeLists.txt, а не CMakeList.txt
Можно посмотреть на главной странице отчёт о сборке - она не прошла.

2022-09-27 10:56 UTC, GAZON17 commented on Lab1/CMakeList.txt
> +target_link_libraries(Algorithms1 LibraryCPP)
Исправил

2022-09-28 04:42 UTC, Dovgalyuk commented
* Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

Реализовать команды манипуляции стеком из языка Forth: https://skilldrick.github.io/easyforth
Программа читает входную строку из следующих команд:
* 0-9 - заносит число в стек
* +-*/% - арифметические операции. Извлекают два числа из стека, а потом заносят туда результат
* dup - дублирует число на вершине стека
* drop - удаляет число с вершины стека
* swap - меняет местами два числа на вершине стека
* over - берёт элемент под вершиной стека и добавляет его в стек
* rot - перемещает "по кругу" верхние три элемента стека
* . - извлекает из стека верхний элемент и выводит на экран

Входные данные
```
1 2 3 rot . . .
```
Выходные данные
```
1
3
2
```

Входные данные
```
1 dup . 2 dup . 3 dup . + + .
```
Выходные данные
```
1
2
3
6
```

2022-09-28 04:42 UTC, closed without merging