added solution for second lab
Dovgalyuk/Algorithms pull request #402
Opened 2022-09-29 18:53 UTC by diyliv

2022-09-30 06:14 UTC, Dovgalyuk requested changes

2022-09-30 06:14 UTC, Dovgalyuk commented on secondLab/main.cpp
> +    return stack_empty(stack);
В конце стек надо удалять.

2022-09-30 21:24 UTC, diyliv commented on secondLab/main.cpp
> +    return stack_empty(stack);
фиксанул

2022-10-03 06:41 UTC, Dovgalyuk commented on secondLab/main.cpp
> +    return stack_empty(stack);
После return ничего не выполняется. Надо удалять до его выполнения. И он тут не один.

2022-10-04 05:23 UTC, Dovgalyuk requested changes

2022-10-04 05:23 UTC, Dovgalyuk commented on secondLab/main.cpp
> +                break;
Третий вид скобок куда-то пропал.

2022-10-06 07:30 UTC, Dovgalyuk commented on secondLab/main.cpp
> +    }
Этот цикл работает не как ожидалось.
1. Он не удаляет сам объект стека.
2. Он выходит на первой итерации и остальные элементы всё равно остаются в памяти.

2022-10-10 06:14 UTC, diyliv commented on secondLab/main.cpp
> +    }
fixed

2022-10-10 06:36 UTC, Dovgalyuk commented
* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.

Задан список двунаправленных дорог, соединяющих города и названия городов между которыми нужно найти кратчайший путь. Написать программу, находящую кратчайший путь с помоью поиска в ширину и вывести в выходной файл список городов, которые нужно посетить, чтобы добраться из начального города в конечный.

Входные данные
```
City1 City2
City2 End
Start City1
Start End
```
Выходные данные
```
Start City1 City2 End
```

В примере задано 3 дороги: City1-City2, City2-End, Start-City1. Последние 2 города в списке – начальный и конечный города в искомом пути.

2022-10-10 06:36 UTC, closed without merging

2022-10-10 10:57 UTC, diyliv commented
а надо приходить защищать лабу?

2022-10-11 07:45 UTC, Dovgalyuk commented
да, конечно