Second Lab
Dovgalyuk/Algorithms pull request #409
Opened 2022-10-05 19:32 UTC by ErikMak

2022-10-06 07:27 UTC, Dovgalyuk commented on LabTasks/Lab2/main.cpp
> +                    }
Можно вместо этого всего stack_push(stack, val_1 > val_2)

2022-10-06 07:28 UTC, Dovgalyuk commented on LabTasks/Lab2/main.cpp
> +                    int result = val_1 / val_2;
Тут тоже можно исключение выбрасывать.

2022-10-07 06:46 UTC, Dovgalyuk commented
> Функция list_erase() неприменима для односвязных списков? 

Это даже написано в комментариях в заголовочном файле.

> Как можно выполнить stack_pop() для единственного значения стэка?

Просто удалить элемент из списка.

2022-10-10 06:28 UTC, Dovgalyuk requested changes

2022-10-10 06:28 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +            delete item;
Не очень хорошо делать такую неочевидную функцию, на поведение которой влияют не сами параметры, а то, как они связаны с другими элементами.
Возможны несколько вариантов:
- фиктивный головной элемент, который никогда не удаляется
- дополнительная функция для удаления первого элемента
- передавать NULL в качестве item, если нужно удалять первый элемент

2022-10-10 06:28 UTC, Dovgalyuk commented on LabTasks/Lab2/main.cpp
> +                    stack_pop(stack);
Вот во всех таких случаях нет проверки на пустоту.

2022-10-10 19:24 UTC, ErikMak commented on LibraryCPP/list.cpp
> +            delete item;
Я думал нельзя добавлять новые функции в рамках уже объявленных функций. Исправлено

2022-10-11 08:02 UTC, Dovgalyuk requested changes

2022-10-11 08:02 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +        list_erase_next(stack->list, list_first(stack->list));
А нельзя вместо этого всего просто делать erase head?

2022-10-12 09:23 UTC, Dovgalyuk commented
Теперь тест для стека не проходит.

2022-10-13 06:33 UTC, Dovgalyuk commented
* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.

Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной – «#» или пустым пространством – «.». Стартовая позиция обозначается как X, финишная как Y. Написать программу, находящую минимальный путь от стартовой до финишной клетки, если это возможно. За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди. Если решения нет, вывести IMPOSSIBLE.

Входные данные
```
######
#...X#
#.####
#...Y#
######
```
Выходные данные
```
######
#xxxX#
#x####
#xxxY#
######
```

Входные данные
```
######
#...X#
######
#...Y#
######
```
Выходные данные
```
IMPOSSIBLE
```

2022-10-13 06:33 UTC, closed without merging