Lab 2 solve
Dovgalyuk/Algorithms pull request #413
Opened 2022-10-09 13:43 UTC by DashkovskiyNikita

2022-10-10 06:32 UTC, Dovgalyuk commented
Тест для вектора тоже должен проходить (см. вкладку checks)

2022-10-11 17:13 UTC, DashkovskiyNikita commented
Исправил

2022-10-12 09:26 UTC, Dovgalyuk commented on LibraryCPP/vector.cpp
> +    if (size > vector->capacity || cur_size > size) {
Почему для cur_size > size надо перевыделять память?

2022-10-13 06:23 UTC, Dovgalyuk commented on LibraryCPP/vector.cpp
> +    if (size > vector->capacity || cur_size > size) {
Обычно так как раз не делается. Тем более, для случая стека, когда уменьшение часто происходит, будет постоянно происходить копирование всех элементов.

2022-10-19 16:40 UTC, DashkovskiyNikita commented
Исправил vector_resize

2022-10-20 07:30 UTC, Dovgalyuk requested changes

2022-10-20 07:30 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +        this->last = -1;
last можно выкинуть, вектор же хранит используемый размер самостоятельно

2022-10-20 07:30 UTC, Dovgalyuk commented on Labs/lab2.cpp
> +	int v2 = stack_get(stack); stack_pop(stack);
Неплохо бы проверять стек на пустоту, прежде чем добывать из него значения.

2022-10-20 07:30 UTC, Dovgalyuk commented on Labs/lab2.cpp
> +	stack_push(stack, v1 / v2 * 100);
Процент - это остаток от деления.

2022-10-20 09:51 UTC, DashkovskiyNikita commented
Исправил

2022-10-21 06:55 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и очередь на основе этого списка (модуль queue).
* Решить задачу, используя реализованную очередь.

Входной файл содержит последовательность положительных чисел. Отсортировать последовательность с помощью поразрядной сортировки.
Число битов, по которым происходит сравнение должно задаваться в виде константы в коде.
Для каждой комбинации битов должна быть организована отдельная очередь, хранящая соответствующие числа.

Входные данные
```
8 4 1 5 6
```
Выходные данные
```
1 4 5 6 8
```

Если разделять числа из примера по одному (младшему) биту, то получатся два набора: {8, 4, 6} и {1, 5}.
Если брать сразу по два бита, то будет 4 набора: {8, 4}, {1, 5}, {6}, {}.

2022-10-21 06:55 UTC, closed without merging