Lab2 Ovchinnikov
Dovgalyuk/Algorithms pull request #417
Opened 2022-10-15 16:28 UTC by Merk9ayt

2022-10-17 06:36 UTC, Dovgalyuk requested changes

2022-10-17 06:36 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +    }
Можно не перекладывать всё в дополнительный стек, а просто сканировать входную строку слева направо. А стеки использовать только для храния операндов и операций, чтобы правильно обработать приоритеты операций и скобки.

2022-10-17 06:36 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +                a = a * b;
проделывать вычисления не нужно, только сгенерировать программу

2022-10-17 18:18 UTC, Merk9ayt commented on Lab2/lab2.cpp
> +    }
Я использую дополнительный стек чтобы временно хранить в нём и операнды и операции, чтобы не пришлось вводить дополнительные переменные для хранения данных, просто я сразу смогу обратится к элементу когда дойду до операций и в buf и в stack.

2022-10-18 07:53 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +    }
Так строка и без этого все опреации будет хранить. А перекладывать их два раза - это лишняя работа.

2022-10-19 07:53 UTC, Dovgalyuk requested changes

2022-10-19 07:53 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +            switch (stack_get(buf))
Генерация кода повторяется дважды, можно её вынести в функцию.

2022-10-19 10:57 UTC, Merk9ayt commented on Lab2/lab2.cpp
> +            switch (stack_get(buf))
Не особо понял что вы хотели вынести в функцию, если switch то они разные, если действия в switch то они тоже разные

2022-10-20 06:57 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +            switch (stack_get(buf))
Примерно одно и то же. Немного по-разному организовано, но можно же и реорганизовать. Не придётся дважды один и тот же код повторять тогда.

2022-10-20 11:16 UTC, Merk9ayt commented on Lab2/lab2.cpp
> +            switch (stack_get(buf))
Поправил

2022-10-21 08:37 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +            stack_push(buf, stack_get(stack));
Но числа в стеке не нужны, можно их неявно подразумевать, раз они уже попали в вывод.

2022-10-21 08:38 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +        if(stack_get(stack)==')')
В скобках может быть больше одной операции.

2022-10-24 08:07 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +    Stack* stack = stack_create();
Осталось этот стек выкинуть.

2022-10-24 08:22 UTC, Merk9ayt commented on Lab2/lab2.cpp
> +    Stack* stack = stack_create();
Мне тогда стек заменить на другой тип данных, или переделать программу под другую реализацию

2022-10-24 09:31 UTC, Merk9ayt commented on Lab2/lab2.cpp
> +    Stack* stack = stack_create();
Чтобы был только один стек

2022-10-25 08:48 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +    for (int i = str.length(); i >= 0;i--)
Из этого стека данные достаются в том же порядке, в котором они хранились во входной строке. Причём они только поочерёдно удаляются и всё, больше ничего с ним не происходит. Поэтому вместо этого стека нужно просто использовать исходную строку.

2022-10-25 09:33 UTC, Merk9ayt commented on Lab2/lab2.cpp
> +    for (int i = str.length(); i >= 0;i--)
Аааа всё я понял

2022-10-26 09:36 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +        stack_push(buf, str[i]);
Уже намного лучше.
Осталось убрать, чтобы цифры в стек не попадали, а только операции.

2022-10-26 10:09 UTC, Merk9ayt commented on Lab2/lab2.cpp
> +        stack_push(buf, str[i]);
У меня в стеке хранятся цифры чтобы не вводить новый тип данных, и чтобы сразу как пришёл к операции её удалил и взял цифры находящиеся слева и справа, если цифр в стеке не будет то мне надо будет вводить новую переменную (скорее всего string)

2022-10-27 06:52 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +        stack_push(buf, str[i]);
Так цифры же сразу пишутся (как только будут встречены в строке) в вывод с командой PUSH. Дальше они не нужны вообще.

2022-10-27 09:03 UTC, Merk9ayt commented on Lab2/lab2.cpp
> +        stack_push(buf, str[i]);
Я думал они там содержаться где-то должны, понял переделаю

2022-10-27 15:06 UTC, Merk9ayt commented on Lab2/lab2.cpp
> +        stack_push(buf, str[i]);
Поправил

2022-10-28 09:40 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +    Stack* buf = stack_create();
Осталось немного здесь поправить. На самом деле этот buf не нужен, если исправить ошибку.
Ошибка в том, что не будет работать такой пример:
1-2*3+4

2022-10-29 15:29 UTC, Merk9ayt commented on Lab2/lab2.cpp
> +    Stack* buf = stack_create();
Пример 1-2*3+4 работает 
ВХОДНЫЕ ДАННЫЕ:
1-2*3+4
ВЫХОДНЫЕ ДАННЫЕ:
PUSH 1
PUSH 2
PUSH 3
PUSH 4
POP A
POP B
MUL A, B
PUSH A
POP A
POP B
SUB A, B
PUSH A
POP A
POP B
ADD A, B
PUSH A

2022-10-29 15:42 UTC, Merk9ayt commented on Lab2/lab2.cpp
> +    Stack* buf = stack_create();
Чтобы убрать buf мне надо будет тогда отсортировать символы которые поступают в stack, чтобы первыми были + и - , затем шло * , следующим (, операции в скобках, и последним ) , соответственно первым на выход из stack идёт ) если она существует и т.д. 
Например: 
Входные данные:1+2*3-(4+5*6) 
Отсортированная строка поступающая в stack: )*+(*+-
Мне так реализовать генерацию кода?

2022-10-31 06:57 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +    Stack* buf = stack_create();
> Пример 1-2 * 3+4 работает ВХОДНЫЕ ДАННЫЕ: 1-2 * 3+4 ВЫХОДНЫЕ ДАННЫЕ: PUSH 1 PUSH 2 PUSH 3 PUSH 4 POP A POP B MUL A, B PUSH A POP A POP B SUB A, B PUSH A POP A POP B ADD A, B PUSH A

Так вот как раз видно, что не работает. Тут перемножаются 3 и 4 вместо 2 и 3.

2022-10-31 07:26 UTC, Merk9ayt commented on Lab2/lab2.cpp
> +    Stack* buf = stack_create();
Понял переделаю, но buf скорее всего останятся

2022-10-31 15:47 UTC, Merk9ayt commented
Поправил

2022-11-01 06:08 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +            if (str[i-1] == '*' && int(str.find('(')) < 0)
Выглядит странно. Наверняка есть пример, когда такой способ не работает.

Правильно это делается через приоритеты операций. Если встречена операция с меньшим приоритетом, то надо выполнить все операции в стеке, которые имеют больший приоритет.
Примерно так же, как и с закрывающей скобкой. Будто бы мы операции с большим приоритетом заключили в скобки.

2022-11-01 16:38 UTC, Merk9ayt commented
Re-fix

2022-11-02 11:06 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +    stack_delete(stack);
Уже хорошо читается код.
По-моему, не сработает такое: 1 + (2+3*4+1)

2022-11-03 05:06 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.

Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной - «#» или пустым пространством – «.». Стартовая позиция обозначается как X. Написать программу, считающую количество клеток, до которых можно найти из начальной, а также выводящую лабиринт с достижимыми клетками, отмеченными символом «x». За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди.

Входные данные
```
######
#...X#
#.####
#....#
######
```
Выходные данные
```
9
######
#xxxx#
#x####
#xxxx#
######
```

2022-11-03 05:06 UTC, closed without merging