3 Task Галицкий Я.В. гр.1092
Dovgalyuk/Algorithms pull request #420
Opened 2022-10-16 18:49 UTC by IPOMPONI

Можно ли защитить 2ю и 3ю работы вместе или лучше 2ю работу защитить до 9й недели?

2022-10-17 06:46 UTC, Dovgalyuk commented
Работы можно защищать вместе. Сданное до 9 недели влияет (вероятно) только на стипендию.

2022-10-17 07:47 UTC, Dovgalyuk requested changes

2022-10-17 07:47 UTC, Dovgalyuk commented on Lab3/3Task.cpp
> +		main();                                                                  // и позволяем запустить программу снова
Так лучше не делать, а написать просто цикл.

2022-10-17 07:47 UTC, Dovgalyuk commented on Lab3/3Task.cpp
> +			if (z != Str.size())
Мы же по определению не можем выйти за строку.

2022-10-17 07:47 UTC, Dovgalyuk commented on Lab3/3Task.cpp
> +			maze[i][j] = Str[z];                            // Переносим все элементы лабиринта в двумерный массив строк (матрицу)
Разве переводы строк в Str здесь не мешают?

2022-10-17 07:47 UTC, Dovgalyuk commented on Lab3/3Task.cpp
> +		while (flag && maze[X][Y].find(Way) == string::npos && (maze[X][Y].find(Wall) == string::npos) && (maze[X][Y].find("X") == string::npos))
maze[X][Y] это же один символ, какой смысл использовать find?

2022-10-17 09:30 UTC, IPOMPONI commented on Lab3/3Task.cpp
> +			maze[i][j] = Str[z];                            // Переносим все элементы лабиринта в двумерный массив строк (матрицу)
Тут идет перенос элементов лабиринта (который был записан в строку Str) в двумерный массив строк maze[i][j].
Т.е. я перетаскиваю определенный (zй) символ из Str в определенную позицию двумерного массива  maze[i][j].

2022-10-17 09:37 UTC, IPOMPONI commented on Lab3/3Task.cpp
> +		while (flag && maze[X][Y].find(Way) == string::npos && (maze[X][Y].find(Wall) == string::npos) && (maze[X][Y].find("X") == string::npos))
Тут вы правы. Просто т.к. в лабиринте присутствуют и символы и числа, то я создавал двумерный динамический массив строк maze[i][j]. Поэтому я не мог сравнивать maze[i][j] == '.' (например), ведь строку нельзя сравнивать с символом, а вот про сравнения типа  maze[i][j] == "." (например) я позабыл. Поэтому да,  необходимости использовать find тут нет.

2022-10-17 09:37 UTC, IPOMPONI commented
Вроде как подправил все.

2022-10-17 09:38 UTC, IPOMPONI commented on Lab3/3Task.cpp
> +		main();                                                                  // и позволяем запустить программу снова
Решил упростить программу и вообще убрать ее перезапуск. Он требовался мне во время дебага.

2022-10-18 07:25 UTC, IPOMPONI commented on Lab3/3Task.cpp
> +			maze[i][j] = Str[z];                            // Переносим все элементы лабиринта в двумерный массив строк (матрицу)
Понял о чем вы говорили. Убрал добавление '\n' в строку Str из кода (цикл 29-32 строки). Это был остаточный код, который я забыл почистить.

2022-10-18 16:04 UTC, IPOMPONI commented
Надеюсь теперь точно все подправил.

2022-10-18 16:14 UTC, IPOMPONI commented
Надеюсь теперь точно все подправил.

2022-10-19 08:21 UTC, Dovgalyuk requested changes

2022-10-19 08:21 UTC, Dovgalyuk commented on Lab3/3Task.cpp
> +		mark[X][Y] = true;       // Помечаем текущее местоположение как посещенное
Вроде это ни к чему.

2022-10-19 08:21 UTC, Dovgalyuk commented on Lab3/3Task.cpp
> +				++distance;                // Считаем пройденный путь
Путь считается неверно. Попробуй вывести результат для какой-нибудь почти пустой комнаты.

2022-10-19 08:21 UTC, Dovgalyuk commented on Lab3/3Task.cpp
> +	string** maze = new string * [height];                         // Создаем двумерный масиив строк (матрицу) для лабиринта (При дебаге кода легко отслеживать текущее местоположение в лабиринте и запом
Лучше тогда и заменить на массив символов, строки не нужны там.

2022-10-19 08:21 UTC, Dovgalyuk commented on Lab3/3Task.cpp
> +	while (!queue_empty(queue))       // Пока очередь НЕ пуста
А где же поиск ближайшей цифры?

2022-10-19 13:48 UTC, IPOMPONI commented on Lab3/3Task.cpp
> +		mark[X][Y] = true;       // Помечаем текущее местоположение как посещенное
Я убрал пометку посещенных мест из ветвей перемещения по лабиринту, поэтому теперь это необходимо.

2022-10-20 07:16 UTC, Dovgalyuk commented
Принято.

* Разработать программный интерфейс модуля (заголовки функций) для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
* Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
* Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List той же библиотеки.
* Разработать и добавить в проект Library программу, тестирующую работу библиотеки для графа.
* Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать для него минимальное покрывающее дерево алгоритмом Крускала.

2022-10-20 07:16 UTC, closed without merging