third lab solution
Dovgalyuk/Algorithms pull request #421
Opened 2022-10-16 23:18 UTC by diyliv

2022-10-16 23:22 UTC, diyliv commented
я сдал первые две лабы, но когда надо прийти, чтобы защищить их?

2022-10-17 08:01 UTC, Dovgalyuk commented
приходить можно в любой вторник в 2309 в 9:00

2022-10-17 08:14 UTC, Dovgalyuk requested changes

2022-10-17 08:14 UTC, Dovgalyuk commented on LibraryCPP/vector.cpp
> +    delete vector->data;
здесь нужен оператор delete[]

2022-10-17 08:14 UTC, Dovgalyuk commented on LibraryCPP/vector.cpp
> +   if ((size < vector->size) || (size >= vector->reserved_size))
пересоздавать хранилище не нужно, когда размер уменьшается

2022-10-17 08:14 UTC, Dovgalyuk commented on thirdLab/main.cpp
> +			cityIdx.insert( pair< string, int>(Start, cityAmount++));
есть функция make_pair

2022-10-17 08:14 UTC, Dovgalyuk commented on thirdLab/main.cpp
> +	Data path[arrSize];
Раз уж у нас есть вектор, можно его здесь использовать.

2022-10-17 11:58 UTC, diyliv commented on thirdLab/main.cpp
> +	Data path[arrSize];
так это же запара, нет?

2022-10-17 20:16 UTC, diyliv commented on thirdLab/main.cpp
> +			cityIdx.insert( pair< string, int>(Start, cityAmount++));
changed

2022-10-17 20:16 UTC, diyliv commented on LibraryCPP/vector.cpp
> +   if ((size < vector->size) || (size >= vector->reserved_size))
changed

2022-10-17 20:16 UTC, diyliv commented on LibraryCPP/vector.cpp
> +    delete vector->data;
changed

2022-10-18 07:54 UTC, Dovgalyuk commented on thirdLab/main.cpp
> +	Data path[arrSize];
Нет, тут же только добавлять значения надо, а потом проходить по ним в обратном порядке. Как раз растущий контейнер подходит.

2022-10-18 07:56 UTC, Dovgalyuk commented on LibraryCPP/vector.cpp
> +   	if (size < vector->reserved_size)
а если равно?

2022-10-18 10:48 UTC, diyliv commented on thirdLab/main.cpp
> +	Data path[arrSize];
а использовать встроенные векторы или контракт? "vector.h"

2022-10-18 20:31 UTC, diyliv commented on LibraryCPP/vector.cpp
> +   	if (size < vector->reserved_size)
фиксанул реализацию вектора + через вектор сделал

2022-10-19 08:28 UTC, Dovgalyuk commented on thirdLab/main.cpp
> +	vector <list<Data>> path(arrSize);
Просто vector<Data>. И добавлять туда через push_back.

2022-10-19 19:20 UTC, diyliv commented on thirdLab/main.cpp
> +	vector <list<Data>> path(arrSize);
changed

2022-10-20 07:36 UTC, Dovgalyuk commented on thirdLab/main.cpp
> +	vector <list<Data>> path(arrSize);
Теперь это массив из векторов. Нам надо набор чисел хранить, нужен только один вектор.

2022-10-21 08:04 UTC, diyliv commented
я исправил

2022-10-24 06:56 UTC, Dovgalyuk commented
Принято. Следующее задание после защиты.

2022-10-24 06:56 UTC, closed without merging

2022-10-24 06:56 UTC, Dovgalyuk commented
Принято. Следующее задание после защиты.

2022-12-13 10:48 UTC, Dovgalyuk commented
* Разработать программный интерфейс модуля (заголовки функций) для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
* Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
* Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List той же библиотеки.
* Разработать и добавить в проект Library программу, тестирующую работу библиотеки для графа.
* Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать в нем кратчайшие пути для заданной пары вершин с помощью алгоритма Дейкстры.