Lab1 solve
Dovgalyuk/Algorithms pull request #422
Opened 2022-10-17 14:56 UTC by Riba4koff

2022-10-18 07:51 UTC, Dovgalyuk commented
Надо подключить CMakeLists.txt от решённой задачи в основной файл, чтобы сборка проходила и на сервере тоже.

2022-10-18 10:56 UTC, Riba4koff commented
исправил

2022-10-19 08:06 UTC, Dovgalyuk requested changes

2022-10-19 08:06 UTC, Dovgalyuk commented on LibraryCPP/array.cpp
> +#define ARRAY_H
Это не нужно. Такие вещи пишутся в заголовочных файлах.

2022-10-19 08:06 UTC, Dovgalyuk commented on LibraryCPP/array.cpp
> +typedef int Data;
Это тоже из заголовочного файла.

2022-10-19 08:06 UTC, Dovgalyuk commented on Labs/Algorithms_lab_1.cpp
> +void fill_array(Array* arr, int size) {
Размер передавать не нужно, его можно узнать у массива.

2022-10-19 13:29 UTC, Riba4koff commented
Исправил

2022-10-19 13:33 UTC, Riba4koff commented
исправил array.cpp и файл с заданием

2022-10-20 07:06 UTC, Dovgalyuk commented
Принято.


* Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
* Решить задачу, используя реализованный стек.

Реализовать команды манипуляции стеком из языка Forth: https://skilldrick.github.io/easyforth
Программа читает входную строку из следующих команд:
* 0-9 - заносит число в стек
* +-*/% - арифметические операции. Извлекают два числа из стека, а потом заносят туда результат
* dup - дублирует число на вершине стека
* drop - удаляет число с вершины стека
* swap - меняет местами два числа на вершине стека
* over - берёт элемент под вершиной стека и добавляет его в стек
* rot - перемещает "по кругу" верхние три элемента стека
* . - извлекает из стека верхний элемент и выводит на экран

Входные данные
```
1 2 3 rot . . .
```
Выходные данные
```
1
3
2
```

Входные данные
```
1 dup . 2 dup . 3 dup . + + .
```
Выходные данные
```
1
2
3
6
```

2022-10-20 07:06 UTC, closed without merging

2022-10-20 17:08 UTC, Riba4koff commented
А как получилось 6?
Если вершина стэка 3 и после неё идет 2, если их сложить получим 5, после второго сложения будет 8 ??