Laba1_Lebedev_1091
Dovgalyuk/Algorithms pull request #424
Opened 2022-10-20 10:14 UTC by Andruf12

2022-10-21 06:55 UTC, Dovgalyuk commented
Кроме своей задачи надо реализовать ещё и array в одной из библиотек Library*

2022-11-26 10:47 UTC, Andruf12 commented
Извините, но можно по подробнее обьяснить, что мне нужно сделать?

2022-11-27 19:07 UTC, Andruf12 commented
> Кроме своей задачи надо реализовать ещё и array в одной из библиотек Library*

Извините, а можно по подробнее, что мне нужно сделать?

2022-11-28 07:57 UTC, Dovgalyuk commented
В проекте есть несколько каталогов Library*, где приведены заготовки для реализации разных контейнеров.
Нужно выбрать один вариант библиотеки (на C, C++ или с шаблонами) и реализовать в нём контейнер Array.
Затем подключить эту библиотеку к своему проекту и использовать этот Array при решении задачи.

2022-12-02 07:20 UTC, Dovgalyuk commented
Конфиг описан неверно, проект не собирается.
Массив надо добавить в библиотеку, а не в корневой каталог.

2022-12-09 07:19 UTC, Dovgalyuk requested changes

2022-12-09 07:19 UTC, Dovgalyuk commented on array.cpp
> +}
Этот файл не нужен.

2022-12-09 07:19 UTC, Dovgalyuk commented on Source.cpp
> +}
Этот файл в конфиге называется не так, поэтому ничего не компилируется.

2022-12-12 08:16 UTC, Dovgalyuk commented
add_subdirectory(LAB1)
вот тут ошибка

2022-12-13 10:13 UTC, Dovgalyuk commented
* Реализовать в проекте Library двусвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

Написать программу, которая с помощью стека проверяет правильность последовательности из скобок вида (), [], {} и <>. В выходной файл напечатать YES, если последовательность правильная и NO, если неправильная.

Входные данные
```
([])<>
```
Выходные данные
```
YES
```

Входные данные
```
()>
```
Выходные данные
```
NO
```

2022-12-13 10:13 UTC, closed without merging