Lab 2 solve
Dovgalyuk/Algorithms pull request #426
Opened 2022-10-20 21:02 UTC by Riba4koff

2022-10-20 21:11 UTC, Riba4koff commented
Посмотрел, почему-то CMake не собирается :(

2022-10-21 08:45 UTC, Dovgalyuk commented
Что-то не так с исключениями. Либо нужен другой конструктор, либо может быть такой вариант в каком-то другом заголовочном файле есть?

2022-10-21 14:53 UTC, Riba4koff commented
Даже без исключений пишет, что что-то с исключениями

2022-10-21 15:00 UTC, Riba4koff commented
Не понимаю..

2022-10-24 07:11 UTC, Dovgalyuk requested changes

2022-10-24 07:11 UTC, Dovgalyuk commented on Labs/Algorithms_lab_2.cpp
> +	}
Обработчики исключения все одинаковые. Но они почему-то не везде. Можно их вынести во внешний по отношению к этим функциям код.

2022-10-24 07:11 UTC, Dovgalyuk commented on Labs/Algorithms_lab_2.cpp
> +		case 48:
Во всех случаях надо писать сам символ, а не его код.
Например, здесь case '0':

2022-10-24 07:11 UTC, Dovgalyuk commented on Labs/Algorithms_lab_2.cpp
> +		case 49:
Цифры лучше отдельным условием обработать и сделать stack_push(stack, choise - '0')

2022-10-24 11:59 UTC, Riba4koff commented
Исправил

2022-10-25 08:42 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и очередь на основе этого списка (модуль queue).
* Решить задачу, используя реализованную очередь.

Задано начальное вещество и список химических реакций, в которых оно превращается в другое вещество.  Написать программу, использующую поиск в ширину, и выводящую список веществ, которые можно получить из исходного.

Входные данные
```
A
A->B
B->C
D->E
```
Выходные данные
```
B
C
```

В примере из вещества A можно получить вещества B и C.

2022-10-25 08:42 UTC, closed without merging