Lab 3 solve
Dovgalyuk/Algorithms pull request #428
Opened 2022-10-24 19:53 UTC by DashkovskiyNikita

2022-10-25 08:54 UTC, Dovgalyuk requested changes

2022-10-25 08:54 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        return list->head = next;
А если удалялся единственный элемент, куда будет указывать last?

2022-10-25 08:54 UTC, Dovgalyuk commented on Labs/lab3.cpp
> +	return (num & (1 << pos)) >> pos;
Эта функция работает только при RADIX=2

2022-10-30 15:55 UTC, DashkovskiyNikita commented on Labs/lab3.cpp
> +	return (num & (1 << pos)) >> pos;
Не совсем понял.По условию можно же делить на любые группы?В моем случае только по одному разряду, т.е. (0,1)

2022-10-31 07:31 UTC, Dovgalyuk commented on Labs/lab3.cpp
> +	return (num & (1 << pos)) >> pos;
Когда говорят "должна быть константа", то предполагается, что её можно менять в каких-то пределах. В нашем случае значение (степень двойки) от 2 до 16 хотя бы вполне разумно.

2022-11-03 05:15 UTC, Dovgalyuk requested changes

2022-11-03 05:15 UTC, Dovgalyuk commented on Labs/lab3.cpp
> +	}
(num >> pos) & ((1 << count) - 1)

2022-11-03 05:15 UTC, Dovgalyuk commented on Labs/lab3.cpp
> +	int offset = sqrt(RADIX);
Лучше обойтись без вещественных чисел.
const int offset = 2;
const int RADIX = 1 << offset;

2022-11-03 20:39 UTC, DashkovskiyNikita commented
Исправил

2022-11-07 11:38 UTC, Dovgalyuk commented
Следующее задание после защиты.

2022-11-07 11:38 UTC, closed without merging

2022-11-07 16:50 UTC, DashkovskiyNikita commented
А куда и во сколько можно подойти?

2022-11-08 08:28 UTC, Dovgalyuk commented
По вторникам в 9:00 в 2309.

2022-11-15 07:44 UTC, Dovgalyuk commented
* Разработать программный интерфейс модуля (заголовки функций) для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
* Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
* Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List той же библиотеки.
* Разработать и добавить в проект Library программу, тестирующую работу библиотеки для графа.
* Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать для него минимальное покрывающее дерево алгоритмом Прима.