3 lab
Dovgalyuk/Algorithms pull request #430
Opened 2022-10-26 23:43 UTC by Riba4koff

2022-10-27 00:02 UTC, Riba4koff commented
Скоро подправлю тест на list

2022-10-27 00:34 UTC, Riba4koff commented
Понял, я думал, что в список добавляется в конец, а в тестах в начало

2022-10-27 00:35 UTC, Riba4koff commented
Утром переделаю

2022-10-27 01:35 UTC, Riba4koff commented
Позже напишу решение задания

2022-10-27 12:48 UTC, Riba4koff commented
Задано начальное вещество и список химических реакций, в которых оно превращается в другое вещество. Написать программу, использующую поиск в ширину, и выводящую список веществ, которые можно получить из исходного.

Входные данные

A
A->B
B->C
D->E
Выходные данные

B
C
В примере из вещества A можно получить вещества B и C.
-----------------------------------------------------------------------

Не совсем понял, откуда взялось D->E?
И сколько реакций должно быть из первоначальной A, т.е., допустим, 3: A->B, B->C, C->D. Это сделать рандомайзером или же ручной ввод?

2022-10-27 13:12 UTC, Riba4koff commented
D->E Это фиктивный узел? (элемент)

2022-10-28 09:35 UTC, Dovgalyuk commented
Ну это же абстрактные правила превращений.
Не обязательно все должны использоваться в конкретном примере.

Вывести нужно все достижимые вещества. В нашем примере это BC.

2022-11-02 23:54 UTC, Riba4koff commented
написал решение

2022-11-03 05:51 UTC, Dovgalyuk requested changes

2022-11-03 05:51 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    while (previous != item) previous = previous->pNext;
Предыдущий же задаётся в параметре, зачем поиск тут нужен?

2022-11-03 05:51 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +ListItem* list_erase_next(List* list, ListItem* item){
Вот это как раз без циклов делается, потому что previous - это параметр.

2022-11-03 05:51 UTC, Dovgalyuk commented on Labs/Algorithms_lab_3.cpp
> +                answer_string.push_back(input_string[j + 1]);
Тут элементы могут попасть в ответ дважды.

2022-11-03 05:51 UTC, Dovgalyuk commented on Labs/Algorithms_lab_3.cpp
> +        for (int j = 0; j < input_string.length(); j += 3)
Можно было и двумерный массив завести, чтобы тут не искать всё время.

2022-11-03 21:43 UTC, Riba4koff commented on Labs/Algorithms_lab_3.cpp
> +        for (int j = 0; j < input_string.length(); j += 3)
Без цикла for сделать или без обоих циклов?

2022-11-03 22:35 UTC, Riba4koff commented on Labs/Algorithms_lab_3.cpp
> +        for (int j = 0; j < input_string.length(); j += 3)
Поменял на двумерный

2022-11-03 22:36 UTC, Riba4koff commented on Labs/Algorithms_lab_3.cpp
> +                answer_string.push_back(input_string[j + 1]);
убрал такой вывод и сделал с помощью посещенной вершины

2022-11-03 22:36 UTC, Riba4koff commented on LibraryCPP/list.cpp
> +ListItem* list_erase_next(List* list, ListItem* item){
Понял, исправил

2022-11-07 11:50 UTC, Dovgalyuk requested changes

2022-11-07 11:50 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        ListItem* current = item->pNext;
Тут цикл куда-то пропал.

2022-11-07 11:50 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    if (item == list->head) {
Нужно удалять элемент, следующий за item.

2022-11-07 12:34 UTC, Riba4koff commented on LibraryCPP/list.cpp
> +        ListItem* current = item->pNext;
Так я его специально убрал, потому что item в параметре передаётся

2022-11-07 12:36 UTC, Riba4koff commented on LibraryCPP/list.cpp
> +    if (item == list->head) {
Не понял немного, там и так удаляет следующий после item?

2022-11-07 12:53 UTC, Riba4koff commented on LibraryCPP/list.cpp
> +        ListItem* current = item->pNext;
здесь получаем item после которого нужно удалить и уже к current присваиваем следующий элемент, которой нужно удалить, после item->pNext, который ссылался на current, мы присвоим к current->pNext и удалим наш current (След. за item) А первый if это, если Item голова, т.к. мы не можем удалить после item->pNext, если там ничего нет. Ну либо я чего-то не понял

2022-11-07 13:21 UTC, Riba4koff commented on LibraryCPP/list.cpp
> +        ListItem* current = item->pNext;
а понял, тут нужен предыдущий

2022-11-07 13:35 UTC, Riba4koff commented on LibraryCPP/list.cpp
> +    if (item == list->head) {
исправил

2022-11-08 08:19 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    if (item == list->head) {
Функция называется "удалить следующий". Сам элемент item должен остаться.
Поэтому head измениться не может, проверка не нужна. Если за item ничего нет, то удалять тоже ничего не надо.

2022-11-08 20:01 UTC, Riba4koff commented
исправил

2022-11-09 07:47 UTC, Dovgalyuk commented
Принято. Следующее задание после защиты.

2022-11-09 07:47 UTC, closed without merging

2022-11-22 08:55 UTC, Dovgalyuk commented
* Разработать программный интерфейс модуля (заголовки функций) для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
* Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
* Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List той же библиотеки.
* Разработать и добавить в проект Library программу, тестирующую работу библиотеки для графа.
* Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать для него алгоритмом Флойда самый длинный из кратчайших путей.