4 Task Галицкий Я.В. гр.1092
Dovgalyuk/Algorithms pull request #431
Opened 2022-10-30 20:15 UTC by IPOMPONI

2022-10-31 07:41 UTC, Dovgalyuk commented
Тесты пока не сработали :)

2022-10-31 08:03 UTC, Dovgalyuk commented
Завтра занятия у меня не будет. Передай остальным, пожалуйста.

2022-10-31 08:51 UTC, IPOMPONI commented
Подправил тесты. Остальным все передал.

2022-11-01 06:03 UTC, Dovgalyuk requested changes

2022-11-01 06:03 UTC, Dovgalyuk commented on Lab4/4Task.cpp
> +    int** GrapgData = new int* [EdgeCount];                            // Создаем двумерный массив для ввода вершин и веса ребра между ними (первые два чила - вершина, третье число - вес ребра между
Почему сразу нельзя добавлять вводимые рёбра в граф?

2022-11-01 17:42 UTC, IPOMPONI commented on LibraryCPPTemplate/graph.h
> +            List<Edge*> *edges = new List<Edge*>;
Поправил

2022-11-01 17:51 UTC, IPOMPONI commented on Lab4/4Task.cpp
> +    int** GrapgData = new int* [EdgeCount];                            // Создаем двумерный массив для ввода вершин и веса ребра между ними (первые два чила - вершина, третье число - вес ребра между
Чутка исправил. Я использую двумерный динамический массив, тк я хочу вводить сразу 3 числа (Первые два числа вершины, а третье число это вес ребра между вводимыми вершинами). Поэтому записываю в граф, используя индексы массива.

2022-11-02 11:22 UTC, Dovgalyuk requested changes

2022-11-02 11:22 UTC, Dovgalyuk commented on Lab4/4Task.cpp
> +    int** GrapgData = new int* [EdgeCount];                            // Создаем двумерный массив для ввода вершин и веса ребра между ними (первые два чила - вершина, третье число - вес ребра между
int a, b, c;
cin >> a >> b >> c;

2022-11-02 11:22 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +            void AddEdge(Vertex* toVertex)
Так это же через граф и делается. Через вершину-то зачем.

2022-11-02 11:22 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +            List<Edge*> edges = List<Edge*>();
Конструктор по умолчанию можно и не указывать.

2022-11-02 15:49 UTC, IPOMPONI commented on LibraryCPPTemplate/graph.h
> +            List<Edge*> edges = List<Edge*>();
1) Сделал
2) Вы наверное не поняли, это не методы графа, это методы ребер, которые используются в логике на добавления ребра в граф на стр 200 - 212. Эти методы находятся в структуре вершин, потому что там объявляется список, из которого я использую методы в логике графа. 
3) Сделал

2022-11-02 15:50 UTC, IPOMPONI commented
Надеюсь вроде все объяснил/поправил.

2022-11-02 16:59 UTC, IPOMPONI commented
Надеюсь вроде все объяснил/поправил.

2022-11-03 05:17 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +            List<Edge*> edges = List<Edge*>();
Эти методы должен использовать только граф. Однако пользователь может через GetEdge получить ребро, а потом их вызывать, что не очень хорошо, на мой взгляд. То же и с вершиной.

2022-11-03 15:40 UTC, IPOMPONI commented
Fix

2022-11-07 11:36 UTC, Dovgalyuk commented
А почему теперь граф - это вершина.
Как-то очень всё стало странно.
Надо было просто методы сделать приватными (возможно, для этого класс граф должен быть другом, я не помню).
Ну и у ребра публичные атрибуты, любой может их испортить.

2022-11-07 14:33 UTC, IPOMPONI commented
А, я видимо вас не так понял. Думал нужно в приватную область графа методы выносить... Вернул структуру Vertex, добавил все важные атрибуты/методы в приватную область структуры (для Edge тоже).

2022-11-08 08:28 UTC, Dovgalyuk commented
Принято.

* Разработать интерфейс (набор функций) для ассоциативного массива, который хранит пары (ключ)строка -> (значение)строка. Поддерживаемые операции: добавить пару ключ-значение, найти значение по ключу, удалить значение по ключу.
* Реализовать контейнер на основе красно-чёрного дерева, реализующий разработанный интерфейс.
* Создать тест для проверки работы контейнера. Программа должна включать в себя нагрузочное тестирование для исключения ошибок, приводящих к сложности работы O(N*N) при поиске, удалении или добавлении значений.
* Написать генератор входных данных различного объема для этого контейнера.
* Сравнить скорость выполнения операции добавления в контейнер содержимого файла со стандартным контейнером std::map при различных объемах данных. Построить график зависимости времени работы от объёма входных данных и оценить характер зависимости.

2022-11-08 08:28 UTC, closed without merging