Laba3
Dovgalyuk/Algorithms pull request #438
Opened 2022-11-07 07:59 UTC by SaintEfim

2022-11-07 12:33 UTC, Dovgalyuk commented
Тест для очереди должен проходить.

2022-11-08 08:13 UTC, Dovgalyuk requested changes

2022-11-08 08:13 UTC, Dovgalyuk commented on Laba3/Source.cpp
> +    else cout <<"IMPOSSIBLE";
В конце очередь надо удалить.

2022-11-08 08:13 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
>  struct ListItem
В задании кольцевой двусвязный список.

2022-11-09 07:35 UTC, Dovgalyuk commented
Тест для очереди не проходит.

2022-11-14 07:11 UTC, Dovgalyuk requested changes

2022-11-14 07:11 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +    typename List<Data>::Item* _last;
Ни к чему это хранить, можно же получить у списка.

2022-11-14 07:11 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +        Item* item = new Item();
Список кольцевой, prevItem тоже надо установить.

2022-11-16 07:10 UTC, Dovgalyuk requested changes

2022-11-16 07:10 UTC, Dovgalyuk commented on Laba3/Source.cpp
> +    if (b[f] < 1000000) cout << b[f];
Не исправлено.

2022-11-16 07:10 UTC, Dovgalyuk commented on Laba3/Source.cpp
> +    else cout <<"IMPOSSIBLE";
Тоже.

2022-11-17 06:45 UTC, Dovgalyuk requested changes

2022-11-17 06:45 UTC, Dovgalyuk commented on LibraryCPP/Tests/queue.cpp
> +    queue_insert(queue, 1);
Тест менять нельзя, он правильный.

2022-11-17 06:45 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +        Item* item = new Item();
Этот вопрос остался.

2022-11-17 06:45 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +    typename List<Data>::Item* _last;
Этот вопрос остался.

2022-11-18 06:34 UTC, Dovgalyuk requested changes

2022-11-18 06:34 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +        Item* item = new Item();
item->prevItem чему равно?

2022-11-18 06:34 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +        if (newItem->next()) {
В кольцевом списке эта проверка бессмысленна.

2022-11-18 06:34 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +        if (item->next()) {
В кольцевом списке не может быть нулевых указателей, когда он не пустой.

2022-11-21 07:40 UTC, Dovgalyuk commented
Все остальные функции тоже надо проверить, чтобы они корректно реализовывали кольцевой список.

2022-11-21 10:46 UTC, SaintEfim commented
> Все остальные функции тоже надо проверить, чтобы они корректно реализовывали кольцевой список.

Проверил, считаю, что они корректно реализованы для кольцевого списка.

2022-11-22 08:32 UTC, Dovgalyuk commented
Нужно доделать insert, insert_after, erase

2022-11-23 09:34 UTC, Dovgalyuk commented
Проект не собирается.

2022-11-23 18:20 UTC, SaintEfim commented
> Проект не собирается.

А кольцевой список, вообще может пройти тесты ?

2022-11-24 08:39 UTC, Dovgalyuk commented
> > Проект не собирается.
> 
> А кольцевой список, вообще может пройти тесты ? Просто он впадает в бесконечный цикл, когда мы хотим вывести элементы for (ListItem* item = list_first(list); item; item = list_item_next(item)) { std::cout << list_item_data(item) << " "; }

В этом случае можно доработать тест.

2022-11-25 06:43 UTC, Dovgalyuk requested changes

2022-11-25 06:43 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    if (list->head == nullptr || list->length == 0)
Зачем проверять оба условия?

2022-11-25 06:43 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    if (item->next != nullptr)
Откуда там возмётся nullptr?

2022-11-25 06:43 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    return nullptr;
Возвращать нужно следующий элемент.

2022-11-25 06:43 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    ListItem* new_head = list->head->next;
Что будет, если удаляется единственный элемент?

2022-11-25 06:43 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    if (item_next != nullptr)
В кольцевом списке не может быть nullptr.

2022-11-28 07:00 UTC, Dovgalyuk requested changes

2022-11-28 07:00 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    ListItem* new_head = list->head->next;
На это нет ответа.

2022-11-28 07:00 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    if (list_item_data(item_next))
?

2022-11-28 18:34 UTC, SaintEfim commented on LibraryCPP/list.cpp
> +    ListItem* new_head = list->head->next;
В head будет мусор

2022-11-29 07:07 UTC, Dovgalyuk requested changes

2022-11-29 07:07 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    if (list->length)
Это условие всегда истинно, ведь мы вставляем элемент после уже какого-то существующего.

2022-11-29 07:07 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    ListItem* new_head = list->head->next;
Он должен становиться равным null, как после инициализации.

2022-11-30 06:06 UTC, Dovgalyuk commented
Принято. Следующее задание после защиты.

2022-11-30 06:06 UTC, closed without merging