Lab1_Kurdova
Dovgalyuk/Algorithms pull request #446
Opened 2022-11-13 20:28 UTC by julktnn

2022-11-14 07:20 UTC, Dovgalyuk requested changes

2022-11-14 07:20 UTC, Dovgalyuk commented on LibraryCPP/array.cpp
> +    if (array_size(arr) > index)
Что будет, если эти два значения равны?

2022-11-14 07:20 UTC, Dovgalyuk commented on Lab1/l1.cpp
> +void rain(Array* arr, int const Size)
Размер передавать не надо, потому что он уже содержится в массиве.

2022-11-14 08:14 UTC, julktnn commented on LibraryCPP/array.cpp
> +    if (array_size(arr) > index)
Если мы заполним элемент равный размеру массива то будет переполнение, так что так сделать нельзя. Этот индекс находится вне диапазона так как номера элементов начинаются с 0.

2022-11-15 05:54 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library двусвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

Вычислить значение корректного арифметического выражения, использующего операции сложения, вычитания, умножения и деления. Программа должна учитывать приоритет операторов умножения и деления и использовать стек для хранения промежуточных результатов. Операндами в выражении являются неотрицательные целые числа.

Входные данные
```
1+2*3-1
```
Выходные данные
```
6
```

Входные данные
```
1*(2+3)
```
Выходные данные
```
5
```

2022-11-15 05:54 UTC, closed without merging