first lab Nikita Lukin 1095
Dovgalyuk/Algorithms pull request #447
Opened 2022-11-14 09:40 UTC by Mist531

2022-11-15 07:40 UTC, Dovgalyuk requested changes

2022-11-15 07:40 UTC, Dovgalyuk commented on LibraryC/CMakeLists.txt
> +add_library(LibraryC STATIC array.c list.c queue.c stack.c vector.c ../Labs/First/lab1.cpp)
В библиотеки не надо включать файл с лабораторной.

2022-11-15 07:40 UTC, Dovgalyuk commented on Labs/First/lab1.cpp
> +#include "../../LibraryCPP/array.h"
Для указания пути есть директива target_include_directories в CMakeLists.txt

2022-11-15 23:57 UTC, Mist531 commented on Labs/First/lab1.cpp
> +#include "../../LibraryCPP/array.h"
В CMakeList я прописал target_include_directories(First PUBLIC ../LibraryCPP), но почему то при указании #include "array.h" в lab1.cpp, у меня выдаёт ошибку: fatal error: array.h: No such file or directory, поэтому прописал полый путь к файлу
Использую среду разработки CLion

2022-11-16 00:23 UTC, Mist531 commented
Исправил CMake

2022-11-16 07:15 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
* Решить задачу, используя реализованный стек.

Написать программу, работу процессора со стеком. Процессор имеет 4 регистра, обозначенных буквами A, B, C, D. Во входном файле присутствуют операции PUSH и POP. Операция PUSH может иметь в качестве параметра число или регистр. Операция POP в качестве параметра имеет регистр и считывает в него значение с вершины стека. После выполнения последовательности операций программа должна распечатать содержимое регистров.

Входные данные
```
PUSH 1
POP B
```
Выходные данные
```
A = 0
B = 1
C = 0
D = 0
```

Входные данные
```
PUSH 1
PUSH 2
POP B
POP C
PUSH C
POP D
```
Выходные данные
```
A = 0
B = 2
C = 1
D = 1
```

2022-11-16 07:15 UTC, closed without merging