Решение первой Лабораторной работы
Dovgalyuk/Algorithms pull request #453
Opened 2022-11-17 15:44 UTC by KozlikGoat

2022-11-18 06:03 UTC, Dovgalyuk requested changes

2022-11-18 06:03 UTC, Dovgalyuk commented on LibraryCPP/array.cpp
> +    if (index < size && index >= 0) {
size_t не может быть меньше 0

2022-11-18 06:03 UTC, Dovgalyuk commented on labs/lab1.cpp
> +    return (checkedValue[checkedValue.size() - 1] == '5') ? true : false;
Последнюю цифру можно найти, посчитав остаток от деления на 10.

2022-11-22 20:09 UTC, KozlikGoat commented
Исправил.

2022-11-23 09:33 UTC, Dovgalyuk commented
* Реализовать в проекте Library двусвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

Написать программу, работу процессора со стеком. Процессор имеет 4 регистра, обозначенных буквами A, B, C, D. Во входном файле присутствуют операции PUSH и POP. Операция PUSH может иметь в качестве параметра число или регистр. Операция POP в качестве параметра имеет регистр и считывает в него значение с вершины стека. После выполнения последовательности операций программа должна распечатать содержимое регистров.

Входные данные
```
PUSH 1
POP B
```
Выходные данные
```
A = 0
B = 1
C = 0
D = 0
```

Входные данные
```
PUSH 1
PUSH 2
POP B
POP C
PUSH C
POP D
```
Выходные данные
```
A = 0
B = 2
C = 1
D = 1
```

2022-11-23 09:33 UTC, closed without merging