5 Task Галицкий Я.В. гр.1092
Dovgalyuk/Algorithms pull request #455
Opened 2022-11-20 09:54 UTC by IPOMPONI

2022-11-21 07:36 UTC, Dovgalyuk requested changes

2022-11-21 07:36 UTC, Dovgalyuk commented on LibraryCPPTemplate/Tests/associative_array.cpp
> +    for (int i = 0; i < 5; ++i) {
Лучше все поискать. Хотя бы потому что некоторые реализации rand() могут возвращать значения только до 32767.

2022-11-21 07:36 UTC, Dovgalyuk commented on Lab5/5Task.cpp
> +        arr->Insert(to_string(i), to_string(i));
Чтобы исключить влияние преобразований числа в строку, стоит заранее сформировать массив строк, а потом использовать его для добавления в оба контейнера.

2022-11-21 11:47 UTC, IPOMPONI commented on LibraryCPPTemplate/Tests/associative_array.cpp
> +    for (int i = 0; i < 5; ++i) {
Поискал все, что добавил в свой контейнер, все нашлось, тест проходит.

2022-11-21 12:19 UTC, IPOMPONI commented on Lab5/5Task.cpp
> +        arr->Insert(to_string(i), to_string(i));
На 19 строке создал динамический массив строк.

2022-11-22 08:52 UTC, Dovgalyuk commented
https://www.youtube.com/watch?v=-4M5P5af7NE

2022-11-22 16:22 UTC, IPOMPONI commented on LibraryCPPTemplate/associative_array.h
> +template<typename Key, typename Value> class RBAssociativeArray
Вы ничего не пропустили, просто я слишком зациклился на том, что ключ и значение это строка. Теперь и правда шаблон не нужен, убрал его.

2022-11-22 16:23 UTC, IPOMPONI commented on LibraryCPPTemplate/Tests/associative_array.cpp
> +    int count = 100000;
Увеличил

2022-11-23 09:39 UTC, Dovgalyuk commented
Принято.

2022-11-23 09:39 UTC, closed without merging

2022-12-06 09:50 UTC, Dovgalyuk commented
Разработать контейнер, реализующий структуру данных «двоичная куча».
Использовать его для реализации алгоритма Дейкстры.
Сравнить производительность кучи со стандартным контейнером std::priority_queue для разных объемов входных данных.