Lab2 FILIPPOV
Dovgalyuk/Algorithms pull request #456
Opened 2022-11-20 13:58 UTC by COURAGE231

2022-11-21 07:37 UTC, Dovgalyuk commented
Тест для вектора должен проходить.

2022-11-21 08:29 UTC, COURAGE231 commented
Исправлено.

2022-11-22 08:25 UTC, Dovgalyuk requested changes

2022-11-22 08:25 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +int stack_prior(Stack* stack)
Такую функцию надо в основной программе реализовывать, потому что она не имеет отношения к стеку в целом.

2022-11-22 08:25 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +                     if (stack_prior(stack) >= 2)
Здесь не стоит использовать константы. Лучше что-то типа get_priority((expression[i]))
Тогда ещё и код можно будет упростить.

2022-11-22 09:27 UTC, COURAGE231 commented
Исправлено.

2022-11-23 09:30 UTC, Dovgalyuk requested changes

2022-11-23 09:30 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +            case 2:
Веткип 2 и 3 можно объединить, если поменять немного. Если подумать, может быть и с 1 получится.

2022-11-23 09:30 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +            case 1: if (expression[i] == 40)
Вместо 40 надо писать символ в кавычках.

2022-11-23 11:08 UTC, COURAGE231 commented
Строка 42 и 52 очень похожи по смыслу, но в одно их не объединить

2022-11-24 08:38 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +                    if (expression[i] == '(')
Тут явно не тот приоритет. Скобка вполне могла бы попадать в ветку else от условия выше.

2022-11-24 08:38 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +            case 1: case 2: case 3:
Теперь можно написать просто if

2022-11-24 08:38 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +                        while (get_priority(stack_get(stack)) >= get_priority(expression[i]))
А если стек опустеет?

2022-11-24 08:51 UTC, COURAGE231 commented on Lab2/lab2.cpp
> +                        while (get_priority(stack_get(stack)) >= get_priority(expression[i]))
Нужно добавить обработку этого варианта?

2022-11-24 08:56 UTC, COURAGE231 commented on Lab2/lab2.cpp
> +                        while (get_priority(stack_get(stack)) >= get_priority(expression[i]))
В таком случае функция get_priority выведет 0 и цикл закончится.

2022-11-24 08:58 UTC, COURAGE231 commented
Исправлено.

2022-11-24 10:00 UTC, COURAGE231 commented
А можно делать несколько лабораторных параллельно? Чтобы успеть всё в срок.

2022-11-25 06:34 UTC, Dovgalyuk requested changes

2022-11-25 06:34 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +        return false;
Надо возвращать хотя бы Data(), потому что этот тип задан отдельно и может быть несовместим со значением false.

2022-11-25 06:34 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +}
Тут должен быть return, если ни одно из условий не сработало.

2022-11-25 06:34 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +            if (get_priority(expression[i]) == 1 || 2 || 3)
В том виде, в котором это записано, это условие всегда истинно.

2022-11-25 06:34 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +                    i++;
А если две открывающиеся скобки подряд?

2022-11-25 06:35 UTC, Dovgalyuk commented
> А можно делать несколько лабораторных параллельно? Чтобы успеть всё в срок.

Нет.

2022-11-25 12:00 UTC, COURAGE231 commented
Исправлено. Добавил обработку случая, где больше одной открывающей скобки. Сделал return 0 для пустого стека.  Заменил false на Data().  Изменил условие, на вхождение приоритета в диапазон.

2022-11-28 06:49 UTC, Dovgalyuk requested changes

2022-11-28 06:49 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +                if (expression[i] == '(')
Тут можно сразу написать while.

2022-11-28 06:49 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +                    if (get_priority(stack_get(stack)) >= get_priority(expression[i]))
Если убрать if, то можно оставить просто одну эту ветку, а else убрать вообще.

2022-11-28 06:49 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +                        i++;
i++ делается всегда, поэтому его стоит поместить в заголовок цикла.

2022-11-28 07:41 UTC, COURAGE231 commented on Lab2/lab2.cpp
> +                if (expression[i] == '(')
Не понимаю, где вы хотите написать while.

2022-11-28 07:56 UTC, COURAGE231 commented on Lab2/lab2.cpp
> +                        i++;
Его нельзя добавить в заголовок. Здесь он как break в кейсах, не даёт перейти к другому if. Если i++ добавить в заголовок, то некоторые буквы и операции будут пропадать, а выражения с скобками уйдут в бесконечный цикл.

2022-11-28 08:03 UTC, COURAGE231 commented on Lab2/lab2.cpp
> +                if (expression[i] == '(')
Прописал while.

2022-11-29 05:40 UTC, Dovgalyuk commented
Некоторая путаница осталась, на защите обсудим.

* Реализовать в проекте Library кольцевой двусвязный список (модуль list) и очередь на основе этого списка (модуль queue).
* Решить задачу, используя реализованную очередь.

Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной – «#» или пустым пространством – «.». Стартовая позиция обозначается как X, финишная как Y. Написать программу, находящую минимальный путь от стартовой до финишной клетки, если это возможно. За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди. Если решения нет, вывести IMPOSSIBLE.

Входные данные
```
######
#...X#
#.####
#...Y#
######
```
Выходные данные
```
######
#xxxX#
#x####
#xxxY#
######
```

Входные данные
```
######
#...X#
######
#...Y#
######
```
Выходные данные
```
IMPOSSIBLE
```

2022-11-29 05:40 UTC, closed without merging