Lab 4
Dovgalyuk/Algorithms pull request #459
Opened 2022-11-23 23:00 UTC by Riba4koff

2022-11-23 23:01 UTC, Riba4koff commented
Можно использовать сторонние библиотеки? Допустим map, для хранения веса ребра?

2022-11-24 08:45 UTC, Dovgalyuk commented
Нет, в реализации графа должны использоваться только свои библиотеки.

2022-11-27 17:33 UTC, Riba4koff commented
Чет всё очень плохо

2022-11-27 18:51 UTC, Riba4koff commented
Всё починил

2022-11-28 08:43 UTC, Dovgalyuk requested changes

2022-11-28 08:43 UTC, Dovgalyuk commented on Labs/Algorithms_lab_4.cpp
> +        int tempData;
Если это всё равно int, то нет никакого смысла делать все эти функции шаблонными. Или надо их аккуратно исправить.

2022-11-28 08:43 UTC, Dovgalyuk commented on Labs/Algorithms_lab_4.cpp
> +    showTheShortestPath(size_graph, shortest_path, graph);
В задании сказано, что надо выбрать самый длинный из кратчайших путей.

2022-11-28 08:43 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +	Graph(Data data, Weight weight) {
Почему второй параметр weight, когда это должен быть size?

2022-11-28 08:43 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +	~Graph() { vertexes.list_delete(&vertexes); }
Для этого в list есть (должен быть) деструктор.
А вот сами вершины удалять нужно отдельно.

2022-11-28 08:43 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +				delete item;
Не нужно вне списка вызывать delete для его внутренней структуры.

2022-11-28 08:43 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +		List<Edge*> edges;
Edge маленькая структура, можно сделать просто List<Edge>

2022-11-28 08:59 UTC, Riba4koff commented on LibraryCPPTemplate/graph.h
> +		List<Edge*> edges;
Не совсем понял

2022-11-28 10:12 UTC, Riba4koff commented on Labs/Algorithms_lab_4.cpp
> +    showTheShortestPath(size_graph, shortest_path, graph);
А нужно именно алгоритмом найти самый длинный из кратчайших или можно найти все и уже выборкой вывести?

2022-11-29 01:34 UTC, Riba4koff commented
Всё,, что понял, попытался исправить. Насчёт поиска самого длинного из кратчайших не уверен

2022-11-29 07:12 UTC, Dovgalyuk requested changes

2022-11-29 07:12 UTC, Dovgalyuk commented on Labs/Algorithms_lab_4.cpp
> +    int data = -1, index_i = 0, index_j = 0;
data опять int.

2022-11-29 07:15 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +				delete item;
Вот это не заметил.

2022-11-29 07:41 UTC, Riba4koff commented on LibraryCPPTemplate/graph.h
> +				delete item;
А я просто её удалил, я ей в лабе не пользовался. У меня у структуры vertex есть метод remove_edge

2022-11-29 07:55 UTC, Riba4koff commented on LibraryCPPTemplate/graph.h
> +		List<Edge*> edges;
List<edge>?

2022-11-29 07:57 UTC, Riba4koff commented on LibraryCPPTemplate/graph.h
> +		List<Edge*> edges;
Я понял гитхаб считает ребро в скобочках как тег, скоро исправлю

2022-11-29 08:10 UTC, Riba4koff commented on Labs/Algorithms_lab_4.cpp
> +    int data = -1, index_i = 0, index_j = 0;
Просто эти функции не используются без template, а я хотел сократить код в main`e, просто тогда сделаю решение без функций именно под Int

2022-11-29 08:45 UTC, Riba4koff commented on LibraryCPPTemplate/graph.h
> +		List<Edge*> edges;
Исправил

2022-11-29 08:46 UTC, Riba4koff commented on Labs/Algorithms_lab_4.cpp
> +    int data = -1, index_i = 0, index_j = 0;
Сделал использование графа под тип int

2022-11-29 10:25 UTC, Riba4koff commented on LibraryCPPTemplate/graph.h
> +		List<Edge*> edges;
Не исправил, если использовать просто List<*Edge*> (звездочки сочтём ничем), то у меня при вызове функции set_weight, this->weight равен какому-то мусору, и если я присвою новое значение, то ничего не произойдет. Еще я посмотрел у других ребят реализацию, они тоже используют List<Edge*>. Может стоит всё таки использовать указатели? Писав код, я не сильно и возился с ними

2022-11-29 10:37 UTC, Riba4koff commented on LibraryCPPTemplate/graph.h
> +		List<Edge*> edges;
Есть предположение, что он присваивает значение не той ячейке в памяти

2022-11-29 11:18 UTC, Riba4koff commented on LibraryCPPTemplate/graph.h
> +		List<Edge*> edges;
Я написал тот же граф, но без некоторых методов, с вершиной, которая хранит List<*Edges*>, в ней тоже не устанавливается вес. Но если я использую List<Edge*>, то всё отлично присваивается
![image](https://user-images.githubusercontent.com/90069034/204515618-db4a2e5d-e68b-4b5d-915f-caed5a4b4282.png)

2022-11-29 11:20 UTC, Riba4koff commented on LibraryCPPTemplate/graph.h
> +		List<Edge*> edges;
Тот же код, но List<*Edges*>
![image](https://user-images.githubusercontent.com/90069034/204516029-def5eb3f-8836-4eeb-9442-ec553bf22979.png)
![image](https://user-images.githubusercontent.com/90069034/204516069-aed8b246-8ecb-4cc0-8cf6-67ef15179afb.png)

2022-11-29 11:21 UTC, Riba4koff commented on LibraryCPPTemplate/graph.h
> +		List<Edge*> edges;
Если возвращать указатель на элемент (вершину в списке рёбер), происходит то же самое

2022-11-29 11:25 UTC, Riba4koff commented on LibraryCPPTemplate/graph.h
> +		List<Edge*> edges;
Либо я чего-то не понимаю

2022-11-30 06:12 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +		Edge* get_edge(Vertex* vertex) {
Просто если используется ```List<Edge>```, то надо возвращать ссылку на Edge, а не копию значения структуры.

2022-12-02 07:15 UTC, Dovgalyuk requested changes

2022-12-02 07:15 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +			this->edges.push_back(*new Edge(vertex, weight));
тут не нужен new. Просто push_bask(Edge(vertex, weight))

2022-12-02 07:15 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +    Data &operator[](int index) {
У списка не должно быть индексированного доступа.

2022-12-03 01:30 UTC, Riba4koff commented on LibraryCPPTemplate/graph.h
> +			this->edges.push_back(*new Edge(vertex, weight));
Исправил

2022-12-03 01:30 UTC, Riba4koff commented on LibraryCPPTemplate/list.h
> +    Data &operator[](int index) {
Исправил

2022-12-05 10:51 UTC, Dovgalyuk requested changes

2022-12-05 10:51 UTC, Dovgalyuk commented on LibraryCPPTemplate/Tests/graph.cpp
> +	catch (const char* e)
Исключение в тесте тоже ошибка.
Надо return -1 тогда написать.

2022-12-05 11:18 UTC, Riba4koff commented
исправил

2022-12-06 05:41 UTC, Dovgalyuk commented
Надо или убрать обработку исключения, либо там возвращать -1.

2022-12-06 06:22 UTC, Riba4koff commented
А, его там вообще не должно быть, просто когда тест менял выдавал исключение, сейчас оно там не нужно. Исправил

2022-12-07 05:18 UTC, Dovgalyuk commented
Принято.

* Разработать интерфейс (набор функций) для ассоциативного массива, который хранит пары (ключ)строка -> (значение)строка. Поддерживаемые операции: добавить пару ключ-значение, найти значение по ключу, удалить значение по ключу.
* Реализовать контейнер на основе хэш-таблицы с открытой адресацией, реализующий разработанный интерфейс. Таблица должна поддерживать расширение при большой доле заполненных ячеек.
* Создать тест для проверки работы контейнера. Программа должна включать в себя нагрузочное тестирование для исключения ошибок, приводящих к сложности работы O(N*N) при поиске, удалении или добавлении значений.
* Написать генератор входных данных различного объема для этого контейнера.
* Сравнить скорость выполнения операции добавления в контейнер содержимого файла со стандартным контейнером std::unordered_map при различных объемах данных. Построить график зависимости времени работы от объёма входных данных и оценить характер зависимости.

2022-12-07 05:18 UTC, closed without merging