Lab3 Filippov
Dovgalyuk/Algorithms pull request #469
Opened 2022-11-29 21:24 UTC by COURAGE231

Файл лабораторной и файл очереди queue я ещё не загрузил, поскольку есть вопрос к тесту листа. В коде теста проверяется не кольцевой лист, поэтому вывод будет бесконечным. Я, вроде как, исправил файл, однако думаю, что у вас будет несколько вопросов к моей реализации листа. Поэтому хочу начать с него.

2022-11-30 06:17 UTC, Dovgalyuk commented
Тест немного исправить можно, чтобы подходил.
Во всех случаях, кроме пустого списка, в кольцевом списке не может быть нулевых указателей. Поэтому проверки указателей там не нужны.

2022-12-01 20:13 UTC, COURAGE231 commented
Не могу понять, почему вызывается исключение в тесте очереди.

2022-12-02 07:22 UTC, Dovgalyuk commented
Можно запустить этот тест локально в отладчике и посмотреть, где именно падает.
Там же можно увидеть стек вызовов функций, чтобы узнать, откуда текущая функция вызывалась и с какими параметрами.

2022-12-03 15:52 UTC, COURAGE231 commented
Всё равно не понимаю, в чем проблема. Я уже сделал лабораторную, которая работает, все тесты запускал у себя локально. Но никаких вылетов не было. Подскажите, что делать, пожалуйста.

2022-12-05 11:19 UTC, COURAGE231 commented
Проблема решена. Нашёл утечку памяти, обработал случай удаления последнего элемента листа. Теперь всё работает как надо.

2022-12-06 05:34 UTC, Dovgalyuk requested changes

2022-12-06 05:34 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
>  }
Функция обязательно должна что-то возвращать.

2022-12-06 05:34 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    return item->prev;
А почему next возвращает prev и наоборот?

2022-12-06 18:38 UTC, COURAGE231 commented
У меня всё прекрасно работает, и тесты, и лабораторная. Память в листе и списке выделяется и удаляется полностью, с этим всё хорошо. Не могу никак по другому отладить код, не знаю почему вызывает ошибку тест.

2022-12-06 18:39 UTC, COURAGE231 commented on LibraryCPP/list.cpp
> +    return item->prev;
Всё поменял.

2022-12-07 05:31 UTC, Dovgalyuk requested changes

2022-12-07 05:31 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    if (item == list->first)
Этот случай ничем не отличается от последнего.

2022-12-07 05:31 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    if (item == list->last)
Здесь нужно будет обновить list->last.
Вообще list->last не нужен, потому что у нас кольцевой список. Стоит его вообще убрать.

2022-12-07 11:11 UTC, COURAGE231 commented
Всё... Исправил. А можно как то через Visual Studio улавливать эти ошибки? Он видимо сглаживает эти углы и компилирует код. А здесь нет.  Приходилось удалять строчки теста, чтобы понять, где программа падает.

2022-12-08 08:14 UTC, Dovgalyuk requested changes

2022-12-08 08:14 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +            return item;
item указывает на несуществующий элемент

2022-12-08 08:14 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +                erase = item;
в обеих ветках erase == item

2022-12-08 08:14 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +            return item;
И опять возвращается указатель на несуществующий элемент.

2022-12-08 08:15 UTC, Dovgalyuk commented
> Всё... Исправил. А можно как то через Visual Studio улавливать эти ошибки? Он видимо сглаживает эти углы и компилирует код. А здесь нет. Приходилось удалять строчки теста, чтобы понять, где программа падает.

Тестовые приложения можно так же собрать и запускать локально.

2022-12-08 18:28 UTC, COURAGE231 commented
Исправил

2022-12-09 07:48 UTC, Dovgalyuk requested changes

2022-12-09 07:48 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        return newItem;
item->next->prev не меняется

2022-12-09 07:48 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +            return item->next;
Это поле не существует, мы уже удалили item.

2022-12-09 08:06 UTC, COURAGE231 commented on LibraryCPP/list.cpp
> +        return newItem;
newItem->prev = item 
а newItem = item->next
значит item->next->prev = newItem

2022-12-09 08:11 UTC, COURAGE231 commented on LibraryCPP/list.cpp
> +        return newItem;
item->next это newItem
newItem->prev = item;
значит 
item->next->prev = item

2022-12-09 08:21 UTC, COURAGE231 commented
Исправил.

2022-12-12 08:07 UTC, Dovgalyuk commented
Принято.

2022-12-12 08:07 UTC, closed without merging

2022-12-13 10:50 UTC, Dovgalyuk commented
* Разработать программный интерфейс модуля (заголовки функций) для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
* Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
* Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List той же библиотеки.
* Разработать и добавить в проект Library программу, тестирующую работу библиотеки для графа.
* Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать для него все длины кратчайших путей алгоритмом Флойда.