Решение 2 лабораторной
Dovgalyuk/Algorithms pull request #471
Opened 2022-11-30 21:05 UTC by igor81258

2022-12-02 07:18 UTC, Dovgalyuk requested changes

2022-12-02 07:18 UTC, Dovgalyuk commented on Labs/lab2.cpp
> +    Stack* stack = stack_create();
Созданный стек не удаляется.

2022-12-02 07:18 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +    return stack_empty(stack) ? throw "Empty stack error"
?: так использовать не нужно, лучше написать if.

2022-12-06 21:20 UTC, igor81258 commented on Labs/lab2.cpp
> +    Stack* stack = stack_create();
Исправил

2022-12-06 21:20 UTC, igor81258 commented on LibraryCPP/stack.cpp
> +    return stack_empty(stack) ? throw "Empty stack error"
Исправил

2022-12-07 05:38 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library кольцевой двусвязный список (модуль list) и очередь на основе этого списка (модуль queue).
* Решить задачу, используя реализованную очередь.

Задан неориентированный граф. Написать программу для определения длины кратчайшего пути от одной вершины для другой. В первой строке входного файла записано количество вершин, номер стартовой вершины и номер финишной. В последующих строках идут описания ребер, заданные номерами вершин, которые они соединяют. В выходной файл выводится длина кратчайшего пути. Если решения не существует – выводится IMPOSSIBLE. Программа должна использовать поиск в ширину на основе очереди.

Входные данные
```
4 1 2
1 3
1 4
3 2
4 3
```
Выходные данные
```
2
```

2022-12-07 05:38 UTC, closed without merging