lab1
Dovgalyuk/Algorithms pull request #474
Opened 2022-12-05 11:05 UTC by nikita-rain

2022-12-06 05:32 UTC, Dovgalyuk requested changes

2022-12-06 05:32 UTC, Dovgalyuk commented on Lab1/lab1.cpp
> +	Array* arr = array_create(size);
В конце массив нужно удалить.

2022-12-06 07:01 UTC, nikita-rain commented on Lab1/lab1.cpp
> +	Array* arr = array_create(size);
Исправил

2022-12-07 05:19 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

Преобразовать корректное арифметическое выражение, использующее операции сложения, вычитания, умножения и деления, в арифметическое выражение в обратной польской записи. Программа должна учитывать приоритет операторов умножения и деления и использовать стек. Операндами в выражении являются однобуквенные переменные.

Входные данные
```
A+B*C+D
```
Выходные данные
```
ABC*+D+
```

Входные данные
```
A*B+C
```
Выходные данные
```
AB*C+
```

Входные данные
```
A+B*(C+D)
```
Выходные данные
```
ABCD+*+
```

2022-12-07 05:19 UTC, closed without merging