Lab 4 solve
Dovgalyuk/Algorithms pull request #475
Opened 2022-12-05 11:12 UTC by DashkovskiyNikita

2022-12-06 05:56 UTC, Dovgalyuk requested changes

2022-12-06 05:56 UTC, Dovgalyuk commented on Labs/lab4.cpp
> +			for (auto k = vertex->begin(); k.item != 0; ++k) {
Вот этот цикл нужно исключить.
Для каждой вершины стоит хранить "минимальное расстояние до дерева".
Обновляется оно при добавлении новой вершины в остовное дерево.

2022-12-06 05:56 UTC, Dovgalyuk commented on LibraryCPPTemplate/Tests/graph.cpp
> +	for (auto i = from->begin(); i.item != 0; ++i) {
Можно ещё проверить количество сделанных итераций (или что-то другое придумать для проверки итератора).

2022-12-08 21:28 UTC, DashkovskiyNikita commented on Labs/lab4.cpp
> +			for (auto k = vertex->begin(); k.item != 0; ++k) {
А как его исключить, если мне нужно по всем ребрам пройтись?

2022-12-09 10:48 UTC, DashkovskiyNikita commented
Исправил

2022-12-12 08:15 UTC, Dovgalyuk commented on Labs/lab4.cpp
> +		auto vertex = graph.get_vertex(i);
Так надо же ближайшую выбрать, руководствуясь массивом prims_tree.

2022-12-12 14:39 UTC, DashkovskiyNikita commented on Labs/lab4.cpp
> +		auto vertex = graph.get_vertex(i);
prims_tree это массив состоящий из ребер. Индекс ребра в массиве prims_tree указывает на вершину в которую она ведет. На каждой итерации я беру вершину оригинального дерева и прохожусь по всем ее ребрам. Затем беру ребро из массива prims_tree и сравниваю его вес с весом ребра оригинального массива. Если вес меньше, то записываю его в ребро и так же присваиваю полю vertex вершину из которой выходит ребро. И так мы проверяем все вершины оригинального дерева и находим дерево с минимальной суммой весов ребер.

2022-12-13 10:08 UTC, Dovgalyuk requested changes

2022-12-13 10:08 UTC, Dovgalyuk commented on Labs/lab4.cpp
> +		auto vertex = graph.get_vertex(i);
Алгоритм Прима вершины берёт не все по порядку, а на каждом шаге находит ближайшую к уже построенному поддереву.

2022-12-14 14:48 UTC, DashkovskiyNikita commented
Исправил

2022-12-15 06:41 UTC, Dovgalyuk commented on Labs/lab4.cpp
> +			for (auto k = vertex->begin(); k.item != 0; ++k) {
Теперь возвращаемся к тому, что нужно хранить минимальное расстояние для каждой вершины, а не перебирать все рёбра каждый раз.

2022-12-15 19:21 UTC, DashkovskiyNikita commented
Исправил

2022-12-16 07:53 UTC, Dovgalyuk commented
Нет, всё ещё не исправлено.

2022-12-18 21:54 UTC, DashkovskiyNikita commented
Исправил

2022-12-19 07:50 UTC, Dovgalyuk commented on Labs/lab4.cpp
> +		visited[near_ver_pos] = true;
Если граф не связный, то в какой-то момент вершина не будет найдена.

2022-12-19 22:22 UTC, DashkovskiyNikita commented on Labs/lab4.cpp
> +		visited[near_ver_pos] = true;
Я думал под входным деревом подразумевается связный граф. Если граф не связный, то тогда не возможно найти минимальное остовное дерево?

2022-12-20 08:30 UTC, Dovgalyuk commented on Labs/lab4.cpp
> +		visited[near_ver_pos] = true;
Либо написать, что это невозможно.
Либо найти деревья для всех подграфов.

2022-12-20 19:02 UTC, DashkovskiyNikita commented
Исправил

2022-12-21 08:34 UTC, Dovgalyuk commented
* Разработать интерфейс (набор функций) для контейнера для хранения множества значений строк с возможностью быстрого поиска. Поддерживаемые операции: добавить значение, найти значение, удалить значение.
* Реализовать контейнер на основе красно-чёрного дерева, реализующий разработанный интерфейс.
* Создать тест для проверки работы контейнера. Программа должна включать в себя нагрузочное тестирование для исключения ошибок, приводящих к сложности работы O(N*N) при поиске, удалении или добавлении значений.
* Написать генератор входных данных различного объема для этого контейнера.
* Сравнить скорость выполнения операции добавления в контейнер содержимого файла со стандартным контейнером std::set при различных объемах данных. Построить график зависимости времени работы от объёма входных данных и оценить характер зависимости.

2022-12-21 08:34 UTC, closed without merging