Lab2
Dovgalyuk/Algorithms pull request #477
Opened 2022-12-05 21:05 UTC by Terit21

2022-12-06 05:39 UTC, Dovgalyuk commented
Тест для списка должен проходить (см вкладку Checks)

2022-12-06 14:24 UTC, Terit21 commented
А может быть такое, что у меня тест не  проходит из-за erase? У меня односвязный список, поэтому я его не реализовывал

2022-12-07 05:26 UTC, Dovgalyuk commented
Стоит попробовать запустить тест локально и проверить это.
erase можно либо сделать через цикл, либо скорректировать тест.

2022-12-08 08:49 UTC, Dovgalyuk requested changes

2022-12-08 08:49 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +    stack_delete(stack);
Тест: ```[<]>```

2022-12-08 08:49 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
>  }
Если условие не выполняется, функция всё равно должна что-то возвращать.

2022-12-08 08:49 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +    delete list_first(stack->list);
Нельзя напрямую удалять элементы списка, нужно пользоваться его функциями для этого.

2022-12-09 07:45 UTC, Dovgalyuk requested changes

2022-12-09 07:45 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +    stack_delete(stack);
Всё ещё не работает такой тест.

2022-12-12 08:32 UTC, Dovgalyuk commented
Я не понимаю, про какой segfault речь. Для теста, который я предлагаю проверить, ответ должен быть NO, а такая программа выдаст ответ YES.

2022-12-13 10:34 UTC, Dovgalyuk requested changes

2022-12-13 10:34 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +        stack_push(stack, a[i]);
Здесь не нужно использовать стек. Он нужен только для проверки скобок.

2022-12-14 07:02 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +}
Вот ещё один пример: ```([]```

2022-12-15 06:34 UTC, Dovgalyuk commented
* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.

Во входном файле заданы два числа a, b и последовательность целых чисел. За один просмотр файла с этой последовательностью переписать ее элементы в выходной файл так, чтобы сначала шли числа меньшие заданного числа a, затем все числа из отрезка [a, b], а затем – все остальные. Взаимный порядок чисел в каждой из групп должен быть сохранен. Входной файл содержит числа a, b и последовательность, которую нужно переписать. При реализации программы использовать очередь.

Входные данные
```
1 2
0 -1 1 5 6 2 1 7 -2
```
Выходные данные
```
0 -1 -2 1 2 1 5 6 7
```

2022-12-15 06:34 UTC, closed without merging