second lab
Dovgalyuk/Algorithms pull request #480
Opened 2022-12-07 16:42 UTC by Mist531

2022-12-08 08:19 UTC, Dovgalyuk requested changes

2022-12-08 08:19 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +    stack_empty(stack) ? throw "ERROR: Stack empty" :
Так писать не стоит. Лучше использовать обычный if.

2022-12-08 08:59 UTC, Mist531 commented on LibraryCPP/stack.cpp
> +    stack_empty(stack) ? throw "ERROR: Stack empty" :
Поправил.

2022-12-09 07:33 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и очередь на основе этого списка (модуль queue).
* Решить задачу, используя реализованную очередь.

Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной - «#» или пустым пространством – «.».
Стартовая позиция обозначается как X, финишные позиции цифрами от 0 до 9.
Написать программу, которая выводит цифру, ближайшую к стартовой позиции.
За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди.

Входные данные
```
######
#...X#
#.#.##
#3.4.#
######
```
Выходные данные
```
4
```

2022-12-09 07:33 UTC, closed without merging