lab 2
Dovgalyuk/Algorithms pull request #481
Opened 2022-12-07 16:44 UTC by jscelle

2022-12-08 08:33 UTC, Dovgalyuk requested changes

2022-12-08 08:33 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    if (list->firstItem != nullptr)
Проверка ничего не даёт, можно просто присвоить поле nextItem.

2022-12-08 08:33 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        return temp;
Нужно ли скорректировать lastItem?

2022-12-09 07:42 UTC, Dovgalyuk requested changes

2022-12-09 07:42 UTC, Dovgalyuk commented on Solutions/lab2.cpp
> +    if (currentNumber != 0) {
Только это (и такое же условие выше) не сработает, если на входе был 0.

2022-12-09 07:42 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    list->firstItem = newItem;
Вопрос остался.

2022-12-09 07:42 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
>  ListItem *list_erase(List *list, ListItem *item)
Тоже вопрос остался.

2022-12-09 07:42 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +    list_erase(stack->list, list_first(stack->list));
Теперь же есть list_erase_first

2022-12-15 06:36 UTC, Dovgalyuk requested changes

2022-12-15 06:36 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +}
Не починилось.

2022-12-16 07:11 UTC, Dovgalyuk commented
Последний коммит без изменений.

2022-12-18 16:39 UTC, jscelle commented
> Последний коммит без изменений.

У меня list_erase_next уже в прошлом был изменен, там учтен lastItem, в репозитории последняя версия

2022-12-19 06:56 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +}
Всегда сработает первое условие и функция завершится, не доходя до второго.

2022-12-20 07:55 UTC, Dovgalyuk commented
Там ошибка, см. мой комментарий в коде.

2022-12-21 06:55 UTC, Dovgalyuk commented
* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.

Задан неориентированный граф. Написать программу для определения кратчайшего пути от одной вершины для другой. В первой строке входного файла записано количество вершин, номер стартовой вершины и номер финишной. В последующих строках идут описания ребер, заданные номерами вершин, которые они соединяют. В выходной файл выводится последовательность вершин в кратчайшем пути. Если решения не существует – выводится IMPOSSIBLE. Программа должна использовать поиск в ширину на основе очереди.

Входные данные
```
4 1 2
1 3
1 4
3 2
4 3
```
Выходные данные
```
1 3 2
```

2022-12-21 06:55 UTC, closed without merging