6 Task Галицкий Я.В. гр.1092
Dovgalyuk/Algorithms pull request #487
Opened 2022-12-11 09:32 UTC by IPOMPONI

2022-12-12 08:42 UTC, Dovgalyuk requested changes

2022-12-12 08:42 UTC, Dovgalyuk commented on LibraryCPP/BinaryHeap.h
> +    void sift_up(int v)
Обе функции лучше переписать через while вместо рекурсии.

2022-12-12 08:42 UTC, Dovgalyuk commented on Lab6/6Task.cpp
> +				BinH->Insert(to);
Это же разнородные данные в одном контейнере. Они разбегутся там как попало.

2022-12-12 12:24 UTC, IPOMPONI commented on LibraryCPP/BinaryHeap.h
> +        return GetSize() == false;
Исправил

2022-12-13 09:32 UTC, Dovgalyuk requested changes

2022-12-13 09:32 UTC, Dovgalyuk commented on Lab6/6Task.cpp
> +	vector < vector < pair<int, int> > > g(n);
Если g - это граф, то где он заполняется?

2022-12-13 09:32 UTC, Dovgalyuk commented on Lab6/6Task.cpp
> +		int v = q.top().second, cur_d = q.top().first;
Стоит как-то это протестировать. Хранится отрицательное значение, а потом оно сравнивается с обычными положительными.

2022-12-13 13:54 UTC, IPOMPONI commented on Lab6/6Task.cpp
> +		int v = q.top().second, cur_d = q.top().first;
Проблема в том, что из priority_queue нельзя удалять произвольные элементы. Поэтому я просто не удаляю старые пары из очереди. Как итог: в очереди могут находится несколько пар для одной вершины, но с разными расстояниями. Если .first = d[v], то это наша пара, остальные фиктивные. Поэтому я на каждой итерации их сравниваю и ищу нужную.
Вторая проблема это то, что в priority_queue упорядочивание происходит по убыванию. Поэтому в .first помещаю расстояния со знаком минус. Как итог: в корне будут элементы с наименьшим расстоянием.
Выглядит странно, но у priority_queue много неудобств. Свой контейнер я старался сделать с тем же функционалом для чистоты тестов.

2022-12-14 07:23 UTC, Dovgalyuk commented
Судя по графику, время работы алгоритма Дейкстры не зависит от числа вершин. Значит, плохо генерируется граф. Или всё совсем не работает.

2022-12-14 13:19 UTC, IPOMPONI commented
Нашел ошибочку, график обновил.

2022-12-15 06:53 UTC, Dovgalyuk commented
А где скрипт сборки для этого проекта?

2022-12-15 09:43 UTC, IPOMPONI commented
А, исправил.

2022-12-15 09:49 UTC, IPOMPONI commented
Перепроверил все CMakeLists и вроде больше ничего не забыл в них.

2022-12-16 08:09 UTC, Dovgalyuk commented
Ну вот появился warning, который указывает на ошибку.

2022-12-16 10:36 UTC, IPOMPONI commented
Исправил его. На данный момент никаких "warning", связанных с Lab6 не наблюдаю (надеюсь, что зрение не подводит). Вроде как все собирается и тесты проходятся.

2022-12-19 08:12 UTC, Dovgalyuk commented on LibraryCPP/BinaryHeap.h
> +            return tree[0];
Только вот нулевой элемент не существует для массива размером 0.

2022-12-19 12:22 UTC, IPOMPONI commented on LibraryCPP/BinaryHeap.h
> +            return tree[0];
Ну вроде как исправил в более правильной форме.

2022-12-20 08:40 UTC, Dovgalyuk commented on LibraryCPP/BinaryHeap.h
> +            return code;
Можно же просто return T(). Или уж исключение выбрасывать, а не на консоль выводить сообщение.

2022-12-20 09:11 UTC, IPOMPONI commented
Воспользовался return T();

2022-12-21 06:46 UTC, Dovgalyuk commented
Принято.

2022-12-21 06:46 UTC, closed without merging