Lab4 Ovchinnikov
Dovgalyuk/Algorithms pull request #491
Opened 2022-12-12 19:21 UTC by Merk9ayt

2022-12-13 10:32 UTC, Dovgalyuk requested changes

2022-12-13 10:32 UTC, Dovgalyuk commented on CMakeLists.txt
> +add_subdirectory(Lab1)
Последнюю программу тоже надо включить в сборку.

2022-12-13 10:32 UTC, Dovgalyuk commented on Lab4/Lab4_dov.cpp
> +                if (graph->contains_edge_between_vertices(vertex->data.index, i))
Вот тут нужно использовать итератор.

2022-12-13 10:32 UTC, Dovgalyuk commented on LibraryCPPTemplate/d_graph.h
> +        Vertex* second;
Эти указатели хранить не надо, потому что они однозначно определяются по матрице смежности.

2022-12-13 12:05 UTC, Merk9ayt commented on CMakeLists.txt
> +add_subdirectory(Lab1)
Поправил

2022-12-13 13:17 UTC, Merk9ayt commented on Lab4/Lab4_dov.cpp
> +                if (graph->contains_edge_between_vertices(vertex->data.index, i))
Поправил, вроде

2022-12-13 13:17 UTC, Merk9ayt commented on LibraryCPPTemplate/d_graph.h
> +        Vertex* second;
Поправил

2022-12-14 07:10 UTC, Dovgalyuk commented
Проект должен успешно собираться на сервере.

2022-12-14 08:06 UTC, Merk9ayt commented
Странно, у меня собирался

2022-12-15 06:46 UTC, Dovgalyuk commented on CMakeLists.txt
> +add_subdirectory(Lab1)
И где же она?

2022-12-15 09:04 UTC, Merk9ayt commented on CMakeLists.txt
> +add_subdirectory(Lab1)
Добавил, но я не понимаю почему проект не собирается на сервере

2022-12-15 13:41 UTC, Merk9ayt commented
Проект собран успешно

2022-12-16 07:42 UTC, Dovgalyuk requested changes

2022-12-16 07:42 UTC, Dovgalyuk commented on Lab4/Lab4dov.cpp
> +    DGraph<Data>* graph = new DGraph<Data>(0, Data(-1));
Ни к чему создавать эту переменную в динамической памяти.

2022-12-16 07:42 UTC, Dovgalyuk commented on Lab4/Lab4dov.cpp
> +    int index = -1;
Надо как-то всё поменять, чтобы не пришлось в каждой вершине дополнительно хранить её номер.

2022-12-16 07:42 UTC, Dovgalyuk commented on Lab4/Lab4dov.cpp
> +    bool is_empty = false;
Можно обойтись без этой переменной, проверяя min_cost_vertex.

2022-12-16 07:42 UTC, Dovgalyuk commented on Lab4/Lab4dov.cpp
> +    cout << graph->get_vertex(SECOND_VERTEX)->data.cost;
Надо искать путь, а не длину пути.

2022-12-16 07:42 UTC, Dovgalyuk commented on LibraryCPPTemplate/dgraph.h
> +        Vertex* vertex;
В случае матрицы смежности не нужно хранить вершину, потому что она однозначно определяется.

2022-12-16 07:42 UTC, Dovgalyuk commented on LibraryCPPTemplate/dgraph.h
> +    Vector<Edge*>* matrix;
Ребро - это только метка, поэтому нет смысла хранить указатели, можно сразу хранить значения.

2022-12-18 17:10 UTC, Merk9ayt commented on Lab4/Lab4dov.cpp
> +    DGraph<Data>* graph = new DGraph<Data>(0, Data(-1));
Здесь я пытался использовать оператор new для инициализации ненулевого указателя, коряво. Просто не чего другого на ум не приходит

2022-12-18 17:11 UTC, Merk9ayt commented on Lab4/Lab4dov.cpp
> +    int index = -1;
Если я не буду хранить номер вершины тогда скорее всего потеряется путь

2022-12-18 17:11 UTC, Merk9ayt commented on Lab4/Lab4dov.cpp
> +    bool is_empty = false;
Поправил

2022-12-18 17:12 UTC, Merk9ayt commented on Lab4/Lab4dov.cpp
> +    cout << graph->get_vertex(SECOND_VERTEX)->data.cost;
Поправил

2022-12-18 17:12 UTC, Merk9ayt commented on LibraryCPPTemplate/dgraph.h
> +        Vertex* vertex;
Поправил

2022-12-18 17:13 UTC, Merk9ayt commented on LibraryCPPTemplate/dgraph.h
> +    Vector<Edge*>* matrix;
Не особо понял о чём вы

2022-12-18 20:04 UTC, Merk9ayt commented on LibraryCPPTemplate/dgraph.h
> +    Vector<Edge*>* matrix;
Поправил, вроде

2022-12-19 07:34 UTC, Dovgalyuk requested changes

2022-12-19 07:34 UTC, Dovgalyuk commented on Lab4/Lab4dov.cpp
> +    DGraph<Data>* graph = new DGraph<Data>(0, Data(-1));
```DGraph<Data> graph(0, Data(-1));```

2022-12-19 07:34 UTC, Dovgalyuk commented on Lab4/Lab4dov.cpp
> +    int index = -1;
Так путь нигде и не ищется, находится только длина пути.

2022-12-19 07:34 UTC, Dovgalyuk commented on LibraryCPPTemplate/dgraph.h
> +    Vector<Edge*>* matrix;
Я имел в виду, сделать ```Vector<Edge>```

2022-12-19 08:35 UTC, Merk9ayt commented on Lab4/Lab4dov.cpp
> +    DGraph<Data>* graph = new DGraph<Data>(0, Data(-1));
Поправил

2022-12-19 08:41 UTC, Merk9ayt commented on LibraryCPPTemplate/dgraph.h
> +    Vector<Edge*>* matrix;
Понял, поправил

2022-12-20 08:25 UTC, Dovgalyuk commented
Только надо теперь всё исправить, чтобы работало.

2022-12-22 06:44 UTC, Dovgalyuk commented
Всё по-прежнему.

2022-12-23 06:26 UTC, Dovgalyuk commented
Тест для графа не проходит.

2022-12-24 12:26 UTC, Merk9ayt commented
Не понимаю в чём конкретно проблема на 81 строчке в функции resize(), основной трабл скорее всего в том что в vector.h Data как указатель, а в конструкторе Edge без указателя. 
До какого числа можно сдавать лабы?

2022-12-26 08:28 UTC, Dovgalyuk commented
1. Проблема в том, что у Edge нет подходящего под такие аргументы конструктора.
2. Сдавать можно до экзамена, но проверять на сессии я буду редко (1-2 раза).

2023-01-06 16:08 UTC, Merk9ayt commented
На консультацию приходить 16.01 к 16:00 или во сколько?

2023-01-09 09:22 UTC, Dovgalyuk commented
> На консультацию приходить 16.01 к 16:00 или во сколько?

Если всех устраивает другое время, можно договориться пораньше.

2023-01-09 09:25 UTC, Dovgalyuk requested changes

2023-01-09 09:25 UTC, Dovgalyuk commented on Lab4/Lab4dov.cpp
> +    int index = -1;
Что-то ничего не изменилось.

2023-09-06 07:09 UTC, closed without merging