Lab4 filippov
Dovgalyuk/Algorithms pull request #492
Opened 2022-12-13 16:26 UTC by COURAGE231

2022-12-13 16:52 UTC, COURAGE231 commented
Если это не критично, то я поменял next() и prev() на item_next() и item_prev() соответственно. Просто я делал лист именно с такими названиями функций, поэтому с ними мне было проще всё понять. В основе графа лежит двусвязный список. Только лишь хранение вершин происходит в vector из STL.

2022-12-14 07:19 UTC, Dovgalyuk requested changes

2022-12-14 07:19 UTC, Dovgalyuk commented on Lab4/Lab4.cpp
> +}
В конце нужно удалить массив и граф.

2022-12-14 07:19 UTC, Dovgalyuk commented on Lab4/Lab4.cpp
> +    auto graph = new Graph<int, int>(countVertexes, 1);
Можно не выделять память динамически, а просто объявить локальную переменную.

2022-12-14 07:19 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +        List<Edge*> edges = List<Edge*>();
А ещё Edge это достаточно небольшая структура, лучше хранить в списке прямо экземпляры Edge, а не указатели на них.

2022-12-14 14:01 UTC, COURAGE231 commented on LibraryCPPTemplate/graph.h
> +        List<Edge*> edges = List<Edge*>();
Немного не понял. Можно ли это сделать не меняя код листа вообще? В Item листа всё равно должны будут храниться два элемента 
1. Ссылка на вершину
2. Вес ребра
А в листе у нас тип данных Data.  Значит нужно сделать конструктор Edge в листе? 
И когда всё будет сделано правильно, то в grahp можно будет обращаться к элементам листа просто вот так?
![image](https://user-images.githubusercontent.com/113786856/207612388-e8236655-f748-4f17-84e7-74ea46742e15.png)

2022-12-14 17:54 UTC, COURAGE231 commented on Lab4/Lab4.cpp
> +    auto graph = new Graph<int, int>(countVertexes, 1);
Исправил

2022-12-14 17:54 UTC, COURAGE231 commented on Lab4/Lab4.cpp
> +}
Исправил

2022-12-15 06:43 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +        List<Edge*> edges = List<Edge*>();
Нужно сделать ```List<Edge>```. Это же шаблон, он любые данные может хранить. И чтобы эти значения можно было менять, функция get_item у списка должна возвращать ссылку, а не значение.

2022-12-15 06:43 UTC, Dovgalyuk commented on Lab4/Lab4.cpp
> +    auto graph = &graph1;
А это зачем?

2022-12-15 06:44 UTC, Dovgalyuk commented on Lab4/Lab4.cpp
> +    delete graph;
Удалять уже не нужно, раз мы заменили на автоматическую переменную.

2022-12-15 08:46 UTC, COURAGE231 commented on Lab4/Lab4.cpp
> +    auto graph = &graph1;
У нас в коде стоят операторы ->. Я хотел их сохранить таким способом.

2022-12-15 20:27 UTC, COURAGE231 commented
Попробовал, поменял. Но по сути ничего не изменилось, да и проект перестал собираться. Вернул, пока что, лист с указателями. Возникает проблема на стадии добавления в лист, Edge*  невозможно преобразовать в Data и наоборот.

2022-12-15 20:33 UTC, COURAGE231 commented
![image](https://user-images.githubusercontent.com/113786856/207960295-fd7b338a-e0b4-4e1f-a6c4-285b47f35bcc.png)
допустим у нас в листе хранится элемент структуры Edge (item->data()), а возвращать нам нужно ссылку на него, но если я поменяю в листе Data на Data*, то мы ничего не поменяем и будем опять иметь лист с ссылками.

2022-12-15 21:00 UTC, COURAGE231 commented on LibraryCPPTemplate/graph.h
> +        List<Edge*> edges = List<Edge*>();
![image](https://user-images.githubusercontent.com/113786856/207966037-675d01be-937e-4c29-ad0a-d492fefbe83f.png)
Вы имели ввиду это?

2022-12-16 07:54 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +        List<Edge*> edges = List<Edge*>();
```Item(Data data) ...

Data &data() { return field; }
const Data &data() const { return field; }

Data field;
```

2022-12-16 08:27 UTC, COURAGE231 commented on LibraryCPPTemplate/graph.h
> +        List<Edge*> edges = List<Edge*>();
{ return field; }
Она всё так же возвращает значение, field же Data. 
![image](https://user-images.githubusercontent.com/113786856/208055981-3d0c9c42-36e1-44b3-9aee-c458d78691f0.png)

2022-12-18 15:53 UTC, COURAGE231 commented
![image](https://user-images.githubusercontent.com/113786856/208307072-c2e9aa34-434f-4048-a26b-59f31f1bb074.png)
Подскажите пожалуйста, функция обязательно должна что то возвращать, что можно вернуть в случае Edge& когда не выполнено условие IF?
Граф не проходит тест, точно из за этого, но может ещё из за чего то.

2022-12-19 07:24 UTC, Dovgalyuk commented
> ![image](https://user-images.githubusercontent.com/113786856/208307072-c2e9aa34-434f-4048-a26b-59f31f1bb074.png) Подскажите пожалуйста, функция обязательно должна что то возвращать, что можно вернуть в случае Edge& когда не выполнено условие IF? Граф не проходит тест, точно из за этого, но может ещё из за чего то.

В этом случае лучше вообще возвращать указатель. return &item->data();

2022-12-19 07:27 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +        List<Edge*> edges = List<Edge*>();
Ещё остался этот вопрос? А то я его не понял.

2022-12-19 10:58 UTC, COURAGE231 commented on LibraryCPPTemplate/graph.h
> +        List<Edge*> edges = List<Edge*>();
Вопрос снят :)

2022-12-19 11:21 UTC, COURAGE231 commented
Всё сделал - работает.  Если какие то ещё вопросы по коду, завтра планирую прийти, разберёмся.

2022-12-20 08:29 UTC, Dovgalyuk requested changes

2022-12-20 08:29 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +            delete this->getEdge(this);
Этой памятью владеет список, для неё не нужно вызывать delete.

2022-12-20 10:47 UTC, COURAGE231 commented on LibraryCPPTemplate/graph.h
> +            delete this->getEdge(this);
Вообще сомневаюсь в надобности деструктора Vertex. У нас же в листе прописан деструктор, который вызывается при очистки памяти элемента вектора. А для data деструктор то и не нужен.

2022-12-21 07:20 UTC, Dovgalyuk commented
* Разработать интерфейс (набор функций) для ассоциативного массива, который хранит пары (ключ)строка -> (значение)строка. Поддерживаемые операции: добавить пару ключ-значение, найти значение по ключу, удалить значение по ключу.
* Реализовать контейнер на основе АВЛ-дерева, реализующий разработанный интерфейс.
* Создать тест для проверки работы контейнера. Программа должна включать в себя нагрузочное тестирование для исключения ошибок, приводящих к сложности работы O(N*N) при поиске, удалении или добавлении значений.
* Написать генератор входных данных различного объема для этого контейнера.
* Сравнить скорость выполнения операции добавления в контейнер содержимого файла со стандартным контейнером std::map при различных объемах данных. Построить график зависимости времени работы от объёма входных данных и оценить характер зависимости.

2022-12-21 07:20 UTC, closed without merging