fourth lab
Dovgalyuk/Algorithms pull request #495
Opened 2022-12-14 21:05 UTC by diyliv

2022-12-15 06:37 UTC, Dovgalyuk commented
Надо сделать так, чтобы тест запускался на сервере.

2022-12-15 10:43 UTC, diyliv commented
added cmake tests

2022-12-16 07:31 UTC, Dovgalyuk requested changes

2022-12-16 07:31 UTC, Dovgalyuk commented on LibraryCPPTemplate/d_graph.h
> +        List<Edge*> *edges = new List<Edge*>;
Лучше хранить просто структуры: ```List<Edge>```

2022-12-16 07:31 UTC, Dovgalyuk commented on fourthLab/main.cpp
> +     D_Graph<int>* graph = new D_Graph<int>(vertexCount, 0);
Можно создать просто автоматическую переменную и не использовать new.

2022-12-16 07:31 UTC, Dovgalyuk commented on fourthLab/main.cpp
> +        }
Было бы нагляднее без if, а просто установить всем метку MAX, а потом нужной вершине 0.

2022-12-16 07:31 UTC, Dovgalyuk commented on fourthLab/main.cpp
> +            size_t minVertexIndex = vertexWithMinLabel(graph);
Тут второй раз подряд вызывается функция поиска, которая только что отработала.

2022-12-16 07:31 UTC, Dovgalyuk commented on fourthLab/main.cpp
> +    std::vector<int> pathTo(size_t index) {
Как отработает эта функция, если путь не был найден?

2022-12-18 17:22 UTC, diyliv commented
fixed

2022-12-19 07:29 UTC, Dovgalyuk commented on LibraryCPPTemplate/d_graph.h
> +        List<Edge*> *edges = new List<Edge*>;
Не сделано.

2022-12-19 07:29 UTC, Dovgalyuk commented on fourthLab/main.cpp
> +    std::vector<int> pathTo(size_t index) {
?

2022-12-19 07:29 UTC, Dovgalyuk commented on fourthLab/main.cpp
> +            size_t minVertexIndex = vertexWithMinLabel(graph);
?

2023-09-06 07:09 UTC, closed without merging