Решение 2 лабораторной работы
Dovgalyuk/Algorithms pull request #498
Opened 2022-12-15 20:24 UTC by KozlikGoat

2022-12-16 07:12 UTC, Dovgalyuk commented
Собственные программы тоже нужно подключить в основной конфиг CMake для сборки на сервере.

2022-12-21 06:44 UTC, Dovgalyuk requested changes

2022-12-21 06:44 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +	else if (item == list->head) {
Этот случай нет смысла рассматривать отдельно.

2022-12-21 06:44 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +		return item->next;
здесь может измениться last?

2022-12-21 06:44 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +bool list_empty(List* list) { return (list->head) ? false : true; }
нагляднее написать head != nullptr

2022-12-21 06:44 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +		if (list_first(list) == item) {
Везде было написано head, а здесь вызов list_first. Стоит делать одинаково.

2022-12-21 06:44 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +			return list_first(list);
prev не корректируется

2022-12-21 06:44 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +bool stack_empty(const Stack* stack) { return (list_empty(stack->list)) ? true : false; }
Не нужно писать функции в одну строчку.

2022-12-21 06:44 UTC, Dovgalyuk commented on labs/lab2.cpp
> +    return 0;
В конце контейнеры нужно удалить.

2022-12-21 06:44 UTC, Dovgalyuk commented on labs/lab2.cpp
> +                    if (array_get(processor, index) != 0) { stack_push(stack, array_get(processor, index)); }
Что делать, если значение регистра на самом деле 0?

2022-12-26 08:04 UTC, Dovgalyuk commented
Сделать три лабораторных до сессии уже не получится.

2022-12-26 08:04 UTC, closed without merging

2022-12-26 08:23 UTC, KozlikGoat commented
Что мне в таком случае делать? Я могу вторую лабораторную закончить?

2022-12-26 08:25 UTC, Dovgalyuk commented
Идти на комиссию, например. Нет.