lab3
Dovgalyuk/Algorithms pull request #502
Opened 2022-12-15 23:28 UTC by Terit21

2022-12-16 07:20 UTC, Dovgalyuk requested changes

2022-12-16 07:20 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +    vector_resize(queue->vec, vector_size(queue->vec)+1);
Нужно реализовать кольцевой буфер, чтобы в функции remove не перемещались все элементы, а в функции insert переиспользовалось освобождающееся место.

2022-12-16 07:20 UTC, Dovgalyuk commented on LibraryCPP/vector.cpp
> +    delete vector->data;
Тут нужно использовать delete[]

2022-12-16 07:20 UTC, Dovgalyuk commented on LibraryCPP/vector.cpp
> +        vector->data = nw;
Зачем здесь заново выделять память, если можно просто изменить size?

2022-12-18 13:49 UTC, Terit21 commented on LibraryCPP/vector.cpp
> +        vector->data = nw;
Я подумал, что в случае, если у нас был массив, предположим, с миллионом элементов, а потом его размер меняют на 3, то получится, что элемента нужна 3, а capasity будет 2000000, решил, что нужно освободить лишнее место в куче

2022-12-19 07:21 UTC, Dovgalyuk requested changes

2022-12-19 07:21 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +        while (queue->id_l != 0)
В этом цикле что-то плохое произойдёт. remove уменьшает amount и двигает id_l. Потом мы уменьшаем id_l, так что он остаётся на месте.

2022-12-19 07:21 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +    if (queue->el_amount == 0)
return queue->el_amount == 0

2022-12-20 08:23 UTC, Dovgalyuk requested changes

2022-12-20 08:23 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +        }
Вложенные циклы для перемещения последовательности в новое место - это перебор.
Можно удвоить размер вектора, чтобы было проще.

2022-12-20 08:23 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +    if (queue->el_amount == 0)
?

2022-12-20 18:54 UTC, Terit21 commented
У себя в коде поменял "return queue->el_amount == 0", а в гитхаб только функцию inserst кинул. Решил всё-таки попробовать сделать vector, который будет освобождать место при уменьшение размера

2022-12-21 07:11 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +        }
Разве не достаточно только одного цикла, который переместит хвост очереди с начала массива в ту часть, которая только что добавилась?

2022-12-22 06:37 UTC, Dovgalyuk commented
* Разработать программный интерфейс модуля (заголовки функций) для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
* Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
* Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List той же библиотеки.
* Разработать и добавить в проект Library программу, тестирующую работу библиотеки для графа.
* Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать в нем длины кратчайших путей от одной вершины до всех остальных с помощью алгоритма Дейкстры.

2022-12-22 06:37 UTC, closed without merging