Lab_2_Shedrin
Dovgalyuk/Algorithms pull request #507
Opened 2022-12-17 18:46 UTC by NikitaShd

2022-12-19 06:49 UTC, Dovgalyuk commented
1. Своё решение тоже надо добавить в сборку.
2. Лишние файлы от visual studio выкладывать не нужно.

2022-12-19 08:10 UTC, NikitaShd commented
Обновил

2022-12-20 07:53 UTC, Dovgalyuk commented
34 файла это всё ещё многовато.

2022-12-20 13:36 UTC, NikitaShd commented
забыл удалить фалы visual studio из 1 задания . Обновил

2022-12-21 06:52 UTC, Dovgalyuk requested changes

2022-12-21 06:52 UTC, Dovgalyuk commented on Lab_2_Shedrin/Lab_2_Shedrin.cpp
> +#include "../LibraryCPP/stack.h"
Не нужно писать путь, т.к. он уже сконфигурирован через cmake.

2022-12-21 06:52 UTC, Dovgalyuk commented on Lab_2_Shedrin/Lab_2_Shedrin.cpp
> +    Stack* stack_number = stack_create();
Все создаваемые контейнеры в конце нужно удалять.

2022-12-21 06:52 UTC, Dovgalyuk commented on Lab_2_Shedrin/Lab_2_Shedrin.cpp
> +    }
Пример входных данных:  (1+2)*3+(4+5)*6

2022-12-21 15:52 UTC, NikitaShd commented on Lab_2_Shedrin/Lab_2_Shedrin.cpp
> +#include "../LibraryCPP/stack.h"
да но VS без этой строчки класс не видит и отказывается компилировать .

2022-12-21 15:52 UTC, NikitaShd commented
Исправил ошибки .

2022-12-21 17:54 UTC, NikitaShd commented
Попытка #2

2022-12-22 06:11 UTC, Dovgalyuk requested changes

2022-12-22 06:11 UTC, Dovgalyuk commented on Lab_2_Shedrin/Lab_2_Shedrin.cpp
> +#include "../LibraryCPP/stack.h" //Это нужно для визуал студии
Проект для VS надо создавать с помощью CMake, тогда не будет этой проблемы.

2022-12-22 06:11 UTC, Dovgalyuk commented on Lab_2_Shedrin/Lab_2_Shedrin.cpp
> +            datareader(in.substr(i+1, stop - i));
Смысл задания в том, чтобы не использовать аппаратный стек для рекурсии, а пользоваться своим, реализуя разбор выражения.
Поэтому здесь нужно добавлять в стек операции (и скобки), а когда они извлекаются - выводить инструкции.

2022-12-22 06:12 UTC, Dovgalyuk commented on Lab_2_Shedrin/Lab_2_Shedrin.cpp
> +            datareader(in.substr(i+1, stop - i));
К тому же, сложность реализованного подхода - O(N^2) вместо O(N).

2022-12-23 09:19 UTC, NikitaShd commented
На мой взгляд задание выполнено и соответствует начальному ТЗ .

2022-12-26 07:51 UTC, Dovgalyuk commented
Сделать три лабораторных до сессии уже не получится.

2022-12-26 07:51 UTC, closed without merging