LabWork3
Dovgalyuk/Algorithms pull request #508
Opened 2022-12-18 02:46 UTC by RickCodeProg

2022-12-19 07:08 UTC, Dovgalyuk requested changes

2022-12-19 07:08 UTC, Dovgalyuk commented on LabWorks/Lab3/LabWork3.cpp
> +		out << BFS(matrix, 0, i, V) << '\n';
BFS можно вызвать только один раз.

2022-12-19 07:08 UTC, Dovgalyuk commented on LabWorks/Lab3/LabWork3.cpp
> +					if (count < min || min == NULL)
Поиск в ширину не может найти более короткий путь, чем тот, что уже найден, потому что первым всегда находится кратчайший.

2022-12-19 07:08 UTC, Dovgalyuk commented on LabWorks/Lab3/LabWork3.cpp
> +	return min;
Очередь тоже нужно удалить.

2022-12-19 07:08 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +    if (queue->last == vector_size(queue->queueVector) - 1)
Очередь может переполниться не только в таком случае.

2022-12-19 07:08 UTC, Dovgalyuk commented on LibraryCPP/vector.cpp
> +        return;
Или else или return. Оба использовать здесь ни к чему.

2022-12-20 08:19 UTC, Dovgalyuk requested changes

2022-12-20 08:19 UTC, Dovgalyuk commented on LabWorks/Lab3/LabWork3.cpp
> +	for (int v = start; v < V; v++)
Цикл не нужен, поиск в ширину найдёт все расстояния, если его не останавливать.

2022-12-20 08:19 UTC, Dovgalyuk commented on LibraryCPP/vector.cpp
> +    if (index < vector->size && index >= 0)
size_t не может быть отрицательным

2022-12-21 07:03 UTC, Dovgalyuk requested changes

2022-12-21 07:03 UTC, Dovgalyuk commented on LabWorks/Lab3/LabWork3.cpp
> +}
Пример входных данных:
```
5
0 1 1 0 0
0 0 0 1 0
0 0 0 0 1
0 0 0 0 0
0 0 0 0 0
```

2022-12-22 06:32 UTC, Dovgalyuk requested changes

2022-12-22 06:32 UTC, Dovgalyuk commented on LabWorks/Lab3/LabWork3.cpp
> +	}
Зачем второй раз инициализировать used?

2022-12-22 06:32 UTC, Dovgalyuk commented on LabWorks/Lab3/LabWork3.cpp
> +			if ((matrix[st][i]) == 1 && (!used[i]))
можно здесь used заменить на f и тогда второй массив станет ненужным

2022-12-23 06:24 UTC, Dovgalyuk requested changes

2022-12-23 06:24 UTC, Dovgalyuk commented on LabWorks/Lab3/LabWork3.cpp
> +	queue_insert(queue, start);
f[0] неправильное значение имеет.

2022-12-23 06:24 UTC, Dovgalyuk commented on LabWorks/Lab3/LabWork3.cpp
> +				if (f[i] != true)
Повторная проверка f[i]

2022-12-23 10:27 UTC, RickCodeProg commented
Вроде бы у меня получилось исправить условие так, что используется только лишь один массив расстояний, а остальные оказались не нужны

2022-12-26 08:08 UTC, Dovgalyuk commented
Принято.

2022-12-26 08:08 UTC, closed without merging