lab2
Dovgalyuk/Algorithms pull request #511
Opened 2022-12-18 21:49 UTC by likazzz

2022-12-19 06:59 UTC, Dovgalyuk commented
Тест для списка тоже должен проходить (см. вкладку checks)

2022-12-19 19:25 UTC, likazzz commented
Поменяла тест, потому что список односвязный

2022-12-20 08:07 UTC, Dovgalyuk requested changes

2022-12-20 08:07 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        return list->top;
Если оставить только эту строку, то результат будет тем же.

2022-12-20 08:07 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        return NULL;
NULL используется для указателей. Тут можно написать, к примеру, Data().

2022-12-20 08:07 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        return item->next;
То же самое.

2022-12-21 06:53 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        return item->next;
Не сделано.

2022-12-22 13:56 UTC, likazzz commented
Я не понимаю, что в list_item_next вернуть кроме NULL? Я же тут NULL для указателя и использую

2022-12-23 06:15 UTC, Dovgalyuk commented
* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.

Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной - «#» или пустым пространством – «.».
Стартовая позиция обозначается как X, финишные позиции цифрами от 0 до 9.
Написать программу, которая выводит цифру, ближайшую к стартовой позиции.
За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди.

Входные данные
```
######
#...X#
#.#.##
#3.4.#
######
```
Выходные данные
```
4
```

2022-12-23 06:15 UTC, closed without merging