Лабораторная 1
Dovgalyuk/Algorithms pull request #514
Opened 2022-12-20 13:01 UTC by MardanovAziz

2022-12-21 06:47 UTC, Dovgalyuk commented
Нужно убрать из репозитория все лишние файлы, оставив лишь исходники и сборочные конфиги.

2022-12-21 20:05 UTC, MardanovAziz commented
Здравствуйте, укажите конкретно, какие файлы и папки я должен убрать ? не
понял суть вопроса, спасибо за понимание

ср, 21 дек. 2022 г. в 09:47, Pavel Dovgalyuk ***@***.***>:

> Нужно убрать из репозитория все лишние файлы, оставив лишь исходники и
> сборочные конфиги.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Dovgalyuk/Algorithms/pull/514#issuecomment-1360919442>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3K45V3NEPJO4KOFWH74AXDWOKRY3ANCNFSM6AAAAAATEPHK2Q>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-22 11:07 UTC, MardanovAziz commented
Убрал лишние файлы

2022-12-23 06:07 UTC, Dovgalyuk requested changes

2022-12-23 06:07 UTC, Dovgalyuk commented on LibraryCPP/array.cpp
> +		if (index < size && index >= 0) {
size_t не может быть отрицательным

2022-12-23 06:07 UTC, Dovgalyuk commented on Labs/lab1.cpp
> +    int* mass = new int[size];
Нужно использовать разработанный array, а не просто динамический массив.

2022-12-23 21:21 UTC, MardanovAziz commented
Второй вопрос понятен, что касается 1 вопроса где size_t не может быть
отрицательным, можете ли вы конкретно объяснить в чем заключается проблема,
спасибо за понимание

пт, 23 дек. 2022 г. в 09:08, Pavel Dovgalyuk ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In LibraryCPP/array.cpp
> <https://github.com/Dovgalyuk/Algorithms/pull/514#discussion_r1056064370>:
>
> > -size_t array_size(const Array *arr)
>
> -{
>
> -    return 0;
>
> -}
>
> +	// delete array, free memory
>
> +
>
> +	void array_delete(Array* arr) {
>
> +		delete arr;
>
> +	}
>
> +
>
> +	// returns specified array element
>
> +
>
> +
>
> +	Data array_get(const Array* arr, size_t index) {
>
> +		size_t size = array_size(arr);
>
> +		if (index < size && index >= 0) {
>
>
> size_t не может быть отрицательным
> ------------------------------
>
> In Labs/lab1.cpp
> <https://github.com/Dovgalyuk/Algorithms/pull/514#discussion_r1056064776>:
>
> > @@ -0,0 +1,30 @@
>
> +#include <iostream>
>
> +#include "array.h"
>
> +
>
> +using namespace std;
>
> +
>
> +int main()
>
> +{
>
> +    int sred_arifmet = 0;
>
> +    int chislo = 0;
>
> +    int size = 0;
>
> +    cout << "Enter array size: ";
>
> +    cin >> size;
>
> +    int* mass = new int[size];
>
>
> Нужно использовать разработанный array, а не просто динамический массив.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Dovgalyuk/Algorithms/pull/514#pullrequestreview-1228566781>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3K45VYHGQ4OHMKPKAWJDZTWOU6ULANCNFSM6AAAAAATEPHK2Q>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-24 11:45 UTC, MardanovAziz commented
Исправленно

2022-12-26 06:22 UTC, Dovgalyuk commented
Выполнить три задания до сессии уже не получится.

2022-12-26 06:22 UTC, closed without merging

2022-12-26 09:06 UTC, MardanovAziz commented
Ещё как получиться, дайте мне следующую лабораторную прошу вас! Я как
студент получающий стипендию намерен ее сохранить, а не потерять. Спасибо
за понимание.

пн, 26 дек. 2022 г., 09:22 Pavel Dovgalyuk ***@***.***>:

> Closed #514 <https://github.com/Dovgalyuk/Algorithms/pull/514>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Dovgalyuk/Algorithms/pull/514#event-8109839332>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3K45V5AZRGYMCMNL2SMRYLWPE2SNANCNFSM6AAAAAATEPHK2Q>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>