Lab2 Panteleev 1091
Dovgalyuk/Algorithms pull request #516
Opened 2022-12-20 18:47 UTC by Taushicki

2022-12-21 06:58 UTC, Dovgalyuk requested changes

2022-12-21 06:58 UTC, Dovgalyuk commented on Labs/LabLaboratornaya2.cpp
> +		}
Стек надо использовать для проверки порядка скобок, а не просто для их хранения.

2022-12-21 06:58 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        return list->firstItem;
Тут удаляется первый элемент, а не переданный параметр item.

2022-12-21 06:58 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        if (tempPtr->nextItem != nullptr)
Эта проверка не нужна.

2022-12-22 06:05 UTC, Dovgalyuk requested changes

2022-12-22 06:05 UTC, Dovgalyuk commented on Labs/LabLaboratornaya2.cpp
> +		}
Пример входных данных: ```())```

2022-12-22 06:05 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +ListItem* list_erase(List* list, ListItem* item) {
Частично работающая функция - это неправильно.
Нужно либо немного изменить тест, либо реализовать здесь корректное удаление любого элемента.

2022-12-22 06:05 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        item->nextItem = nullptr;
Элемент может удаляться из середины списка.

2022-12-22 16:02 UTC, Taushicki commented on LibraryCPP/list.cpp
> +ListItem* list_erase(List* list, ListItem* item) {
То есть я могу в тестовом файле заменить функцию list_erese на свою(list_erese_first)?

2022-12-23 06:19 UTC, Dovgalyuk commented on Labs/LabLaboratornaya2.cpp
> +}
Такой пример: ```(")"```

2022-12-26 07:52 UTC, Dovgalyuk commented
Ошибки ещё остаются. Сделать три лабораторных до сессии уже не получится.

2022-12-26 07:52 UTC, closed without merging