Laba4
Dovgalyuk/Algorithms pull request #519
Opened 2022-12-21 19:59 UTC by SaintEfim

2022-12-22 06:45 UTC, Dovgalyuk commented
Не компилируется.

2022-12-23 06:25 UTC, Dovgalyuk commented
Всё ещё не компилируется.

2022-12-25 19:44 UTC, SaintEfim commented
Извините, можете сказать почему проект не собирается, у меня на пк всё компилируется

2022-12-26 08:39 UTC, Dovgalyuk requested changes

2022-12-26 08:39 UTC, Dovgalyuk commented on Laba4/Source.cpp
> +    return 0;
Тут вообще не используется разработанный граф.

2022-12-26 08:39 UTC, Dovgalyuk commented on LibraryCPPTemplate/Tests/graph.cpp
> +    }
Если итераций не было вообще, тест тоже пройдёт.

2022-12-26 08:39 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +            edgeMatrix->set(start_vertex_index * vertex_amount + end_vertex_index, edge);
А если там уже была связь?

2022-12-26 08:39 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +            edgeMatrix->set(start_vertex_index * vertex_amount + end_vertex_index, nullptr);
Тут утечка памяти.

2022-12-26 08:39 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +        Vector<Vertex*> *vertexes;
Вот здесь точно можно просто Vector, а не указатель на него. Для рёбер тоже можно, если очень постараться, но не обязательно.

2023-09-06 07:09 UTC, closed without merging