Lab5 Filippov
Dovgalyuk/Algorithms pull request #522
Opened 2022-12-21 21:32 UTC by COURAGE231

Пока что файл лабораторной ничем не заполнен, поскольку есть несколько вопросов.  У меня АВЛ-дерево в отдельном файле, а файл ассоциативного массива просто вызывает функции оттуда. Можно оставить так, или нужно обязательно переносить всё в один файл? Условие о том, что хранимые элементы являются строками является вечным? Не нужно же делать шаблоны для возможности хранения разных типов? И, как я понял, реализация на АВЛ-дереве здесь нужна только для быстрого поиска нужного нам элемента?

2022-12-22 06:38 UTC, Dovgalyuk commented
Шаблоны не обязательны, можно реализовать просто для строк.
Отделять реализацию дерева от интерфейса допустимо.
Дерево нужно именно для быстрого поиска.

2022-12-22 16:48 UTC, COURAGE231 commented
Добавил тест массива. Проверяю скорость выполнения пока что, и вроде бы всё хорошо. Хотя, мне кажется, что процесс добавления элемента можно ускорить, выбрана не самая лучшая балансировка. 
Ведь даже скорость добавления элемента должна быть быстрее чем у map?

2022-12-23 06:28 UTC, Dovgalyuk commented
1. Свою программу тоже надо добавить в сборочный скрипт.
2. Скорость может быть и хуже, чем у map, но её изменение должно подчиняться тому же закону.

2022-12-25 17:03 UTC, COURAGE231 commented
Исправил пару моментов. Вообще, хотел сделать цикл вместо рекурсии при добавлении элементов, но по ходу дела я только путался и читаемость кода падала. Из-за этого я не заметил одну страшную вещь. У меня функции принимали string по значению, поэтому происходило копирование и это кушало ресурсы. Заменил везде на const string& - ускорил работу в 5 раз.  Загрузил один файл экселя с таблицей, и два сравнивающих графика.

2022-12-26 08:52 UTC, Dovgalyuk requested changes

2022-12-26 08:52 UTC, Dovgalyuk commented on Lab5/CMakeLists.txt
> +target_link_libraries(Lab5 LibraryCPP)
Надо ещё подключить этот файл к общему конфигу.

2022-12-26 09:27 UTC, COURAGE231 commented on Lab5/CMakeLists.txt
> +target_link_libraries(Lab5 LibraryCPP)
Точно, забыл в суматохе. Надеюсь это единственный недочет и завтра смогу уже защитить. А то другой возможности не будет.

2022-12-27 03:02 UTC, COURAGE231 commented
Вообще, по-хорошему, возвращать нужно не значение, а элемент, как у map. Да и вообще можно сделать чтобы ключи были уникальными. Реализовать не сложно, но я не думаю что смысл лабораторной заключается в этом.

2022-12-27 03:57 UTC, COURAGE231 commented
Исправил поиск, теперь он возвращает элемент, а не его значение. 
Даже ускорил.
Сравнение поиска в АВЛ-дереве и std::map - 
![HCaaIznCqQw](https://user-images.githubusercontent.com/113786856/209608765-c7b0b1a9-4282-4dcc-b8d3-333ec9775597.jpg)

2023-01-15 19:38 UTC, COURAGE231 commented
Здравствуйте, скорее всего, не успею реализовать то, что хотел.  Эту лабораторную можно защитить на консультации?

2023-01-16 09:42 UTC, Dovgalyuk commented
Можно.

2023-01-16 09:42 UTC, closed without merging