Lab4_Kurdova
Dovgalyuk/Algorithms pull request #523
Opened 2022-12-22 05:52 UTC by julktnn

Сейчас готов list.h

2022-12-22 06:46 UTC, Dovgalyuk commented
А где тест?

2022-12-22 06:51 UTC, julktnn commented
Тест не меняла, так как названия как в шаблоне оставила

2022-12-23 06:25 UTC, Dovgalyuk commented
В шаблоне не было теста для графа.

2022-12-26 08:44 UTC, Dovgalyuk requested changes

2022-12-26 08:44 UTC, Dovgalyuk commented on Lab4/l4.cpp
> +        cout << "Кратчайший путь: ";
В задании сказано найти все кратчайшие пути, а не только один.

2022-12-27 09:25 UTC, Dovgalyuk commented on Lab4/l4.cpp
> +            if (matr[a][i] == true) // проверяем, какие ребра идут в конечную вершину
Развилка может быть не только на первом шаге.

2023-01-06 16:47 UTC, julktnn commented
Скажите пожалуйста, вы в начале года вроде говорили, что на экзамене можно будет пользоваться своими записями. Это так?

2023-01-09 09:26 UTC, Dovgalyuk commented
> Скажите пожалуйста, вы в начале года вроде говорили, что на экзамене можно будет пользоваться своими записями. Это так? И еще, во сколько и в какой аудитории будет экзамен 17 числа? В расписании сессии только про 18 есть

На экзамене можно пользоваться бумажными источниками.
17 числа надо смотреть у другой группы.

2023-01-09 09:31 UTC, Dovgalyuk requested changes

2023-01-09 09:31 UTC, Dovgalyuk commented on Lab4/l4.cpp
> +        for (int i = 0; i < kolvoPaths; i++) // для каждого кратчайшего пути ищем кандидатов
Очень длинный код. Достаточно идти по всем вариантам развилок от конечной вершины в направлении уменьшения расстояний. Можно реализовать рекурсивно, можно с помощью циклов.

2023-09-06 07:09 UTC, closed without merging