Laba 3 Reshenye
Dovgalyuk/Algorithms pull request #528
Opened 2022-12-23 06:30 UTC by pol0praktika

2022-12-26 08:06 UTC, Dovgalyuk commented
Код решения тоже должен быть добавлен к сборке.

2022-12-26 08:42 UTC, pol0praktika commented
Немного не поняла, что конкретно нужно добавить? Вектора и очередь проверку прошли, а сам файл лабораторной есть в cmake и в репозитории

2022-12-27 09:03 UTC, Dovgalyuk requested changes

2022-12-27 09:03 UTC, Dovgalyuk commented on labs/Laba3.cpp
> +	const int bitSort = 1;
Стоит протестировать хотя бы для значений 2 и 3.

2023-01-13 06:08 UTC, Dovgalyuk commented on labs/Laba3.cpp
> +	const int bitSort = 1;
Плохо протестировано, для 3 (к примеру) есть ошибки в остальном коде.

2023-01-16 06:39 UTC, pol0praktika commented on labs/Laba3.cpp
> +	const int bitSort = 1;
Павел Михайлович, не могу понять в чем ошибка. так как у меня правильно сортирует и не выдает ошибок

2023-01-16 09:37 UTC, Dovgalyuk commented
Уточнение: все collection[i] должны заполняться чем-то, если, к примеру подать на вход числа от 0 до 15. Сейчас будет заполняться только 2 из них.

2023-09-06 07:09 UTC, closed without merging