Lab 4 Semenov
Dovgalyuk/Algorithms pull request #531
Opened 2022-12-26 05:39 UTC by midhey

•Разработать программный интерфейс модуля (заголовки функций) для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
•Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
•Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List той же библиотеки.
•Разработать и добавить в проект Library программу, тестирующую работу библиотеки для графа.
•Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать в нем количество компонентов связности с помощью обхода в глубину.

2022-12-26 07:00 UTC, midhey commented
![Безымянный](https://user-images.githubusercontent.com/45918010/209515219-ae5ae520-1831-4402-bff0-836bbeee25b9.png)

2022-12-26 07:02 UTC, midhey commented
Можно спросить насчет самого задания? Мне нужно заполнить граф и обходом глубину определить количество компонентов связности? То есть, условно, как на рисунке снизу получить число 3?
![Безымянный](https://user-images.githubusercontent.com/45918010/209515394-4c1c7f49-9aa2-4b01-997d-f6af1103f7a7.png)

2022-12-26 08:45 UTC, Dovgalyuk commented
> Можно спросить насчет самого задания? Мне нужно заполнить граф и обходом глубину определить количество компонентов связности? То есть, условно, как на рисунке снизу получить число 3? ![Безымянный](https://user-images.githubusercontent.com/45918010/209515394-4c1c7f49-9aa2-4b01-997d-f6af1103f7a7.png)

Да, всё так.

2022-12-26 08:48 UTC, midhey commented
> > Можно спросить насчет самого задания? Мне нужно заполнить граф и обходом глубину определить количество компонентов связности? То есть, условно, как на рисунке снизу получить число 3? ![Безымянный](https://user-images.githubusercontent.com/45918010/209515394-4c1c7f49-9aa2-4b01-997d-f6af1103f7a7.png)
> 
> Да, всё так.

Понял, спасибо. А можно еще уточнить, еще есть время доделать и сдать?

2022-12-26 08:52 UTC, Dovgalyuk commented
Сдавать ещё можно будет на консультации.

2022-12-27 09:41 UTC, Dovgalyuk requested changes

2022-12-27 09:41 UTC, Dovgalyuk commented on labs/lab4d.cpp
> +void searchInDepth(Graph<int>::Vertex* vertex, List<Graph<int>::Vertex*>* visitedVertexes) {
Вместо списка посещённых вершин лучше просто использовать пометки вершин графа, которые и так уже предусмотрены.

2023-01-11 19:17 UTC, midhey commented on labs/lab4d.cpp
> +void searchInDepth(Graph<int>::Vertex* vertex, List<Graph<int>::Vertex*>* visitedVertexes) {
Можете пожалуйста подсказать что конкретно вы имеете ввиду? Все никак не доходит 😅

2023-01-13 06:11 UTC, Dovgalyuk commented on labs/lab4d.cpp
> +void searchInDepth(Graph<int>::Vertex* vertex, List<Graph<int>::Vertex*>* visitedVertexes) {
visitedVertexes убрать. Для того, чтобы узнать, посещена ли вершина, можно устанавливать ей пометку. Для этого в графе они и есть.

2023-01-16 09:41 UTC, Dovgalyuk commented
Принято, хотя похоже на ненужное усложнение.

2023-01-16 09:41 UTC, closed without merging