Lab Third
Dovgalyuk/Algorithms pull request #534
Opened 2022-12-26 20:32 UTC by Mist531

2022-12-27 09:22 UTC, Dovgalyuk requested changes

2022-12-27 09:22 UTC, Dovgalyuk commented on Labs/Third/lab3.cpp
> +}
Вот ещё тест:
```
##############################################
#X...........................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#............................................#
#...........................................2#
##############################################

```

2022-12-27 09:22 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
>  ListItem *list_erase(List *list, ListItem *item)
Эта функция должна быть либо реализована для всех случаев, либо не реализована вообще.

2022-12-27 09:22 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        return item->next = next;
Тут возможно потребуется скорректировать last.

2022-12-27 18:37 UTC, Mist531 commented
Поправил.

2023-01-09 08:58 UTC, Dovgalyuk requested changes

2023-01-09 08:58 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    //Реализована только часть, тк у меня односвязный список, а не двусвязный
Надо или реализовать полностью, с поиском нужного элемента.

2023-01-09 09:43 UTC, Mist531 commented on LibraryCPP/list.cpp
> +    //Реализована только часть, тк у меня односвязный список, а не двусвязный
Я не могу понять, как я могу это реализовать, если у меня односвязный список по заданию?

2023-01-13 06:01 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    //Реализована только часть, тк у меня односвязный список, а не двусвязный
Циклом находить предыдущий элемент, чтобы можно было удалить текущий.

2023-01-16 09:27 UTC, closed without merging