Lab1
Dovgalyuk/Algorithms pull request #583
Opened 2023-09-15 15:37 UTC by stmay4

2023-09-16 11:43 UTC, Dovgalyuk commented
Проект должен собираться (и релевантные тесты должны проходить).
См. отчёт CMake/build на этой странице.

2023-10-01 15:24 UTC, stmay4 commented
Здравствуйте! Подскажите, пожалуйста, тест TestArrayC провален из-за ошибки alloc-dealloc-mismatch (operator new vs free), я должен это исправлять если пишу библиотеку и лабораторную на си, а new используется в тесте array.cpp?

2023-10-02 07:47 UTC, Dovgalyuk commented
> Здравствуйте! Подскажите, пожалуйста, тест TestArrayC провален из-за ошибки alloc-dealloc-mismatch (operator new vs free), я должен это исправлять если пишу библиотеку и лабораторную на си, а new используется в тесте array.cpp?

На не имеющие отношения к заданию тесты можно не обращать внимания.
Но тест для той части, которая реализуется, должен проходить.

2023-10-02 14:01 UTC, stmay4 commented
Тест TestArrayC пройден

2023-10-03 09:29 UTC, Dovgalyuk requested changes

2023-10-03 09:29 UTC, Dovgalyuk commented on LibraryC/array.c
> +        return malloc(sizeof(Array));
Здесь структура будет содержать мусор.

2023-10-05 06:22 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
* Решить задачу, используя реализованный стек.

Дано выражение в обратной польской записи. Используя стек, написать программу, которая проверяет выражение на наличие ошибок. Ошибкой считается деление на 0 (ZERO), выполнение операции, когда в стеке меньше двух элементов (UNDERFLOW), наличие больше одного элемента в стеке после завершения работы программы (OVERFLOW).

Входные данные
```
1 2 + 3
```
Выходные данные
```
OVERFLOW
```

Входные данные
```
10 9 - +
```
Выходные данные
```
UNDERFLOW
```

2023-10-05 06:22 UTC, closed without merging