lab1 update Pusep Alexey 2091
Dovgalyuk/Algorithms pull request #595
Opened 2023-09-22 07:07 UTC by alexeypusep

2023-09-22 08:02 UTC, Dovgalyuk requested changes

2023-09-22 08:02 UTC, Dovgalyuk commented on Lab1CPP/lab1.cpp
> +    if (shift_direction < 0 || shift_direction > 1) //Если при вводе числа, отвечающего за направление сдвига, введено число меньше 0 или больше 1 (выбрано некорректное направление сдвига)
Лучше просто использовать bool, в который преобразовывать число после ввода.
Чтобы эта функция не засорялась ненужными проверками.

2023-09-22 08:02 UTC, Dovgalyuk commented on Lab1CPP/lab1.cpp
> +                print_array(arr); //Вывод измененного массива
Один шаг - это сдвиг массива на единицу, а не сдвиг одного элемента куда надо.

2023-09-22 08:14 UTC, alexeypusep commented on Lab1CPP/lab1.cpp
> +        total_resistance += array_get(arr, i); //Суммирование значений всех элемнтов массива
Вот задание, тут про резисторы нет слов. Хорошо сделаю для резисторов.

Ввести целое число с клавиатуры, создать массив такой размерности и заполнить его случайными числами. В массиве хранится информация о сопротивлении элементов электрической цепи. Все элементы соединены параллельно. Определить общее сопротивление цепи.

2023-09-22 08:15 UTC, alexeypusep commented on Lab1CPP/lab1.cpp
> +                print_array(arr); //Вывод измененного массива
Не совсем понимаю, что значит сдвиг массива на единицу...
В задании речь о сдвиге элементов массива

Вот текст задания:
Ввести целое число с клавиатуры, создать массив такой размерности и заполнить его случайными числами. Сдвинуть элементы массива в указанном направлении (влево или вправо) и на указанное число шагов. Освободившиеся ячейки заполнить нулями. Выводить массив после каждого шага.

2023-09-22 13:43 UTC, alexeypusep commented
Я исправил Ваши замечания

2023-09-25 06:31 UTC, Dovgalyuk requested changes

2023-09-25 06:31 UTC, Dovgalyuk commented on Lab1CPP/lab1.cpp
> +        for (size_t i = 0; i < number_elements_shift; i++) //Выплнение сдвига введенное количство раз
Цикл можно сделать один, а if сделать внутри, будет меньше кода.

2023-09-25 06:49 UTC, alexeypusep commented on Lab1CPP/lab1.cpp
> +        for (size_t i = 0; i < number_elements_shift; i++) //Выплнение сдвига введенное количство раз
Исправил

2023-09-26 05:20 UTC, Dovgalyuk requested changes

2023-09-26 05:20 UTC, Dovgalyuk commented on Lab1CPP/lab1.cpp
> +            print_array(arr); //Вывод измененного массива
Строчки с выводом можно вытащить из ветвления, они в обоих случаях одинаковые.

2023-09-26 06:27 UTC, alexeypusep commented
Исправил работу

2023-09-27 05:40 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library двусвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

Преобразовать корректное арифметическое выражение, использующее операции сложения, вычитания, умножения и деления, в арифметическое выражение в обратной польской записи. Программа должна учитывать приоритет операторов умножения и деления и использовать стек. Операндами в выражении являются однобуквенные переменные.

Входные данные
```
A+B*C+D
```
Выходные данные
```
ABC*+D+
```

Входные данные
```
A*B+C
```
Выходные данные
```
AB*C+
```

Входные данные
```
A+B*(C+D)
```
Выходные данные
```
ABCD+*+
```

2023-09-27 05:40 UTC, closed without merging