лаба 1
Dovgalyuk/Algorithms pull request #598
Opened 2023-09-23 17:20 UTC by duraaach0k

2023-09-25 07:01 UTC, Dovgalyuk commented
Проект должен собираться (см. отчёт CMake build)

2023-10-03 10:57 UTC, duraaach0k commented
отправил новую версию, запустите, пожалуйста, когда будет время

2023-10-04 05:23 UTC, Dovgalyuk commented
Ошибка в том, что нет пустой строки в конце файла.

2023-10-04 09:24 UTC, duraaach0k commented
в программе на компе у меня там есть пустая строка, кит сам ее обрезает похоже, не знаю че с этим делать

2023-10-05 06:15 UTC, Dovgalyuk commented
Пустой строки нет в файле array.c (это написано в сообщении об ошибке)

2023-10-05 13:16 UTC, duraaach0k commented
исправил

2023-10-06 04:28 UTC, Dovgalyuk commented
Ещё ошибка компиляции.

2023-10-06 13:03 UTC, duraaach0k commented
не знаю чем ему айострим не понравился, исправил

2023-10-09 06:39 UTC, Dovgalyuk commented
Там в исходном файле с расширением .c находится программа на C++, а компилятор ожидает C.

2023-10-09 13:36 UTC, duraaach0k commented
ну теперь вроде точно чистый си

2023-10-09 14:05 UTC, duraaach0k commented
вроде все теперь верно?

2023-10-09 14:05 UTC, duraaach0k commented
первый тест она прошла

2023-10-10 06:09 UTC, Dovgalyuk requested changes

2023-10-10 06:09 UTC, Dovgalyuk commented on Lab1C/lab1.c
> +size_t a;
Глобальную переменную надо убрать, а размер узнавать с помощью array_size

2023-10-10 06:09 UTC, Dovgalyuk commented on Lab1C/lab1.c
> +                    array_set(arr, i, p);
Это лучше делать не здесь, а во внешнем цикле, потому что мы заменяем элемент i.

2023-10-10 06:09 UTC, Dovgalyuk commented on LibraryC/array.c
> +		arr->array[index] = value;
Надо освобождать старый элемент, когда он затирается.

2023-10-10 15:46 UTC, duraaach0k commented
void array_set(Array* arr, size_t index, Data value)
{
	if (arr->del != NULL)
		
			arr->del(arr->array[index]);
		
	else
		
			free(arr->array[index]);
		
	if (index < arr->size) {
		arr->array[index] = value;
	}
	else return;
}
написал удаление так, но оно не работает

2023-10-11 05:35 UTC, Dovgalyuk commented
Во-первых, индекс надо проверять и для удаления.
Во-вторых, при создании массива его нужно инициализировать нулевыми указателями. А сейчас там после выделения памяти будет мусор.

2023-10-11 09:43 UTC, duraaach0k commented
все поправил кроме        z = *(int*)(array_get(arr, i));
                    int* p = (int*)malloc(sizeof(int));
                    *p = -1;
                    array_set(arr, i, p); не понимаю как и зачем это писать во внешнем цикле, оно же нормально работает. Можно мне начать делать 2 лабу?

2023-10-16 12:35 UTC, duraaach0k commented
Можно задания для второй лабы?

2023-10-17 06:01 UTC, Dovgalyuk commented
> Можно задания для второй лабы?

Сначала надо завершить эту.

2023-10-17 08:55 UTC, duraaach0k commented
Так я вроде все сделал уже. Что ещё то не так?

2023-10-18 05:23 UTC, Dovgalyuk requested changes

2023-10-18 05:23 UTC, Dovgalyuk commented on Lab1C/lab1.c
> +                    array_set(arr, i, p);
Что с этим примером?

2023-10-18 16:06 UTC, duraaach0k commented
все поправил вроде работает как надо теперь

2023-10-19 11:17 UTC, Dovgalyuk commented on Lab1C/lab1.c
> +                    z = *(int*)(array_get(arr, i));
А это зачем, если мы можем просто считать i-й элемент позднее?
Или тогда надо z инициализировать в самом начале итерации, чтобы использовать везде.

2023-10-19 12:36 UTC, duraaach0k commented
это тоже исправил

2023-10-20 08:48 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
* Решить задачу, используя реализованный стек.

Во входном файле записана последовательность операций со стеком JAVA-машины.
Упрощённая JAVA-машина может оперировать стеком и четырьмя локальными переменными с номерами от 0 до 3.
Выполнить операции и напечатать финальное состояние стека и переменных.

Список операций, которые должны поддерживаться:
* bipush число - занести число в стек
* pop - вытолкнуть верхнее значение со стека
* imul - умножение
* iand - побитовое "и"
* ior - побитовое "или"
* ixor - операция "исключающее или"
* iadd - сложение
* isub - вычитание
* iload_0, iload_1, iload_2, iload_3 - занести в стек значение соответствующей переменной
* istore_0, istore_1, istore_2, istore_3 - записать значение с вершины стека в соответствующую переменную
* swap - меняет местами два верхних значения в стеке

Все арифметические операции берут операнды с вершины стека, а затем записывают в стек результат вычислений.

Входные данные
```
bipush 1
bipush 2
bipush 3
iadd
istore_0
```
Выходные данные
```
stack:
1
vars:
5
0
0
0
```

2023-10-20 08:48 UTC, closed without merging