Федоров Иван 2091
Dovgalyuk/Algorithms pull request #599
Opened 2023-09-24 13:19 UTC by Estomee

2023-09-25 07:07 UTC, Dovgalyuk requested changes

2023-09-25 07:07 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +        for (size_t i = second_task(arr); i < second_task(arr) + 5; i++)
Зачем много раз делать одно и то же, вызывая функцию?

2023-09-25 07:07 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +            sum += array_get(arr, j);
Можно ли не пересчитывать всю сумму на каждой итерации, а только обновлять её, используя предыдущее значение?

2023-09-25 07:07 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +    if (flag == 1)                       //����� ����������� ������� �������
flag в этот момент всегда 0.
И лучше так вообще не делать, а удалить переменную flag.

2023-09-25 07:07 UTC, Dovgalyuk commented on LibraryCPP/Tests/array.cpp
> -#include <iostream>
в тест вообще не нужно вмешиваться (в большинстве случаев)

2023-09-26 05:19 UTC, Dovgalyuk commented
Нужно откатить не связанные с решением изменения. В частности, чтобы тест оставался тестом.

2023-09-26 06:46 UTC, Estomee commented
в тест пришлось добавить функцию main, иначе проект просто не собирается

2023-09-27 05:41 UTC, Dovgalyuk commented
Посмотри содержимое теста в оригинальном репозитории.

2023-09-27 12:35 UTC, Estomee commented
Павел Михайлович, я посмотрел содержимое теста в оригинальном репозитории, заменил. Сейчас проблема с тестами, CMakeList.txt в папках LibraryC и LibraryCPP. Даёт вот такую ошибку, если там прописаны инструкции для всех структур данных:
![image](https://github.com/Dovgalyuk/Algorithms/assets/112470254/ce8affeb-2cd8-4afc-8504-6f26deaccf43)
Если же убрать все инструкции, кроме array, Git даже не даёт сделать попытку, чтобы собрать проект.

2023-09-28 05:02 UTC, Dovgalyuk commented
Стирать файлы из скрипта сборки CMakeLists.txt для LibraryCPP не нужно.

2023-09-28 13:15 UTC, Estomee commented
Павел Михайлович, ветку оригинальную поставил, всё сделал как вы сказали. В билде нет проблем, тест по array проходит, но по queue, list и т.д - нет. Из-за этого галочку build я не получаю. Не знаю, что нужно ещё сделать 
![image](https://github.com/Dovgalyuk/Algorithms/assets/112470254/c9b2f34f-2195-46db-ba1b-1ccc503ac2e4)
![image](https://github.com/Dovgalyuk/Algorithms/assets/112470254/9c7a8234-0aef-4d1b-864e-d37216469919)

2023-09-29 07:51 UTC, Dovgalyuk commented
> Павел Михайлович, ветку оригинальную поставил, всё сделал как вы сказали. В билде нет проблем, тест по array проходит, но по queue, list и т.д - нет. Из-за этого галочку build я не получаю. Не знаю, что нужно ещё сделать

Если нужный тест проходит, то всё нормально.

2023-09-29 07:59 UTC, Dovgalyuk requested changes

2023-09-29 07:59 UTC, Dovgalyuk commented on Lab1CPP/lab1.cpp
> +            }
Тут делается не то, что нужно. Надо выбрать максимальную из всех возможных сумм из идущих подряд 5 элементов.

2023-10-02 06:46 UTC, Estomee commented
Павел Михайлович, правки внёс. Тест прошёл, проект сбилдился.

2023-10-02 07:59 UTC, Dovgalyuk commented
В репозиторий попало много ненужных файлов.

2023-10-02 08:25 UTC, Estomee commented
Павел Михайлович, какие файлы не нужны? Там репозиторий чистый, я копировал его заново, когда были проблемы с тестами на прошлой неделе. Я вернул название папки Lab1C. Только это было поменяно. Больше ничего не трогал.

2023-10-03 09:10 UTC, Dovgalyuk commented
Во вкладке Files changed можно увидеть их все.

2023-10-03 17:12 UTC, closed without merging