up
Dovgalyuk/Algorithms pull request #607
Opened 2023-09-28 18:54 UTC by ekaterina209

2023-09-29 07:14 UTC, ekaterina209 commented
Все сбилдилось, тест на array прошло, остальное не проходит
![image](https://github.com/Dovgalyuk/Algorithms/assets/114601312/5a8afefe-2347-4915-acd8-176ec13d5d0c)
![image](https://github.com/Dovgalyuk/Algorithms/assets/114601312/6400e31b-d00a-4a5b-883e-7faf154988b8)

2023-09-29 08:21 UTC, Dovgalyuk requested changes

2023-09-29 08:21 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +void count(Array *arr, Data value, int &znach) { //���������� ����������� ���������� ������
Лучше результат возвращать, а не записывать по ссылке.

2023-09-29 08:21 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +	vector<Data> replays(0);
Можно обойтись без этого массива.

2023-10-02 08:01 UTC, Dovgalyuk requested changes

2023-10-02 08:01 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +void examination(size_t &size) { //�������� �� ��������� ����
Лучше size возвращать, а не передавать переменную для этого по ссылке.

2023-10-03 09:22 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +	cout << "Enter array length:";
А тут зачем выводится ещё одно сообщение?

2023-10-04 05:12 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
* Решить задачу, используя реализованный стек.

Преобразовать корректное арифметическое выражение, использующее операции сложения, вычитания, умножения и деления, в арифметическое выражение в обратной польской записи. Программа должна учитывать приоритет операторов умножения и деления и использовать стек. Операндами в выражении являются однобуквенные переменные.

Входные данные
```
A+B*C+D
```
Выходные данные
```
ABC*+D+
```

Входные данные
```
A*B+C
```
Выходные данные
```
AB*C+
```

Входные данные
```
A+B*(C+D)
```
Выходные данные
```
ABCD+*+
```

2023-10-04 05:12 UTC, closed without merging