1lab
Dovgalyuk/Algorithms pull request #608
Opened 2023-09-30 09:05 UTC by MKBA13

Хаванов М.Ю. 2093

2023-10-02 07:44 UTC, Dovgalyuk commented
Проект должен компилироваться (см. отчёт CMake build).

2023-10-02 12:44 UTC, MKBA13 commented
add_executable(Lab1C "lab1.cpp"). Здесь у меня отсутствовали двойные кавычки. Попробуйте. В среду подойду.

2023-10-03 09:38 UTC, Dovgalyuk commented
Осталось несколько ошибок сборки.

2023-10-06 05:59 UTC, MKBA13 commented
Проблемы со cmake продолжаются. На этот раз проект скомпилировался, но не могу запустить. 
![2](https://github.com/Dovgalyuk/Algorithms/assets/144269975/ddce6384-8226-4c17-b22e-04a887b531a5)
![1](https://github.com/Dovgalyuk/Algorithms/assets/144269975/5030e23c-8674-4f98-bac7-28eb8600a297)

2023-10-06 19:13 UTC, MKBA13 commented
Разобрался... Запускается. В понедельник-вторник отошлю очередную версию.

2023-10-09 06:22 UTC, MKBA13 commented
Что делать с этим тестом? cppcheck-action-test / cppcheck-test (pull_request). Оно похоже не работает из-за ошибки, которую присылал ранее. У себя я её обошёл, назначив Lab1C в качестве собираемого проекта.

2023-10-09 06:46 UTC, MKBA13 commented
У меня не отработал тест cppcheck-action-test / cppcheck-test (pull_request) пишет не найдён файл array.h 
С чем это связано я не понял.

2023-10-09 07:43 UTC, Dovgalyuk commented
> У меня не отработал тест cppcheck-action-test / cppcheck-test (pull_request) пишет не найдён файл array.h С чем это связано я не понял.

Потому что он не знает о структуре каталогов в проекте, можно не обращать на это внимание.

2023-10-09 07:44 UTC, Dovgalyuk commented
> У меня не отработал тест cppcheck-action-test / cppcheck-test (pull_request) пишет не найдён файл array.h С чем это связано я не понял.

Потому что он не знает о структуре каталогов в проекте, можно не обращать на это внимание.

2023-10-09 07:47 UTC, Dovgalyuk requested changes

2023-10-09 07:47 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +        else if (array_get(arr, i) == 0)
Тут похоже не тот индекс используется.

2023-10-11 13:39 UTC, MKBA13 commented
Всё!

2023-10-12 05:56 UTC, MKBA13 commented
Всё!

2023-10-12 08:14 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

Написать программу, моделирующую работу стека ограниченного объема. В качестве входных данных программа получает максимально возможный размер стека и последовательность команд: push N – занести число N в стек, pop – достать число из стека и напечатать его. Если стек переполняется или производится попытка извлечь значение из пустого стека, программа должна печатать одно из сообщений: BAD PUSH или BAD POP. После окончания работы программы, она должна напечатать текущее состояние стека.

Входные данные
```
2
push 3
push 2
push 4
pop
push 1
```
Выходные данные
```
BAD PUSH
2
STACK
3
1
```

2023-10-12 08:14 UTC, closed without merging