Супрун Роман 2091 Lab1
Dovgalyuk/Algorithms pull request #609
Opened 2023-09-30 18:15 UTC by PieDIEmaN

2023-09-30 18:16 UTC, PieDIEmaN commented
![изображение](https://github.com/Dovgalyuk/Algorithms/assets/113968388/2729f218-b376-4374-aadb-fe9b246d5583)
Все сбилдилось, но не все тесты прошли.

2023-09-30 18:21 UTC, PieDIEmaN commented
Исправил ввод данных

2023-10-02 07:57 UTC, Dovgalyuk requested changes

2023-10-02 07:57 UTC, Dovgalyuk commented on LibraryC/array.cpp
> +#include "array.h"
Не нужно модифицировать файлы, не относящиеся к выполнению задания.

2023-10-02 07:57 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +        sum += elem; // ��������� ��� �������� �������
В задании требуется искать два разных средних арифметических.

2023-10-02 07:57 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +    second(arr); // ��������� ������ �������
Массив нужно удалить.

2023-10-02 14:28 UTC, PieDIEmaN commented
![изображение](https://github.com/Dovgalyuk/Algorithms/assets/113968388/99215002-fe79-4845-b306-df02e082ffb6)
Все сбилдилось, ошибки исправил.

2023-10-03 09:32 UTC, Dovgalyuk requested changes

2023-10-03 09:32 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +        sum += elem; // ��������� ��� �������� �������
Не исправлено.

2023-10-03 09:32 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +    second(arr); // ��������� ������ �������
И это.

2023-10-03 09:32 UTC, Dovgalyuk commented on LibraryC/array.cpp
> +#include "array.h"
И это.

2023-10-05 06:24 UTC, Dovgalyuk requested changes

2023-10-05 06:24 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +    ariph = ((float)sum / (float)count); // Вычисляем среднее арифметическое положительных
sum накапливает отрицательные числа

2023-10-05 06:24 UTC, Dovgalyuk commented on LibraryC/array.cpp
> +#include "array.h"
Это осталось.

2023-10-06 05:39 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
* Решить задачу, используя реализованный стек.

Преобразовать арифметическое выражение в ассемблерные опреации работы со стеком и регистрами.
Используются команды PUSH (занести в стек), POP (извлечь из стека в регистр), ADD (сложить),
SUB (вычесть), MUL (перемножить). Достаточно использовать два регистра A и B.

Входные данные
```
1+2*3
```
Выходные данные
```
PUSH 1
PUSH 2
PUSH 3
POP A
POP B
MUL A, B
PUSH A
POP A
POP B
ADD A, B
PUSH A
```

Входные данные
```
(1+2)*3
```
Выходные данные
```
PUSH 1
PUSH 2
POP A
POP B
ADD A, B
PUSH A
PUSH 3
POP A
POP B
MUL A, B
PUSH A
```

2023-10-06 05:39 UTC, closed without merging