Lab2 Prokopenko Andrey 2091
Dovgalyuk/Algorithms pull request #610
Opened 2023-10-01 10:12 UTC by Ynic2

2023-10-01 19:11 UTC, Ynic2 commented
Не работает файл с тестом, потому что вектор создается без параметра в тесте
![image](https://github.com/Dovgalyuk/Algorithms/assets/63044918/6eaabdef-e2d7-41e8-941d-ff1a329c83fa)

2023-10-02 08:03 UTC, Dovgalyuk commented
Либо нужно не изменять заголовочный файл (оставив функцию как есть), либо поменять тест.

2023-10-02 08:23 UTC, Ynic2 commented
Починил vector, но тест со стэком не работает, т.к. у меня вводятся char в стэк, а не int
![image](https://github.com/Dovgalyuk/Algorithms/assets/63044918/32100450-e822-4e02-8f37-55efbd0f0739)
![image](https://github.com/Dovgalyuk/Algorithms/assets/63044918/2aebac5b-d744-4d75-b03f-b6536eb46d48)

2023-10-03 09:09 UTC, Dovgalyuk commented
> Починил vector, но тест со стэком не работает, т.к. у меня вводятся char в стэк, а не int

char тоже целочисленный тип, поэтому можно хранить значения в стеке с int.
Либо поменять стек на char и исправить тест.

2023-10-03 11:25 UTC, Ynic2 commented
Необходимые тесты проходит, все билдится
![image](https://github.com/Dovgalyuk/Algorithms/assets/63044918/28ff1ea2-5c47-4cfa-90fa-c97247d17d64)

2023-10-04 05:38 UTC, Dovgalyuk requested changes

2023-10-04 05:38 UTC, Dovgalyuk commented on Labs/lab2.cpp
> +	char* c = const_cast<char*>(str.c_str()); //������ �� string char*, ����� ���������� � Data
Тут надо использовать const char *

2023-10-04 05:38 UTC, Dovgalyuk commented on Labs/lab2.cpp
> +		stack_push(stack, c[i]);
Стек нужен, чтобы непосредственно проверять порядок, а не просто хранить скобки.
Когда открывающая скобка - добавляем в стек. Когда закрывающая - удаляем.

2023-10-04 05:38 UTC, Dovgalyuk commented on LibraryCPP/lab2.cpp
> +#include <iostream>
В библиотку не надо добавлять файл с решением.

2023-10-04 05:38 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +    Stack() {
Одинокий конструктор только путает. Лучше вынести этот код в функцию stack_create.

2023-10-04 05:38 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +    if (size == 0) {
Можно написать return size == 0;

2023-10-04 05:38 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +Stack* stack_copy(const Stack* stack)
А это зачем?

2023-10-05 16:41 UTC, Ynic2 commented
![image](https://github.com/Dovgalyuk/Algorithms/assets/63044918/9a2c46d9-d688-47cc-943a-70cf623e6a3f)
Проходит все нужные тесты
Изначально неправильно понял задание, сейчас вроде все верно

2023-10-06 05:34 UTC, Dovgalyuk requested changes

2023-10-06 05:34 UTC, Dovgalyuk commented on LibraryCPP/lab2.cpp
> +#include <iostream>
Этот файл надо удалить.

2023-10-06 05:34 UTC, Dovgalyuk commented on Labs/lab2.cpp
> +				for (size_t j = i + 1; j < size; j++) {
Это не нужно. Достаточно поочерёдно обрабатывать все скобки в основном цикле.

2023-10-06 05:34 UTC, Dovgalyuk commented on Labs/lab2.cpp
> +	if (size % 2 == 0) {
Хоть и ускорение для отдельно взятого случая, но усложняет код.
Такие вещи оправданны только если обрабатывается много входных данных сразу. Тогда часть из них будет отсеяна.

2023-10-06 07:45 UTC, Ynic2 commented
![image](https://github.com/Dovgalyuk/Algorithms/assets/63044918/4595c5ea-cd92-41bd-ba35-d8e937a08cd2)
Удалил файл, исправил через один for, убрал проверку длины на четность

2023-10-06 14:25 UTC, Ynic2 commented
![273139872-4595c5ea-cd92-41bd-ba35-d8e937a08cd2](https://github.com/Dovgalyuk/Algorithms/assets/63044918/0f454e86-d140-4a6d-a078-891e44b11f6c)
Удалил файл, исправил через один for, убрал проверку длины на четность

2023-10-09 06:57 UTC, Dovgalyuk commented on Labs/lab.cpp
> +}
Как насчёт такого примера: ]]]

2023-10-10 22:36 UTC, Ynic2 commented
![image](https://github.com/Dovgalyuk/Algorithms/assets/63044918/04a43bcb-a310-46f6-af95-6609195f5323)
Тесты проходит, исправил код

2023-10-11 05:40 UTC, Dovgalyuk commented on Labs/lab.cpp
> +}
Теперь такой пример: [)

2023-10-12 07:52 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и очередь на основе этого списка (модуль queue).
* Решить задачу, используя реализованную очередь.

Задан ориентированный граф виде матрицы смежности. Написать программу для определения длины кратчайшего пути от одной вершины для другой. В первой строке входного файла записано количество вершин, номер стартовой вершины и номер финишной. В последующих строках идет описание матрицы смежности. Значения 0 в матрице обозначают отсутствие ребра. В выходной файл выводится длина кратчайшего пути. Если решения не существует – выводится IMPOSSIBLE. Программа должна использовать поиск в ширину на основе очереди.

Входные данные
```
4 1 4
0 1 1 0
0 0 0 0
0 1 0 1
0 0 1 0
```
Выходные данные
```
2
```

2023-10-12 07:52 UTC, closed without merging