Лабораторная работа 1
Dovgalyuk/Algorithms pull request #612
Opened 2023-10-01 17:38 UTC by Evvadium

Лабораторная работа 1
Речкин Вадим группа 2091

2023-10-02 07:45 UTC, Dovgalyuk commented
Нужно исправить конфликт изменений в CMakeLists.txt, чтобы запустилась сборка на сервере.

2023-10-02 16:44 UTC, Evvadium commented
Исправил

2023-10-03 09:34 UTC, Dovgalyuk commented
Теперь надо посмотреть отчёт CMake build и исправить ошибки сборки.

2023-10-06 04:21 UTC, Dovgalyuk commented
Тест для Array нужно оставить, чтобы он запускался на сервере.

2023-10-12 07:41 UTC, Dovgalyuk requested changes

2023-10-12 07:41 UTC, Dovgalyuk commented on Lab1C/Source.cpp
> +    }
Нужна сумма элементов, которые в массиве между минимальным и максимальным, а не по значению.

2023-10-13 05:15 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

Написать программу, работу процессора со стеком. Процессор имеет 4 регистра, обозначенных буквами A, B, C, D. Во входном файле присутствуют операции PUSH и POP. Операция PUSH может иметь в качестве параметра число или регистр. Операция POP в качестве параметра имеет регистр и считывает в него значение с вершины стека. После выполнения последовательности операций программа должна распечатать содержимое регистров.

Входные данные
```
PUSH 1
POP B
```
Выходные данные
```
A = 0
B = 1
C = 0
D = 0
```

Входные данные
```
PUSH 1
PUSH 2
POP B
POP C
PUSH C
POP D
```
Выходные данные
```
A = 0
B = 2
C = 1
D = 1
```

2023-10-13 05:15 UTC, closed without merging