Кудряшов 1 лаб
Dovgalyuk/Algorithms pull request #620
Opened 2023-10-04 09:47 UTC by Salazar4ever

2023-10-05 06:16 UTC, Dovgalyuk commented
Нужно удалить временные файлы из репозитория.

2023-10-09 09:24 UTC, Salazar4ever commented
Я не понимаю. Что сделать-то нужно?

2023-10-10 07:10 UTC, Dovgalyuk commented
Посмотрел в чём изменения. Не нужно удалять все файлы из оригинального репозитория.
Это затрудняет просмотр изменений. Нужно добавить только своё решение и реализовать свой контейнер.
Другие файлы добавлять или удалять не нужно.

2023-10-12 07:50 UTC, Dovgalyuk commented
Зачем одновременно изменять array в LibraryC и в LibraryCPP?

2023-10-12 14:26 UTC, Salazar4ever commented
Я сначала начал делать в C, но потом передумал и сделал в CPP. Те изменения отменить забыл.

2023-10-13 05:18 UTC, Dovgalyuk commented
CMake пишет, что тест не проходит.

2023-10-16 05:15 UTC, Dovgalyuk requested changes

2023-10-16 05:15 UTC, Dovgalyuk commented on Lab1CPP/lab1.cpp
> +    cout << "\nNumber of rainy days: " << rainyDays << "\nAmount of precipitation per month: " << precipitation << "\nAverage precipitation: " << (float)precipitation / rainyDays << endl;
А если не было ни одного дождливого дня?

2023-10-16 05:15 UTC, Dovgalyuk commented on Lab1CPP/lab1.cpp
> +            curDifference = -abs(array_get(tempArr, i) - array_get(tempArr, j));
Какой смысл в минусе перед abs?

2023-10-16 09:48 UTC, Salazar4ever commented on Lab1CPP/lab1.cpp
> +            curDifference = -abs(array_get(tempArr, i) - array_get(tempArr, j));
В задании сказано: "Найти минимальную разность между разными чётными элементами массива". 
Я подумал, что нужно взять результат вычитания двух чисел, а потом найти среди всех этих результатов минимальное. Возьмем два числа, например, 2 и 6. Можно вычесть 2 из 6 и получить 4, а можно вычесть 6 из 2 и получить -4. Поскольку по модулю результат один, то я вместо 2 операций вычитания и сравнения нахожу наименьший модуль, который является отрицательным.

2023-10-17 06:00 UTC, Dovgalyuk commented on Lab1CPP/lab1.cpp
> +            curDifference = -abs(array_get(tempArr, i) - array_get(tempArr, j));
Ну почему для первых двух не надо ставить минус, а для остальных надо?

2023-10-18 05:17 UTC, Dovgalyuk commented on Lab1CPP/lab1.cpp
> +            curDifference = -abs(array_get(tempArr, i) - array_get(tempArr, j));
Для начала, что будет для такого примера:
2 4 8

2023-10-18 20:21 UTC, Salazar4ever commented on Lab1CPP/lab1.cpp
> +            curDifference = -abs(array_get(tempArr, i) - array_get(tempArr, j));
-6

2023-10-19 11:42 UTC, Dovgalyuk commented on Lab1CPP/lab1.cpp
> +            curDifference = -abs(array_get(tempArr, i) - array_get(tempArr, j));
А должно быть 2.

2023-10-20 08:57 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library двусвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

Написать программу, работу процессора со стеком. Процессор имеет 4 регистра, обозначенных буквами A, B, C, D. Во входном файле присутствуют операции PUSH и POP. Операция PUSH может иметь в качестве параметра число или регистр. Операция POP в качестве параметра имеет регистр и считывает в него значение с вершины стека. После выполнения последовательности операций программа должна распечатать содержимое регистров.

Входные данные
```
PUSH 1
POP B
```
Выходные данные
```
A = 0
B = 1
C = 0
D = 0
```

Входные данные
```
PUSH 1
PUSH 2
POP B
POP C
PUSH C
POP D
```
Выходные данные
```
A = 0
B = 2
C = 1
D = 1
```

2023-10-20 08:57 UTC, closed without merging