Igor Andreev 2093 laba1
Dovgalyuk/Algorithms pull request #623
Opened 2023-10-05 12:25 UTC by IgorAndreev24

^_^

2023-10-06 04:31 UTC, Dovgalyuk commented
Проект не собирается (см. отчёт CMake build)

2023-10-09 13:38 UTC, IgorAndreev24 commented
Вроде сделал commit поменял make файлы, на visual studio Lab1.exe запустился

2023-10-09 21:08 UTC, IgorAndreev24 commented
![image](https://github.com/Dovgalyuk/Algorithms/assets/144487334/08e2ae6f-0aef-49b9-8235-3e6c822c61f7)
А что это обозначает?

2023-10-10 07:21 UTC, Dovgalyuk commented
> ![image](https://user-images.githubusercontent.com/144487334/273697800-8c921ba5-1fb5-4a05-aea3-380b6ec30907.png) А что это обозначает?

Этот отчёт можно игнорировать, он сейчас неисправен.

2023-10-10 07:26 UTC, Dovgalyuk requested changes

2023-10-18 16:51 UTC, IgorAndreev24 commented
Все переделал, очень много тупил с сравнением типов, пришлось использовать size_t везде, для того что бы не было утечек данных

2023-10-19 11:22 UTC, Dovgalyuk commented
Принято.


* Реализовать в проекте Library двусвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

Преобразовать арифметическое выражение в ассемблерные опреации работы со стеком и регистрами.
Используются команды PUSH (занести в стек), POP (извлечь из стека в регистр), ADD (сложить),
SUB (вычесть), MUL (перемножить). Достаточно использовать два регистра A и B.

Входные данные
```
1+2*3
```
Выходные данные
```
PUSH 1
PUSH 2
PUSH 3
POP A
POP B
MUL A, B
PUSH A
POP A
POP B
ADD A, B
PUSH A
```

Входные данные
```
(1+2)*3
```
Выходные данные
```
PUSH 1
PUSH 2
POP A
POP B
ADD A, B
PUSH A
PUSH 3
POP A
POP B
MUL A, B
PUSH A
```

2023-10-19 11:22 UTC, closed without merging