lab 1
Dovgalyuk/Algorithms pull request #626
Opened 2023-10-08 12:52 UTC by Gebrur

У вас похоже была опечатка  в задании два раза было написано нечетные поэтому я взял n  как четные и у меня почему то не вышло протестить локально

2023-10-08 13:23 UTC, Gebrur commented
у меня такая проблема нельзя посмотреть checks 
![image](https://github.com/Dovgalyuk/Algorithms/assets/146195758/d4c584a9-4d89-46af-b8cd-fcb6b8fe4522)

2023-10-09 07:35 UTC, Dovgalyuk commented
В задании опечатки нет, там написано разное.

2023-10-09 08:29 UTC, Gebrur commented
Понял, не увидел что там номера элементов и код не компилируется из за глупой ошибки сегодня приду исправлю

2023-10-10 07:19 UTC, Dovgalyuk requested changes

2023-10-10 07:19 UTC, Dovgalyuk commented on .vscode/settings.json
> +{
папку .vscode выкладывать не нужно

2023-10-10 07:19 UTC, Dovgalyuk commented on Labs/lab1.cpp
> +        //использовал логику того что элементы с нечетными номерами  и  нечетные элементы идут друг за другом
нечётные элементы и элементы с нечётными номерами не обязательно идут друг за другом

2023-10-10 07:19 UTC, Dovgalyuk commented on Labs/lab1.cpp
> +        for (size_t i = 0; i < size; i++)
А тут зачем цикл, если мы уже вызываем эту функцию в цикле?

2023-10-11 15:04 UTC, Gebrur commented
внес изменения в код исправил  логику в первом таске но не знаю чем именно мне считать первое число у него нулевой индекс и оно нечетный элемент во втором таске убрал функцию и просто используя два цикла проверяю делится ли число на все другие числа в массиве потом проверяю следующее число и так далее

2023-10-12 08:00 UTC, Dovgalyuk requested changes

2023-10-12 16:05 UTC, Gebrur commented
удалил папку и внес ее в gitignore

2023-10-13 05:29 UTC, Dovgalyuk requested changes

2023-10-13 05:29 UTC, Dovgalyuk commented on Labs/lab1.cpp
> +            array_set(arr, i, value + n);
Здесь нужно изменять элементы с нечётными номерами.

2023-10-13 11:29 UTC, Gebrur commented
изначально неправильно понял что такое нечетный элемент думал что это нечетный элемент по позиции в массиве, исправил первое задание теперь если число и нечетное и имеет нечетный индекс его сразу и уменьшится и увеличится

2023-10-16 05:10 UTC, Dovgalyuk commented on Labs/lab1.cpp
> +    }
Можно сделать две проверки, но без else. Тогда не придётся три ветки условия писать.

2023-10-16 05:49 UTC, Gebrur commented
Я пытался сделать двумя проверками но в случае если элемент массива подходит сразу по двум проверкам (нечетный и с нечетным индексом ) выполняется только одно действие хотя должны выполняться оба

2023-10-16 05:51 UTC, Gebrur commented
Так что я сделал три проверки для того чтобы данные случаи тоже проверялись

2023-10-17 05:47 UTC, Dovgalyuk commented
> Я пытался сделать двумя проверками но в случае если элемент массива подходит сразу по двум проверкам (нечетный и с нечетным индексом ) выполняется только одно действие хотя должны выполняться оба

Чтобы выполнялись оба, не нужно писать else.

2023-10-17 07:55 UTC, Gebrur commented
Я пытался сделать просто двумя if но когда должно выполняться сразу два условия выполняется только одно и чтобы код выполнял свою работу полностью мне пришлось написать третье условие для проверки двух случаев сразу, с двумя проверками код работает не правильно

2023-10-17 10:57 UTC, Gebrur commented
Хотя я скорее всего понимаю про что вы говорите я переделаю и посмотрю как будет работать код

2023-10-18 09:38 UTC, Gebrur commented
Попытался сделать с помощью только двух if без else вот что вывело 
![image](https://github.com/Dovgalyuk/Algorithms/assets/146195758/b964ca8c-fcc8-4835-a33c-42d84ecdf363)
в изначальном массиве есть два числа на нечетных элементах 94 и 39, 94 увеличивается на 10 как и должно а 39 только уменьшается как нечетное число при это оно имеет нечетный индекс и должно увеличится тоже, но этого не происходит

2023-10-18 09:47 UTC, Gebrur commented
код с 3 условиями у меня работает корректно а с двумя в некоторых случаях работает некорректно

2023-10-19 11:03 UTC, Dovgalyuk commented
А можно увидеть вариант, который работает не так, как нужно?

2023-10-20 07:19 UTC, Gebrur commented
Если нужен то что выводит то это первый вариант если нужен сам код скину как будет возможность

2023-10-20 12:37 UTC, Gebrur commented
![image](https://github.com/Dovgalyuk/Algorithms/assets/146195758/7a4d987e-1d2d-4819-9a11-6969221bf584)
вот вариант который работает неправильно просто два if без else

2023-10-23 10:05 UTC, Dovgalyuk commented
> ![image](https://user-images.githubusercontent.com/146195758/276932084-7a4d987e-1d2d-4819-9a11-6969221bf584.png) вот вариант который работает неправильно просто два if без else

Надо или обновлять value, или перед вторым if считывать его заново.

2023-10-23 14:23 UTC, Gebrur commented
Исправил все работает как надо

2023-10-24 09:26 UTC, closed without merging