Дописал массив
Dovgalyuk/Algorithms pull request #629
Opened 2023-10-10 11:20 UTC by Myfasick

2023-10-11 05:20 UTC, Dovgalyuk commented
Проект должен собираться (см. отчёт CMake build)

2023-10-12 07:54 UTC, Dovgalyuk commented
Теперь нужно удалить из репозитория временные файлы и откатить изменения, не имеющие отношения к решению задачи.

2023-10-12 22:14 UTC, Myfasick commented
Откатил, у себя подтер ненужную историю ошибочных коммитов, удалил временные файлы

2023-10-13 05:24 UTC, Dovgalyuk requested changes

2023-10-13 05:24 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +size_t findSmallestPosition(Array *arr, size_t startPosition, size_t listLength)
Длину же можно запросить у массива.

2023-10-13 05:24 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +    return;
return без аргумента в конце не нужно писать

2023-10-13 05:24 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +    int minDiff = array_get(arr, 1) - array_get(arr, 0);
В задании сказано искать разность между чётными элементами.

2023-10-15 08:28 UTC, Myfasick commented
Исправил

2023-10-16 05:16 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +    int minDiff = array_get(arr, 1) - array_get(arr, 0);
А если первые два элемента нечётные? Или один из них?

2023-10-18 05:21 UTC, Dovgalyuk requested changes

2023-10-18 05:21 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +    for (size_t i = 2; i != size; i++)
Почему начиная с 2?

2023-10-18 05:21 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +            minDiff = min(minDiff, array_get(arr, i) - array_get(arr, i - 2));
Почему i-2?

2023-10-18 10:56 UTC, Myfasick commented on Lab1C/lab1.cpp
> +    for (size_t i = 2; i != size; i++)
Забыл поправить

2023-10-19 11:11 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +}
Как насчёт примера:
1 3 5 8 10

2023-10-19 13:08 UTC, Myfasick commented on Lab1C/lab1.cpp
> +}
Понял, поправил

2023-10-20 08:50 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +    vector<int> nambers;
vector использовать нельзя. Надо брать либо такой же array, либо обойтись без второго хранилища.

2023-10-20 10:22 UTC, Myfasick commented on Lab1C/lab1.cpp
> +    vector<int> nambers;
Принял

2023-10-23 10:20 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +    nambers = array_create(size);
Его ещё удалять нужно.

2023-10-23 14:18 UTC, Myfasick commented on Lab1C/lab1.cpp
> +    nambers = array_create(size);
Поправил

2023-10-24 09:23 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
* Решить задачу, используя реализованный стек.

Написать программу, которая с помощью стека проверяет правильность последовательности из скобок вида (), [], {} и <>. В выходной файл напечатать YES, если последовательность правильная и NO, если неправильная.

Входные данные
```
([])<>
```
Выходные данные
```
YES
```

Входные данные
```
()>
```
Выходные данные
```
NO
```

2023-10-24 09:23 UTC, closed without merging