lab2 Пусеп А.В. 2091
Dovgalyuk/Algorithms pull request #630
Opened 2023-10-10 12:48 UTC by alexeypusep

2023-10-11 05:33 UTC, Dovgalyuk requested changes

2023-10-11 05:33 UTC, Dovgalyuk commented on Lab1CPP/lab2.cpp
> +#include "list.h"
Список вроде здесь не нужен.

2023-10-11 05:33 UTC, Dovgalyuk commented on Lab1CPP/lab2.cpp
> +            while (get_level_operation(stack_get(stack_for_operation_signs)) >= get_level_operation(input_expression[i])) //Пока уровень приоритета элемента на вершине стека больше или равен текущему
Нехорошо, что в циклах не проверяется, что стек не пустой.

2023-10-11 05:33 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    if (item_new == nullptr)
Так не может быть, new выбрасывает исключение в случае нехватки памяти.

2023-10-13 07:47 UTC, alexeypusep commented
Исправил ваши замечания

2023-10-16 05:09 UTC, Dovgalyuk commented
Принято.


* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.

Задан неориентированный граф. Написать программу для определения длины кратчайшего пути от одной вершины для другой. В первой строке входного файла записано количество вершин, номер стартовой вершины и номер финишной. В последующих строках идут описания ребер, заданные номерами вершин, которые они соединяют. В выходной файл выводится длина кратчайшего пути. Если решения не существует – выводится IMPOSSIBLE. Программа должна использовать поиск в ширину на основе очереди.

Входные данные
```
4 1 2
1 3
1 4
3 2
4 3
```
Выходные данные
```
2
```

2023-10-16 05:09 UTC, closed without merging