Lab1, Матвеев Кирилл, гр. 2093
Dovgalyuk/Algorithms pull request #635
Opened 2023-10-16 08:47 UTC by playnikov

2023-10-17 05:59 UTC, Dovgalyuk requested changes

2023-10-17 05:59 UTC, Dovgalyuk commented on CMakeSettings.json
Это выкладывать не нужно.

2023-10-17 05:59 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +#include "array.cpp"
Подключать надо заголовочные файлы, а не с реализацией контейнера.

2023-10-17 05:59 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +    cout << "result: " << array_get(arr, index);
Вот для этого примера не сработает
6 3 4 1 1

2023-10-17 05:59 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +    bool flag = 1;
не стоит записывать в bool числа, лучше написать true или false

2023-10-17 05:59 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +}
Это вообще не работает.

2023-10-17 05:59 UTC, Dovgalyuk commented on Labs/lab1.cpp
Зачем второй раз одно и то же?

2023-10-17 10:23 UTC, playnikov commented
В labs рабочий вариант. 
1) Первое задание на примере 6 3 4 1 1 работает. Выводит 3
2) Исправил второе задание, работает

2023-10-18 05:30 UTC, Dovgalyuk requested changes

2023-10-18 05:30 UTC, Dovgalyuk commented on CMakeSettings.json
Этот файл не нужен.

2023-10-19 11:41 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
* Решить задачу, используя реализованный стек.

Во входном файле записана последовательность тегов в формате HTML. Каждый тег расположен на отдельной строке. Используя стек, проверить правильность этой последовательности. Вывести в выходной файл YES, если последовательность корректна и NO, если нет.

Входные данные
```
<HTML>
<Body>
</body>
</HTML>
```
Выходные данные
```
YES
```

Входные данные
```
<HTML>
</body>
```
Выходные данные
```
NO
```

2023-10-19 11:41 UTC, closed without merging