Pr/568
Dovgalyuk/Algorithms pull request #638
Opened 2023-10-16 14:29 UTC by Ivan20030

Lab1SudevIvan

2023-10-17 06:13 UTC, Dovgalyuk commented
Нужно разобраться с конфликтующими изменениями в CMakeLists.txt, чтобы мого запуститься тестирование на сервере.

2023-10-17 08:49 UTC, Ivan20030 commented
Здравствуйте, исправил предыдущие ошибки

2023-10-18 05:22 UTC, Dovgalyuk commented
Проект не собирается (см. отчёт CMake build)

2023-10-18 09:06 UTC, Ivan20030 commented
На этот раз должен собраться

2023-10-18 09:26 UTC, Ivan20030 commented
Вот сейчас точно

2023-10-19 11:01 UTC, Dovgalyuk requested changes

2023-10-19 11:01 UTC, Dovgalyuk commented on .github/workflows/clangtidy.yml
Этот файл не надо удалять.

2023-10-19 11:01 UTC, Dovgalyuk commented on CMakeSettings.json
А этот нужно удалить.

2023-10-19 11:14 UTC, Ivan20030 commented
Удалил и добавил

2023-10-20 08:39 UTC, Dovgalyuk requested changes

2023-10-20 08:39 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +        Array* vec = NULL;
Для первого и последнего индексов достаточно двух переменных. Целый массив для них не нужен.

2023-10-23 10:28 UTC, Dovgalyuk requested changes

2023-10-23 10:28 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +        }
А что должно быть для примера 3 3 3 ?

2023-10-24 09:11 UTC, Ivan20030 commented
Исправил функцию MinMax

2023-10-24 09:50 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

Во входном файле записана последовательность операций со стеком JAVA-машины.
Упрощённая JAVA-машина может оперировать стеком и четырьмя локальными переменными с номерами от 0 до 3.
Выполнить операции и напечатать финальное состояние стека и переменных.

Список операций, которые должны поддерживаться:
* bipush число - занести число в стек
* pop - вытолкнуть верхнее значение со стека
* imul - умножение
* iand - побитовое "и"
* ior - побитовое "или"
* ixor - операция "исключающее или"
* iadd - сложение
* isub - вычитание
* iload_0, iload_1, iload_2, iload_3 - занести в стек значение соответствующей переменной
* istore_0, istore_1, istore_2, istore_3 - записать значение с вершины стека в соответствующую переменную
* swap - меняет местами два верхних значения в стеке

Все арифметические операции берут операнды с вершины стека, а затем записывают в стек результат вычислений.

Входные данные
```
bipush 1
bipush 2
bipush 3
iadd
istore_0
```
Выходные данные
```
stack:
1
vars:
5
0
0
0
```

2023-10-24 09:50 UTC, closed without merging