lab2
Dovgalyuk/Algorithms pull request #649
Opened 2023-10-19 17:44 UTC by stmay4

2023-10-20 09:00 UTC, Dovgalyuk commented
Тест для вектора должен проходить.

2023-10-20 16:04 UTC, stmay4 commented
Тест для вектора пройден

2023-10-23 10:18 UTC, Dovgalyuk requested changes

2023-10-23 10:18 UTC, Dovgalyuk commented on Lab1C/lab2.c
> +	case 1:
Когда одно число много раз встречается как идентификатор, надо объявить именованную константу.

2023-10-23 10:18 UTC, Dovgalyuk commented on LibraryC/vector.c
> +			vector->maxsize = 2 * size;
Тут же никуда не пропадают запасные элементы, зачем менять maxsize?

2023-10-28 15:37 UTC, stmay4 commented
Добавил именованные константы, изменил vector_resize.

2023-10-30 09:22 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library кольцевой двусвязный список (модуль list) и очередь на основе этого списка (модуль queue).
* Решить задачу, используя реализованную очередь.

Задан список двунаправленных дорог, соединяющих города и названия городов между которыми нужно найти кратчайший путь. Написать программу, находящую кратчайший путь с помоью поиска в ширину и вывести в выходной файл список городов, которые нужно посетить, чтобы добраться из начального города в конечный.

Входные данные
```
City1 City2
City2 End
Start City1
Start End
```
Выходные данные
```
Start City1 City2 End
```

В примере задано 3 дороги: City1-City2, City2-End, Start-City1. Последние 2 города в списке – начальный и конечный города в искомом пути.

2023-10-30 09:22 UTC, closed without merging