Индивидуальное задание Лопатин Д. М. 9091
Dovgalyuk/Algorithms pull request #65
Opened 2020-09-03 12:56 UTC by Lapohuy

2020-09-05 13:07 UTC, Lapohuy commented
Переделанное индивидуальное задание 1 залито.

2020-09-05 17:50 UTC, Lapohuy commented
Косметические доработки; исправлен недочет с типами данных.

2020-09-07 07:23 UTC, Dovgalyuk commented
Для начала стоит удалить временные файлы.

2020-09-07 07:38 UTC, Lapohuy commented
А что за временные файлы? В последних двух изменениях затронуты три основных файла - array.cpp, main.cpp из папки с индивидуальным заданием и CmakeLists.txt к нему. Что из этого считается временными файлами?

2020-09-07 07:39 UTC, Dovgalyuk commented
Нажми files changed - там их видно.

2020-09-07 08:09 UTC, Dovgalyuk commented
Ещё не всё.

2020-09-07 08:14 UTC, Lapohuy commented
Остальные три не удаляются. Там кнопка делит не активна

2020-09-07 08:18 UTC, Dovgalyuk commented
Стоит попробовать командную строку.

2020-09-07 10:10 UTC, Lapohuy commented
Ну, теперь вроде как все

2020-09-07 10:50 UTC, Dovgalyuk requested changes

2020-09-07 10:50 UTC, Dovgalyuk commented on LibraryCPP/array.cpp
> +	delete[] arr;
Второй оператор должен быть просто delete, так как память выделялась с помощью обычного new.

2020-09-07 10:50 UTC, Dovgalyuk commented on IndividualTask/main.cpp
> +	search_low_avg(arr, size);
Есть же функция array_size, так что size никуда передавать не надо.

2020-09-07 12:45 UTC, Lapohuy commented
Исправлены оба недочета

2020-09-07 13:23 UTC, Dovgalyuk commented
1. Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
    2. Решить задачу, используя реализованный стек.
Дано корректное выражение в обратной польской записи. Используя стек, написать калькулятор, считающий значение этого выражения.

Вход | Выход
-- | --
1 			2 			+ 			3 			* | 9
2 			10 			9 			- 			+ | 3

2020-09-07 13:23 UTC, closed without merging