Lab1
Dovgalyuk/Algorithms pull request #650
Opened 2023-10-19 17:56 UTC by MAlutinS

2023-10-20 08:59 UTC, Dovgalyuk commented
Проект должен успешно собираться на сервере (см. отчёт CMake build)

2023-10-23 10:03 UTC, Dovgalyuk requested changes

2023-10-23 10:03 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +    sum /=array_size(arr);
Надо искать среднее арифметическое положительных элементов.

2023-10-23 10:03 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +                    int x = nextNumber - timed;
Разница - это не обязательно из второго вычитать первое. Может быть и из первого второе.

2023-10-24 09:33 UTC, Dovgalyuk requested changes

2023-10-24 09:33 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +        if(array_get(arr,i) >= 0){
0 - это не положительное число

2023-10-24 09:33 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +    sum /=j;
А если ни одного положительного нет?

2023-10-24 09:33 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +}
А если массив такой: 90 2 -2 -90 ?

2023-10-24 16:57 UTC, MAlutinS commented on Lab1C/lab1.cpp
> +}
Я изменил массив на: 90 2 -2 -90 и программа выдала ответ: 4. Минимальная возможная разница между 2 и -2. Разница между ними = 4, что не так, не понял.

2023-10-25 06:44 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +}
Точно, я увлёкся, усложняя пример. Тогда просто 90 -90

2023-10-26 01:35 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library двусвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

Реализовать команды манипуляции стеком из языка Forth: https://skilldrick.github.io/easyforth
Программа читает входную строку из следующих команд:
* 0-9 - заносит число в стек
* +-*/% - арифметические операции. Извлекают два числа из стека, а потом заносят туда результат
* dup - дублирует число на вершине стека
* drop - удаляет число с вершины стека
* swap - меняет местами два числа на вершине стека
* over - берёт элемент под вершиной стека и добавляет его в стек
* rot - перемещает "по кругу" верхние три элемента стека
* . - извлекает из стека верхний элемент и выводит на экран

Входные данные
```
1 2 3 rot . . .
```
Выходные данные
```
1
3
2
```

Входные данные
```
1 dup . 2 dup . 3 dup . + + .
```
Выходные данные
```
1
2
3
6
```

2023-10-26 01:35 UTC, closed without merging