lab_2 upd_7
Dovgalyuk/Algorithms pull request #652
Opened 2023-10-20 09:20 UTC by timlissovv

2023-10-20 09:25 UTC, timlissovv commented
Я почистил мусор.

2023-10-23 10:12 UTC, timlissovv commented
Я ничего не удалял. А было там то, что я скинул вам лабу, вы ответили, что в репощитории много мусора, чтоб я его почистил. Больше не было ничего.

2023-10-23 10:42 UTC, Dovgalyuk commented
Видимо ты неправильно выкладываешь. Больше так не делай, а вместо этого напомни, в чём у тебя сложность.

2023-10-23 10:56 UTC, timlissovv commented
Сложности, по сути, не было. У меня не проходил тест листа, и меня это напрягало, вот и решил спросить. Я тестировал программу, она работает. Пожалуйста, посмотрите работу, может есть какие-то недочёты.

2023-10-24 11:40 UTC, timlissovv commented
Исправил функцию удаления списка.

2023-10-24 11:41 UTC, timlissovv commented
Исправил функцию удаления списка.

2023-10-25 06:30 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        list->head_of_list = list->head_of_list->pointer_to_next;
Как минимум, тут не исправляется указатель на предыдущий элемент.

2023-10-25 16:59 UTC, timlissovv commented
Дописал обнуление указателя на удалённый элемент.

2023-10-26 02:02 UTC, Dovgalyuk requested changes

2023-10-26 02:02 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
>  ListItem *list_insert(List *list, Data data)
list_insert должен вставлять элемент в начало списка

2023-10-26 02:02 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    if (item->pointer_to_next == nullptr || item == nullptr)
В таком порядке проверять указатели неправильно.

2023-10-26 02:02 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        return nullptr;
Возвращать надо указатель на следующий элемент.

2023-10-28 17:04 UTC, timlissovv commented
upd_11

2023-10-30 09:28 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.

Задано начальное вещество и список химических реакций, в которых оно превращается в другое вещество.  Написать программу, использующую поиск в ширину, и выводящую список веществ, которые можно получить из исходного.

Входные данные
```
A
A->B
B->C
D->E
```
Выходные данные
```
B
C
```

В примере из вещества A можно получить вещества B и C.

2023-10-30 09:28 UTC, closed without merging