2lab
Dovgalyuk/Algorithms pull request #656
Opened 2023-10-22 07:37 UTC by MKBA13

Хаванов М.Ю. 2093

2023-10-22 07:59 UTC, MKBA13 commented
GitHub Actions
/ cpp-linter
/Lab2/lab2.cpp:4:9 [clang-diagnostic-error]
'stack.h' file not found

Вопросик... Нужно ли это исправлять?

2023-10-23 10:29 UTC, Dovgalyuk commented
> GitHub Actions / cpp-linter /Lab2/lab2.cpp:4:9 [clang-diagnostic-error] 'stack.h' file not found
> 
> Вопросик... Нужно ли это исправлять?

Нет.

2023-10-23 10:34 UTC, Dovgalyuk requested changes

2023-10-23 10:34 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        list->Head = new_Head;
Это присваивание есть в обеих ветках.

2023-10-23 10:34 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    if (new_item == nullptr)
Оператор new не может вернуть nullptr, он выбрасывает исключение.

2023-10-23 10:34 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +	int size_stack = 0, stack_fill_element = 0;
size_stack надо же прочитать из входного потока.

2023-10-23 15:35 UTC, MKBA13 commented
Исправил.

2023-10-24 09:34 UTC, Dovgalyuk commented
Что-то многовато файлов стало в репозитории.

2023-10-24 13:40 UTC, MKBA13 commented
Каталог build был назван иначе, бывает.

2023-10-25 06:37 UTC, Dovgalyuk requested changes

2023-10-25 06:37 UTC, Dovgalyuk commented on Lab2/lab2.cpp
> +	vector<Data> reverse;
Можно использовать такой же стек, если надо перевернуть последовательность.

2023-10-25 12:37 UTC, MKBA13 commented
Пожалуй, исправил.

2023-10-26 01:50 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.

Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной - «#» или пустым пространством – «.».
Стартовая позиция обозначается как X, финишные позиции цифрами от 0 до 9.
Написать программу, которая выводит цифру, ближайшую к стартовой позиции.
За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди.

Входные данные
```
######
#...X#
#.#.##
#3.4.#
######
```
Выходные данные
```
4
```

2023-10-26 01:50 UTC, closed without merging