lab2
Dovgalyuk/Algorithms pull request #659
Opened 2023-10-22 13:07 UTC by duraaach0k

2023-10-22 17:52 UTC, duraaach0k commented
вроде сделал, тесты прошло. А вот bipush 1 я даю через переменные потому что при вводе с клавиатуры он не видит пробел, не знаю почему так

2023-10-23 10:39 UTC, Dovgalyuk requested changes

2023-10-23 10:39 UTC, Dovgalyuk commented on LibraryC/vector.c
> +			vector->maxsize = 2 * size;
А здесь зачем менять maxsize?

2023-10-23 10:39 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +    z = "bipush 1";
Непонятно, в чём цель этого. Все команды (а они могут быть произвольными) должны читаться из входного потока.

2023-10-24 09:15 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +    z = "bipush 1";
Значит, надо разбираться.

2023-10-24 16:51 UTC, duraaach0k commented on Lab1C/lab2.cpp
> +    z = "bipush 1";
поправил

2023-10-25 06:43 UTC, Dovgalyuk requested changes

2023-10-25 06:43 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +    for (int i = 0; i < 5; i++)
Команд может быть и больше 5.

2023-10-25 06:43 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +        cin >> z;
С пробелом не прочитается таким оператором. Но зато если там push, можно дальше уже прочитать число.

2023-10-25 06:43 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +        if (z == "imul")
Желательно ещё везде писать else.

2023-10-25 06:43 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +            stack_push(a, p);
Нельзя дважды заносить один и тот же указатель.

2023-10-25 06:43 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +
Ещё стек нужно удалить.

2023-10-25 06:43 UTC, Dovgalyuk commented on LibraryC/vector.c
> +			vector->maxsize = 2 * size;
?

2023-10-26 16:46 UTC, duraaach0k commented on Lab1C/lab2.cpp
> +
удалил

2023-10-26 16:46 UTC, duraaach0k commented on Lab1C/lab2.cpp
> +            stack_push(a, p);
исправил

2023-10-26 16:47 UTC, duraaach0k commented on Lab1C/lab2.cpp
> +        if (z == "imul")
это же только будет нагружать код, разве нет? Так он более читаемый

2023-10-26 16:47 UTC, duraaach0k commented on Lab1C/lab2.cpp
> +        cin >> z;
теперь работает

2023-10-26 16:47 UTC, duraaach0k commented on Lab1C/lab2.cpp
> +    for (int i = 0; i < 5; i++)
в задаче не сказано как будет заканчиваться ввод, могу в начале сделать чтобы программа запрашивала кол-во команд

2023-10-26 16:48 UTC, duraaach0k commented
а что касается макс сайз там, без этого происходит утечка памяти.

2023-10-30 06:48 UTC, Dovgalyuk requested changes

2023-10-30 06:48 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +    for (int i = 0; i < 5; i++)
Обычно делают до конца файла.

2023-10-30 06:48 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +        if (z == "imul")
Тут даже если произошло успешное сравнение, то остальные условия тоже будут проверяться, хотя смысла в этом нет.

2023-10-30 06:50 UTC, Dovgalyuk requested changes

2023-10-30 06:50 UTC, Dovgalyuk commented on LibraryC/vector.c
> +			for (size_t i = 2 * size; i < vector->maxsize; i++) {
Тут неправильные пределы в цикле. И видимо из-за этого приходится позднее менять maxsize.

2023-10-30 12:57 UTC, duraaach0k commented
все исправил

2023-10-31 07:08 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и очередь на основе этого списка (модуль queue).
* Решить задачу, используя реализованную очередь.

Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной - «#» или пустым пространством – «.». Стартовая позиция обозначается как X. Написать программу, считающую количество клеток, до которых можно найти из начальной, а также выводящую лабиринт с достижимыми клетками, отмеченными символом «x». За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди.

Входные данные
```
######
#...X#
#.####
#....#
######
```
Выходные данные
```
9
######
#xxxx#
#x####
#xxxx#
######
```

2023-10-31 07:08 UTC, closed without merging