array + 1 и 2 задания
Dovgalyuk/Algorithms pull request #664
Opened 2023-10-24 15:55 UTC by Evgrafov-Veniamin

Вроде как выполненные задания по 1-ой лабе

2023-10-25 06:38 UTC, Dovgalyuk commented on Lab1CPP/lab1.cpp
> +struct Array
Array должен быть только в библиотеке.

2023-10-26 01:43 UTC, Dovgalyuk requested changes

2023-10-26 01:43 UTC, Dovgalyuk commented on .vscode/settings.json
Этот файл не нужно выкладывать.

2023-10-26 01:43 UTC, Dovgalyuk commented on Lab1CPP/lab1.cpp
> +            curDifference = abs(array_get(tempArr, i) - array_get(tempArr, j));
В задании сказано, что надо искать разность между различными элементами.

2023-10-26 01:43 UTC, Dovgalyuk commented on LibraryCPP/array.h
> +struct Array{
В заголовочном файле описание структуры тоже не нужно.

2023-10-26 10:02 UTC, Evgrafov-Veniamin commented on Lab1CPP/lab1.cpp
> +            curDifference = abs(array_get(tempArr, i) - array_get(tempArr, j));
Все верно. Идёт пробежка по массиву при помощи вложенного цикла. Внешний ( с i ) выбирает допустим 0 элемент массива, а внутренний (с j) пробегается по элементам следующими за элементом с индексом 0, то есть от 1 до arr_size.

2023-10-30 04:44 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
* Решить задачу, используя реализованный стек.

В ускорителе по прямой движутся частицы. Положительно заряженные частицы движутся вправо, отрицательно заряженные влево с одинаковой скоростью. При столкновении двух частиц обе они исчезают не влияя на все остальные. Вывести пары начальных координат частиц, которые столкнутся между собой. Во входном файле сначала записано число N, а затем идет описание частиц: начальная координата и заряд. Описания частиц в файле упорядочены по координате.

Входные данные
```
5
1 -
4 +
8 -
9 +
10 -
```
Выходные данные
```
4 8
9 10
```

2023-10-30 04:44 UTC, closed without merging