KirikovTimofey_Lab1
Dovgalyuk/Algorithms pull request #668
Opened 2023-10-27 05:46 UTC by kirikovsky

2023-10-30 08:04 UTC, Dovgalyuk commented
Нужно починить конфликты в изменённых файлах CMakeLists.txt, чтобы на сервере могли работать сборка и тестирование.

2023-10-30 09:59 UTC, kirikovsky commented
Поправил

2023-10-31 06:42 UTC, Dovgalyuk commented
Пока не получилось, вот ниже написаны подробности.

2023-10-31 08:12 UTC, kirikovsky commented
Все поправил. Должно работать

2023-11-01 06:53 UTC, Dovgalyuk requested changes

2023-11-01 06:53 UTC, Dovgalyuk commented on Labs/lab1.cpp
> +    return maxLength;
Результат работы можно хотя бы вывести на экран.

2023-11-01 06:53 UTC, Dovgalyuk commented on Labs/lab1.cpp
> +        if (n == size - 1) {
Инвертированная логика тяжело воспринимается.
Лучше считать количество совпадений.

2023-11-02 05:35 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
* Решить задачу, используя реализованный стек.

Написать программу, работу процессора со стеком. Процессор имеет 4 регистра, обозначенных буквами A, B, C, D. Во входном файле присутствуют операции PUSH и POP. Операция PUSH может иметь в качестве параметра число или регистр. Операция POP в качестве параметра имеет регистр и считывает в него значение с вершины стека. После выполнения последовательности операций программа должна распечатать содержимое регистров.

Входные данные
```
PUSH 1
POP B
```
Выходные данные
```
A = 0
B = 1
C = 0
D = 0
```

Входные данные
```
PUSH 1
PUSH 2
POP B
POP C
PUSH C
POP D
```
Выходные данные
```
A = 0
B = 2
C = 1
D = 1
```

2023-11-02 05:35 UTC, closed without merging