Petrov_Vsevolod_2092_Lab_1
Dovgalyuk/Algorithms pull request #671
Opened 2023-10-27 16:08 UTC by LazyHat

2023-10-30 08:27 UTC, Dovgalyuk commented
1. Нужно избавиться от лишних файлов в репозитории.
2. Должна быть одна реализация Array, остальные убрать.

2023-10-30 12:41 UTC, LazyHat commented
Я все сделал

2023-10-31 07:02 UTC, Dovgalyuk commented
Не нужно всё удалять. Я имел в виду, что там были добавлены несколько готовых реализаций.
Кроме того, нужно удалить временные файлы от vscode.

2023-11-09 08:24 UTC, LazyHat commented
Я удвлил все, что не нужно, код работает, тесты прохолят, через cmake билдится

2023-11-10 05:12 UTC, Dovgalyuk commented
На сервере не собирается (см. отчёт CMake build)

2023-11-13 12:16 UTC, LazyHat commented
Все.
Cppcheck не прошел только из-за гитхаба, у меня на репозитории все проходит.

2023-11-14 07:17 UTC, Dovgalyuk commented
Не надо удалять все файлы, которые уже были в репозитории, это мешает отслеживать изменения.
Достаточно отключить ненужное в конфиге CMakeLists.txt

2023-11-14 19:28 UTC, LazyHat commented
Вернул
Теперь изменено только 10 файлов

2023-11-15 10:20 UTC, Dovgalyuk requested changes

2023-11-15 10:20 UTC, Dovgalyuk commented on Lab1CPP/lab1.cpp
> +}
Тест:
2 7 8 10

2023-11-15 18:10 UTC, LazyHat commented on Lab1CPP/lab1.cpp
> +}
else.

2023-11-16 06:06 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

Написать программу, проверяющую правильность расстановки двух видов кавычек (“ и ‘) и скобок () в строке.  Программа должна выводить YES для правильной последовательности и NO для неправильной.

Входные данные
```
"ab(c 'de' f)gt"
```
Выходные данные
```
YES
```

Входные данные
```
"adjsk 'z' frr')
```
Выходные данные
```
NO
```

2023-11-16 06:06 UTC, closed without merging