Лаб1
Dovgalyuk/Algorithms pull request #673
Opened 2023-10-29 13:47 UTC by gsbfio

В прошлый раз запутался с настройками, пришлось пересоздать

2023-10-30 09:33 UTC, Dovgalyuk commented
Сборка не проходит (см. CMake build)

2023-10-30 11:29 UTC, gsbfio commented
Исправлено, теперь проходит TestArrayCPP

2023-10-31 06:57 UTC, Dovgalyuk requested changes

2023-10-31 06:57 UTC, Dovgalyuk commented on Lab1CPP/.vs/CMake Overview
Эти файлы надо удалить.

2023-10-31 06:57 UTC, Dovgalyuk commented on LibraryCPP/array.h
> +struct Array {
Структуру не надо определять в заголовочном файле.

2023-11-01 09:15 UTC, gsbfio commented
Исправлено

2023-11-02 05:25 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

Преобразовать арифметическое выражение в ассемблерные опреации работы со стеком и регистрами.
Используются команды PUSH (занести в стек), POP (извлечь из стека в регистр), ADD (сложить),
SUB (вычесть), MUL (перемножить). Достаточно использовать два регистра A и B.

Входные данные
```
1+2*3
```
Выходные данные
```
PUSH 1
PUSH 2
PUSH 3
POP A
POP B
MUL A, B
PUSH A
POP A
POP B
ADD A, B
PUSH A
```

Входные данные
```
(1+2)*3
```
Выходные данные
```
PUSH 1
PUSH 2
POP A
POP B
ADD A, B
PUSH A
PUSH 3
POP A
POP B
MUL A, B
PUSH A
```

2023-11-02 05:25 UTC, closed without merging