lab2 Федоров Иван 2091
Dovgalyuk/Algorithms pull request #674
Opened 2023-10-29 17:33 UTC by Estomee

![image](https://github.com/Dovgalyuk/Algorithms/assets/112470254/87d5aebe-d8aa-4d3a-8bf2-ff11113d1913)
![image](https://github.com/Dovgalyuk/Algorithms/assets/112470254/e275b2c0-cc14-41ec-969c-178115433e80)

2023-10-29 17:58 UTC, Estomee commented
Павел Михайлович, не знаю, должны ли у меня тесты проходить? Вроде проблем с утечкой памяти не было, там где выделил память, там и очистил потом в конце. Не понимаю, в чём косяк.

2023-10-30 09:37 UTC, Dovgalyuk commented
А если у себя локально позапускать тот же тест, падает ли он?

2023-10-30 14:28 UTC, Estomee commented
Павел Михайлович, исправил код, тесты локально проходят, при апдейте - тоже.
![image](https://github.com/Dovgalyuk/Algorithms/assets/112470254/63eff6a9-d2d7-4667-91b9-5f0885697bc2)
![image](https://github.com/Dovgalyuk/Algorithms/assets/112470254/a9e409b1-a178-4784-81ba-69e43318e1b6)

2023-10-31 07:18 UTC, Dovgalyuk requested changes

2023-10-31 07:18 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +    while (cin.get(c))
Ни к чему складывать символы в строку, можно сразу их обрабатывать в следующем цикле.

2023-10-31 07:59 UTC, Estomee commented on Lab1C/lab2.cpp
> +    while (cin.get(c))
Павел Михайлович, делаю так как обычное считывание в строку не учитывает пробелы.

2023-11-01 06:47 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +    while (cin.get(c))
Так можно так же в цикле делать cin.get() и сразу обрабатывать символ.

2023-11-01 10:14 UTC, Estomee commented
Павел Михайлович, добавил изменения.

2023-11-02 05:29 UTC, Dovgalyuk requested changes

2023-11-02 05:29 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +    for (size_t i = 0; c!='\n'; i++)
А зачем тут i? Лучше просто написать while.

2023-11-02 05:29 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +    while (stack_empty(stack) != true)
тут просто while (!stack_empty(stack))

2023-11-03 04:20 UTC, closed without merging

2023-11-03 04:20 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и очередь на основе этого списка (модуль queue).
* Решить задачу, используя реализованную очередь.

Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной – «#» или пустым пространством – «.». Стартовая позиция обозначается как X, финишная как Y. Написать программу, находящую минимальный путь от стартовой до финишной клетки, если это возможно. За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди. Если решения нет, вывести IMPOSSIBLE.

Входные данные
```
######
#...X#
#.####
#...Y#
######
```
Выходные данные
```
######
#xxxX#
#x####
#xxxY#
######
```

Входные данные
```
######
#...X#
######
#...Y#
######
```
Выходные данные
```
IMPOSSIBLE
```