lab3
Dovgalyuk/Algorithms pull request #675
Opened 2023-10-30 22:25 UTC by endiepq

lab3.cpp

2023-10-31 07:31 UTC, Dovgalyuk requested changes

2023-10-31 07:31 UTC, Dovgalyuk commented on Lab3C/lab3.cpp
> +typedef map<string, vector<string>> Graph;
Логичнее граф хранить в виде списка идентификаторов, а не строк, чтобы в процессе обхода ничего не преобразовывать.

2023-10-31 07:31 UTC, Dovgalyuk commented on Lab3C/lab3.cpp
> +    map<Data, bool> visited;
Для этих двух достаточно массива, ведь идентификаторы идут подряд.

2023-10-31 07:31 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +        list_insert_after(queue->list, queue->last, data);
Эта функция же возвращает новый указатель, можно его использовать.

2023-10-31 20:43 UTC, endiepq commented on Lab3C/lab3.cpp
> +typedef map<string, vector<string>> Graph;
Исправлено

2023-10-31 20:43 UTC, endiepq commented on Lab3C/lab3.cpp
> +    map<Data, bool> visited;
Исправлено

2023-10-31 20:43 UTC, endiepq commented on LibraryCPP/queue.cpp
> +        list_insert_after(queue->list, queue->last, data);
Исправлено

2023-11-01 06:58 UTC, Dovgalyuk requested changes

2023-11-01 06:58 UTC, Dovgalyuk commented on Lab3C/lab3.cpp
> +typedef map<Data, vector<Data>> Graph;
Теперь, когда тут подряд идущие номера, можно использовать, к примеру, вектор.

2023-11-01 06:58 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +        list_insert(queue->list, data);
Тут тоже можно использовать возвращаемое значение.

2023-11-01 06:58 UTC, Dovgalyuk commented on Lab3C/lab3.cpp
> +typedef map<Data, string> DataToStringMap;
И вот тут map не нужен, можно использовать вектор.

2023-11-01 16:40 UTC, endiepq commented on Lab3C/lab3.cpp
> +typedef map<Data, vector<Data>> Graph;
Исправлено

2023-11-01 16:40 UTC, endiepq commented on LibraryCPP/queue.cpp
> +        list_insert(queue->list, data);
Исправлено

2023-11-01 16:40 UTC, endiepq commented on Lab3C/lab3.cpp
> +typedef map<Data, string> DataToStringMap;
Исправлено

2023-11-02 05:33 UTC, Dovgalyuk requested changes

2023-11-02 05:33 UTC, Dovgalyuk commented on Lab3C/lab3.cpp
> +typedef vector<pair<string, Data>> StringToDataMap;
Вот тут как раз надо было оставить map.

2023-11-02 09:43 UTC, endiepq commented on Lab3C/lab3.cpp
> +typedef vector<pair<string, Data>> StringToDataMap;
Исправлено

2023-11-03 04:42 UTC, closed without merging

2023-11-03 04:42 UTC, Dovgalyuk commented
Принято.

* Разработать программный интерфейс модуля (заголовки функций) библиотеки LibraryCPPTemplate для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
* Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
* Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List библиотеки LibraryCPPTemplate.
* Разработать и добавить в проект LibraryCPPTemplate программу, тестирующую работу библиотеки для графа.
* Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать в нем длины кратчайших путей от одной вершины до всех остальных с помощью алгоритма Дейкстры. Для хранения порядка обработки вершин использовать очередь с приоритетами.