Lab_1_Timofeev_Ivan_2091
Dovgalyuk/Algorithms pull request #679
Opened 2023-11-02 21:59 UTC by Morivan

Реализация следующего технического задания:
Реализовать контейнер - динамический массив array с неизменяемым размером (на любом из языков)
Проверить работу соответствующей тестовой программы
Написать две функции для обработки массива из следующих пунктов и вызвать их из функции main.
Ввести целое число с клавиатуры, создать массив такой размерности и заполнить его случайными числами. Найти среднее арифметическое положительных элементов массива
Ввести целое число с клавиатуры, создать массив такой размерности и заполнить его случайными числами. В массиве найти элементы, которые не делятся ни на какой другой элемент массива.

2023-11-03 04:55 UTC, Dovgalyuk commented
Сборка не проходит (см. отчёт CMake build).

2023-11-07 07:20 UTC, Dovgalyuk requested changes

2023-11-07 07:20 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +}
Что будет выведено для такого массива?
2 3 4 2 3

2023-11-07 17:11 UTC, Morivan commented on Lab1C/lab1.cpp
> +}
task1 вывел "2.8", что корректно
task2 вывел "2 3", что некорректно
Спасибо за обнаружение ошибки, буду исправлять

2023-11-08 05:19 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

Во входном файле записана последовательность тегов в формате HTML. Каждый тег расположен на отдельной строке. Используя стек, проверить правильность этой последовательности. Вывести в выходной файл YES, если последовательность корректна и NO, если нет.

Входные данные
```
<HTML>
<Body>
</body>
</HTML>
```
Выходные данные
```
YES
```

Входные данные
```
<HTML>
</body>
```
Выходные данные
```
NO
```

2023-11-08 05:19 UTC, closed without merging