1 лабораторка
Dovgalyuk/Algorithms pull request #681
Opened 2023-11-04 11:13 UTC by ShinuiMK2092

2092 Куприянов М.В ,присылаю вам доделанную первую лабораторную работу

2023-11-07 06:48 UTC, Dovgalyuk commented
Нужно правильно сконфигурировать проект (в файле CMakeLists.txt), чтобы он собирался (в том числе и на сервере, см. отчёт CMake build)

2023-11-25 00:02 UTC, ShinuiMK2092 commented
Здравствуйте,сборка собралась

2023-11-27 06:05 UTC, Dovgalyuk requested changes

2023-11-27 06:05 UTC, Dovgalyuk commented on Lab1C/lab1prog.cpp
> +			vector<int> mas(N);
Надо использовать не вектор, а собственный реализованный контейнер array.

2023-11-28 02:28 UTC, ShinuiMK2092 commented
Здравствуйте ,исправил везде вектора на массивы

2023-11-28 09:21 UTC, Dovgalyuk commented on Lab1C/lab1prog.cpp
> +void first_podschet(const array<int, 6>& arr, const int N) {
Надо использовать не std::array, а собственный контейнер array из LibraryCPP.

2023-11-28 22:25 UTC, ShinuiMK2092 commented
Вроде как всё переделал

2023-11-29 09:36 UTC, Dovgalyuk requested changes

2023-11-29 09:36 UTC, Dovgalyuk commented on Lab1C/lab1prog.cpp
> +#include "array.cpp"
cpp подключать не надо, функции оттуда добавятся в исполняемый файл при линковке

2023-11-29 09:36 UTC, Dovgalyuk commented on Lab1C/lab1prog.cpp
> +			first_podschet(*arr);
Лучше сразу и передавать указатель, потому что дальше идёт именно он.

2023-11-29 21:49 UTC, ShinuiMK2092 commented
Здравствуйте,исправил
Во все две функции теперь передаётся указатель

2023-11-30 06:57 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

Дано выражение в обратной польской записи. Используя стек, написать программу, которая проверяет выражение на наличие ошибок. Ошибкой считается деление на 0 (ZERO), выполнение операции, когда в стеке меньше двух элементов (UNDERFLOW), наличие больше одного элемента в стеке после завершения работы программы (OVERFLOW).

Входные данные
```
1 2 + 3
```
Выходные данные
```
OVERFLOW
```

Входные данные
```
10 9 - +
```
Выходные данные
```
UNDERFLOW
```

2023-11-30 06:57 UTC, closed without merging