Lab3 Prokopenko Andrey
Dovgalyuk/Algorithms pull request #682
Opened 2023-11-05 18:47 UTC by Ynic2

2023-11-05 18:50 UTC, Ynic2 commented
Все тесты прошли

2023-11-07 06:58 UTC, Dovgalyuk requested changes

2023-11-07 06:58 UTC, Dovgalyuk commented on Labs/lab3.cpp
> +int shortestPath(vector<vector<int>> graph, int start, int finish) {
Ни к чему передавать большую структуру (граф) по значению, если не предполагается её изменять.
Кроме того, можно сделать typedef, чтобы два раза не писать объявление сложного типа.

2023-11-07 06:58 UTC, Dovgalyuk commented on Labs/lab3.cpp
> +                if (queue_empty(que)) {
Очередь должна быть устроена так, чтобы этого не приходилось делать.

2023-11-07 12:34 UTC, Ynic2 commented
Теперь передаю граф по константной ссылке, забыл удалить очередь в конце программы, исправил это. Проверка на пустоту очереди была не нужна, забыл убрать, когда была ошибка. Ошибку исправил, а проверка осталась

2023-11-08 05:17 UTC, Dovgalyuk commented
Принято. Следующее задание после защиты.

2023-11-08 05:17 UTC, closed without merging