lab3
Dovgalyuk/Algorithms pull request #683
Opened 2023-11-05 20:13 UTC by ekaterina209

2023-11-05 20:15 UTC, ekaterina209 commented
Всё работает, тесты проходят

2023-11-07 07:15 UTC, Dovgalyuk requested changes

2023-11-07 07:15 UTC, Dovgalyuk commented on Labs/lab3.cpp
> +    Queue* q = queue_create();
Очередь ещё нужно удалить.

2023-11-09 07:31 UTC, Dovgalyuk commented
Принято.

Следующее задание после защиты.

2023-11-09 07:31 UTC, closed without merging