lab1
Dovgalyuk/Algorithms pull request #685
Opened 2023-11-09 02:29 UTC by Sonicspeedfly

Задания выполнены! Ожидаю новых, на данный момент реализовал работу в языке C и C++. C++ Template и C++ Class, не успеваю реализовать поэтому в дальнейшем задания будут выполнены на C и C++. Если будут рекомендации и ошибки по коду пишите сразу исправлю!

2023-11-09 07:37 UTC, Dovgalyuk commented
> Задания выполнены! Ожидаю новых, на данный момент реализовал работу в языке C и C++. C++ Template и C++ Class, не успеваю реализовать поэтому в дальнейшем задания будут выполнены на C и C++. Если будут рекомендации и ошибки по коду пишите сразу исправлю!

Надо реализовывать какой-то один вариант библиотеки (C, C++, C++Class или Template), а затем его использовать.

2023-11-09 07:40 UTC, Dovgalyuk requested changes

2023-11-09 07:40 UTC, Dovgalyuk commented on .vscode/c_cpp_properties.json
Этот файл не нужен в репозитории.

2023-11-09 07:40 UTC, Dovgalyuk commented on LibraryC/array.c
> +                free(arr->value[i]);
Вот для этого должна служить функция, передаваемая в качестве параметра FFree f в функцию array_create.

2023-11-09 07:47 UTC, Sonicspeedfly commented
На С++ буду реализовывать дальнейшие задания, так как всё же для Си опыта у меня немного, а времени не так много

2023-11-10 05:06 UTC, Dovgalyuk commented
Файлы, которые не были затронуты, удалять не нужно. Это мешает смотреть настоящие изменения.
Следующее задание:

* Реализовать в проекте Library двусвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

В ускорителе по прямой движутся частицы. Положительно заряженные частицы движутся вправо, отрицательно заряженные влево с одинаковой скоростью. При столкновении двух частиц обе они исчезают не влияя на все остальные. Вывести пары начальных координат частиц, которые столкнутся между собой. Во входном файле сначала записано число N, а затем идет описание частиц: начальная координата и заряд. Описания частиц в файле упорядочены по координате.

Входные данные
```
5
1 -
4 +
8 -
9 +
10 -
```
Выходные данные
```
4 8
9 10
```

2023-11-10 05:06 UTC, closed without merging