3 лабораторная
Dovgalyuk/Algorithms pull request #686
Opened 2023-11-10 14:31 UTC by Gebrur

2023-11-13 05:06 UTC, Dovgalyuk requested changes

2023-11-13 05:06 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    if (new_item == nullptr)
new не может возвращать nullptr

2023-11-14 23:14 UTC, Gebrur commented
Исправил ошибки и разобрался с new,  при ошибке связанной с выделением памяти с помощью new  выводиться std::bad_alloc а не nullptr, исправил с помощью параметра для new(std::nothrow) который при использовании выведет nullptr вместо std::bad_alloc

2023-11-15 10:26 UTC, Dovgalyuk commented
Принято. Следующее задание после защиты.

2023-11-15 10:26 UTC, closed without merging