lab3
Dovgalyuk/Algorithms pull request #688
Opened 2023-11-12 15:23 UTC by duraaach0k

2023-11-12 16:41 UTC, duraaach0k commented
Вроде все сделал

2023-11-13 05:25 UTC, Dovgalyuk requested changes

2023-11-13 05:25 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +	string lab[5] = {
Это надо читать из файла или с клавиатуры.

2023-11-13 05:25 UTC, Dovgalyuk commented on LibraryC/queue.c
Зачем что-то менять в этих файлах, если используется С++-версия?

2023-11-13 14:24 UTC, duraaach0k commented on LibraryC/queue.c
я только недавно узнал, что можно на с++ писать и решил на нем сделать

2023-11-13 14:36 UTC, duraaach0k commented on Lab1C/lab3.cpp
> +	string lab[5] = {
сделал ввод с клавиатуры

2023-11-14 07:25 UTC, Dovgalyuk requested changes

2023-11-14 07:25 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +				kordinata = a * 10 + b;
Ширина лабиринта может быть больше 10.

2023-11-14 07:25 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +		if (queue_empty(a))
Это надо убрать, а вместо этого сделать нормальное условие while.

2023-11-14 13:36 UTC, duraaach0k commented
сделал на двух очередях, а убрать условие для брейка там нельзя, потому что появляется момент когда очередь пуста и цикл прерывается

2023-11-15 10:07 UTC, Dovgalyuk requested changes

2023-11-15 10:07 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +	for (int a = 0; a < 5; a++)
Здесь фиксированная размерность указана.

2023-11-15 10:07 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +	while (1)
Вот этот цикл надо переделать. Условие "пока очередь не пуста".

2023-11-15 10:14 UTC, duraaach0k commented
Все поправил

2023-11-16 05:55 UTC, Dovgalyuk commented
Принято. Следующее задание после защиты.

2023-11-16 05:55 UTC, closed without merging

2023-11-21 06:36 UTC, duraaach0k commented
.

2023-11-21 08:47 UTC, Dovgalyuk commented
* Разработать программный интерфейс модуля (заголовки функций) библиотеки LibraryCPPTemplate для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
* Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
* Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде матрицы смежности в контейнере Vector библиотеки LibraryCPPTemplate.
* Разработать и добавить в проект LibraryCPPTemplate программу, тестирующую работу библиотеки для графа.
* Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать для него минимальное покрывающее дерево алгоритмом Крускала. Использовать систему непересекающихся множеств для поддеревьев в процессе работы алгоритма.