lab2
Dovgalyuk/Algorithms pull request #689
Opened 2023-11-13 15:56 UTC by PieDIEmaN

2023-11-13 16:00 UTC, PieDIEmaN commented
![изображение](https://github.com/Dovgalyuk/Algorithms/assets/113968388/0c068c8d-fa5d-4bcd-a50d-86334462af4d)

нужные тесты прошли

2023-11-13 16:01 UTC, PieDIEmaN commented
![изображение](https://github.com/Dovgalyuk/Algorithms/assets/113968388/a215388d-55cb-436a-8b51-4590a6e9e8b1)
нужные тесты прошли

2023-11-14 07:31 UTC, Dovgalyuk requested changes

2023-11-14 07:31 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +            }
Если здесь убирать скобку из стека, то в предыдущем цикле проверять её не понадобится.

2023-11-15 10:12 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +            }
Проверка 20 строками выше осталась.

2023-11-16 05:57 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +                stack_pop(stack);  // ������������ ���������� � ����� ������� �����������
А вывод операций куда пропал?

2023-11-17 10:48 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library кольцевой двусвязный список (модуль list) и очередь на основе этого списка (модуль queue).
* Решить задачу, используя реализованную очередь.

Задан ориентированный граф виде матрицы смежности. Написать программу для определения длины кратчайшего пути от одной вершины для другой. В первой строке входного файла записано количество вершин, номер стартовой вершины и номер финишной. В последующих строках идет описание матрицы смежности. Значения 0 в матрице обозначают отсутствие ребра. В выходной файл выводится длина кратчайшего пути. Если решения не существует – выводится IMPOSSIBLE. Программа должна использовать поиск в ширину на основе очереди.

Входные данные
```
4 1 4
0 1 1 0
0 0 0 0
0 1 0 1
0 0 1 0
```
Выходные данные
```
2
```

2023-11-17 10:48 UTC, closed without merging