3lab
Dovgalyuk/Algorithms pull request #692
Opened 2023-11-14 06:55 UTC by MKBA13

Хаванов М.Ю. 2093

2023-11-14 07:08 UTC, MKBA13 commented
Посмотрите.

2023-11-14 07:43 UTC, Dovgalyuk requested changes

2023-11-14 07:43 UTC, Dovgalyuk commented on Lab3/lab3.cpp
> +			case 1:
Можно сделать массив из приращений координат, откуда и выбирать именения x, y.

2023-11-14 07:43 UTC, Dovgalyuk commented on Lab3/lab3.cpp
> +			if (labyrinth[y][x] == *".")
Можно написать просто '.'

2023-11-14 07:43 UTC, Dovgalyuk commented on Lab3/lab3.cpp
> +		for (int j = 1, x=0, y=0; j <= 8 && !f_exit; j++)  //S�ANNER
Проверку f_exit лучше вставить в while.
Или вообще написать break там, где она сейчас устанавливается.

2023-11-14 14:07 UTC, MKBA13 commented
Случайно удалил сообщение про то, что можно написать так:
labyrinth[y][x] == '.' вместо моего labyrinth[y][x] == *"."

Всё подправил.

2023-11-15 10:09 UTC, Dovgalyuk requested changes

2023-11-15 10:09 UTC, Dovgalyuk commented on Lab3/lab3.cpp
> +					break;
Раз есть break, то f_exit не нужен вообще.

2023-11-15 10:09 UTC, Dovgalyuk commented on Lab3/lab3.cpp
> +				else if (labyrinth[y][x] >= *"0" && labyrinth[y][x] <= *"9")
Много где странные символы надо исправить.

2023-11-15 14:23 UTC, MKBA13 commented
Если я уберу f_exit, то у меня полетит алгоритм - бесконечный while и вылетит ошибка(скрин). Если я это исправляю, то придётся перелопачивать восстановление изначальных клеток(доп. структура) либо не будет их восстановления. А можно сделать гадость и отправить в функцию вектор по значению.

Что делать? Не восстанавливать клетки, восстанавливать по другому и оставить f_exit как есть?
![Screenshot_1](https://github.com/Dovgalyuk/Algorithms/assets/144269975/97f11e8e-260a-4342-b7d0-17b14261a9ee)

2023-11-15 14:44 UTC, MKBA13 commented
А это исправление странных символов.

2023-11-16 06:04 UTC, Dovgalyuk commented
Понял. Break не сработал, потому что там два цикла. Тогда f_exit нужно в условие продолжения первого цикла добавить, а не писать отдельный if.

2023-11-16 13:32 UTC, MKBA13 commented
Окей, но тогда у меня ломается восстановление клеток. А раз уж восстанавливать клетки похоже не нужно, то я и не буду с этим парится.

2023-11-17 09:10 UTC, Dovgalyuk commented
Принято.

* Разработать программный интерфейс модуля (заголовки функций) библиотеки LibraryCPPTemplate для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
* Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
* Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List библиотеки LibraryCPPTemplate.
* Разработать и добавить в проект LibraryCPPTemplate программу, тестирующую работу библиотеки для графа.
* Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать в нем количество компонентов связности с помощью обхода в глубину.

2023-11-17 09:10 UTC, closed without merging