lab3
Dovgalyuk/Algorithms pull request #696
Opened 2023-11-15 08:42 UTC by stmay4

2023-11-15 09:01 UTC, stmay4 commented
Тесты для очереди и листа пройдены

2023-11-15 10:39 UTC, Dovgalyuk requested changes

2023-11-15 10:39 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +size_t FindRootIndex(vector<vector<string>> v, string root) {
v не стоит передавать по значению. Да и root тоже.

2023-11-15 10:39 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +	vector<vector<string>> graph;
В графе нет смысла хранить строки, это слишком медленно работает.
Лучше завести отдельно массив названий городов, а в графе все города будут представлены числовыми идентификаторами. Они же индексы в массиве названий.

2023-11-15 10:39 UTC, Dovgalyuk commented on LibraryC/list.c
> +	ListItem* Tail;
Для кольцевого списка можно хранить только head.

2023-11-19 08:19 UTC, stmay4 commented
Внес изменения. В графе храню индексы, ввел массив названий points, в листе убрал хранение Tail

2023-11-20 06:39 UTC, Dovgalyuk requested changes

2023-11-20 06:39 UTC, Dovgalyuk commented on LibraryC/list.c
> +	list->Head = NULL;
Этого не нужно делать, мы же освобождаем память.

2023-11-20 06:39 UTC, Dovgalyuk commented on LibraryC/list.c
> +	list_item_prev(list->Head)->Next = newItem;
А зачем функцию вызывать, если все остальные обращения просто к полям?

2023-11-20 06:39 UTC, Dovgalyuk commented on LibraryC/list.c
> +	list->Head = list_item_next(first);
Тут тоже проще будет без функций.

2023-11-20 06:39 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +size_t FindRootIndex(vector<vector<size_t>> v, size_t root) {
Не нужно в таких ситуациях передавать вектор по значению.
И ещё для него не помешает typedef.

2023-11-20 06:39 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +			size_t index = FindRootIndex(graph, index1);
А почему индексы не могут быть такими же индексами в графе? Т.е. размерность того вектора равняется размерности points. Достаточно просто делать resize.

2023-11-20 15:14 UTC, stmay4 commented
Убрал лишние вызовы функций в библиотеке, векторы теперь передаю по ссылке (const & или &), сделал typedef и поменял хранение индексов в графе

2023-11-21 08:37 UTC, Dovgalyuk requested changes

2023-11-21 08:37 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +	if (size > 0) {
Это условие ничего полезного не делает.

2023-11-21 08:37 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +		vector<size_t> nodes = findNodes(g, node);
Можно же просто получить ссылку на нужную строку таблицы.

2023-11-21 08:37 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +			size_t index2 = SIZE_MAX;
Будет нагляднее, если сделать просто два вызова вспомогательной функции, а не дублировать код для каждого из индексов.

2023-11-22 08:42 UTC, stmay4 commented
Добавил вспомогательные функции для выделения нод из ввода пользователя(GetNodes) и для определения индексов введенных нод(GetIndex), убрал функцию поиска смежных нод (findNodes), благодаря изменению хранения в графе ( `graph[index1].push_back(index2); graph[index2].push_back(index1);` вместо `graph[index1].push_back(index2);`)

2023-11-22 08:55 UTC, Dovgalyuk commented
Принято. Следующее задание после защиты.

2023-11-22 08:55 UTC, closed without merging