lab4.3
Dovgalyuk/Algorithms pull request #699
Opened 2023-11-16 13:41 UTC by heheheee21

2023-11-17 10:42 UTC, Dovgalyuk requested changes

2023-11-17 10:42 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +                insert(current->data());
Тут разве список не разворачивается задом наперёд?

2023-11-17 10:42 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +        int from;
Зачем хранить from, если у нас списки смежности?

2023-11-20 06:52 UTC, Dovgalyuk requested changes

2023-11-20 06:52 UTC, Dovgalyuk commented on LibraryCPPTemplate/Tests/CMakeLists.txt
> +add_test(TestListCPPTemplate TestGraphCPPTemplate)
Название теста неправильное. Непонятно, кто из них вообще запустился.

2023-11-20 06:52 UTC, Dovgalyuk commented on LibraryCPPTemplate/Tests/graph.cpp
> +        graph.addEdge(i, (i + 1) % graph.vertexCount(), 10 * i);
Ещё чтобы у одной вершины было несколько рёбер, а не одно.

2023-11-20 06:52 UTC, Dovgalyuk commented on LibraryCPPTemplate/Tests/graph.cpp
> +    graph.addVertex();
removeVertex в какой-то момент тоже надо проверять. Желательно, чтобы множество рёбер при этом не было пустым.

2023-11-21 07:40 UTC, Dovgalyuk requested changes

2023-11-21 07:40 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +            if (i != vertex)
А разве не будет утечки памяти для i==vertex?

2023-11-21 08:43 UTC, heheheee21 commented on LibraryCPPTemplate/graph.h
> +            if (i != vertex)
Могу сказать, что утечки памяти при удалении вершины не происходит. В методе removeVertex я создаю новый массив для списков смежности, куда копирую все списки, исключая список удаляемой вершины. Это не приводит к утечке памяти, тк память, выделенная для списка смежности удаляемой вершины, освобождается позже при удалении старого массива списков:

`delete[] adjacencyList_;
adjacencyList_ = newAdjacencyList;
`
Также, в листе реализованы деструктор и оператор присваивания, что гарантирует правильное управление памятью списка. Поэтому, при освобождении памяти старого массива списков, корректно удаляются все элементы, включая список смежности удаляемой вершины, что исключает возможность утечки памяти.

2023-11-22 08:30 UTC, Dovgalyuk commented
Принято.

* Разработать интерфейс (набор функций) для ассоциативного массива, который хранит пары (ключ)строка -> (значение)строка. Поддерживаемые операции: добавить пару ключ-значение, найти значение по ключу, удалить значение по ключу.
* Реализовать контейнер на основе АВЛ-дерева, реализующий разработанный интерфейс.
* Создать тест для проверки работы контейнера. Программа должна включать в себя нагрузочное тестирование для исключения ошибок, приводящих к сложности работы O(N*N) при поиске, удалении или добавлении значений.
* Написать генератор входных данных различного объема для этого контейнера.
* Сравнить скорость выполнения операции добавления в контейнер содержимого файла со стандартным контейнером std::map при различных объемах данных. Построить график зависимости времени работы от объёма входных данных и оценить характер зависимости.

2023-11-22 08:30 UTC, closed without merging