Petrov_Vsevolod_2092_Lab_2
Dovgalyuk/Algorithms pull request #701
Opened 2023-11-16 16:54 UTC by LazyHat

2023-11-17 11:00 UTC, Dovgalyuk requested changes

2023-11-17 11:00 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +    std::size_t mSize;
Здесь списку не нужен размер.

2023-11-17 11:00 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +    std::size_t indexOf(Data data)
Много ненужных функций, которые не были предусмотрены.

2023-11-17 11:00 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +}
Как насчёт примера: "")

2023-11-17 11:09 UTC, LazyHat commented on LibraryCPPTemplate/list.h
> +    std::size_t indexOf(Data data)
Я их реализовал, для того, чтобы удобнее было с помощью них выполнить задание.

2023-11-17 11:18 UTC, LazyHat commented on Lab2CPP/lab2.cpp
> +}
Исправил

2023-11-17 11:19 UTC, LazyHat commented on LibraryCPPTemplate/list.h
> +    std::size_t mSize;
Убрал, теперь стек хранит размер.

2023-11-17 11:22 UTC, LazyHat commented
Исправил

2023-11-20 05:49 UTC, Dovgalyuk requested changes

2023-11-20 05:49 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +    std::size_t indexOf(Data data)
Именно эту функцию нужно убрать, потому что она вводит пользователя в заблуждение. Будто бы в списке есть быстрый способ искать или обращаться по индексу.

2023-11-20 05:49 UTC, Dovgalyuk commented on LibraryCPPTemplate/stack.h
> +    std::size_t mSize;
А зачем вообще нужен размер?

2023-11-20 05:49 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +    List<char> closeSymbols = {'\'', '\"', ')'};
Можно же просто сделать std::string

2023-11-20 16:54 UTC, LazyHat commented on LibraryCPPTemplate/stack.h
> +    std::size_t mSize;
Действительно. Удалил.

2023-11-20 16:54 UTC, LazyHat commented on Lab2CPP/lab2.cpp
> +    List<char> closeSymbols = {'\'', '\"', ')'};
Я так захотел. Проблема-то в чем?

2023-11-21 08:41 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +    List<char> closeSymbols = {'\'', '\"', ')'};
Проблема в том, что из-за этого появляется indexOf. Но раз эта функция нигде неправильно не используется, то пусть уж остаётся.

2023-11-21 08:43 UTC, Dovgalyuk commented
* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.

Входной файл содержит последовательность положительных чисел. Отсортировать последовательность с помощью поразрядной сортировки.
Число битов, по которым происходит сравнение должно задаваться в виде константы в коде.
Для каждой комбинации битов должна быть организована отдельная очередь, хранящая соответствующие числа.

Входные данные
```
8 4 1 5 6
```
Выходные данные
```
1 4 5 6 8
```

Если разделять числа из примера по одному (младшему) биту, то получатся два набора: {8, 4, 6} и {1, 5}.
Если брать сразу по два бита, то будет 4 набора: {8, 4}, {1, 5}, {6}, {}.

2023-11-21 08:43 UTC, closed without merging