3LAB Novikov
Dovgalyuk/Algorithms pull request #705
Opened 2023-11-21 14:52 UTC by Myfasick

2023-11-22 08:35 UTC, Dovgalyuk requested changes

2023-11-22 08:35 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    ListItem *next;
В задании требуется кольцевой двусвязный список.

2023-11-24 07:40 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    ListItem *tail;
В кольцевом списке можно обходиться без tail.

2023-11-28 09:14 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    ListItem *tail;
tail всё ещё здесь.

2023-11-29 06:50 UTC, Myfasick commented on LibraryCPP/list.cpp
> +    ListItem *tail;
Поправил

2023-11-29 09:37 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    ListItem *tail;
Ну вот же переменная прямо над комментарием осталась.

2023-12-01 13:37 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    ListItem *tail;
Всё ещё висит.

2023-12-05 08:21 UTC, Dovgalyuk requested changes

2023-12-08 13:26 UTC, Myfasick commented
Переписал модуль list учитывая новые условия

2023-12-11 05:23 UTC, Dovgalyuk commented
А почему кольцевой двусвязный список превратился в односвязный?

2023-12-11 11:11 UTC, Myfasick commented
Запутался, исправил

2023-12-12 07:28 UTC, Dovgalyuk commented
Всё ещё односвязный список.

2023-12-13 06:28 UTC, Myfasick commented
Исправлено

2023-12-13 08:55 UTC, Dovgalyuk commented
Теперь нужно удалить tail.

2023-12-14 10:45 UTC, Myfasick commented
👁

2023-12-14 11:47 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    newListItem->prev = nullptr;
Это же кольцевой список, тут не может быть нулевых указателей в элементах.

2023-12-14 15:49 UTC, Myfasick commented on LibraryCPP/list.cpp
> +    newListItem->prev = nullptr;
Поправил

2023-12-18 05:57 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    if (item->next)
Там не могло быть нулевого указателя.

2023-12-19 08:03 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    if (newListItem->next)
Опять проверка на нулевой указатель.

2023-12-20 23:40 UTC, Myfasick commented
👁

2023-12-21 06:25 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        if (list->head->next)
Ещё проверка на нулевой указатель.
Стоит пересмотреть весь код на подобное.

2023-12-22 14:56 UTC, Myfasick commented
👁

2023-12-25 06:56 UTC, Dovgalyuk commented
Ничего не изменилось.

2023-12-25 13:52 UTC, Myfasick commented
Вы так и не ответили на мое сообщение выше, так что продублирую его еще раз.

Я не вижу причин удалять или исправлять это. Здесь идет проверка, если в списке есть следующий элемент, эта строка обновляет указатель prev следующего элемента, чтобы он указывал на предыдущий элемент в списке, который в данный момент является временным указателем.
На 54 строке код проверяет, пуст ли список. Если список не пуст, то он устанавливает поле prev текущего заголовка списка в новую структуру ListItem. В противном случае он устанавливает поле head списка в новую структуру ListItem.
На 105 строке проверка на то, что кольцевой список не состоит из одного и меньше элементов.
Я не вижу тут лишнего и требующего исправления.

2023-12-26 08:25 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    ListItem *newListItem = new ListItem{data, list->head, nullptr};
prev не устанавливается

2023-12-26 08:26 UTC, Dovgalyuk commented
> Вы так и не ответили на мое сообщение выше, так что продублирую его еще раз.
> 
> Я не вижу причин удалять или исправлять это. Здесь идет проверка, если в списке есть следующий элемент, эта строка обновляет указатель prev следующего элемента, чтобы он указывал на предыдущий элемент в списке, который в данный момент является временным указателем. На 54 строке код проверяет, пуст ли список. Если список не пуст, то он устанавливает поле prev текущего заголовка списка в новую структуру ListItem. В противном случае он устанавливает поле head списка в новую структуру ListItem. На 105 строке проверка на то, что кольцевой список не состоит из одного и меньше элементов. Я не вижу тут лишнего и требующего исправления.

В кольцевом списке не может быть нулевых указателей. Устанавливать в NULL их не нужно, проверять тоже.

2023-12-26 10:44 UTC, Myfasick commented
поправил

2023-12-27 08:21 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    ListItem *newListItem = new ListItem{data, list->head, nullptr};
Это осталось.

2023-12-27 23:59 UTC, Myfasick commented
👍

2023-12-29 06:16 UTC, Myfasick commented
✍️

2023-12-29 10:54 UTC, Dovgalyuk commented
Проект не собирается.

2023-12-29 11:07 UTC, Myfasick commented
Готово

2024-01-11 04:59 UTC, Dovgalyuk commented
Всё ещё множество ошибок. Не зачтено.

2024-01-11 04:59 UTC, closed without merging