Лабораторная работа 2
Dovgalyuk/Algorithms pull request #706
Opened 2023-11-22 13:30 UTC by Morivan

Задание:
Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
Решить задачу, используя реализованный стек.
Во входном файле записана последовательность тегов в формате HTML. Каждый тег расположен на отдельной строке. Используя стек, проверить правильность этой последовательности. Вывести в выходной файл YES, если последовательность корректна и NO, если нет.
Входные данные
<HTML>
<Body>
</body>
</HTML> 
Выходные данные
YES 
Входные данные
<HTML>
</body> 
Выходные данные
NO

2023-11-23 05:40 UTC, Dovgalyuk commented
Нужно разрешить конфликты в CMakeLists.txt, чтобы могла запуститься сборка на сервере.

2023-11-23 06:06 UTC, Morivan commented
Проблема была в убранной из CMakeLists.txt

add_executable(TestQueueCPP queue.cpp)
target_include_directories(TestQueueCPP PUBLIC ..)
target_link_libraries(TestQueueCPP LibraryCPP)
add_test(TestQueueCPP TestQueueCPP)

Вернул проверку очереди обратно

2023-11-24 07:58 UTC, Dovgalyuk requested changes

2023-11-24 07:58 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +    for (std::size_t i = 0; i < html.size(); i+=6) {
Длина тегов не обязательно равна 6.
Но каждый из тегов расположен в отдельной строке, поэтому не стоит их складывать все вместе.

2023-11-24 07:58 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +    return 1;
Стек нужно удалить.

2023-11-24 07:58 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +    ListItem* last_item = nullptr;
last_item не очень-то и нужен

2023-11-26 19:17 UTC, Morivan commented on Lab1C/lab2.cpp
> +    for (std::size_t i = 0; i < html.size(); i+=6) {
Исправил, теперь длина тега не важна для программы. А так же, хоть это и не относится напрямую к поставленной задаче, изменённый код, позволяет обрабатывать, например, "<h2>Hello</h2>" корректно.

2023-11-26 19:18 UTC, Morivan commented on Lab1C/lab2.cpp
> +    return 1;
Добавил удаление стека, а так же проверку стека на пустоту.

2023-11-26 19:19 UTC, Morivan commented on LibraryCPP/stack.cpp
> +    ListItem* last_item = nullptr;
Убрал "Last_item", действительно не нужен

2023-11-26 19:23 UTC, Morivan commented
Спасибо за нахождение недочётов в коде, исправил их.

2023-11-27 06:38 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.

Задан неориентированный граф. Написать программу для определения кратчайшего пути от одной вершины для другой. В первой строке входного файла записано количество вершин, номер стартовой вершины и номер финишной. В последующих строках идут описания ребер, заданные номерами вершин, которые они соединяют. В выходной файл выводится последовательность вершин в кратчайшем пути. Если решения не существует – выводится IMPOSSIBLE. Программа должна использовать поиск в ширину на основе очереди.

Входные данные
```
4 1 2
1 3
1 4
3 2
4 3
```
Выходные данные
```
1 3 2
```

2023-11-27 06:38 UTC, closed without merging