lab5.0
Dovgalyuk/Algorithms pull request #707
Opened 2023-11-23 12:02 UTC by heheheee21

2023-11-24 08:29 UTC, Dovgalyuk requested changes

2023-11-24 08:29 UTC, Dovgalyuk commented on Lab1C/lab5.cpp
> +        string key = generateRandomString(10);
Строки надо сгенерировать заранее, чтобы это не влияло на измерение тестируемых функций.

2023-11-24 08:29 UTC, Dovgalyuk commented on LibraryCPPTemplate/avl.h
> +    AVLNode* insertInternal(AVLNode* node, const string& key, const string& value)
Раз уж эта функция internal, то её надо сделать private.

2023-11-24 08:29 UTC, Dovgalyuk commented on LibraryCPPTemplate/Tests/avl.cpp
> +    return 0;
В тестах, которые запускаются на сервере, надо проверять корректность. И немного производительность.
А тут нет проверок, что всё отработало корректно.

2023-11-27 06:00 UTC, Dovgalyuk commented on Lab1C/lab5.cpp
> +        string key = generateRandomString(10);
Вот это не исправлено.

2023-11-27 11:49 UTC, heheheee21 commented on Lab1C/lab5.cpp
> +        string key = generateRandomString(10);
Немного не понял, я же исправил, вот:
```
// Генерация случайных строк заранее
vector<string> keys;
for (int i = 0; i < size; i++)
{
    keys.push_back(generateRandomString(10));
}

cout << "Testing with " << size << " elements:" << endl;
testAVLTreeInsertion(keys);
testMapInsertion(keys);
```
В этой части кода я сначала генерирую, а после на этих данных тестирую и AVL и std::map. В прошлой версии кода было по-другому, я генерировал в функциях случайные значения, сейчас же генерация происходит в main(), соответственно тестирование происходит на одинаковом наборе данных.

2023-11-28 09:02 UTC, Dovgalyuk commented
Принято. К защите надо подготовить сравнение производительности контейнеров, измеренное в lab5.cpp.

2023-11-28 09:02 UTC, closed without merging