lab3 Федоров Иван 2091
Dovgalyuk/Algorithms pull request #709
Opened 2023-11-23 16:22 UTC by Estomee

![image](https://github.com/Dovgalyuk/Algorithms/assets/112470254/cfd5316b-622c-4cde-b063-2b25a3bb9faf)
![image](https://github.com/Dovgalyuk/Algorithms/assets/112470254/2c02172d-9f96-47b8-a95e-4dab2e0e88e1)

2023-11-23 16:31 UTC, Estomee commented
Павел Михайлович, не знаю что с тестами, локально они проходят:
![image](https://github.com/Dovgalyuk/Algorithms/assets/112470254/f748cfdc-d494-49ca-ad5b-258048527239)
![image](https://github.com/Dovgalyuk/Algorithms/assets/112470254/72b6a02e-0b50-4e83-b514-cc3a676d2bcb)
Но при загрузке лабы: 
![image](https://github.com/Dovgalyuk/Algorithms/assets/112470254/d423aa4b-e3c0-4575-b672-e885b97c9296)

2023-11-24 08:22 UTC, Dovgalyuk commented
Список и очередь не выложены в репозиторий.

2023-11-27 05:56 UTC, Dovgalyuk requested changes

2023-11-27 05:56 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    return item = item->Next;
Ненужное присваивание.

2023-11-27 05:56 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +        ListItem* TempItem = new ListItem;
При удалении незачем выделять память.

2023-11-27 05:56 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +const vector <Point> directions =  //������� ��� ������� (����������� ��������)
Тут логичнее выглядит std::array, ведь размер не меняется.

2023-11-27 05:56 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +	queue_delete(queue);
Странно выглядит удаление очереди в этой функции, если она передаётся в качестве параметра.

2023-11-27 05:56 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +	queue_delete(queue);
Странно выглядит удаление очереди в этой функции, если она передаётся в качестве параметра.

2023-11-27 05:56 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +void Answer_Print(int** paths, vector<string> maze, int EndX, int EndY)
maze не стоит по значению передавать

2023-11-27 05:56 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +	delete[] paths;
То же самое с удалением.

2023-11-27 11:43 UTC, Estomee commented
Добавил изменения.

2023-11-28 08:47 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +void Answer_Print(int** paths, vector<string>& maze, int EndX, int EndY)
Уже лучше. Теперь для vector<string> можно сделать typedef.
А там, где лабиринт не меняется, передавать его по константной ссылке.

2023-11-28 14:08 UTC, Estomee commented
Сделано.

2023-11-29 08:55 UTC, Dovgalyuk commented
Принято. Следующее задание после защиты.

2023-11-29 08:55 UTC, closed without merging

2023-12-12 10:24 UTC, Estomee commented
Паве Михайлович, защитил у вас сегодня третью лабораторную. теперь хотел бы получить четвёртую.

2023-12-13 08:26 UTC, Dovgalyuk commented
* Разработать программный интерфейс модуля (заголовки функций) библиотеки LibraryCPPTemplate для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
* Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
* Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List библиотеки LibraryCPPTemplate.
* Разработать и добавить в проект LibraryCPPTemplate программу, тестирующую работу библиотеки для графа.
* Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать в нем кратчайшие пути для заданной пары вершин с помощью алгоритма Дейкстры. Для хранения порядка обработки вершин использовать очередь с приоритетами.