lab_3
Dovgalyuk/Algorithms pull request #710
Opened 2023-11-25 12:04 UTC by timlissovv

2023-11-27 06:07 UTC, Dovgalyuk commented on LibraryCPP/vector.cpp
> +        vector->current_size = size;
Из-за этого дальше копирование будет обращаться к неправильному числу элементов.

2023-11-27 06:08 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +        for (size_t i = 0; i < vector_size(queue->data) - 1; ++i)
Из-за этого удаление будет работать за O(N), а должно быть O(1). Чтобы этого достичь, нужно использовать кольцевой буфер.

2023-11-27 07:00 UTC, timlissovv commented on LibraryCPP/queue.cpp
> +        for (size_t i = 0; i < vector_size(queue->data) - 1; ++i)
А как мне сделать кольцевой буффер, если у меня вектор написан на обычном интовом массиве, если реализовывать на нём. кольцевой буффер, мне нужно будет сдвигать все элементы, что потребует сложности О(n). Может я чего-то не понимаю?

2023-11-28 08:35 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +        for (size_t i = 0; i < vector_size(queue->data) - 1; ++i)
Если места хватает в векторе, то срабатывает, как кольцевой буфер.
Если место кончилось, то переупорядочить элементы, скопировав их в вектор большего размера.

2023-12-05 08:13 UTC, Dovgalyuk requested changes

2023-12-05 08:13 UTC, Dovgalyuk commented on Lab1C/lab_3.cpp
> +    sort(input_data.begin(), input_data.end());
Это не сработает.
Может ведь быть так:
C
A->B
B->D
C->A

2023-12-07 19:19 UTC, timlissovv commented
Здравствуйте, у меня не билдится программа, потому что я поменял тайпдеф в файлах структур. Поменял тип данных с int на string, а так как тесты проходят на интовых значениях, они, естественно, не собираются, он так у меня получилось сделать так, чтобы программа работала. Посмотрите пожалуйста. Надеюсь, это можно принять.

2023-12-11 05:18 UTC, Dovgalyuk commented
Принято.

* Разработать программный интерфейс модуля (заголовки функций) библиотеки LibraryCPPTemplate для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
* Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
* Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List библиотеки LibraryCPPTemplate.
* Разработать и добавить в проект LibraryCPPTemplate программу, тестирующую работу библиотеки для графа.
* Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать в нем все кратчайшие пути между заданной парой вершин с помощью обхода в ширину.

2023-12-11 05:18 UTC, closed without merging