4lab
Dovgalyuk/Algorithms pull request #712
Opened 2023-11-26 19:41 UTC by Gebrur

Хочу получить задание для 4 лабораторной работы

2023-11-27 06:39 UTC, Dovgalyuk commented
* Разработать программный интерфейс модуля (заголовки функций) библиотеки LibraryCPPTemplate для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
* Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
* Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде матрицы смежности в контейнере Vector библиотеки LibraryCPPTemplate.
* Разработать и добавить в проект LibraryCPPTemplate программу, тестирующую работу библиотеки для графа.
* Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать для него алгоритмом Флойда самый длинный из кратчайших путей.

2023-12-08 07:08 UTC, Gebrur commented
У меня вопрос, для алгоритма Флойда обязательно использовать структуру итератор?

2023-12-08 07:47 UTC, Dovgalyuk commented
В алгоритме Флойда можно не использовать, но простестировать надо обязательно.

2023-12-11 05:26 UTC, Dovgalyuk commented
Если нужно, чтобы я проверил, то надо решить конфликты, которые показываются в resolve conflicts.

2023-12-12 07:38 UTC, Dovgalyuk requested changes

2023-12-12 07:38 UTC, Dovgalyuk commented on Labs/lab4.cpp
> +                        mutableGraph.getVertex(j)->setVertexData(
В рёбрах должны веса путей храниться, а не в вершинах.

2023-12-12 07:38 UTC, Dovgalyuk commented on LibraryCPPTemplate/Tests/graph.cpp
> +        if ((*it)->getVertexData() != 3) {
Слишком простой тест для итератора.

2023-12-12 07:38 UTC, Dovgalyuk commented on LibraryCPPTemplate/Tests/graph.cpp
> +    graph->removeEdge(2, 1);
Для удалений тоже желательно граф побольше сделать.

2023-12-12 07:38 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +    Vector<Vertex*>* vertexes;
Зачем хранить указатели на вектора, если можно просто сами вектора хранить?
В хранинии указателей на вершины тоже нет смысла, потому что все они всегда существуют.

2023-12-12 07:38 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +            if (edge1) {
delete допустимо вызывать с нулевым указателем.

2023-12-14 16:01 UTC, Gebrur commented on LibraryCPPTemplate/graph.h
> +    Vector<Vertex*>* vertexes;
Я во всем graph.h обращаюсь к векторам и вершинам как к указателям и для доступа к ним я использую оператор    -> если бы я хранил их как объекты то для доступа использовал бы оператор   .  , также при использовании указателей мы получаем доступ к командам как delete и new для управления памятью и можем сделать например так delete vertexes; что позволяет нам самостоятельно управлять памятью, если бы vertexes был объектом так мы бы сделать не смогли

2023-12-14 16:48 UTC, Gebrur commented
исправил все ошибки

2023-12-18 06:06 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +    Vector<Vertex*>* vertexes;
И какой в этом смысл? Вершины же не могут отсутствовать.

2023-12-18 06:07 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +    Vector<Edge*>* edgeMatrix;
Тут остался указатель на вектор, хотя можно просто сразу объект объявить.

2023-12-18 12:06 UTC, Gebrur commented
я использую указатели для того чтобы у меня был доступ к new и delete они мне нужны потому что при  использовании addVertex, removeVertex, removeEdge мы должны удалять прошлые значения матрицы чтобы заменить их новыми, или же удалить ребро из нашего графа, все это нужно чтобы память занятая уже ненужными для нас данными удалялась, именно поэтому я использовал указатели так как с их помощью и используя new и delete мне показалось что это сделать будет проще

2023-12-19 08:01 UTC, Dovgalyuk commented
> я использую указатели для того чтобы у меня был доступ к new и delete они мне нужны потому что при использовании addVertex, removeVertex, removeEdge мы должны удалять прошлые значения матрицы чтобы заменить их новыми, или же удалить ребро из нашего графа, все это нужно чтобы память занятая уже ненужными для нас данными удалялась, именно поэтому я использовал указатели так как с их помощью и используя new и delete мне показалось что это сделать будет проще

Для этого в стандартной библиотеке vector предоставляет метод swap.
Здесь можно сделать то же самое. Либо аккуратно перемещать элементы и изменять размер.

2023-12-19 11:48 UTC, Gebrur commented
Вектор по заданию у нас используется для хранения связей в виде матрицы смежности, и даже если мы реализуем swap то она просто меняет данные в двух векторах местами это может сработать у нас мы переносим все данные из одного вектора в другой с необходимыми нам изменениями например с удаленной вершиной, что мы для этого сделаем удалим одно ребро из вершины потом удалим второе перезапишем данные матрицы в новый вектор старый удалим, но у нас остануться веса удаленных ребер и они будут занимать память, в тоже время у  меня в коде сделано так что при необходимости мы можем просто удалить все что связано с вершиной с помощью delete  и после этого ничего не останется, возможно это и увеличит объем кода но это сделает его более понятным и читаемым, и при возникновении утечек памяти даст нам возможность легко их выявить и устранить.

2023-12-21 05:36 UTC, Dovgalyuk commented
Суть использования swap в следующем.
Мы делаем локальную переменную vector, который заполняется новыми данными.
Затем мы делаем swap этого вектора с нашим основным.
После завершения функции локальный вектор, который получил старые данные, уничтожается вместе с ними.

2023-12-21 06:57 UTC, Gebrur commented
Ну так я себе это и представлял, только не понимаю зачем нам делать это другим способом если мой изначальный код делает все тоже самое, но использует указатели

2023-12-22 05:51 UTC, Dovgalyuk commented
> Ну так я себе это и представлял, только не понимаю зачем нам делать это другим способом если мой изначальный код делает все тоже самое, но использует указатели вместо объектов

В общем случае, если нет лишних new/delete - меньше шансов на ошибку.

2023-12-24 15:00 UTC, Gebrur commented
заменил в addVertex removeVertex и Graph& operator=  копирование данных с помощью new  на использование swap. По итогу код стал короче и стало меньше вызовов new и delete

2023-12-25 08:41 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +    Vector<Edge*>* edgeMatrix;
Что-то все указатели остались как были.

2023-12-25 13:13 UTC, Gebrur commented
я доработал свою лабу теперь она без указателей и проходит все тесты

2023-12-26 08:11 UTC, Dovgalyuk commented
Принято.

* Разработать интерфейс (набор функций) для ассоциативного массива, который хранит пары (ключ)строка -> (значение)строка. Поддерживаемые операции: добавить пару ключ-значение, найти значение по ключу, удалить значение по ключу.
* Реализовать контейнер на основе красно-чёрного дерева, реализующий разработанный интерфейс.
* Создать тест для проверки работы контейнера. Программа должна включать в себя нагрузочное тестирование для исключения ошибок, приводящих к сложности работы O(N*N) при поиске, удалении или добавлении значений.
* Написать генератор входных данных различного объема для этого контейнера.
* Сравнить скорость выполнения операции добавления в контейнер содержимого файла со стандартным контейнером std::map при различных объемах данных. Построить график зависимости времени работы от объёма входных данных и оценить характер зависимости.

2023-12-26 08:11 UTC, closed without merging