Lab1
Dovgalyuk/Algorithms pull request #714
Opened 2023-11-27 22:20 UTC by Artickgg

Скинул 1 лабу

2023-11-28 09:17 UTC, Dovgalyuk requested changes

2023-11-28 09:17 UTC, Dovgalyuk commented on .vscode/tasks.json
Этот файл надо удалить из репозитория.

2023-11-28 09:17 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +        element = pow(element, -1);
Обратное значение логичнее сохранять в переменной вещественного типа.

2023-11-28 18:27 UTC, Artickgg commented
Удалил папку, исправил на double элементы, которые меньше 1. А также изменил небольшую опечатку во 2 задании

2023-11-29 09:29 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

Реализовать команды манипуляции стеком из языка Forth: https://skilldrick.github.io/easyforth
Программа читает входную строку из следующих команд:
* 0-9 - заносит число в стек
* +-*/% - арифметические операции. Извлекают два числа из стека, а потом заносят туда результат
* dup - дублирует число на вершине стека
* drop - удаляет число с вершины стека
* swap - меняет местами два числа на вершине стека
* over - берёт элемент под вершиной стека и добавляет его в стек
* rot - перемещает "по кругу" верхние три элемента стека
* . - извлекает из стека верхний элемент и выводит на экран

Входные данные
```
1 2 3 rot . . .
```
Выходные данные
```
1
3
2
```

Входные данные
```
1 dup . 2 dup . 3 dup . + + .
```
Выходные данные
```
1
2
3
6
```

2023-11-29 09:29 UTC, closed without merging