Petrov_Vsevolod_2092_Lab_3
Dovgalyuk/Algorithms pull request #715
Opened 2023-11-28 16:31 UTC by LazyHat

2023-11-29 09:19 UTC, Dovgalyuk requested changes

2023-11-29 09:19 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +            shift_left(buffer_size);
remove должен выполняться за O(1) в среднем

2023-12-07 17:49 UTC, LazyHat commented on LibraryCPPTemplate/queue.h
> +            shift_left(buffer_size);
Так оно и так выполняется за O(1) в среднем.
И я не понимаю, почему очередь нужно реализовать на основе вектора, а не списка, это испытание такое?

2023-12-08 07:04 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +            shift_left(buffer_size);
Я не заметил, что перемещение не каждый раз происходит. Тогда действительно O(N) в среднем.

2023-12-08 07:09 UTC, Dovgalyuk requested changes

2023-12-08 07:09 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +    return (pow == 0) ? 1 : a * powul(a, pow - 1);
Не стоит использовать рекурсию вместо цикла в общем случае. Не всегда компилятор её оптимизирует.

2023-12-08 07:09 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +    std::size_t count_of_steps = ceil(max_bits / (float)MAX_BITS_IN_STEP);
Если все числа целые, то лучше сразу и считать в целых числах.

2023-12-08 07:09 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +            arr.erase(arr.begin());
Вот из-за этого мы получим сложность сортировки O(N^2)

2023-12-14 15:02 UTC, LazyHat commented on Lab3CPP/lab3.cpp
> +    std::size_t count_of_steps = ceil(max_bits / (float)MAX_BITS_IN_STEP);
Не всегда получатся целые числа.

2023-12-14 15:02 UTC, LazyHat commented on Lab3CPP/lab3.cpp
> +    return (pow == 0) ? 1 : a * powul(a, pow - 1);
Сделал

2023-12-14 15:04 UTC, LazyHat commented on Lab3CPP/lab3.cpp
> +            arr.erase(arr.begin());
Да, вижу.
Исправил.

2023-12-18 05:53 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +    return (pow == 0) ? 1 : a * powul(a, pow - 1);
Рекурсия нуждается в дополнительной памяти, нужной для стека вызовов.

2023-12-18 05:55 UTC, Dovgalyuk commented
Принято. Следующее задание после защиты.

2023-12-18 05:55 UTC, closed without merging