Lab3
Dovgalyuk/Algorithms pull request #716
Opened 2023-11-28 17:08 UTC by PieDIEmaN

2023-11-29 09:27 UTC, Dovgalyuk requested changes

2023-11-29 09:27 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +    int distances[MAX_VERTICES] = { 0 };
Так не надо писать, потому что это не означает, что все элементы будут инициализированы таким значением. На самом деле они получат значение по умолчанию (то есть 0).
И логичнее будет написать = {};

2023-11-29 09:27 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +            cin >> adjMatrix[i][j];
В задании не матрица смежности на входе.

2023-11-29 19:23 UTC, PieDIEmaN commented
"Задан ориентированный граф виде матрицы смежности. В первой строке входного файла записано количество вершин, номер стартовой вершины и номер финишной. В последующих строках идет описание матрицы смежности."
Слегка не понял в чем была ошибка "В задании не матрица смежности на входе.". Можете уточнить?

2023-11-30 07:00 UTC, Dovgalyuk commented
> "Задан ориентированный граф виде матрицы смежности. В первой строке входного файла записано количество вершин, номер стартовой вершины и номер финишной. В последующих строках идет описание матрицы смежности." Слегка не понял в чем была ошибка "В задании не матрица смежности на входе.". Можете уточнить что не так? Или мне нужно было выводить и вводить все в файл ?

У меня было неверно записано.

Следующее задание после защиты.

2023-11-30 07:00 UTC, closed without merging