Lab_1
Dovgalyuk/Algorithms pull request #717
Opened 2023-11-28 20:20 UTC by Alav1e

2023-11-28 20:21 UTC, Alav1e commented
reshenia неверна, выполняет с ошибкой. верная lab_1

2023-11-30 06:56 UTC, Dovgalyuk requested changes

2023-12-01 13:39 UTC, Dovgalyuk commented on Lab1C/FileName.cpp
> +		for (size_t j = 0; j < array_size(newArray) - i - 1; j++) {
Достаточно одного цикла, чтобы переместить все ненужные элементы в конец. Можно это совместить с их нахождением.

2023-12-01 15:48 UTC, Alav1e commented
Исправил.

2023-12-01 15:49 UTC, Alav1e commented on Lab1C/FileName.cpp
> +		for (size_t j = 0; j < array_size(newArray) - i - 1; j++) {
Но ведь это не ошибка? Я могу приступать ко второму или обязательно к доработке?

2023-12-05 07:44 UTC, Dovgalyuk commented on Lab1C/FileName.cpp
> +		for (size_t j = 0; j < array_size(newArray) - i - 1; j++) {
Тут явно делается совсем не то, что требуется по заданию.

2023-12-06 07:43 UTC, Dovgalyuk requested changes

2023-12-06 07:43 UTC, Dovgalyuk commented on Lab1C/FileName.cpp
> +	}
Зачем этот код остался?

2023-12-06 07:43 UTC, Dovgalyuk commented on Lab1C/FileName.cpp
> +	}
Тут будет выход за границы массива.

2023-12-06 07:43 UTC, Dovgalyuk commented on Lab1C/FileName.cpp
> +	anotherone = array_create(array_size(oldArray) + no_need_element);
Этот массив зачем?

2023-12-06 10:00 UTC, Alav1e commented on Lab1C/FileName.cpp
> +	}
Не понял. Выставил cout << i , вывелось столько цифр, сколько элементов в oldArray. Потом просто из newArray ввел числа в oldArray, столько цифр, сколько действует цикл. Или вы о другом?

2023-12-06 10:02 UTC, Alav1e commented on Lab1C/FileName.cpp
> +	anotherone = array_create(array_size(oldArray) + no_need_element);
Я думал, что по заданию изначальный массив нужно удалить и записать данные в другой, перечитал - такого пункта нет. Получается, что можно просто вывести newArray в конце? Тогда от этого массива можно избавиться.

2023-12-06 10:06 UTC, Alav1e commented on Lab1C/FileName.cpp
> +	}
Для сортировки элементов, чтобы не нужные элементы были в конце и чтобы потом можно было передать нужные элементы в новый массив, отбросив нули.

2023-12-07 06:43 UTC, Dovgalyuk commented on Lab1C/FileName.cpp
> +	}
Нет, надо "сжать" массив, перемещая оставшиеся элементы в том же относительном порядке, в котором они были раньше.

2023-12-11 05:08 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
* Решить задачу, используя реализованный стек.

Написать программу, которая с помощью стека проверяет правильность последовательности из скобок вида (), [] и {} и кавычек вида “” и ‘’. В выходной файл напечатать YES, если последовательность правильная и NO, если неправильная.

Входные данные
```
([]"")
```
Выходные данные
```
YES
```

Входные данные
```
(")"
```
Выходные данные
```
NO
```

2023-12-11 05:08 UTC, closed without merging