lab4
Dovgalyuk/Algorithms pull request #719
Opened 2023-11-29 13:59 UTC by duraaach0k

2023-11-29 14:40 UTC, duraaach0k commented
у меня какие-то странные ошибки, как мне их исправить? Файлы то все есть

2023-11-30 07:02 UTC, Dovgalyuk commented
Для шаблонов не надо использовать target_link_libraries, потому что они не собираются в виде библиотеки, а используются только как заголовочные файлы.

2023-12-01 13:50 UTC, Dovgalyuk requested changes

2023-12-01 13:50 UTC, Dovgalyuk commented on Lab1C/lab4.cpp
> +#define V 5
Размер графа не должен быть константой.

2023-12-01 13:50 UTC, Dovgalyuk commented on Lab1C/lab4.cpp
> +        i = parent[i];
Тут не хватает "сжатия" дерева, когда во время поиска все просмотренные вершины подцепляются к корню, чтобы в следующий раз быстрее искать.

2023-12-01 13:50 UTC, Dovgalyuk commented on Lab1C/lab4.cpp
> +    KruskalMST(adjMatrix);
Нельзя просто выгружать матрицу. Надо работать с графом через запрос отдельных рёбер и вершин. И добиться того, чтобы это было достаточно удобным.

2023-12-01 13:50 UTC, Dovgalyuk commented on LibraryCPPTemplate/Tests/graphmatr.cpp
> +
Слишком мало всего в графе. Нужно добавить побольше, а кроме всего этого тестировать ещё и удаление вершины.

2023-12-01 13:50 UTC, Dovgalyuk commented on LibraryCPPTemplate/graphmatr.h
> +    std::vector<std::vector<int>> adjMatrix;
Тут должен быть собственный вектор.

2023-12-05 08:08 UTC, Dovgalyuk commented
1. Можно хранить матрицу в одномерном векторе
2. Можно реализовать вектор-шаблон, тогда получится использовать двумерный способ

2023-12-06 07:48 UTC, Dovgalyuk commented
Лучше всего реализовать шаблонный vector в файле LibraryCPPTemplate/vector.h, а потом его подключать.

2023-12-07 06:51 UTC, Dovgalyuk commented
erase правильнее сделать по индексу, а не по значению

2023-12-07 14:38 UTC, duraaach0k commented
так я тоже пробовал вчера, была такая же ошибка, я не знаю как ее исправить

2023-12-08 13:58 UTC, duraaach0k commented
времени не так много осталось, чтобы сдать лабу, тут еще такие проблемы, так и не успею, а мне 4 по предмету очень надо(

2023-12-11 05:25 UTC, Dovgalyuk commented
Надо нажать resolve conflicts, чтобы посмотреть, какие там изменения основной ветки конфликтуют с твоими. И поправить свои в итоге.

2023-12-11 14:58 UTC, duraaach0k commented
наконец-то все работает

2023-12-12 07:51 UTC, Dovgalyuk commented
Теста на реализованный вектор нет.

2023-12-12 15:20 UTC, duraaach0k commented
тест сделал

2023-12-13 08:36 UTC, Dovgalyuk requested changes

2023-12-13 08:36 UTC, Dovgalyuk commented on LibraryCPPTemplate/Tests/vector.h
А зачем это в тестах?

2023-12-13 08:36 UTC, Dovgalyuk commented on LibraryCPPTemplate/vector.h
> +    void erase(const Data& value)
erase должен удалять по индексу, а не по значению

2023-12-13 08:36 UTC, Dovgalyuk commented on LibraryCPPTemplate/graphmatr.h
> +    Vector<T>* vertices;
Зачем тут указатель на вектор, если можно просто вектор?

2023-12-13 08:36 UTC, Dovgalyuk commented on LibraryCPPTemplate/graphmatr.h
> +    Vector<int>* adjMatrix;
В матрице смежности нужно хранить ещё метки для рёбер, а их тип должен быть вторым параметром шаблона Graph.

2023-12-13 08:36 UTC, Dovgalyuk commented on LibraryCPPTemplate/Tests/graphmatr.cpp
> +
Тест всё ещё недостаточно хорош.

2023-12-13 08:36 UTC, Dovgalyuk commented on Lab1C/lab4.cpp
> +    graph.addEdge(3, 4, 70);
Граф должен считываться откуда-нибудь.

2023-12-13 08:36 UTC, Dovgalyuk commented on Lab1C/lab4.cpp
> +void KruskalMST(Graph<int>cost)
Граф не меняется, поэтому его можно передавать по константой ссылке.

2023-12-13 19:50 UTC, duraaach0k commented on LibraryCPPTemplate/Tests/vector.h
"vector.h дублируется в тестах" вы сами писали ранее, когда у меня не работало

2023-12-13 19:50 UTC, duraaach0k commented on LibraryCPPTemplate/vector.h
> +    void erase(const Data& value)
сделал

2023-12-13 19:50 UTC, duraaach0k commented on LibraryCPPTemplate/graphmatr.h
> +    Vector<T>* vertices;
по-другому у меня не работает

2023-12-13 19:51 UTC, duraaach0k commented on LibraryCPPTemplate/graphmatr.h
> +    Vector<int>* adjMatrix;
в матрице и так хранятся веса ребер, это и есть метка для ребра, ну это как минимум логично. потому что в графах никаких других меток у ребер нет

2023-12-13 19:51 UTC, duraaach0k commented on Lab1C/lab4.cpp
> +    graph.addEdge(3, 4, 70);
сделал

2023-12-13 19:52 UTC, duraaach0k commented on Lab1C/lab4.cpp
> +void KruskalMST(Graph<int>cost)
не совсем понял. А зачем тут это менять? Код эффективнее же не будет? Я ведь в данном случае разработчик программы и имею какую-то свободу действий

2023-12-13 19:53 UTC, duraaach0k commented
А что касается теста, он тестирует все функции библиотеки

2023-12-14 11:40 UTC, Dovgalyuk commented on Lab1C/lab4.cpp
> +void KruskalMST(Graph<int>cost)
Код будет эффективнее, если не передавать сложные типы данных по значению, когда в копировании нет необходимости.

2023-12-14 11:42 UTC, Dovgalyuk commented on LibraryCPPTemplate/Tests/vector.h
так сейчас и дублируется, хотя можно просто подключить файл из библиотеки

2023-12-14 11:42 UTC, Dovgalyuk commented on LibraryCPPTemplate/graphmatr.h
> +    Vector<T>* vertices;
Надо добиться, чтобы заработало.

2023-12-14 11:43 UTC, Dovgalyuk commented on LibraryCPPTemplate/graphmatr.h
> +    Vector<int>* adjMatrix;
Это в текущей задаче веса. А где-то может строки нужны будут как метки рёбер. Для того и шаблон.

2023-12-14 14:33 UTC, duraaach0k commented on Lab1C/lab4.cpp
> +void KruskalMST(Graph<int>cost)
сделал

2023-12-14 15:12 UTC, duraaach0k commented on LibraryCPPTemplate/graphmatr.h
> +    Vector<T>* vertices;
сделал

2023-12-14 15:32 UTC, duraaach0k commented on LibraryCPPTemplate/Tests/vector.h
попробовал, не получается (писал путь к файлу, не помогло)

2023-12-16 21:02 UTC, duraaach0k commented
я 25 числа уже уеду из новгорода, очень хотелось бы успеть защитить 4 лабу на следующей неделе, это возможно? Ну очень нужно 4 по предмету, чтобы сохранить стипендию

2023-12-18 06:39 UTC, Dovgalyuk requested changes

2023-12-18 06:39 UTC, Dovgalyuk commented on LibraryCPPTemplate/Tests/graphmatr.cpp
> +
Ничего не изменилось.
Итератор вообще не тестируется.

2023-12-18 06:39 UTC, Dovgalyuk commented on LibraryCPPTemplate/graphmatr.h
> +    }
Этих двух функций быть не должно в публичном интерфейсе.

2023-12-18 06:39 UTC, Dovgalyuk commented on LibraryCPPTemplate/graphmatr.h
> +    Vector<int> adjMatrix;
Тут должен быть дополнительный тип из шаблона.

2023-12-18 06:39 UTC, Dovgalyuk commented on LibraryCPPTemplate/graphmatr.h
> +        vertices.resize(numVertices);
Тут удаляется последняя вершина.
Значит всё же тест недостаточно хорош.

2023-12-18 06:40 UTC, Dovgalyuk commented
> я 25 числа уже уеду из новгорода, очень хотелось бы успеть защитить 4 лабу на следующей неделе, это возможно? Ну очень нужно 4 по предмету, чтобы сохранить стипендию

На этой неделе будет занятие во вторник, на следующей во вторник и среду.

2023-12-18 15:22 UTC, duraaach0k commented on LibraryCPPTemplate/graphmatr.h
> +    Vector<int> adjMatrix;
Из какого шаблона то? Я не понимаю. У меня вроде все работает и выполняет функции, которые были описаны в задании

2023-12-18 15:22 UTC, duraaach0k commented on LibraryCPPTemplate/graphmatr.h
> +        vertices.resize(numVertices);
она удаляется после сдвига всех вершин, поэтому все работает как надо

2023-12-18 15:36 UTC, duraaach0k commented on LibraryCPPTemplate/graphmatr.h
> +    }
убрал в приват их

2023-12-18 15:37 UTC, duraaach0k commented
сделал тест итератора

2023-12-19 08:08 UTC, Dovgalyuk requested changes

2023-12-19 08:08 UTC, Dovgalyuk commented on LibraryCPPTemplate/Tests/graphmatr.cpp
> +    Vector<long unsigned int> actualAdjacentVertices = graph.getAdjacentVertices(0);
Это не итератор.
Итератор должен поочерёдно извлекать соседние вершины, а не все сразу.

2023-12-19 08:08 UTC, Dovgalyuk commented on LibraryCPPTemplate/graphmatr.h
> +    Vector<int> adjMatrix;
Должно быть ```Graph<A, B>```

2023-12-19 08:08 UTC, Dovgalyuk commented on LibraryCPPTemplate/graphmatr.h
> +        vertices.resize(numVertices);
А где сдвиг вершин?

2023-12-19 08:08 UTC, Dovgalyuk commented on LibraryCPPTemplate/graphmatr.h
> +    Vector<long unsigned int> getAdjacentVertices(long unsigned int vertex) {
Вместо этого нужен нормальный итератор.

2023-12-19 15:10 UTC, duraaach0k commented
итератор сделал. Сдвиг по вершинам там два цикла в функции удаления. А про Должно быть Graph<A, B> я так и не понял что тут надо сделать.

2023-12-21 05:47 UTC, Dovgalyuk commented
> итератор сделал. Сдвиг по вершинам там два цикла в функции удаления. А про Должно быть Graph<A, B> я так и не понял что тут надо сделать.

Вместо ```template <typename T> class Graph {```, где T - тип пометки вершины, должно быть ```template <typename T, template T2> class Graph {```, где T2 - тип пометки ребра.

2023-12-21 13:38 UTC, duraaach0k commented
Сделал, можно во вторник прийти защитить? Или если не получится в январе до экзамена?

2023-12-22 06:14 UTC, Dovgalyuk requested changes

2023-12-22 06:14 UTC, Dovgalyuk commented on LibraryCPPTemplate/graphmatr.h
> +    Vector<long unsigned int> adjacentVertices;
Ни к чему копию делать, когда можно просто ходить по матрице смежности.

2023-12-22 06:14 UTC, Dovgalyuk commented on LibraryCPPTemplate/graphmatr.h
> +        vertices.resize(numVertices);
Всё ещё не вижу сдвига вершин.

2023-12-22 06:14 UTC, Dovgalyuk commented
> Сделал, можно во вторник прийти защитить? Или если не получится в январе до экзамена?

Можно будет в январе до экзамена, но сначала надо исправить.

2023-12-23 22:17 UTC, duraaach0k commented on LibraryCPPTemplate/graphmatr.h
> +    Vector<long unsigned int> adjacentVertices;
если правильно понял, то поправил.

2023-12-23 22:29 UTC, duraaach0k commented
сдвигаются строки и столбцы матрицы по сути, чтобы когда сделаем ресайз удалились крайние, то есть пустые. Сдвиг идет в двух циклах, сначала для строк, потом для столбиков. 
        for (long unsigned int i = vertex; i < numVertices - 1; i++) {
            for (long unsigned int j = 0; j < numVertices; j++) {
                adjMatrix.set(i * numVertices + j, adjMatrix.get((i + 1) * numVertices + j));
            }
        }


        for (long unsigned int i = 0; i < numVertices; i++) {
            for (long unsigned int j = vertex; j < numVertices - 1; j++) {
                adjMatrix.set(i * numVertices + j, adjMatrix.get(i * numVertices + j + 1));
            }
        }

2023-12-25 08:38 UTC, Dovgalyuk commented
no

> сдвигаются строки и столбцы матрицы по сути, чтобы когда сделаем ресайз удалились крайние, то есть пустые. Сдвиг идет в двух циклах, сначала для строк, потом для столбиков. for (long unsigned int i = vertex; i < numVertices - 1; i++) { for (long unsigned int j = 0; j < numVertices; j++) { adjMatrix.set(i * numVertices + j, adjMatrix.get((i + 1) * numVertices + j)); } }
> 
> ```
>     for (long unsigned int i = 0; i < numVertices; i++) {
>         for (long unsigned int j = vertex; j < numVertices - 1; j++) {
>             adjMatrix.set(i * numVertices + j, adjMatrix.get(i * numVertices + j + 1));
>         }
>     }
> ```

Но при этом в середине vertices остаётся вершина, которую мы удаляем.

2023-12-25 11:45 UTC, duraaach0k commented
Все дошло про какой сдвиг вы писали, сделал его тоже.

2023-12-25 11:47 UTC, duraaach0k commented
А можно как-то онлайн защититься? Например по дискорду? Показать все или нарисовать смогу и так

2023-12-26 07:37 UTC, Dovgalyuk commented
> А можно как-то онлайн защититься? Например по дискорду? Показать все или нарисовать смогу и так

Онлайн нельзя.

2023-12-26 07:39 UTC, Dovgalyuk commented on LibraryCPPTemplate/graphmatr.h
> +    int getEdgeWeight(long unsigned int src, long unsigned int dest)const {
Тут же должен быть не int, а T2. Ну и везде такое.

2023-12-29 10:58 UTC, Dovgalyuk requested changes

2023-12-29 10:58 UTC, Dovgalyuk commented on LibraryCPPTemplate/graphmatr.h
> +    const Vector<int>* adjMatrix;
Тут целый тип вместо параметра шаблона.

2023-12-29 16:11 UTC, duraaach0k commented
поправил

2024-01-09 19:02 UTC, duraaach0k commented
Здравствуйте. Поздравляю с прошедшими праздниками. Что там с моей лабой? Принята?

2024-01-11 05:05 UTC, Dovgalyuk commented
Принято.

2024-01-11 05:05 UTC, closed without merging