Lab5
Dovgalyuk/Algorithms pull request #720
Opened 2023-12-01 02:35 UTC by endiepq

2023-12-01 13:41 UTC, Dovgalyuk requested changes

2023-12-01 13:41 UTC, Dovgalyuk commented on LibraryCPPTemplate/splaytree.h
> +    std::string value;
Раз уж мы в библиотеке template, то типы key и value должны быть параметрами шаблона.

2023-12-05 08:23 UTC, Dovgalyuk commented
Принято.

2023-12-05 08:23 UTC, closed without merging

2023-12-12 07:44 UTC, endiepq commented
![График](https://github.com/Dovgalyuk/Algorithms/assets/92216179/8ff942b1-5c02-4e55-b351-1ed03b605d90)

Исходные данные:
Testing with 100 elements:
SplayTree Insertion Time: 443 microseconds
map Insertion Time: 550 microseconds

Testing with 500 elements:
SplayTree Insertion Time: 2543 microseconds
map Insertion Time: 2732 microseconds

Testing with 1000 elements:
SplayTree Insertion Time: 5068 microseconds
map Insertion Time: 6655 microseconds

Testing with 10000 elements:
SplayTree Insertion Time: 52990 microseconds
map Insertion Time: 68679 microseconds

Testing with 100000 elements:
SplayTree Insertion Time: 609613 microseconds
map Insertion Time: 554281 microseconds

Testing with 500000 elements:
SplayTree Insertion Time: 2867737 microseconds
map Insertion Time: 3058222 microseconds

С количеством элементов время выполнения увеличивается. В визуальном представлении график является линейным.

2023-12-13 08:24 UTC, Dovgalyuk commented
Разработать архиватор для кодирования и раскодирования файла с помощью кода Хаффмана.
Код архивации/разархивации оформить в виде библиотеки, в которую передается ссылка на объекты istream/ostream для возможности работы с произвольными файлами и буферами через этот интерфейс.
При кодировании использовать собственную реализацию очереди с приоритетами.
Добавить тесты для проверки всех вспомогательных структур данных.