up
Dovgalyuk/Algorithms pull request #722
Opened 2023-12-02 14:45 UTC by masha3430

2023-12-04 22:25 UTC, masha3430 commented
Здравствуйте
Никак не могу понять почему не проходят тесты, можно ли получить какую-нибудь подсказку

2023-12-05 08:27 UTC, Dovgalyuk requested changes

2023-12-05 08:27 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +    task1(arr);
Либо мы создаём массив до вызова функции, а потом передаём его в качестве параметра, либо создаём внутри функции и там же удаляем.

2023-12-05 08:27 UTC, Dovgalyuk commented
Нужный тест (для array) проходит успешно. На остальные можно пока не обращать внимания.

2023-12-05 14:37 UTC, masha3430 commented
Теперь массив создается и удаляется внутри функций

2023-12-06 07:46 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library двусвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

Написать программу, проверяющую правильность расстановки двух видов кавычек (“ и ‘) и скобок () в строке.  Программа должна выводить YES для правильной последовательности и NO для неправильной.

Входные данные
```
"ab(c 'de' f)gt"
```
Выходные данные
```
YES
```

Входные данные
```
"adjsk 'z' frr')
```
Выходные данные
```
NO
```

2023-12-06 07:46 UTC, closed without merging