Lab1
Dovgalyuk/Algorithms pull request #725
Opened 2023-12-04 23:20 UTC by makargravanov

lab1

2023-12-04 23:28 UTC, makargravanov commented
Здравствуйте, Павел Михайлович, сделал первую лабу, у меня, вроде бы, всё собирается. Если Вы хотите посмотреть код, то это https://github.com/Dovgalyuk/Algorithms/pull/725/commits/8ca9235cd75b988df7827cc3f43812d81183cc9a для самого массива и https://github.com/Dovgalyuk/Algorithms/pull/725/commits/20f9187b717875c5162d8061eb49e45e14135cf1 для алгоритмической задачи. Также, для Вашего удобства, ссылка на само задание : https://github.com/Dovgalyuk/Algorithms/pull/553 .

2023-12-04 23:37 UTC, makargravanov commented
Единственный момент, только сейчас заметил, cppcheck-action-test жаловался (не работал print-result) на оставленный мною костыль в виде #include "array.cpp", без которого всё это дело не работало в visual studio в отрыве от cmake, я отредактировал уже после пуллреквеста, потому, пока что, заливать новый не буду, если того не потребуется. Так что, с нетерпением жду Вашего ответа!

2023-12-04 23:40 UTC, makargravanov commented
А, заметил, что это изменение отображается, как https://github.com/Dovgalyuk/Algorithms/pull/725/commits/3a282a6b7d0ce50a407bcf74ea4555ea8db97e00 , так что всё окей должно быть

2023-12-04 23:44 UTC, makargravanov commented
А, нет, стоп, опять что-то не так(

2023-12-04 23:56 UTC, makargravanov commented
Так, всё было вроде бы правильно изначально. Теперь поправил, обратно добавив инклюд для array.cpp, теперь всё должно собираться.

2023-12-05 08:31 UTC, Dovgalyuk requested changes

2023-12-05 08:31 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +void task1(Array* arr,int size)
Нет смысла передавать size, если его можно запросить у массива.

2023-12-05 13:27 UTC, makargravanov commented
Обновил код в соответствии с Вашими требованиями

2023-12-06 07:39 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

Написать программу, которая с помощью стека проверяет правильность последовательности из скобок вида (), [] и {} и кавычек вида “” и ‘’. В выходной файл напечатать YES, если последовательность правильная и NO, если неправильная.

Входные данные
```
([]"")
```
Выходные данные
```
YES
```

Входные данные
```
(")"
```
Выходные данные
```
NO
```

2023-12-06 07:39 UTC, closed without merging

2023-12-10 23:01 UTC, makargravanov commented
Вот предыдущий пуллреквест, с заданием https://github.com/Dovgalyuk/Algorithms/pull/725#issuecomment-1842262230

2023-12-10 23:01 UTC, makargravanov commented
ой, не сюда