Lab2
Dovgalyuk/Algorithms pull request #727
Opened 2023-12-06 21:31 UTC by gsbfio

2023-12-07 07:06 UTC, Dovgalyuk requested changes

2023-12-07 07:06 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    ListItem* end;
Зачем здесь нужен end?

2023-12-07 07:06 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +};
Стек должен не реализовывать список заново, а использовать готовый.

2023-12-08 00:14 UTC, gsbfio commented
Здравствуйте, у меня два вопроса:

1) **"lab2.cpp Сюда стек не надо включать, а надо использовать библиотеку."**
Оно иначе не работает (error C2027: использование неопределенного типа "Stack"). Я вижу два рабочих варианта только: -либо в заголовочном файле stack.h прописывать (тогда его видит и lab2.cpp и stack.cpp при подключении библиотеки, но так запретили делать)
-либо прописывать структуру и в lab2.cpp и в stack.cpp
В ином случае он просто не передает у меня структуру из stack.cpp в main.cpp я не понимаю что с этим делать.

2) **"Нужно реализовать разбор произвольного выражения."**
Нужно чтобы после выполнения шагов вывело "1+2*3" в итоге, а не результат вычисления "7"?
Или чтобы считывало строку "1+2*3" и на ее основе выполняла шаги операции, которые указаны в задании?

2023-12-08 07:47 UTC, Dovgalyuk commented
1. Не нужно использовать саму структуру. Там есть набор функций, в которые просто передаётся указатель. Его и нужно использовать, чтобы работать со стеком.
2. Нужно считать строку с клавиатуры или файла, а потом вычислить выражение из этой строки.

2023-12-17 01:39 UTC, gsbfio commented
Исправил.
Использовал дополнительно обычный стэк для хранения символов, т.к менять библиотеки не разрешается, а там используются численные значения.

2023-12-18 06:45 UTC, Dovgalyuk requested changes

2023-12-18 06:45 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +ListItem* list_erase_next(List* list, ListItem* item)
Эта функция не реализована.

2023-12-18 06:45 UTC, Dovgalyuk commented on Lab1CPP/lab2.cpp
> +    }
Вводиться должно произвольное выражение.

2023-12-18 06:45 UTC, Dovgalyuk commented on Lab1CPP/lab2.cpp
> +    stack<char> opstack;
Стек должен быть не из стандартной библиотеки, а собственный.

2023-12-18 06:45 UTC, Dovgalyuk commented on Lab1CPP/lab2.cpp
> +            opstack.push(c);
Тут надо учитывать приоритет операций.

2023-12-19 02:40 UTC, gsbfio commented
Исправлено

2023-12-19 08:27 UTC, Dovgalyuk requested changes

2023-12-19 08:27 UTC, Dovgalyuk commented on Lab1CPP/lab2.cpp
> +    List* oplist = list_create();
А зачем эти списки?

2023-12-19 08:27 UTC, Dovgalyuk commented on Lab1CPP/lab2.cpp
> +                    break;
Одинаковый код вывода можно вынести в функцию.

2023-12-19 08:27 UTC, Dovgalyuk commented on Lab1CPP/lab2.cpp
> +    while (stack_empty(opstack) == false && stack_get(opstack) != '(') {
А тут зачем проверка на скобку?

2023-12-20 01:02 UTC, gsbfio commented
Исправлено

2023-12-21 06:17 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.

Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной - «#» или пустым пространством – «.».
Стартовая позиция обозначается как X, финишные позиции цифрами от 0 до 9.
Написать программу, которая выводит цифру, ближайшую к стартовой позиции.
За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди.

Входные данные
```
######
#...X#
#.#.##
#3.4.#
######
```
Выходные данные
```
4
```

2023-12-21 06:17 UTC, closed without merging