Lab_2
Dovgalyuk/Algorithms pull request #730
Opened 2023-12-07 23:10 UTC by masha3430

2023-12-08 07:45 UTC, Dovgalyuk requested changes

2023-12-08 07:45 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +    Vector* vector;
В задании требуется использовать list.

2023-12-08 07:45 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +            }
Эти три действия можно объединить в два, если переделать условия.

2023-12-08 07:45 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +            if ((c == ')' && top == '(') || (c == ']' && top == '[') || (c == '}' && top == '{') || (c == top && (count % 2 != 0)) || (c == top && (count % 2 != 0))) {
Последние два условия непонятно зачем.

2023-12-09 03:35 UTC, masha3430 commented
Внесла изменения во 2 лабораторную

2023-12-11 05:31 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +            }
Это замечание осталось.

2023-12-11 11:55 UTC, masha3430 commented on Lab1C/lab2.cpp
> +            }
Условия изменила

2023-12-12 07:30 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +            if ((stack_empty(bracketsAndQuotes)) || ((stack_get(bracketsAndQuotes) != c) && (stack_empty(bracketsAndQuotes) == false))) {
Вторая проверка на пустоту лишняя.

2023-12-12 13:34 UTC, masha3430 commented
Убрала ненужную проверку

2023-12-13 08:29 UTC, Dovgalyuk commented
Принято


* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.

Имеется поток заявок для трех очередей. Заявки отсортированы по времени поступления в каждую очередь. Написать программу, печатающую порядок, в котором эти заявки будут обслужены. Время обслуживания всех заявок одинаковое. Формат входного файла: количество заявок в первой очереди, список моментов времени в которые они возникают; аналогично для второй и третей очередей. В выходной файл для каждой обслуженной заявки печатается номер очереди и время прихода заявки.

Входные данные
```
3
1
5
7
2
2
10
1
11
```
Выходные данные
```
1 1
2 2
1 5
1 7
2 10
3 11
```

2023-12-13 08:29 UTC, closed without merging

2023-12-18 21:07 UTC, masha3430 commented
Здравствуйте
Совсем не понимаю суть 3 лабораторной, можно ли получить какое-то дополнительное разъяснение, вообще объяснить как из входных данных, получаются выходные

2023-12-19 08:15 UTC, Dovgalyuk commented
Во входных данных описаны три потока заявок. Для каждого потока сначала указано число заявок, а потом время их поступления. 
1 очередь - 3 заявки 1, 5, 7
2 очередь - 2 заявки 2, 10
3 очередь - 1 заявка 11

Все заявки помещаются в разные очереди, а потом извлекаются, чтобы получить общий правильный порядок.