lab 1
Dovgalyuk/Algorithms pull request #736
Opened 2023-12-09 04:05 UTC by thatpel

Вышлите, пожалуйста, сразу 2 и 3 лабы, когда эту примете

2023-12-11 05:32 UTC, Dovgalyuk commented
Проект не собирается (см. отчёт CMake build)

2023-12-15 12:48 UTC, thatpel commented
Вроде бы исправил.

2023-12-18 06:28 UTC, Dovgalyuk requested changes

2023-12-18 06:28 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +        printf("%d", summ);
Сумму после цикла стоит выводить.

2023-12-18 06:28 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +            int summ = array_get(arr, i-4) + array_get(arr, i-3) + array_get(arr, i-2) + array_get(arr, i-1) + array_get(arr, i);
Стоит поддерживать переменную "сумма", которую на каждой итерации модифицировать, чтобы не складывать все элементы заново.

2023-12-19 16:56 UTC, thatpel commented
Исправил

2023-12-21 05:49 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
* Решить задачу, используя реализованный стек.

Дана строка вида s*w, где s и w состоят из букв и цифр. Проверить, является ли w записанной в обратном порядке s. Программа должна читать из файла по одному символу и использовать стек. Если w является строкой s, записанной задом наперед, то программа должна напечатать YES. В противном случае печатается NO.

Входные данные
```
abcd*dcba
```
Выходные данные
```
YES
```

Входные данные
```
acd3*3d
```
Выходные данные
```
NO
```

2023-12-21 05:49 UTC, closed without merging