secondlabmk
Dovgalyuk/Algorithms pull request #737
Opened 2023-12-09 13:37 UTC by ShinuiMK2092

Здравствуйте,присылаю вам 2ую лабораторку.Куприянов 2092
(Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
Решить задачу, используя реализованный стек.
Дано выражение в обратной польской записи. Используя стек, написать программу, которая проверяет выражение на наличие ошибок. Ошибкой считается деление на 0 (ZERO), выполнение операции, когда в стеке меньше двух элементов (UNDERFLOW), наличие больше одного элемента в стеке после завершения работы программы (OVERFLOW).

Входные данные

1 2 + 3
Выходные данные

OVERFLOW
Входные данные

10 9 - +
Выходные данные

UNDERFLOW )

2023-12-11 05:38 UTC, Dovgalyuk requested changes

2023-12-11 05:38 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +    vector<string> expression2 = { "10", "9", "-", "+" };
Выражение надо считывать с клавиатуры или из файла.

2023-12-11 17:03 UTC, ShinuiMK2092 commented
Здравствуйте,переделал

2023-12-11 17:06 UTC, ShinuiMK2092 commented
Здравствуйте ,переделал

2023-12-12 07:55 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +    if (!stack_empty(stack)) {
Если в конце осталось только одно число, то это корректное выражение.

2023-12-12 19:15 UTC, ShinuiMK2092 commented
Добавил доп условие

2023-12-13 08:46 UTC, closed without merging

2023-12-13 08:46 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.

Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной – «#» или пустым пространством – «.». Стартовая позиция обозначается как X, финишная как Y. Написать программу, находящую минимальный путь от стартовой до финишной клетки, если это возможно. За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди. Если решения нет, вывести IMPOSSIBLE.

Входные данные
```
######
#...X#
#.####
#...Y#
######
```
Выходные данные
```
######
#xxxX#
#x####
#xxxY#
######
```

Входные данные
```
######
#...X#
######
#...Y#
######
```
Выходные данные
```
IMPOSSIBLE
```