Lab2
Dovgalyuk/Algorithms pull request #739
Opened 2023-12-10 23:00 UTC by makargravanov

Здравствуйте, Павел Михайлович, я сделал вторую лабу

2023-12-10 23:02 UTC, makargravanov commented
Вот предыдущий пуллреквест, с заданием https://github.com/Dovgalyuk/Algorithms/pull/725#issuecomment-1842262230

2023-12-10 23:05 UTC, makargravanov commented
Решение задачи: https://github.com/Dovgalyuk/Algorithms/pull/739/commits/6a5a34ec02abe49178a3b5f5ce912336b2f8780f
list.h https://github.com/Dovgalyuk/Algorithms/pull/739/commits/8998b1379fb83b44cd825aa86009edb4ba739a17
list.cpp https://github.com/Dovgalyuk/Algorithms/pull/739/commits/beca07e0267ada7199f30d0d71b2c6c83cde94b0
stack.h https://github.com/Dovgalyuk/Algorithms/pull/739/commits/7d4856098f41e9411e57c318c35f44018949876b
stack.cpp https://github.com/Dovgalyuk/Algorithms/pull/739/commits/a755811aaf394b21ad1c3652a61c1eaeeea34a8e

2023-12-11 05:53 UTC, Dovgalyuk requested changes

2023-12-11 05:53 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +#include "stack.cpp"
cpp файл включать не надо

2023-12-11 05:53 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +            if (c == '"') {
Вот это непонятно почему.

2023-12-11 12:44 UTC, makargravanov commented on Lab1C/lab2.cpp
> +            if (c == '"') {
Если Вы о проверке на пустоту qStack, то тут всё просто. Давайте ещё раз посмотрим на полную функцию:
     
```
      for (char c : s) {
        if (!qStack.empty()) {
            if (c == '"') {
                qStack.pop();
            }
        }
        else {
            if (c == '"') {
                qStack.push(c);
            }
            else if (pairs.find(c) == pairs.end()) {
                stack.push(c);
            }
            else {
                if (stack.empty() || stack.get() != pairs[c])
                    return false;
                stack.pop();
            }
        }
    }
```
Допустим, мы итерируем по строке { "(" }. Тогда, когда мы входим в цикл, на первой итерации видим, что стек пустой, соответственно - !qStack.empty() не выполняется. Идём дальше. c!=' " ', а вот следующее условие подходит, соответственно, добавляем нашу скобку ' { ' в stack. 
На второй итерации цикла мы так же проскакиваем мимо первого условия !qStack.empty(), но нам подходит условие, что c == '"', пушим эти кавычки в qStack.
На третьей итерации выполняется условие !qStack.empty(), потому как мы туда добавили кавычки на второй итерации. Но символ сейчас у нас - это ( , т.е. вложенное условие c == '"' не выполняется, а раз так, то мы на новую итерацию идём, и сама скобка внутри кавычек, как бы, будто бы не рассматривается, потому как она никуда не записывается, и просто пропускается. Просто, я считаю, что это правильно, потому как содержимое кавычек - это всё-таки текст. 
На четвёртой итерации условие !qStack.empty() опять выполняется, а символом у нас снова является кавычка, но теперь уже закрывающая (хотя, де-факто, закрывающая и открывающая кавычки идентичны). Потому условие c == '"' выполняется, и вызывается qStack.pop(), который убирает из qStack нашу добавленную ранее кавычку, и, грубо говоря, тут программа считает, что мы вышли из кавычек. 
На пятой итерации !qStack.empty() не выполняется, c == '"' не выполняется, pairs.find(c) == pairs.end() не выполняется, потому как эта скобка - } не открывающая. Вот это условие - if (stack.empty() || stack.get() != pairs[c]) тоже не выполняется, а потому - вызывается stack.pop();
Таким образом - строка закончилась, стек stack пустой, соответственно - возвращаем true. Печатается в консоль в итоге YES.

Так что, обобщённо говоря, вся эта штука с отдельным qStack нужна для того, чтобы игнорировать форматирование скобок внутри кавычек. 

Причём, можете проверить, код корректно работает на данных вроде {"}" , потому как на таких данных он всё равно увидит не закрытую скобку, и выдаст NO.

2023-12-11 12:52 UTC, makargravanov commented
И да, я там немного сейчас отрефакторил, убрав некоторый избыточный код, в частности, в мапке кавычки были лишними, и возвращать true/false из функции можно напрямую, в виде return stack.empty();
Но это мелочи.
Если остались вопросы, с нетерпением жду!

2023-12-12 07:41 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +            if (c == '"') {
Если что-то есть внутри кавычек, то для этого порядок скобок тоже должен быть корректным.

2023-12-13 08:43 UTC, makargravanov commented
Здравствуйте, Павел Михайлович, доделал, как Вы просили.
Более того, сделал вложенность кавычек. Так как все кавычки одинаковы, оставляется, во-первых, возможность экранировать двойные кавычки символом \ . Во-вторых, добавил возможность осуществлять вложенность кавычек при помощи чередования ' и ", примерно так, как это сделано на питоне (давно не писал на нём, плохо помню, можно ли там чередовать до бесконечности, но там точно можно сделать запись вида ' "hello" ').

Причём, что самое главное, чередовать их у меня можно столько, сколько захочется. Это реализовано с помощью разбиения строки на слои и записи оных в отдельные стеки, которые автоматически генерируются, по необходимости, после чего записываются в std::pair, который находится в std::deque. В паре к стеку идёт интовая переменная, значение которой определяет: этот слой - слой скобок(0), кавычек(1), или же одинарных кавычек(2). 

Кстати говоря, **не стоит путать уровень слоя и его тип**. Уровней может быть сколь угодно много, в то время, как типов всего 3. Также, нулевой тип имеет только нулевой слой, и для него стек был создан вручную.

За счёт разбиения на слои и записи каждого слоя в отдельный стек, достигается изолированность слоёв друг от друга, т.е. содержимое одного слоя невидимо для содержимого другого, соответственно - корректность расстановки скобок и прочего для каждого слоя считается отдельно. 

Важный момент! Переменная типа **deque** у меня называется vect, потому как ранее я использовал вектор, но позднее от него отказался по ряду причин, связанных с его взаимодействием со стеком, о которых, если Вам будет интересно, более подробно могу рассказать на защите. Это было ближе к концу написания программы, потому я решил не тратить лишнее время на переписывание 30+ вхождений слова vect. Всё же, это не рабочий проект, потому не критично, как мне кажется.

К примеру, на вот такой ввод (первый скриншот) код выдаст yes 
![image](https://github.com/Dovgalyuk/Algorithms/assets/121590203/5f224b6d-373d-43e1-8c5d-64031922c977)
А на, например, вот такой (второй скриншот) выдаст NO 
![image](https://github.com/Dovgalyuk/Algorithms/assets/121590203/7e2673fd-dd1f-4b58-92c0-5eee3594118b)
Исключения, где не забыл, обработал, и, разумеется, проект собирается. Вот ещё некоторые скриншоты работы программы. Например, математическое выражение (третий скриншот)
![image](https://github.com/Dovgalyuk/Algorithms/assets/121590203/f916b8ff-154d-4324-9742-db90cf20980b)
Или, например, экранирование. Как Вы видите, экранированная кавычка не влияет на результат (скриншот 4)
![image](https://github.com/Dovgalyuk/Algorithms/assets/121590203/d68170d6-c69a-40a1-9159-0ad20e1b2dd5)
Единственное - не сделал экранирование для одинарных кавычек, но, думаю, это не критично.

2023-12-14 11:03 UTC, Dovgalyuk commented
Это всё слишком сложно. Тот же результат можно получить с помощью одного стека.

2023-12-17 11:41 UTC, makargravanov commented
Здравствуйте, Павел Михайлович, я сделал, как Вы просили, всё то же самое, но при помощи одного стека. Всё работает: 
![image](https://github.com/Dovgalyuk/Algorithms/assets/121590203/624a07d4-e4f7-4109-8370-783ef467226c)

2023-12-18 06:49 UTC, Dovgalyuk requested changes

2023-12-18 06:49 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +#include "stack.cpp"
Вот это осталось.

2023-12-18 06:49 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +                if (stack.empty() || stack.get() != '"') {
Строка может начинаться с кавычки.

2023-12-18 06:49 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +    bool inSQ = false;
Эти две переменные стоит убрать, потому что их логика дублирует логику стека.

2023-12-18 17:29 UTC, makargravanov commented on Lab1C/lab2.cpp
> +                if (stack.empty() || stack.get() != '"') {
Ой, stack.cpp да, убрал. 
Я знаю, что строка может начинаться с кавычки или с одинарной кавычки. Прошу заметить, что если бы Вы пролистали вниз, Вы бы увидели, что код обрабатывает все случаи. Вот, пожалуйста, работа кода: 
![image](https://github.com/Dovgalyuk/Algorithms/assets/121590203/dfb7f6a0-110e-4c47-962b-890076bf649a)
![image](https://github.com/Dovgalyuk/Algorithms/assets/121590203/68f55c80-1a3d-44cc-b431-abc1032ef6d8)
То же самое и для одинарных кавычек. 
Изучите, пожалуйста, ещё раз цикл, в котором обрабатывается строка: 
 

```
for (char c : s) {
        if (inQ) {
            if (c == '"') {
                if (stack.empty() || stack.get() != '"') {
                    return false;
                }
                stack.pop();
                inQ = false;
                if (level > 1) {
                    inSQ = true;
                }
                level--;
            }
            else if (c == '\'') {
                stack.push(c);
                inQ = false;
                inSQ = true;
                level++;
            }
            else if (pairs.find(c) == pairs.end()) {
                stack.push(c);
            }
            else {
                if (stack.empty() || stack.get() != pairs[c]) {
                    return false;
                }
                stack.pop();
            }
        }
        else if (inSQ) {
            if (c == '\'') {
                if (stack.empty() || stack.get() != '\'') {
                    return false;
                }
                stack.pop();
                inSQ = false;
                if (level > 1) {
                    inQ = true;
                }
                level--;
            }
            else if (c == '"') {
                stack.push(c);
                inQ = true;
                inSQ = false;
                level++;
            }
            else if (pairs.find(c) == pairs.end()) {
                stack.push(c);
            }
            else {
                if (stack.empty() || stack.get() != pairs[c]) {
                    return false;
                }
                stack.pop();
            }
        }
        else {
            if (c == '"' || c == '\'') {
                stack.push(c);
                inQ = (c == '"');
                inSQ = (c == '\'');
                level++;
            }
            else if (pairs.find(c) == pairs.end()) {
                stack.push(c);
            }
            else {
                if (stack.empty() || stack.get() != pairs[c]) {
                    return false;
                }
                stack.pop();
            }
        }
    }
```
Пусть у нас строка 
`"{}"`
Тогда, на первой итерации мы попадаем в условие:
```
 else {
            if (c == '"' || c == '\'') {
                stack.push(c);
                inQ = (c == '"');
                inSQ = (c == '\'');
                level++;
            }
            else if (pairs.find(c) == pairs.end()) {
                stack.push(c);
            }
            else {
                if (stack.empty() || stack.get() != pairs[c]) {
                    return false;
                }
                stack.pop();
            }
        }
```
а конкретно - в  эту его часть, потому как символ у нас равен " :  
```
if (c == '"' || c == '\'') {
                stack.push(c);
                inQ = (c == '"');
                inSQ = (c == '\'');
                level++;
            }
```
Далее- поднимается на единицу параметр level, за счёт которого мы понимаем, что перешли на уровень выше.
 inQ становится равно true , что говорит о том, что мы обрабатываем строку по соответствующему варианту. Далее в блоке, выполняемом, если inQ==true, мы стандартно проверяем скобки, таким образом, что, находя открывающую скобку, мы её записываем, а находя закрывающую - удаляем последний добавленный элемент стека. Таким образом, в случае нашей строки "{}" , мы, пройдя скобки, доходим до закрывающей кавычки, выполняется условие :
```
if (c == '"') {
                if (stack.empty() || stack.get() != '"') {
                    return false;
                }
                stack.pop();
                inQ = false;
                if (level > 1) {
                    inSQ = true;
                }
                level--;
            }
```
В нашем случае, вызывается stack.pop(), и для стека, имеющего к этому моменту вид stack= ", удаляется элемент ", таким образом, стек становится пустым.
Так как level у нас равен единице, условие 
```
if (level > 1) {
                    inSQ = true;
                }
```
НЕ выполняется.
Далее level понижается обратно на 0, и происходит выход из цикла. Так как стек пуст, возвращается true, в консоль печатается YES.

Сейчас я ещё раз объясню, зачем нужны переменные level, inQ и inSQ.
Вот пусть мы хотим сделать вложенные кавычки. {"{"{"[]"}"}"} - не получится, так как, как я и говорил - все кавычки одинаковы.
Если мы хотим сделать вложенность, можно делать это чередованием ' и " , как я и говорил ранее. То есть - 
{"{'{"[]"}'}"} .
Без inSQ и inQ мы не сможем адекватно понимать, какой собственно вариант обработки нам выбрать. А без параметра level мы не будем понимать, на каком уровне вложенности мы находимся.
И вот, давайте вернёмся к строке-примеру, обработку которой я разложил выше. Модифицируем её. Пусть она равна не `"{}"`, а `'"{}"'` . В таком случае, мы проходим, по началу, по тому же условию : 
```
 else {
            if (c == '"' || c == '\'') {
                stack.push(c);
                inQ = (c == '"');
                inSQ = (c == '\'');
                level++;
            }
            else if (pairs.find(c) == pairs.end()) {
                stack.push(c);
            }
            else {
                if (stack.empty() || stack.get() != pairs[c]) {
                    return false;
                }
                stack.pop();
            }
        }
```
а конкретно - по этой его части, потому как символ у нас равен ' :  
```
if (c == '"' || c == '\'') {
                stack.push(c);
                inQ = (c == '"');
                inSQ = (c == '\'');
                level++;
            }
```
Подходит оно нам по c == '\''. Точно так же пушим его в стек, но теперь inQ = false, а inSQ = true. level плюсуется на 1, т.е. был нулём, стал единицей. 
Далее мы заходим в блок inSQ. Так как скобок тут нет, заходим сразу в условие 
```
else if (c == '"') {
                stack.push(c);
                inQ = true;
                inSQ = false;
                level++;
            }
```
Пушим в стек ", весь стек сейчас выглядит, как stack= '," .
inQ=true, inQS=false, level++, соответственно - мы, как и в тот раз, пойдём в блок для двойных кавычек, где inQ==true. level увеличился на единицу, т.е. был 1, стал 2.
Там мы точно так же работаем со скобками, т.е. вот так будет меняться стек на следующие 2 итерации: 
stack= ',",{ - это при нахождении открывающейся скобки
stack= '," - это при нахождении закрывающейся.
Далее мы переходим на закрывающуюся двойную кавычку. т.е. входим в блок 
```
if (c == '"') {
                if (stack.empty() || stack.get() != '"') {
                    return false;
                }
                stack.pop();
                inQ = false;
                if (level > 1) {
                    inSQ = true;
                }
                level--;
            }
```
Удаляем последний элемент из стека - " , inQ становится false, а так как level=2>1, то это значит, что это - уже не первые кавычки, и, значит, что, вернувшись на уровень ниже, нам надо будет дообработать те кавычки, в которых были эти кавычки. 
Грубо говоря, в нашем случае, это значит, что кавычки " " закончились, и нам надо посмотреть, закрываются ли кавычки  ' ', в которых и были наши кавычки " ", так как сама строка, напоминаю, выглядела, как '"{}"' . 
Если не будет этого блока:
```
if (level > 1) {
                    inSQ = true;
                }
```
то строка обработается некорректно. 
Так как переменная level=2, то мы делаем inSQ=true. [...]

2023-12-18 18:10 UTC, makargravanov commented
Здравствуйте, Павел Михайлович, я убрал #include "stack.cpp", а насчёт остального - ответил в комментариях к Вашим комментариям

2023-12-19 08:10 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +    bool inSQ = false;
Со стеком это можно сделать так:
- если кавычка, то
- - если в стеке нет кавычки, то добавить её туда
- - если есть кавычка, то удалить
- примерно то же самое со скобками, но попроще, потому что скобки отличаются
-

2023-12-19 23:30 UTC, makargravanov commented
Доброго времени суток, Павел Михайлович, теперь, вроде бы, всё. Действительно, можно было сделать проще, и без переменной level ! Спасибо большое! 
Вот результат работы программы:
![image](https://github.com/Dovgalyuk/Algorithms/assets/121590203/e4c92169-4652-408c-ab7a-af999b8ee3dd)
Код алгоритма, если нужно будет объяснять сам алгоритм задания, а не только код самой структуры данных, смогу объяснить на защите, здесь же расписывать его не вижу смысла, потому как он и так весьма очевиден.
Если всё хорошо, буду ждать задание по третьей лабе, и, скорее всего, во вторник приду защищаться по сданному к тому моменту. Я надеюсь, в крайнем случае, можно будет досдать одну-две лабы после нг, до экзамена?

2023-12-21 06:13 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +            if (stack.get() == c) {
Нужна проверка на пустоту стека.

2023-12-21 06:14 UTC, Dovgalyuk commented
> Я надеюсь, в крайнем случае, можно будет досдать одну-две лабы после нг, до экзамена?

До экзамена кое-что ещё можно будет сдавать, но новые задания можно получать только до НГ.

2023-12-21 14:25 UTC, makargravanov commented
Поправил, Павел Михайлович. Конечно, если это то, что Вы имели в виду.

2023-12-22 06:18 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.

Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной - «#» или пустым пространством – «.».
Стартовая позиция обозначается как X, финишные позиции цифрами от 0 до 9.
Написать программу, которая выводит цифру, ближайшую к стартовой позиции.
За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди.

Входные данные
```
######
#...X#
#.#.##
#3.4.#
######
```
Выходные данные
```
4
```

2023-12-22 06:18 UTC, closed without merging