loading lab3
Dovgalyuk/Algorithms pull request #741
Opened 2023-12-11 21:12 UTC by alexeypusep

2023-12-14 17:24 UTC, alexeypusep commented
Исправил Ваши замечания

2023-12-18 06:16 UTC, Dovgalyuk requested changes

2023-12-18 06:16 UTC, Dovgalyuk commented on Lab1CPP/lab3.cpp
> +        if (distance_found)
Это лучше сразу в условие while внести.

2023-12-18 06:16 UTC, Dovgalyuk commented on Lab1CPP/lab3.cpp
> +                if (!visited_nodess[i])
Два условия можно объединить с помощью &&, чтобы вложенность блоков была меньше.

2023-12-19 07:49 UTC, Dovgalyuk commented
Принято.

* Разработать программный интерфейс модуля (заголовки функций) библиотеки LibraryCPPTemplate для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
* Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
* Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде матрицы смежности в контейнере Vector библиотеки LibraryCPPTemplate.
* Разработать и добавить в проект LibraryCPPTemplate программу, тестирующую работу библиотеки для графа.
* Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать в нем все кратчайшие пути между заданной парой вершин с помощью обхода в ширину.

2023-12-19 07:49 UTC, closed without merging