Lab1_Rakov
Dovgalyuk/Algorithms pull request #742
Opened 2023-12-12 01:19 UTC by Searon1

2023-12-12 08:08 UTC, Dovgalyuk requested changes

2023-12-12 08:08 UTC, Dovgalyuk commented on .vscode/settings.json
Этот файл не нужен в репозитории.

2023-12-12 08:08 UTC, Dovgalyuk commented on Lab1CPP/lab1.cpp
> +    sum += arr->get(4);
Лучше такое делать циклом, чтобы опечаток при копировании избегать.
Ну и именованная константа для 5 не помешает.

2023-12-17 21:14 UTC, Searon1 commented
Ожидаю вашего ответа

2023-12-18 07:02 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library двусвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.

Реализовать интерпретатор подмножества языка Befunge: https://en.wikipedia.org/wiki/Befunge
Программа читает входную строку из следующих команд:
* 0-9 - заносит число в стек
* +-*/% - арифметические операции. Извлекают два числа из стека, а потом заносят туда результат
* ! - логическое "не". Извлекает значение с вершины стека и заносит туда 1, если это был 0. Иначе заносит в стек 0.
* ` - логическое "больше". Извлекает два значения из стека и заносит обратно 1, если первое больше второго и 0 в противном случае.
* : - дублирует значение на вершине стека.
* . - извлекает значение из стека и выводит его.
* & - запрашивает число с клавиатуры и заносит его в стек.

Входные данные
```
123...
```
Выходные данные
```
3
2
1
```

Входные данные
```
1:.2:.3:.++.
```
Выходные данные
```
1
2
3
6
```

2023-12-18 07:02 UTC, closed without merging