Egorov Vitaliy 2092 Lab-2
Dovgalyuk/Algorithms pull request #744
Opened 2023-12-12 18:13 UTC by debcomedian

2023-12-13 08:43 UTC, Dovgalyuk requested changes

2023-12-13 08:43 UTC, Dovgalyuk commented on Lab1CPP/lab2.cpp
> +            char ch = str[i];
Можно эту строчку поставить перед if, а затем никогда не писать str[i]

2023-12-13 08:43 UTC, Dovgalyuk commented on Lab1CPP/lab2.cpp
> +    return 0;
Вот на такой пример должно выводиться NO:
))

2023-12-13 10:16 UTC, debcomedian commented
Исправил условие и вынес char на уровень выше

2023-12-16 19:44 UTC, debcomedian commented
Теперь проверка происходит в функции получения данных из стека

2023-12-18 06:33 UTC, Dovgalyuk commented on Lab1CPP/lab2.cpp
> +            if ( (stack_get(stack) == ch && ch != '(' && ch != ')')
А где проверка на пустоту?

2023-12-18 08:05 UTC, debcomedian commented on Lab1CPP/lab2.cpp
> +            if ( (stack_get(stack) == ch && ch != '(' && ch != ')')
Проверка на пустоту происходила прямо в самой функции "stack_get", но это не совсем верно, поэтому я переделал условие и убрал эту проверку из функции.
Теперь проверка происходит перед извлечением значения из стека в самом условии.

2023-12-19 07:44 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и очередь на основе этого списка (модуль queue).
* Решить задачу, используя реализованную очередь.

Задан неориентированный граф. Написать программу для определения кратчайшего пути от одной вершины для другой. В первой строке входного файла записано количество вершин, номер стартовой вершины и номер финишной. В последующих строках идут описания ребер, заданные номерами вершин, которые они соединяют. В выходной файл выводится последовательность вершин в кратчайшем пути. Если решения не существует – выводится IMPOSSIBLE. Программа должна использовать поиск в ширину на основе очереди.

Входные данные
```
4 1 2
1 3
1 4
3 2
4 3
```
Выходные данные
```
1 3 2
```

2023-12-19 07:44 UTC, closed without merging