Pr/568
Dovgalyuk/Algorithms pull request #746
Opened 2023-12-12 21:57 UTC by Ivan20030

Сделал 2 лабораторную

2023-12-13 08:54 UTC, Dovgalyuk requested changes

2023-12-13 08:54 UTC, Dovgalyuk commented on CMakeSettings.json
Этот файл нужно удалить.

2023-12-13 08:54 UTC, Dovgalyuk commented on Labs/lab2.cpp
> +		 return 0;
Тут стек не удаляется. Можно создавать его позднее.

2023-12-13 11:07 UTC, Ivan20030 commented
Исправил замечания

2023-12-14 11:28 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.

Задано начальное вещество и список химических реакций, в которых оно превращается в другое вещество.  Написать программу, использующую поиск в ширину, и выводящую список веществ, которые можно получить из исходного.

Входные данные
```
A
A->B
B->C
D->E
```
Выходные данные
```
B
C
```

В примере из вещества A можно получить вещества B и C.

2023-12-14 11:28 UTC, closed without merging