lab6
Dovgalyuk/Algorithms pull request #747
Opened 2023-12-13 18:47 UTC by heheheee21

2023-12-14 11:36 UTC, Dovgalyuk requested changes

2023-12-14 11:36 UTC, Dovgalyuk commented on LibraryCPPTemplate/str.h
> +                delete[] prefix;
Чтобы по два раза не писать delete[], можно использовать array или vector.

2023-12-14 11:36 UTC, Dovgalyuk commented on LibraryCPPTemplate/str.h
> +    const int multiplyCapacity = 2;
А это для чего?

2023-12-18 05:51 UTC, Dovgalyuk commented on LibraryCPPTemplate/str.h
> +    size_t capacity = 0;
А это для чего?

2023-12-18 06:05 UTC, heheheee21 commented on LibraryCPPTemplate/str.h
> +    size_t capacity = 0;
`char* string` - указатель на массив символов
`size_t capacity` - размер в символах выделенной памяти для строки
Используются в конструкторе/деструкторе, операторе присваивания, в `resize`, `append`, `copyChars`.

2023-12-19 08:30 UTC, heheheee21 commented
Я вам защитил сегодня 6 лабу, но пул реквест до сих пор открыт, мне что-то еще надо?

2023-12-21 05:27 UTC, Dovgalyuk commented
Ничего, забыл закрыть.

2023-12-21 05:27 UTC, closed without merging