Лаб 1 Джалолов
Dovgalyuk/Algorithms pull request #755
Opened 2023-12-18 11:21 UTC by BillyHendrix

2023-12-19 07:59 UTC, Dovgalyuk commented
Нужно устранить конфликты, чтобы проект мог собираться на сервере.

2023-12-19 22:41 UTC, BillyHendrix commented
Вот всё работает

2023-12-21 06:11 UTC, Dovgalyuk requested changes

2023-12-21 06:11 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +#include "array.cpp"
cpp файл подключать нельзя.

2023-12-21 06:11 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +            array_set(arr, i, array_get(arr, i) - array_get(arr, k1));
Нужно заранее извлечь элементы k1 и k2, так как во время цикла они поменяются.

2023-12-21 06:11 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +    return 0;
Вторая часть задания не выполнена.

2023-12-25 07:08 UTC, BillyHendrix commented
Я сделал как вы сказали

2023-12-26 05:38 UTC, Dovgalyuk requested changes

2023-12-26 05:38 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +            array_set(arr, i, array_get(arr, i) - array_get(arr, k1));
Не исправлено.

2023-12-26 05:38 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +        current_sum = array_get(arr, i) + array_get(arr, i + 1) + array_get(arr, i + 2) + array_get(arr, i + 3) + array_get(arr, i + 4);
Нужно сначала посчитать сумму первых пяти элементов, а затем обновлять её на каждой итерации, а не пересчитывать заново.

2023-12-26 06:01 UTC, BillyHendrix commented on Lab1C/lab1.cpp
> +        current_sum = array_get(arr, i) + array_get(arr, i + 1) + array_get(arr, i + 2) + array_get(arr, i + 3) + array_get(arr, i + 4);
Сейчас сделаю

2023-12-27 08:14 UTC, Dovgalyuk commented
Закрываю, времени на выполнение лабораторных уже не остаётся.

2023-12-27 08:14 UTC, closed without merging

2023-12-27 08:47 UTC, BillyHendrix commented
Но вы хоть приняли мою 1 лабу?

2023-12-27 08:52 UTC, BillyHendrix commented
Отправьте 2 лабу, хоть мне 2 лабы сделать. Вы сказали есть время до Нового Года!

2023-12-29 10:13 UTC, Dovgalyuk commented
> Но вы хоть приняли мою 1 лабу?

Нет, потому что ещё оставались недочёты.