Ivanov 2092 lab1
Dovgalyuk/Algorithms pull request #757
Opened 2023-12-18 21:47 UTC by turn53

2023-12-19 08:20 UTC, Dovgalyuk requested changes

2023-12-19 08:20 UTC, Dovgalyuk commented on Lab1C/Source.cpp
> +#endif // ARRAY_H
Всё вот это не нужно включать в cpp.

2023-12-19 08:20 UTC, Dovgalyuk commented on Lab1C/Source.cpp
> +}
И это тоже должно браться из библиотеки.

2023-12-19 08:20 UTC, Dovgalyuk commented on Lab1C/Source.cpp
> +        int sum = arr.data[i] + arr.data[i + 1] + arr.data[i + 2] + arr.data[i + 3] + arr.data[i + 4];
Сумму можно обновлять на каждой итерации, добавляя один новый элемент и удаляя один старый.

2023-12-21 06:23 UTC, Dovgalyuk commented
Проект не собирается на сервере.

2023-12-21 09:26 UTC, turn53 commented
Переделал, сейчас должен работать

2023-12-22 06:03 UTC, Dovgalyuk commented on Lab1C/Source.cpp
> +}
Тестовый пример:
1 2 3 4 5 6 7 8 9 10

2023-12-22 12:33 UTC, turn53 commented
Перепроверил, внёс правки в функцию, которая считает сумму. До этого были ошибки. Сейчас работает корректно.
Массив заполняется случайными числами (по заданию).

2023-12-25 06:50 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
* Решить задачу, используя реализованный стек.

Написать программу, моделирующую работу стека ограниченного объема. В качестве входных данных программа получает максимально возможный размер стека и последовательность команд: push N – занести число N в стек, pop – достать число из стека и напечатать его. Если стек переполняется или производится попытка извлечь значение из пустого стека, программа должна печатать одно из сообщений: BAD PUSH или BAD POP. После окончания работы программы, она должна напечатать текущее состояние стека.

Входные данные
```
2
push 3
push 2
push 4
pop
push 1
```
Выходные данные
```
BAD PUSH
2
STACK
3
1
```

2023-12-25 06:50 UTC, closed without merging