Vlasov_lab3
Dovgalyuk/Algorithms pull request #761
Opened 2023-12-19 21:11 UTC by RetroBoyy

2023-12-19 21:12 UTC, RetroBoyy commented
3 лабораторная

2023-12-21 06:06 UTC, Dovgalyuk requested changes

2023-12-21 06:06 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +    Graph(int vertices);
Деструктора не хватает.

2023-12-21 15:21 UTC, RetroBoyy commented
Добавил

2023-12-22 06:23 UTC, Dovgalyuk commented
Принято.

2023-12-22 06:23 UTC, closed without merging