2 лаба
Dovgalyuk/Algorithms pull request #762
Opened 2023-12-20 06:15 UTC by Artickgg

2023-12-20 06:23 UTC, Artickgg commented
я хотел бы спросить, почему в проверке выдает ошибку с case drop, swap и т.д.

2023-12-21 06:19 UTC, Dovgalyuk commented
case можно использовать только с целыми числами. Для строк вместо switch придётся использовать цепочку операторов if.

2023-12-25 05:19 UTC, Artickgg commented
Исправил case на цепочку if, также у меня возникала ошибка с multi-character constant, поэтому в проверке я побуквенно текст написал. Я хотел бы спросить, будете ли вы принимать защиту в эту среду? Если нет, то не будет ли возможности защититься после нового года, при условии, что я за эту неделю сдам 3 и возможно 4 лабы

2023-12-25 08:50 UTC, Dovgalyuk commented
> Исправил case на цепочку if, также у меня возникала ошибка с multi-character constant, поэтому в проверке я побуквенно текст написал. Я хотел бы спросить, будете ли вы принимать защиту в эту среду? Если нет, то не будет ли возможности защититься после нового года, при условии, что я за эту неделю сдам 3 и возможно 4 лабы

Можно будет защитить в среду или на консультации.

2023-12-25 08:52 UTC, Dovgalyuk requested changes

2023-12-25 08:52 UTC, Dovgalyuk commented on Lab1C/lab2.cpp
> +        } else if (command == 'd' && cin >> command && command == 'u' && cin >> command && command == 'p') {
Лучше считывать строку, а потом её проверять, потому что так очень непонятный код получается.

2023-12-25 08:52 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    ListItem* tail;
tail нигде не используется.

2023-12-25 10:27 UTC, Artickgg commented on Lab1C/lab2.cpp
> +        } else if (command == 'd' && cin >> command && command == 'u' && cin >> command && command == 'p') {
При считывании строки у меня вылезает ошибка multi-character constant, из-за нее код некорректно работает (он запускается, но не все команды выполняются). Поэтому я решил по букве считывать, а т.к. существует шанс того, что он считает какую-нибудь букву, но выполнит другую команду, я решил просто перезапускать cin

2023-12-25 10:27 UTC, Artickgg commented on LibraryCPP/list.cpp
> +    ListItem* tail;
Просто в самом задании написано сделать библиотеку list, поэтому я и брал как это всегда делается. Однако в основном задании просто так получилось, что все команды не требуют чего-то, кроме вершины.

2023-12-25 10:29 UTC, Artickgg commented
Когда будет консультация? Мне кажется, что отсутствие tail в библиотеке только сделает код более непонятным. А как от ошибки с if избавиться я не знаю, ибо case не работает

2023-12-26 02:17 UTC, Artickgg commented
Решил в итоге просто через getline сделать считывание, также удалил из библиотеки все что связано с tail. Могу я тогда защититься во время консультации?

2023-12-26 09:05 UTC, closed without merging

2023-12-26 09:05 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.

Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной – «#» или пустым пространством – «.». Стартовая позиция обозначается как X, финишная как Y. Написать программу, находящую минимальный путь от стартовой до финишной клетки, если это возможно. За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди. Если решения нет, вывести IMPOSSIBLE.

Входные данные
```
######
#...X#
#.####
#...Y#
######
```
Выходные данные
```
######
#xxxX#
#x####
#xxxY#
######
```

Входные данные
```
######
#...X#
######
#...Y#
######
```
Выходные данные
```
IMPOSSIBLE
```