Egorov_Vitaliy_2092_Lab_3
Dovgalyuk/Algorithms pull request #763
Opened 2023-12-20 20:11 UTC by debcomedian

2023-12-20 20:14 UTC, debcomedian commented on LibraryCPP/queue.cpp
> +};
Павел Михайлович, в процессе реализации возникла проблема, хочу спросить совет по данной ситуации

2023-12-21 06:22 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +};
В очереди можно хранить дополнительный указатель последний элемент списка. Тогда со вставкой проблем не будет.
А удалять из начала списка, для этого нужные функции есть и так.

2023-12-21 18:30 UTC, debcomedian commented on LibraryCPP/queue.cpp
> +};
Исправил

2023-12-22 06:34 UTC, Dovgalyuk requested changes

2023-12-22 06:34 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    ListItem* tail;
tail можно удалить, он же нигде не используется.

2023-12-22 06:34 UTC, Dovgalyuk commented on Lab1CPP/lab3.cpp
> +}
И программу надо не забыть выложить.

2023-12-25 08:46 UTC, Dovgalyuk requested changes

2023-12-25 08:46 UTC, Dovgalyuk commented on Lab1CPP/lab3.cpp
> +                list_insert(list, num);
Стоит для хранения графа придумать что-то получше, чем единый список.
Например, можно сделать массив из списков, чтобы для каждой вершины можно было за O(1) получить список соседей.

2023-12-26 08:21 UTC, Dovgalyuk requested changes

2023-12-26 08:21 UTC, Dovgalyuk commented on Lab1CPP/lab3.cpp
> +    List* road = list_create();
Тут нужен не список, а массив ссылок на предков, потому что граф может быть разветвлённым.

2023-12-26 08:21 UTC, Dovgalyuk commented on Lab1CPP/lab3.cpp
> +bool check_value(Data n, Data child_element, List* list, List* parents)
Вместо этой сложной логики достаточно одного массива с флагами посещённости.

2023-12-26 15:55 UTC, debcomedian commented
Переделал под массивы

2023-12-27 08:25 UTC, Dovgalyuk commented on Lab1CPP/lab3.cpp
> +    List* road = list_create();
А зачем оно осталось?

2023-12-27 08:37 UTC, debcomedian commented on Lab1CPP/lab3.cpp
> +    List* road = list_create();
Не совсем понял вопроса, но массив parents содержит значение позиции предка, что позволяет найти кратчайший путь и записать его в список "road" (логика поиска в строках 139-151).

2023-12-29 10:34 UTC, Dovgalyuk requested changes

2023-12-29 10:34 UTC, Dovgalyuk commented on Lab1CPP/lab3.cpp
> +    if (flag) {
А это всё зачем?

2023-12-29 10:34 UTC, Dovgalyuk commented on Lab1CPP/lab3.cpp
> +    List* road = list_create();
road зачем?

2023-12-29 10:48 UTC, debcomedian commented on Lab1CPP/lab3.cpp
> +    if (flag) {
Флаг используется для того, чтобы не было кучи мест выхода из функции.

2023-12-29 11:38 UTC, debcomedian commented
Убрал флаг
Исправил зависание при тестовом наборе
4 1 2
1 1
1 4
3 2
4 3

2024-01-11 05:23 UTC, Dovgalyuk commented
Принято, но есть ещё мелкие недочёты.

2024-01-11 05:23 UTC, closed without merging