3lab
Dovgalyuk/Algorithms pull request #764
Opened 2023-12-21 08:24 UTC by ShinuiMK2092

Здравствуйте ,присылаю вам 3ью лабораторку.Куприянов 2092

(Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
Решить задачу, используя реализованную очередь.
Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной – «#» или пустым пространством – «.». Стартовая позиция обозначается как X, финишная как Y. Написать программу, находящую минимальный путь от стартовой до финишной клетки, если это возможно. За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди. Если решения нет, вывести IMPOSSIBLE.

Входные данные

#...X#
#.####
#...Y#

Выходные данные

#xxxX#
#x####
#xxxY#

Входные данные

#...X#

#...Y#

Выходные данные

IMPOSSIBLE
)

2023-12-22 06:02 UTC, Dovgalyuk requested changes

2023-12-22 06:02 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +    }
За счёт этого удаление работает за O(N). Нужно использовать кольцевой буфер, чтобы получилось O(1).

2023-12-22 06:02 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +    queue<Point> q;
Нужно использовать собственную очередь, а не стандартную.

2023-12-22 06:02 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +    return 0;
Нужно протестировать программу с разветвлённым лабиринтом.

2023-12-22 20:22 UTC, ShinuiMK2092 commented
Добрый вечер ,знал что ошибки ,но не мог понять почему.Сейчас понял и всё переделал

2023-12-25 08:33 UTC, Dovgalyuk requested changes

2023-12-25 08:33 UTC, Dovgalyuk commented on .vscode/launch.json
Этот файл надо удалить из репозитория.

2023-12-25 08:33 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +    }
Осталось.

2023-12-25 08:33 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +#include "queue.cpp"
cpp файлы включать сюда не нужно.

2023-12-25 08:33 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +    }
Всё пропало.

2023-12-26 17:32 UTC, ShinuiMK2092 commented
Здравствуйте,поправил

2023-12-27 08:36 UTC, Dovgalyuk requested changes

2023-12-27 08:36 UTC, Dovgalyuk commented on .vscode/launch.json
Лишний файл в репозитории.

2023-12-27 08:36 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +    }
Всё ещё ничего.

2023-12-29 10:41 UTC, Dovgalyuk requested changes

2023-12-29 10:41 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +        vector_resize(queue->vector, vector_size(queue->vector) - 1);
Тут мы удаляем не голову очереди, а хвост.

2023-12-29 10:41 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +    return 0;
Поиска пути нет.

2024-01-11 05:25 UTC, closed without merging