lab_3
Dovgalyuk/Algorithms pull request #765
Opened 2023-12-21 20:32 UTC by masha3430

2023-12-21 21:18 UTC, masha3430 commented
Здравствуйте
А что значит, когда не проходит cpp-linter ?

2023-12-22 06:36 UTC, Dovgalyuk commented
> Здравствуйте А что значит, когда не проходит cpp-linter ?

Ничего, он сломан.

2023-12-22 06:39 UTC, Dovgalyuk requested changes

2023-12-22 06:39 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +        queues.push_back(queueRequests);
Не нужно промежуточных векторов, лучше сразу считывать в очередь.

2023-12-22 21:13 UTC, masha3430 commented on Lab1C/lab3.cpp
> +        queues.push_back(queueRequests);
внесла изменения в лаб 3

2023-12-25 08:36 UTC, Dovgalyuk requested changes

2023-12-25 08:36 UTC, Dovgalyuk commented on Lab1C/lab3.cpp
> +        currentTime++;
В этой переменной нет смысла.

2023-12-25 19:49 UTC, masha3430 commented on Lab1C/lab3.cpp
> +        currentTime++;
убрала

2023-12-26 08:33 UTC, Dovgalyuk commented
Принято.

2023-12-26 08:33 UTC, closed without merging