Lab3
Dovgalyuk/Algorithms pull request #777
Opened 2023-12-25 13:00 UTC by Ivan20030

2023-12-26 08:08 UTC, Dovgalyuk requested changes

2023-12-26 08:08 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +        }
Тут копируется только часть данных.

2023-12-26 08:08 UTC, Dovgalyuk commented on Labs/Lab3.cpp
> +	vector<bool> used(500);
500 букв вряд ли наберётся.

2023-12-26 09:59 UTC, Ivan20030 commented
Исправил ошибки

2023-12-27 12:19 UTC, Ivan20030 commented
Здравствуйте, все исправил, все замечания

2023-12-28 21:50 UTC, Ivan20030 commented
Можете пожалуйста проверить третью работу

2023-12-29 10:54 UTC, Dovgalyuk requested changes

2023-12-29 10:54 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +    queue->first++;
Не хватает перехода через конец массива.

2023-12-29 10:54 UTC, Dovgalyuk commented on Labs/Lab3.cpp
> +			graph[indexV][0] = indexV;
Эта ячейка не нужна, потому что мы и так всегда знаем, к какой строке обращаемся.

2023-12-30 12:58 UTC, Ivan20030 commented
Здравствуйте, исправил замечания

2024-01-04 22:17 UTC, Ivan20030 commented
Здравствуйте, посмотрите мои коммиты

2024-01-09 22:17 UTC, Ivan20030 commented
Посмотрите пожалуйста

2024-01-11 05:46 UTC, Dovgalyuk commented
Принято, но есть недочёты.

2024-01-11 05:46 UTC, closed without merging