Lab3, Матвеев Кирилл, гр. 2093
Dovgalyuk/Algorithms pull request #779
Opened 2023-12-25 21:14 UTC by playnikov

2023-12-26 08:40 UTC, Dovgalyuk requested changes

2023-12-26 08:40 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +ListItem* list_erase_tail(List* list)
Лучше удалить эту функцию, потому что удаление будет работать за O(N).
Для очереди стоит добавлять элементы в конец, а удалять из начала списка.

2023-12-26 17:23 UTC, playnikov commented
Да, действительно. Убрал функцию, изменил очередь

2023-12-27 08:34 UTC, Dovgalyuk commented
Принято.

* Разработать программный интерфейс модуля (заголовки функций) библиотеки LibraryCPPTemplate для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины.
* Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
* Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List библиотеки LibraryCPPTemplate.
* Разработать и добавить в проект LibraryCPPTemplate программу, тестирующую работу библиотеки для графа.
* Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать для него минимальное покрывающее дерево алгоритмом Прима.

2023-12-27 08:34 UTC, closed without merging