lab4
Dovgalyuk/Algorithms pull request #780
Opened 2023-12-25 23:25 UTC by Ynic2

2023-12-25 23:52 UTC, Ynic2 commented
Нужные тесты проходит list и graph

2023-12-26 08:54 UTC, Dovgalyuk requested changes

2023-12-26 08:54 UTC, Dovgalyuk commented on LibraryCPPTemplate/list.h
> +    Item* operator[](size_t index) const
У списка не должно быть этого оператора.
Если он понадобился, значит надо поменять алгоритм.

2023-12-26 08:54 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +template <typename Data> class Graph {
Метки рёбер и вершин могут быть разных типов.

2023-12-26 08:54 UTC, Dovgalyuk commented on LibraryCPPTemplate/graph.h
> +	List<Edge> matrix;
Список смежности удобнее хранить отдельный для каждой вершины.

2023-12-26 08:54 UTC, Dovgalyuk commented on Labs/lab4.cpp
> +			adjacencyMatrix[i][iterator.getEnd()] = graph.getEdge(iterator.getStart(), iterator.getEnd()).getWeight();
Указатель на ребро логичнее было бы получать прямо из итератора.

2024-01-11 05:46 UTC, closed without merging