Lab2_Shumilov
Dovgalyuk/Algorithms pull request #786
Opened 2023-12-26 16:14 UTC by ShumilovIgor

Отправил 2ю лабораторную заново, без лишних файлов. Шумилов Игорь 2091

2023-12-27 08:31 UTC, Dovgalyuk requested changes

2023-12-27 08:31 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    ListItem* tail = nullptr;
tail как-то используется?

2023-12-27 08:31 UTC, Dovgalyuk commented on LabCPP/Lab2.cpp
> +                return 1;
Здесь стек не удаляется.

2023-12-28 14:45 UTC, ShumilovIgor commented
Здравствуйте, я сделал удаление стека, отвечая на ваш вопрос про tail, он нужен в двусвязном списке, в моем случае я сделал лишнюю работу и сейчас я доработал под мое задание односвязного списка, удалив tail, так как он не используется

2023-12-29 10:22 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.

Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной – «#» или пустым пространством – «.». Стартовая позиция обозначается как X, финишная как Y. Написать программу, находящую минимальный путь от стартовой до финишной клетки, если это возможно. За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди. Если решения нет, вывести IMPOSSIBLE.

Входные данные
```
######
#...X#
#.####
#...Y#
######
```
Выходные данные
```
######
#xxxX#
#x####
#xxxY#
######
```

Входные данные
```
######
#...X#
######
#...Y#
######
```
Выходные данные
```
IMPOSSIBLE
```

2023-12-29 10:22 UTC, closed without merging