Индивидуальное задание 2 Лопатин Д. М. 9091
Dovgalyuk/Algorithms pull request #83
Opened 2020-09-09 13:22 UTC by Lapohuy

Стек реализован, но, поскольку Data у нас по дефолту - int, - для операций вместо символов пришлось использовать соответствующие им численные значения. Тем самым исключая возможность использования этих чисел как данных.

2020-09-10 07:01 UTC, Dovgalyuk requested changes

2020-09-10 07:01 UTC, Dovgalyuk commented on IndividualTask2/main.cpp
> +		temp_calc->next->next->data = temp;
Не надо обращаться к внутренностям стека и списка напрямую. Только через push/pop.

2020-09-10 07:01 UTC, Dovgalyuk commented on IndividualTask2/main.cpp
> +		stack_push(stack, temp_data);
И нельзя посчитать ничего с числом 42?

2020-10-03 13:48 UTC, Lapohuy commented
Вроде как учел все замечания. Из основных изменений - в листе добавлено поле для операций, выпилены несколько функций, которых для односвязного списка быть не должно, а чтение вводимых пользователем данных теперь производится из строки, которая в последствии проверяется на соответствии операция/дата, что решает возникшую ранее проблему ввода чисел, совпадающих с кодом символов.

2020-10-05 05:55 UTC, Dovgalyuk requested changes

2020-10-05 05:55 UTC, Dovgalyuk commented on IndividualTask2/main.cpp
> +	List* temp_l_c = list_create();
А нельзя просто две переменные завести для операндов?

2020-10-05 05:55 UTC, Dovgalyuk commented on IndividualTask2/main.cpp
> +			if (counter < 2)
Можно это решить через stack_empty, без лишних переменных.

2020-10-05 05:55 UTC, Dovgalyuk commented on LibraryCPP/list.h
> +};
Эта проблема всё ещё остаётся.

2020-10-05 05:55 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +	if (stack_empty(stack) == true)
Лучше просто if (stack_empty(stack))

2020-10-05 05:55 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +		ListItem* temp = stack->list->first->next;
Тут не стоит забираться вовнутрь списка. Модуль стека должен пользоваться только функциями из интерфейса списка.

2020-10-05 15:19 UTC, Lapohuy commented on LibraryCPP/list.h
> +};
Строчка с обновлением структуры уже удалена и отмечена красным тут. Перепроверил исходник на компе - там тоже объявления структуры уже нет.

2020-10-07 06:10 UTC, Dovgalyuk requested changes

2020-10-07 06:10 UTC, Dovgalyuk commented on LibraryCPP/list.h
> +};
Объявление должно быть, а определение - нет.
Сейчас есть определение.

2020-10-08 16:30 UTC, Lapohuy commented
![](https://sun9-35.userapi.com/s2ejbs7H2YWnWQixDEBMt1GbLXLLst2A9GIzBw/threwKiDriQ.jpg)

Я перекинул определение структур из хидеров в спп. В результате - студия отказывается воспринимать вполне рабочий до того код (когда определения были в хидере, ошибки указателя на тип неполного класса не было в принципе). Как решать данную проблему - без малейшего понятия, ибо какой-то конкретной информации по теме мне найти не удалось.

2020-10-09 06:37 UTC, Dovgalyuk commented
Не нужно в стеке обращаться ко внутренностям list. Нужно использовать его через интерфейсные функции.

2020-10-11 12:03 UTC, Lapohuy commented
Исправил, теперь работает

2020-10-12 09:05 UTC, Dovgalyuk requested changes

2020-10-12 09:05 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +			stack_delete(stack);
Удалять стек не стоит. В нём позже могут ещё появиться элементы.

2020-10-14 15:55 UTC, Lapohuy commented on IndividualTask2/main.cpp
> +	for (int i = 0; i < 5; i++)
Не очень понимаю, как это реализовывать. Цикла while(_getch()) с выходом при нажатии escape будет достаточно?

2020-10-14 16:01 UTC, Lapohuy commented on IndividualTask2/main.cpp
> +	for (int i = 0; i < strlen(str); i++)
А можно точнее, что имеется ввиду, пожалуйста? О каком указателе речь?

2020-10-14 16:11 UTC, Lapohuy commented on IndividualTask2/main.cpp
> +	for (int i = 0; i < strlen(str); i++)
Могу реализовать цикл for (i = 0; str[i] != '\n'; i++), но не думаю, что имелось ввиду это

2020-10-15 07:06 UTC, Dovgalyuk commented on IndividualTask2/main.cpp
> +	for (int i = 0; i < 5; i++)
Вообще подразумевался ввод из стандартного потока. До конца файла или до перевода строки. Но можно и через ввод с клавиатуры.

2020-10-15 07:07 UTC, Dovgalyuk commented on IndividualTask2/main.cpp
> +	for (int i = 0; i < strlen(str); i++)
Например for ( ; *str ; ++str)

2020-10-18 17:59 UTC, Lapohuy commented
Что-то я изначально полез не в те дебри, упустив момент с изначальной корректностью строки. Сразу минус куча лишнего кода.

2020-10-19 05:46 UTC, Dovgalyuk requested changes

2020-10-19 05:46 UTC, Dovgalyuk commented on IndividualTask2/main.cpp
> +				str.erase(0, i+1);
Теперь надо переписать без модификации строки. На самом же деле важна только последовательность символов, копия без пробелов не нужна.

2020-10-19 05:46 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +	if (stack_empty(stack) != true)
"!=true" - так никто не пишет

2020-10-19 16:21 UTC, Lapohuy commented
Долго думал, как извлекать из последовательности двузначные числа - случайно наткнулся на листинг с поиском числа в строке через atoi. Вроде как теперь работает, если потребуется вариант для числа с неограниченным числом знаков в записи - велл, переделаю еще раз, изменив одну проверку.

2020-10-19 16:34 UTC, Lapohuy commented
Даже сразу сейчас исправил проверку, а то слишком очевидный недочет

2020-10-20 07:04 UTC, Dovgalyuk approved these changes

2020-10-20 07:09 UTC, Dovgalyuk commented
1. Реализовать в проекте Library массив переменного размера (модуль vector) и очередь на основе этого массива (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
    2. Решить задачу, используя реализованную очередь.
Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной – «#» или пустым пространством – «.». Стартовая позиция обозначается как X. Написать программу, считающую количество клеток, до которых можно найти из начальной, а также выводящую лабиринт с достижимыми клетками, отмеченными символом «x». За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди.


Входные данные
```
######
#...X#
#.####
#....#
######
```

Выходные данные
```
9
######
#xxxx#
#x####
#xxxx#
######

```

2020-10-20 07:09 UTC, closed without merging