Task2
Dovgalyuk/Algorithms pull request #85
Opened 2020-09-09 21:45 UTC by SomeBytes-lab

Выполнено индивидуальное задание 2:

```
1. Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
2. Решить задачу, используя реализованный стек.
```
Преобразовать корректное арифметическое выражение без скобок, использующее операции сложения, вычитания, умножения и деления, в арифметическое выражение в обратной польской записи. Программа должна учитывать приоритет операторов умножения и деления и использовать стек. Операндами в выражении являются однобуквенные переменные.

Вход | Выход
-- | --
A+B*C+D | ABC*+D+
A*B+C | AB*C+

2020-09-10 07:31 UTC, Dovgalyuk requested changes

2020-09-10 07:31 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +	last->pNext = currect->pNext;
Где-то надо ещё и память от удаленного элемента освободить.

2020-09-10 07:31 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +		list_delete(stack->list);
Удалять список нужно, даже если он пуст.

2020-09-10 08:06 UTC, SomeBytes-lab commented on LibraryCPP/list.cpp
> +	last->pNext = currect->pNext;
```suggestion
	last->pNext = currect->pNext;
	delete currect;
```

2020-09-10 08:08 UTC, SomeBytes-lab commented
Исправлено

2020-09-10 16:22 UTC, Dovgalyuk commented
Это зачтено, следующее выдам в понедельник.

2020-09-14 08:26 UTC, Dovgalyuk commented
1. Реализовать в проекте Library массив переменного размера (модуль vector) и очередь на основе этого массива (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
    2. Решить задачу, используя реализованную очередь.
Задан список двунаправленных дорог, соединяющих города и названия городов между которыми нужно найти кратчайший путь. Написать программу, находящую кратчайший путь с помоью поиска в ширину и вывести в выходной файл список городов, которые нужно посетить, чтобы добраться из начального города в конечный. 


Вход | Выход
-- | --
City1 City2 			City2 End 			Start City1 			Start End | Start City1 City2 End



В примере задано 3 дороги: City1-City2, City2-End, Start-City1. Последние 2 города в списке – начальный и конечный города в искомом пути.

2020-09-14 08:26 UTC, closed without merging