1lab
Dovgalyuk/Algorithms pull request #870
Opened 2024-09-11 17:38 UTC by Dethord-hub

Сделал основное задание и первое задание из двух

2024-09-12 04:47 UTC, Dovgalyuk commented
1. Надо доделать всё.
2. Проект должен собираться и тестироваться (см. вкладку checks).

2024-09-16 05:32 UTC, Dovgalyuk commented
Снова ошибки.

2024-09-16 06:22 UTC, Dethord-hub commented
Странно, запуская тесты на компьютере все проходит...
Ну ладно, попробую еще раз! :з

2024-09-23 14:20 UTC, Dethord-hub commented
Павел Михайлович, здравствуйте, извините, что беспокою по глупой теме, но может я что-то не понимаю...
Как правильно запустить тесты для проверки работоспособности своего кода?
Спрашиваю, т.к. в прошлый раз залив код получил две ошибки в тестах, хотя тот тест, который я запускал с папки build показывал, что все верно(
Если вам будет несложно, можете ответить на этот вопрос? Заранее большое спасибо!

2024-09-24 08:22 UTC, Dovgalyuk commented
Выполнить ctest или make test.

2024-09-27 04:26 UTC, Dovgalyuk commented
Сборка не проходит.

2024-10-01 06:01 UTC, Dovgalyuk requested changes

2024-10-01 06:01 UTC, Dovgalyuk commented on LibraryC/array.h
> +typedef void* Data;
Лучше оставить uintptr_t. При использовании такого массива с числами, будет проще с ним работать. Добавятся только приведения типов в самой библиотеке.

2024-10-02 03:53 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library двусвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Реализовать интерпретатор подмножества языка Befunge: https://en.wikipedia.org/wiki/Befunge
Программа читает входную строку из следующих команд:
* 0-9 - заносит число в стек
* +-*/% - арифметические операции. Извлекают два числа из стека, а потом заносят туда результат
* ! - логическое "не". Извлекает значение с вершины стека и заносит туда 1, если это был 0. Иначе заносит в стек 0.
* ` - логическое "больше". Извлекает два значения из стека и заносит обратно 1, если первое больше второго и 0 в противном случае.
* : - дублирует значение на вершине стека.
* . - извлекает значение из стека и выводит его.
* & - запрашивает число с клавиатуры и заносит его в стек.

Входные данные
```
123...
```
Выходные данные
```
3
2
1
```

Входные данные
```
1:.2:.3:.++.
```
Выходные данные
```
1
2
3
6
```

2024-10-02 03:53 UTC, closed without merging