Выполнено индивидуальное задание 3
Dovgalyuk/Algorithms pull request #88
Opened 2020-09-21 10:46 UTC by SomeBytes-lab

Выполнено индивидуальное задание 3:
```
1. Реализовать в проекте Library массив переменного размера (модуль vector) и очередь на основе этого массива (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
2. Решить задачу, используя реализованную очередь. 
```
Задан список двунаправленных дорог, соединяющих города и названия городов между которыми нужно найти кратчайший путь. Написать программу, находящую кратчайший путь с помоью поиска в ширину и вывести в выходной файл список городов, которые нужно посетить, чтобы добраться из начального города в конечный.

Вход | Выход
-- | --
City1 City2 City2 End Start City1 Start End | Start City1 City2 End

В примере задано 3 дороги: City1-City2, City2-End, Start-City1. Последние 2 города в списке – начальный и конечный города в искомом пути.

2020-09-23 07:32 UTC, Dovgalyuk requested changes

2020-09-23 07:32 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +		queue->tail++;
А здесь разве не может быть переполнения очереди?

2020-09-23 07:32 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +	queue->head++;
head тоже может переходить через конец массива.

2020-09-23 07:32 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +		return false;
можно заменить на return queue->head == queue->tail

2020-09-23 07:32 UTC, Dovgalyuk commented on LibraryCPP/vector.cpp
> +		if (index < vector->reservedSize)
Если хочется автоматически увеличивать vector, то лучше просто вызвать resize, где эта же логика должна поддерживаться.

2020-09-23 07:32 UTC, Dovgalyuk commented on LibraryCPP/vector.cpp
> +			if ((vector->data = (Data*)std::realloc(vector->data, size * sizeof(Data) * 2)) == NULL)
realloc работает с парой malloc/free, а не new/delete.

2020-09-23 07:32 UTC, Dovgalyuk commented on Task/main.cpp
> +				graf[cityIndex[start]].pop_back();
Непонятно зачем это.

2020-09-28 16:04 UTC, SomeBytes-lab commented on Task/main.cpp
> +				graf[cityIndex[start]].pop_back();
Чтобы убрать ребро Start->End, потому что в цикле есть лишняя итерация, которая добавляет это лишнее ребро. Если этого не сделать, то результатом выполнения всегда будет Start End.

2020-09-29 12:34 UTC, Dovgalyuk requested changes

2020-09-29 12:34 UTC, Dovgalyuk commented on LibraryCPP/vector.cpp
> +		vector_resize(vector, index);
Может тогда index+1?

2020-09-29 12:34 UTC, Dovgalyuk commented on LibraryCPP/vector.cpp
> +		vector->size = vector->reservedSize;
Вроде не так.

2020-09-29 12:34 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +		queue->head++;
Можно head = head % size

2020-09-29 12:34 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +	else
Блок ниже выглядит более универсальным. Нельзя избавиться от блока выше?

2020-10-04 21:46 UTC, SomeBytes-lab commented
Исправил.

2020-10-05 06:00 UTC, Dovgalyuk requested changes

2020-10-05 06:00 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +		}
В этих двух циклах с индексами что-то не то. Они могут как перекрываться, так и оставлять дыры в массиве.

2020-10-05 17:45 UTC, SomeBytes-lab commented
Исправил.

2020-10-07 06:05 UTC, Dovgalyuk requested changes

2020-10-07 06:05 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +	else
Можно убрать else, тогда установка значения будет одна для всех трех ветвей.

2020-10-12 08:37 UTC, Dovgalyuk approved these changes

2020-10-12 08:44 UTC, Dovgalyuk commented
1. Разработать интерфейс (набор функций) для ассоциативного массива, который хранит пары (ключ)строка -> (значение)строка. Поддерживаемые операции: добавить пару ключ-значение, найти значение по ключу, удалить значение по ключу.
    2. Реализовать ассоциативный массив на основе АВЛ-дерева.
    3. Реализовать функцию проверки баланса АВЛ-дерева и в отладочном режиме вызывать ее после каждого добавления/удаления.
    4. Написать генератор входных данных различного объема для этого контейнера. Сравнить скорость выполнения операции добавления в контейнер содержимого файла для АВЛ-дерева и для std::map при различных объемах данных.

2020-10-12 08:44 UTC, closed without merging