Lab 1 C
Dovgalyuk/Algorithms pull request #888
Opened 2024-09-15 12:40 UTC by Igor-Porubov

2024-09-16 05:49 UTC, Dovgalyuk requested changes

2024-09-16 05:49 UTC, Dovgalyuk commented on Lab1C/lab1.c
> +            }
Лучше всего не передвигать весь хвост массива каждый раз. Вместо этого можно просто ставить очередной элемент на первую свободную позицию.

2024-09-16 05:49 UTC, Dovgalyuk commented on LibraryC/array.c
> +Data* array_get(const Array *arr, size_t index)
А зачем здесь указатель?

2024-09-16 06:20 UTC, Igor-Porubov commented on LibraryC/array.c
> +Data* array_get(const Array *arr, size_t index)
в тесте array.cpp результат функции array_get() приводится к типу указатель на int и разыменовывается. Следовательно, в тесте ожидается, что функция вернёт указатель

2024-09-17 05:20 UTC, Dovgalyuk commented on LibraryC/array.c
> +Data* array_get(const Array *arr, size_t index)
Там в массиве сохраняются указатели. Data - это uintptr_t, в этом типе можно хранить и целые, и указатели.

2024-09-17 19:28 UTC, Igor-Porubov commented
Переделал, теперь в массиве хранятся адреса данных, приведённые к типу Data.
Также переделал функцию task2, теперь на освобождённое место встаёт элемент из конца массива

2024-09-18 06:07 UTC, Dovgalyuk requested changes

2024-09-18 06:07 UTC, Dovgalyuk commented on LibraryC/array.c
> +        free((void*)arr->elem_ptr[i]);
Второй аргумент функции array_create - это указатель на деструктор (который заодно и память освобождает).
В текущей задаче нужно либо передать туда free, либо сохранять в массиве числа вместо указателей.

2024-09-18 06:07 UTC, Dovgalyuk commented on Lab1C/lab1.c
> +            array_set(arr, i, (array_get(arr, end_of_arr - 1)));
Так элементы перемешиваются, а не просто сдвигаются.

2024-09-18 10:38 UTC, Igor-Porubov commented
Добавил в структуру поле указатель на деструктор. Теперь, если деструктор передан, для освобождения указателей в массиве используется он, иначе, если передан NULL, используется free().
В task2 теперь очередной элемент переставляется на первую свободную позицию. Затем освободившееся место в конце массива заполняется указателями на 0

2024-09-19 05:17 UTC, Dovgalyuk commented
Если всегда используется free, то тип элемента должен быть void*, а не uintptr_t. Иначе пользователь может записать каких-то чисел, а потом для них будет вызываться free.

2024-09-19 13:36 UTC, Igor-Porubov commented
Теперь деструктор используется только если он передан

2024-09-20 06:43 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
* Решить задачу, используя реализованный стек.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Преобразовать арифметическое выражение в ассемблерные опреации работы со стеком и регистрами.
Используются команды PUSH (занести в стек), POP (извлечь из стека в регистр), ADD (сложить),
SUB (вычесть), MUL (перемножить). Достаточно использовать два регистра A и B.

Входные данные
```
1+2*3
```
Выходные данные
```
PUSH 1
PUSH 2
PUSH 3
POP A
POP B
MUL A, B
PUSH A
POP A
POP B
ADD A, B
PUSH A
```

Входные данные
```
(1+2)*3
```
Выходные данные
```
PUSH 1
PUSH 2
POP A
POP B
ADD A, B
PUSH A
PUSH 3
POP A
POP B
MUL A, B
PUSH A
```

2024-09-20 06:43 UTC, closed without merging