Задание 3(Баринов Дмитрий)
Dovgalyuk/Algorithms pull request #89
Opened 2020-09-28 23:20 UTC by Golden3oloto

1 - Был реализован модуль list. На основе этого модуля был создан модуль stack.
2 - Используя stack была написана программа(TestHTML), проверяющая последовательность тегов html из одного файла(input.txt), и выводящая результат в другой(output.txt).

2020-09-29 12:26 UTC, Dovgalyuk requested changes

2020-09-29 12:26 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +		list_first(list)->pPrev =new_item;
Лучше сразу брать list->head, раз уж мы все равно обращаемся к внутренностям.

2020-09-29 12:26 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +		list_item_prev(item)->pNext =list_item_next(item);
Странно выглядят обращения к pNext, когда тут же используются функции для чтения этого же поля.
Лучше тогда функции убрать.

2020-09-29 12:26 UTC, Dovgalyuk commented on LibraryCPP/stack.h
> +#include "list.h"
Лучше не тащить сюда list, так как оттуда ничего не нужно.
Если нужен единый тип Data, то можно для него сделать отдельный заголовочный файл.

2020-09-29 12:26 UTC, Dovgalyuk commented on TestHTML/main.cpp
> +	const string output_path ="../../TestHTML/output.txt";
Этот вариант путей не очень.
Нормальные варианты:
1. input/output в текущем каталоге.
2. имена в качестве параметров
3. стандартный ввод-вывод вместо файлов

2020-09-29 12:26 UTC, Dovgalyuk commented on TestHTML/main.cpp
> +	string flag ="YES";
Если нужен флаг, то стоит сделать его булевым.
А на выводе уже преобразовывать в строку.

2020-09-29 12:26 UTC, Dovgalyuk commented on TestHTML/main.cpp
> +		tag.erase(0, 1);
Для этого хорошо подходит string_view.

2020-10-21 06:07 UTC, Dovgalyuk commented
Оставшиеся комментарии тоже стоит учесть.

2020-10-25 15:07 UTC, Golden3oloto commented
По поводу string_view есть небольшая проблема. У меня сейчас из техники доступен только старый ноутбук, на котором стоит window xp. А под неё подходит только visual studio 2010 года, в которой класса string_view ещё не было. Я изменил немного код и убрал строки tag.pop_back(); и tag.erase(0,1); ,но сам класс string_view я не использовал. Можно мне сдать лабораторную в таком виде?

2020-10-26 07:40 UTC, Dovgalyuk commented
Хорошо, пусть остаётся так. Хотя можно было бы использовать c_str() и strcmp(), но это было бы менее красиво.

2020-10-26 07:42 UTC, Dovgalyuk commented
1. Реализовать в проекте Library массив переменного размера (модуль vector) и очередь на основе этого массива (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
    2. Решить задачу, используя реализованную очередь.
Во входном файле записано количество вершин и матрица смежности ориентированного графа. Вывести в выходной файл список расстояний от первой вершины до всех остальных. Для вычисления расстояний использовать поиск в ширину.


Вход | Выход
-- | --
4 			0 1 0 0 			0 0 1 1 			1 0 0 1 			0 1 0 0 | 0 			1 			2 			2

2020-10-26 07:42 UTC, closed without merging