Lab#1
Dovgalyuk/Algorithms pull request #892
Opened 2024-09-16 17:55 UTC by onix1t

2024-09-17 06:00 UTC, Dovgalyuk requested changes

2024-09-17 06:00 UTC, Dovgalyuk commented on AlgLab1CPPClass/CMakeLists.txt
> +add_test(NAME TestAlgLab1CPPClass COMMAND AlgLab1CPPClass ${CMAKE_CURRENT_SOURCE_DIR}/input.txt ${CMAKE_CURRENT_SOURCE_DIR}/output.txt)
Выходной файл не должен создаваться в каталоге с исходными текстами.

2024-09-17 06:00 UTC, Dovgalyuk commented on AlgLab1CPPClass/alg_lab1.cpp
> +#include "../LibraryCPPClass/array.h"
Путь уже прописан в CMakeLists.txt, можно написать просто "array.h".

2024-09-17 06:00 UTC, Dovgalyuk commented on AlgLab1CPPClass/output.txt
Этот файл выкладывать не нужно.

2024-09-18 05:49 UTC, Dovgalyuk commented on AlgLab1CPPClass/CMakeLists.txt
> +add_test(NAME TestAlgLab1CPPClass COMMAND AlgLab1CPPClass ${CMAKE_CURRENT_SOURCE_DIR}/input.txt ${CMAKE_CURRENT_SOURCE_DIR}/output.txt)
Это осталось.

2024-09-18 05:50 UTC, Dovgalyuk commented on AlgLab1CPPClass/output.txt
Тоже осталось.

2024-09-18 10:32 UTC, onix1t reviewed
.

2024-09-18 11:22 UTC, onix1t reviewed
Указанные выше ошибки исправлены.
@Dovgalyuk

2024-09-19 05:22 UTC, Dovgalyuk requested changes

2024-09-19 05:22 UTC, Dovgalyuk commented on AlgLab1CPPClass/CMakeLists.txt
> +add_test(NAME TestAlgLab1CPPClass COMMAND AlgLab1CPPClass ${CMAKE_CURRENT_SOURCE_DIR}/input.txt ${CMAKE_CURRENT_SOURCE_DIR}/Tests/output.txt)
${CMAKE_CURRENT_SOURCE_DIR}/Tests/output.txt
это нехорошо

2024-09-19 18:20 UTC, onix1t reviewed
Файл с выходными данными теперь создаётся в директории сборки

2024-09-20 06:48 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Реализовать интерпретатор подмножества языка Befunge: https://en.wikipedia.org/wiki/Befunge
Программа читает входную строку из следующих команд:
* 0-9 - заносит число в стек
* +-*/% - арифметические операции. Извлекают два числа из стека, а потом заносят туда результат
* ! - логическое "не". Извлекает значение с вершины стека и заносит туда 1, если это был 0. Иначе заносит в стек 0.
* ` - логическое "больше". Извлекает два значения из стека и заносит обратно 1, если первое больше второго и 0 в противном случае.
* : - дублирует значение на вершине стека.
* . - извлекает значение из стека и выводит его.
* & - запрашивает число с клавиатуры и заносит его в стек.

Входные данные
```
123...
```
Выходные данные
```
3
2
1
```

Входные данные
```
1:.2:.3:.++.
```
Выходные данные
```
1
2
3
6
```

2024-09-20 06:48 UTC, closed without merging