lab2
Dovgalyuk/Algorithms pull request #897
Opened 2024-09-17 20:07 UTC by ms-anastasiia

2024-09-18 06:08 UTC, Dovgalyuk commented
Не собирается.

2024-09-19 05:24 UTC, Dovgalyuk commented
Всё ещё не собирается.

2024-09-20 06:37 UTC, Dovgalyuk commented
Теперь не проходит тест.

2024-09-23 05:08 UTC, Dovgalyuk commented
Всё ещё не проходит.

2024-09-24 08:18 UTC, Dovgalyuk requested changes

2024-09-24 08:18 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +                if (stack_empty(operators)) {
Как здесь может сработать empty?

2024-09-24 08:18 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +                if (stack_empty(values)) throw std::runtime_error("Invalid expression");
Тут empty никогда не сработает.

2024-09-24 08:18 UTC, Dovgalyuk commented on LibraryCPP/stack.h
> +} Stack;
В заголовочный файл выносить определение структуры не нужно.

2024-09-25 05:42 UTC, Dovgalyuk requested changes

2024-09-25 05:42 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +                stack_pop(values);
Нужная проверка на пустоту тоже пропала вместе с ненужной.

2024-09-25 05:42 UTC, Dovgalyuk commented on LibraryCPP/vector.h
> +struct Vector {
Этого не должно быть в заголовочном файле.

2024-09-26 06:16 UTC, Dovgalyuk commented
Определение вектора размножилось. И ненужные проверки появились.

2024-09-27 04:16 UTC, Dovgalyuk commented
Несколько лишних проверок, о которых я раньше говорил, осталось.

2024-09-30 05:29 UTC, Dovgalyuk commented
Всё ещё не то.

2024-10-01 05:43 UTC, Dovgalyuk commented
Проверять на пустоту в get - плохая идея, потому что в случае ошибки непонятно что делать.
Надо аккуратно написать проверки в цикле.

2024-10-02 03:55 UTC, Dovgalyuk commented
В циклах проверки на пустоту стека пропали.

2024-10-02 10:11 UTC, ms-anastasiia commented
Дописала внутри циклов две проверки на пустоту стека с операторами. Надеюсь то, что нужно, на мой взгляд их тут точно не хватает)

2024-10-03 05:43 UTC, Dovgalyuk commented
Не везде есть проверки на пустоту перед get.

2024-10-04 04:27 UTC, Dovgalyuk commented
Стоит добавить несколько тестов с некорректными выражениями. Например, "1)".

2024-10-07 05:05 UTC, Dovgalyuk commented
А тест с лишней закрывающей скобкой?

2024-10-07 11:45 UTC, ms-anastasiia commented
добавила выражение с лишней скобкой

2024-10-08 17:08 UTC, Dovgalyuk commented
А выражение только из одной закрывающей скобки?

2024-10-10 10:00 UTC, Dovgalyuk commented
Надо не с лишней скобкой, а вообще только одну скобку: ")"

2024-10-11 08:02 UTC, Dovgalyuk commented
Понятно, тут срабатывает обработка исключений. Тогда надо везде убрать проверки на пустоту, раз обработка ошибок реализована через исключения.

2024-10-14 05:18 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library кольцевой двусвязный список (модуль list) и очередь на основе этого списка (модуль queue).
* Решить задачу, используя реализованную очередь.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной - «#» или пустым пространством – «.».
Стартовая позиция обозначается как X, финишные позиции цифрами от 0 до 9.
Написать программу, которая выводит цифру, ближайшую к стартовой позиции.
За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди.

Входные данные
```
######
#...X#
#.#.##
#3.4.#
######
```
Выходные данные
```
4
```

2024-10-14 05:18 UTC, closed without merging