Lab3
Dovgalyuk/Algorithms pull request #911
Opened 2024-09-20 05:51 UTC by bvaleksch

Баранов Валентин 3091

    Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
    Решить задачу, используя реализованную очередь.
    Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Написать программу для поиска решений головоломки "Игра 8".
Это упрощённый варианты головоломки "Игра 15", в которой фишки перемещаются по квадратной
доске. Программа должна находить кратчайшее решение для заданной позиции.

Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди.

2024-09-20 07:49 UTC, Dovgalyuk requested changes

2024-09-20 07:49 UTC, Dovgalyuk commented on LibraryCPP/queue.h
> +typedef size_t Data;
Если там указатели, стоит сделать void*. Ну или хотя бы uintptr_t.

2024-09-20 07:49 UTC, Dovgalyuk commented on LibraryCPP/vector.cpp
> +#ifndef RESIZE_FACTOR
А где он уже мог быть определён?

2024-09-20 07:49 UTC, Dovgalyuk commented on LibraryCPP/vector.cpp
> +            vector->real_size = new_size / sizeof(Data);
С делением некрасиво. Лучше отдельно сначала посчитать размер в элементах.

2024-09-20 07:49 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +            vector_set(queue->vector, ind - queue->current_index, vector_get(queue->vector, ind));
Если из заполненной очереди постоянно удалять и добавлять по одному элементу, каждое добавление будет занимать O(N) времени. Нужно избегать такого копирования, а для этого сделать кольцевой буфер.

2024-09-20 07:49 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +            row -= x; col -= y;
Лучше временные переменные сделать.

2024-09-20 08:05 UTC, bvaleksch commented on LibraryCPP/queue.cpp
> +            vector_set(queue->vector, ind - queue->current_index, vector_get(queue->vector, ind));
Хорошо перепешу с использование кольцевого. Просто в случае кольцевого буфера чуть проблематичнее вставлять новый элемент когда current_index != 0 и очередь полная

2024-09-20 08:09 UTC, bvaleksch commented on LibraryCPP/queue.h
> +typedef size_t Data;
Тут не понятно как быть с Вашими тестами. Они то используют числа, а не указатели

2024-09-23 05:21 UTC, Dovgalyuk commented on LibraryCPP/queue.h
> +typedef size_t Data;
В этом случае тесты можно исправить.

2024-09-23 05:22 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +            vector_set(queue->vector, ind - queue->current_index, vector_get(queue->vector, ind));
В этом случае придётся копировать всё, но это редкая ситуация, она не приводит к сложности O(N^2).

2024-09-23 05:23 UTC, Dovgalyuk commented on LibraryCPP/queue.h
> +typedef size_t Data;
И кстати uintptr_t для чисел тоже подходит.

2024-09-23 05:56 UTC, bvaleksch commented
Сейчас, вроде, все замечания исправлены.
1) Логичнее вынести всё это за пределы цикла. Будет намного читабельнее.
- Вынес. Теперь это в отдельной функции
2) Если там указатели, стоит сделать void*. Ну или хотя бы uintptr_t.
- Я изменил логику программы, теперь она тоже использует числа. Поменять логику решил, потому что первая версия использовала прилично так памяти, для этой задачи
3) А где он уже мог быть определён?
- Убрал. Уже не помню почему решил тогда эта написать
4) С делением некрасиво. Лучше отдельно сначала посчитать размер в элементах.
- Теперь размер считается в элементах. При выделении памяти домнажаю на sizeof(Data)
5) Если из заполненной очереди постоянно удалять и добавлять по одному элементу, каждое добавление будет занимать O(N) времени. Нужно избегать такого копирования, а для этого сделать кольцевой буфер.
- Сейчас использую кольцевой буфер

2024-09-24 07:57 UTC, Dovgalyuk requested changes

2024-09-24 07:57 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +    num /= std::pow(10, ind);
pow - с вещественными числами работает, так не очень хорошо делать. Можно сделать таблицу целых степеней, например. Может быть даже через constexpr функцию, которая константный массив заполняет.

2024-09-24 07:57 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +                figure = get_figure(current_state, new_index);
это digit, а не figure

2024-09-24 07:57 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +void show_answer(size_t first_state, size_t state, std::unordered_map<size_t, size_t> *all_states)
all_states лучше по ссылке передать, тут же не может быть нулевого указателя

2024-09-24 07:57 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +    while (true){
Тут непонятно, откуда берутся вложенные циклы.

2024-09-24 07:57 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +        vector_resize(queue->vector, max(1, std::ceil(queue->size * RESIZE_FACTOR)));
в макросы нехорошо передавать сложные выражения (особенно функции), потому что они будут вычисляться несколько раз

2024-09-24 07:57 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +void queue_order(Queue *queue, size_t old_size)
Эта функция должна быть static.

2024-09-25 05:40 UTC, Dovgalyuk requested changes

2024-09-25 05:40 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +            if ((new_row < 3) && (new_col < 3)){
А меньше нуля никто из них не станет?

2024-09-25 05:40 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +                new_state = current_state + digit * std::pow(10, zero_index) - digit * std::pow(10, new_index);
Есть же новый pow.

2024-09-25 05:40 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +size_t get_digit(size_t num, size_t ind)
Обычно size_t не для этого. Тут хватает простого unsigned int. Но если очень хочется, ещё есть unsigned long long.

2024-09-25 05:40 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +        state = search_prev_state(state, --count, all_states);
Теперь понял, зачем два цикла. Предыдущее состояние можно хранить прямо в all_states[s] вместо count. Тогда цикл будет только один.

2024-09-25 06:08 UTC, bvaleksch commented on Lab3CPP/lab3.cpp
> +        state = search_prev_state(state, --count, all_states);
Спасибо за замечание. Так действительно будет лучше

2024-09-25 06:08 UTC, bvaleksch commented on Lab3CPP/lab3.cpp
> +                new_state = current_state + digit * std::pow(10, zero_index) - digit * std::pow(10, new_index);
Тут забыл поправить

2024-09-25 06:08 UTC, bvaleksch commented on Lab3CPP/lab3.cpp
> +            if ((new_row < 3) && (new_col < 3)){
Нет. Меньше нуля никто не станет. Будет переполнение, так как size_t

2024-09-25 06:09 UTC, bvaleksch commented on Lab3CPP/lab3.cpp
> +size_t get_digit(size_t num, size_t ind)
Я выбрал тип size_t для хранения состояния, чтобы избежать предупреждений компилятора о несовпадении типов. Это также упрощает код, так как не нужно постоянно использовать явное приведение типов.

2024-09-26 06:59 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +            if ((new_row < 3) && (new_col < 3)){
Так обычно не делается, потому что код тяжело воспринимается.

2024-09-27 04:30 UTC, Dovgalyuk commented
Принято.

* Разработать программный интерфейс модуля (заголовки функций) библиотеки LibraryCPPTemplate для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины,
получить пометки всех вершин в виде вектора.
* Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
* Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List библиотеки LibraryCPPTemplate.
* Разработать и добавить в проект LibraryCPPTemplate программу, тестирующую работу библиотеки для графа.
* Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать для него минимальное покрывающее дерево алгоритмом Крускала. Использовать систему непересекающихся множеств для поддеревьев в процессе работы алгоритма.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

2024-09-27 04:30 UTC, closed without merging