Лабораторная №1
Dovgalyuk/Algorithms pull request #913
Opened 2024-09-20 13:45 UTC by sudo-odner

<img width="925" alt="Снимок экрана 2024-09-20 в 16 45 13" src="https://github.com/user-attachments/assets/ce733ab0-39d0-42a2-9668-a50b5a279f18">

2024-09-23 05:10 UTC, Dovgalyuk commented
Нужно временно отключить неактуальные тесты, чтобы они не замусоривали вывод.

2024-09-24 07:29 UTC, sudo-odner commented
Исправил ошибку с логами

2024-09-24 08:36 UTC, Dovgalyuk commented
Это задание только про Array, остальные контейнеры надо удалить.

2024-09-26 06:48 UTC, Dovgalyuk requested changes

2024-09-26 06:48 UTC, Dovgalyuk commented on .idea/.gitignore
Эти файлы не нужно выкладывать.

2024-09-26 06:48 UTC, Dovgalyuk commented on Lab1/CMakeLists.txt
> +add_test(NAME TestLab1 COMMAND Lab1 ${CMAKE_CURRENT_SOURCE_DIR}/input.txt ${CMAKE_CURRENT_SOURCE_DIR}/output.txt)
output не нужно создавать в каталоге с исходниками

2024-09-26 06:48 UTC, Dovgalyuk commented on Lab1/lab1.cpp
> +    if(test(output, *arrTask1)) {
Тест должен быть отдельно от программы, которая выводит результат.

2024-09-26 06:48 UTC, Dovgalyuk commented on LibraryCPPClass/array.cpp
>  }
Почему две реализации array?

2024-10-07 04:45 UTC, Dovgalyuk commented
Тест на сервере не проходит.

2024-10-08 16:54 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library двусвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Реализовать команды манипуляции стеком из языка Forth: https://skilldrick.github.io/easyforth
Программа читает входную строку из следующих команд:
* 0-9 - заносит число в стек
* +-*/% - арифметические операции. Извлекают два числа из стека, а потом заносят туда результат
* dup - дублирует число на вершине стека
* drop - удаляет число с вершины стека
* swap - меняет местами два числа на вершине стека
* over - берёт элемент под вершиной стека и добавляет его в стек
* rot - перемещает "по кругу" верхние три элемента стека
* . - извлекает из стека верхний элемент и выводит на экран

Входные данные
```
1 2 3 rot . . .
```
Выходные данные
```
1
3
2
```

Входные данные
```
1 dup . 2 dup . 3 dup . + + .
```
Выходные данные
```
1
2
3
6
```

2024-10-08 16:54 UTC, closed without merging