LAB1C
Dovgalyuk/Algorithms pull request #915
Opened 2024-09-21 14:25 UTC by sYkunA1747

2024-09-23 05:20 UTC, Dovgalyuk requested changes

2024-09-23 05:20 UTC, Dovgalyuk commented on Lab1C/lab1.c
> +    }
Чтобы этого всего не делать, у функции для создания массива есть второй операнд, куда можно передать функцию для освобождения памяти для каждого элемента.

2024-09-23 05:20 UTC, Dovgalyuk commented on Lab1C/lab1.c
> +        }
На каждом шаге сумму можно не пересчитывать целиком, если вычитать из неё предыдущий элемент, а добавлять следующий.

2024-09-25 12:44 UTC, sYkunA1747 commented on Lab1C/lab1.c
> +    }
Исправил, но мне кажется не лучшим способом

2024-09-26 06:30 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Преобразовать корректное арифметическое выражение, использующее операции сложения, вычитания, умножения и деления, в арифметическое выражение в обратной польской записи. Программа должна учитывать приоритет операторов умножения и деления и использовать стек. Операндами в выражении являются однобуквенные переменные.

Входные данные
```
A+B*C+D
```
Выходные данные
```
ABC*+D+
```

Входные данные
```
A*B+C
```
Выходные данные
```
AB*C+
```

Входные данные
```
A+B*(C+D)
```
Выходные данные
```
ABCD+*+
```

2024-09-26 06:30 UTC, closed without merging