lab3
Dovgalyuk/Algorithms pull request #917
Opened 2024-09-22 13:57 UTC by ssezmar

1. Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
2. Решить задачу, используя реализованную очередь.
3. Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.
---
На шахматной доске построен лабиринт и задана позиция шахматного коня.
Найти кратчайший путь коня в целевую точку.

Позиция коня обозначена бувой 'K', выход буквой 'E', а препятствие символом '#'.
Вывести такую же доску с клетками, пронумерованными в порядке их посещения.

Входные данные
```
K.######
..#E....
..#.....
..#.###.
..#.....
.....###
.#####..
##......
```
Выходные данные
```
0.######
..#2....
.1#.....
..#.###.
..#.....
.....###
.#####..
##......
```

2024-09-23 05:46 UTC, Dovgalyuk requested changes

2024-09-23 05:46 UTC, Dovgalyuk commented on Lab3CPPTemplate/lab3.cpp
> +bool isValid(const Point& p, Vector<char>& board) {
Для Vector<char> стоит сделать typedef, чтобы не повторяться.
А конкретно в этой функции для board ещё стоит указать const.

2024-09-23 05:46 UTC, Dovgalyuk commented on Lab3CPPTemplate/lab3.cpp
> +        Vector<char> row(8);
Лишняя переменная.

2024-09-23 05:46 UTC, Dovgalyuk commented on Lab3CPPTemplate/lab3.cpp
> +        Vector<int> curr(8);
Ненужная строчка.

2024-09-23 05:46 UTC, Dovgalyuk commented on Lab3CPPTemplate/lab3.cpp
> +                    end.x = np.x; end.y = np.y;
end = np ?

2024-09-23 05:46 UTC, Dovgalyuk commented on Lab3CPPTemplate/lab3.cpp
> +            } else if (board.get(i * 8 + j) != '*' && board.get(i * 8 + j) != 'K' && board.get(i * 8 + j) != 'E') {
Можно упростить вывод, если проверять board.get() == '*'

2024-09-23 05:46 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +public:
Эти данные стоит защитить с помощью private, чтобы пользователь не смог случайно нарушить работу контейнера.

2024-09-23 05:46 UTC, Dovgalyuk commented on LibraryCPPTemplate/queue.h
> +    if (queueSize == data.capacity()) {
Почему не data.size()?

2024-09-23 05:46 UTC, Dovgalyuk commented on LibraryCPPTemplate/vector.h
> +#include "vector.h"
Тут ненужная рекурсия.

2024-09-23 05:46 UTC, Dovgalyuk commented on LibraryCPPTemplate/vector.h
> +        size_t new_capacity = (new_size == 0 ? 1 : new_size * 2);
new_size не может быть равно нулю здесь

2024-09-23 12:45 UTC, ssezmar commented
```template <typename Data>
void Queue<Data>::insert(Data value) {
    if (queueSize == data.capacity()) {
        size_t old_capacity = data.capacity();
        size_t new_capacity = (data.capacity() == 0) ? 1 : data.capacity() * 2;
        Vector<Data> temp(data);
        data.resize(new_capacity);
        for (size_t i = 0; i < queueSize; i++) {
            data.set(i, temp.get((frontIndex + i) % old_capacity));
        }
        frontIndex = 0;
    }
    data.resize(queueSize + 1);

    data.set((frontIndex + queueSize) % data.capacity(), value);
    queueSize++;
}
```
Вот в этом методе я использую data.capacity(), а не data.size(), потому что я разворачиваю кольцевой буфер только если у ветора забилось вообще все пространство, в остальных случаях можно попробовать вставить элементы вперед заместо уже удаленных из очереди.

2024-09-24 08:21 UTC, Dovgalyuk commented
size - это видимый пользователю размер. Поэтому всегда обращаться к элементам можно только до size. Даже если capacity с ним совпадает, код выглядит понятнее, когда используется size.

2024-09-24 19:45 UTC, ssezmar commented
Удалил вообще метод capacity

2024-09-25 06:15 UTC, Dovgalyuk commented
Принято.

* Разработать программный интерфейс модуля (заголовки функций) библиотеки LibraryCPPTemplate для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины,
получить пометки всех вершин в виде вектора.
* Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
* Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List библиотеки LibraryCPPTemplate.
* Разработать и добавить в проект LibraryCPPTemplate программу, тестирующую работу библиотеки для графа.
* Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать для него минимальное покрывающее дерево алгоритмом Прима.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

2024-09-25 06:15 UTC, closed without merging