Lab1 Иванов Никита Александрович 3093
Dovgalyuk/Algorithms pull request #919
Opened 2024-09-22 19:22 UTC by qwxxx

2024-09-23 07:00 UTC, Dovgalyuk requested changes

2024-09-23 07:00 UTC, Dovgalyuk commented on LibraryCPPClass/array.cpp
>  Array &Array::operator=(const Array &a)
Надо ещё проверять, что &a не совпадает с this.

2024-09-23 07:52 UTC, qwxxx commented on Lab1CPP/Tests/test_tasks.cpp
> +        auto it = std::find(res.begin(), res.end(), num);
У нас в самом задании не было сказано про сортировку. Из этого сделал вывод, что правильным ответом может считаться ответ, в котором числа расставлены в любом порядке

2024-09-23 08:12 UTC, qwxxx commented on Lab1CPP/lab1.h
> +std::vector<Data> task2(Array *arr)
поправил код, дописал комментарии по алгоритму второго задания

2024-09-24 08:03 UTC, Dovgalyuk commented
Стоит выбросить выбор максимума в цикле. Проверять только делимость первого на второе, код сильно упростится.

2024-09-24 08:04 UTC, Dovgalyuk commented on Lab1CPP/Tests/test_tasks.cpp
> +        auto it = std::find(res.begin(), res.end(), num);
Тут тест не на любую программу, а только проверка программы из задания, что она не падает и выдаёт что надо.

2024-09-24 12:34 UTC, qwxxx commented
> Стоит выбросить выбор максимума в цикле. Проверять только делимость первого на второе, код сильно упростится.

не понимаю, как тогда, меньшее число по определению не делится на большее, это проверять нет смысла, как мне кажется. А вот большее может делиться, поэтому и сделал такую логику

2024-09-24 12:50 UTC, qwxxx commented on Lab1CPP/Tests/test_tasks.cpp
> +        auto it = std::find(res.begin(), res.end(), num);
Добавил строгую проверку порядка чисел в ответе

2024-09-25 06:08 UTC, Dovgalyuk commented
Если делимое больше, чем делитель, то остаток будет равен делимому. То есть, отличаться от нуля. Поэтому достаточно одной простой проверки на ноль.

2024-09-25 06:52 UTC, qwxxx commented
> Если делимое больше, чем делитель, то остаток будет равен делимому. То есть, отличаться от нуля. Поэтому достаточно одной простой проверки на ноль.

Переделал алгоритм, сделал вложенный цикл до n, а не до i, соответственно убрал все лишнее

2024-09-26 06:12 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library двусвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Во входном файле записана последовательность операций со стеком JAVA-машины.
Упрощённая JAVA-машина может оперировать стеком и четырьмя локальными переменными с номерами от 0 до 3.
Выполнить операции и напечатать финальное состояние стека и переменных.

Список операций, которые должны поддерживаться:
* bipush число - занести число в стек
* pop - вытолкнуть верхнее значение со стека
* imul - умножение
* iand - побитовое "и"
* ior - побитовое "или"
* ixor - операция "исключающее или"
* iadd - сложение
* isub - вычитание
* iload_0, iload_1, iload_2, iload_3 - занести в стек значение соответствующей переменной
* istore_0, istore_1, istore_2, istore_3 - записать значение с вершины стека в соответствующую переменную
* swap - меняет местами два верхних значения в стеке

Все арифметические операции берут операнды с вершины стека, а затем записывают в стек результат вычислений.

Входные данные
```
bipush 1
bipush 2
bipush 3
iadd
istore_0
```
Выходные данные
```
stack:
1
vars:
5
0
0
0
```

2024-09-26 06:12 UTC, closed without merging