Lab2C
Dovgalyuk/Algorithms pull request #920
Opened 2024-09-23 05:11 UTC by Igor-Porubov

- Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
- Решить задачу, используя реализованный стек.
- Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Преобразовать арифметическое выражение в ассемблерные операции работы со стеком и регистрами.
Используются команды PUSH (занести в стек), POP (извлечь из стека в регистр), ADD (сложить),
SUB (вычесть), MUL (перемножить). Достаточно использовать два регистра A и B.
![Снимок экрана 2024-09-23 080944](https://github.com/user-attachments/assets/63966cfb-fe8a-41df-99bc-2e690112b972)

2024-09-23 07:03 UTC, Dovgalyuk commented on Lab2C/lab2.c
> +            stack_push(stack_asm, data);
Тут уже стек не нужен, можно просто выводить код.

2024-09-23 07:05 UTC, Dovgalyuk commented on Lab2C/lab2.c
> +    char rpn_string[20];
Эта строка может быть длиннее, чем входная.
К тому же, нужно сделать так, чтобы работало с входной последовательностью произвольной длины.

2024-09-23 07:07 UTC, Dovgalyuk commented on LibraryC/vector.c
> +        vector->array = (Data*) realloc(vector->array, size * sizeof(Data));
Уменьшать нет смысла, потому что есть capacity.

2024-09-23 20:22 UTC, Igor-Porubov commented
Внёс изменения:

- в функции asm_commands больше не используется стек
- вместо строк теперь используются структуры vector (за исключением буфера token в функции asm_commands, который используется для форматного вывода числа и на случай, если число имеет больше одного разряда)
- в модуле vector при уменьшении размера больше не вызывается realloc, фактическая ёмкость остаётся прежней, изменяется только значение поля size

2024-09-26 07:48 UTC, Igor-Porubov commented on LibraryC/vector.c
> +        vector->array = (Data*) realloc(vector->array, size * sizeof(Data));
Павел Михайлович, вы проверите изменения?

2024-09-27 04:20 UTC, Dovgalyuk requested changes

2024-09-27 04:20 UTC, Dovgalyuk commented
Прошу прощения, комментарий написал, но не нажал отправить в прошлый раз.

2024-10-07 02:58 UTC, Igor-Porubov commented
теперь вместо указателей хранятся символы приведённые сначала к типу uintptr_t и затем к void*

2024-10-07 12:48 UTC, Igor-Porubov commented on Lab2C/lab2.c
> +        char *ptr = malloc(sizeof(char));
Павел Михайлович, проверьте изменения пожалуйста

2024-10-08 17:20 UTC, Dovgalyuk requested changes

2024-10-08 17:20 UTC, Dovgalyuk commented on Lab2C/lab2.c
> +    parser(stack, input, rpn_string, (Data)(uintptr_t)filler);
Какой смысл в первом аргументе? Можно внутри функции стек создавать и удалять.

2024-10-08 17:20 UTC, Dovgalyuk commented on Lab2C/lab2.c
> +        vector_set(buffer, vector_size(buffer), (Data)(uintptr_t)c);
Можно просто последовательно обрабатывать считанные символы, а не записывать их в буфер.

2024-10-08 17:20 UTC, Dovgalyuk commented on Lab2C/lab2.c
> +            vector_set(rpn_buf, out_i++, filler);
Довольно странно в преобразованной строке хранить цифры поодиночке. Логичнее сразу слить их в одно число. А операции хранить в виде отрицательных констант, например.

2024-10-13 23:56 UTC, Igor-Porubov commented
Внёс изменения. Убрал ненужный буфер, теперь при чтении файла сразу происходит анализ и формирование постфиксной записи. Все токены теперь хранятся в виде чисел, а не отдельных символов. Вспомогательный стек для анализа создаётся и удаляется внутри функции

2024-10-14 06:06 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library кольцевой двусвязный список (модуль list) и очередь на основе этого списка (модуль queue).
* Решить задачу, используя реализованную очередь.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.


Написать программу для поиска решений головоломки "Игра 8".
Это упрощённый варианты головоломки "Игра 15", в которой фишки перемещаются по квадратной
доске. Программа должна находить кратчайшее решение для заданной позиции.

Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди.

Вывод на экран может быть в более красивом формате.
В примере перечисляются все фишки на доске слева направо и сверху вниз.
Пустое место кодируется нулём.

Входные данные
```
312456780
```
Выходные данные
```
312456780
312456708
312456078
312056478
012356478
102356478
152306478
152036478
152436078
152436708
152436780
152430786
152403786
102453786
120453786
123450786
123456780
```

2024-10-14 06:06 UTC, closed without merging