lab2
Dovgalyuk/Algorithms pull request #931
Opened 2024-09-29 10:54 UTC by EKATERINAelnova

2024-09-30 05:37 UTC, Dovgalyuk commented
Тест не проходит (см. вкладку checks)

2024-10-03 06:03 UTC, Dovgalyuk requested changes

2024-10-04 04:25 UTC, Dovgalyuk commented
Временные файлы нужно удалить из репозитория.

2024-10-07 04:57 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +    vector<string> postfix;
Это замечание осталось.

2024-10-07 18:40 UTC, EKATERINAelnova commented on Lab2CPP/lab2.cpp
> +    vector<string> postfix;
не совсем поняла третье предложение.

2024-10-08 17:22 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +    vector<string> postfix;
Если в стеке хранить числа и операции (в виде чисел) одновременно, надо сделать так, чтобы они не пересекались по значениям. Так как на входе только положительные числа, то для операций можно выбрать отрицательные.

2024-10-13 23:36 UTC, EKATERINAelnova commented
Клонировала репозиторий повторно, дабы делать две вариации изменений. В итоге, запушен был клонированный. Извините.

2024-10-14 05:59 UTC, Dovgalyuk commented
> Клонировала репозиторий повторно, дабы делать две вариации изменений. В итоге, запушен был клонированный. Извините.

Для этого можно использовать ветки внутри одного репозитория.

2024-10-14 06:03 UTC, Dovgalyuk requested changes

2024-10-14 06:03 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +        case '+': return -1;
Хорошо бы для -1,...,-5 создать именованные константы, которые бы использовались во всех местах в коде.

2024-10-14 06:03 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +        if (list_second_to_last(postfix) == nullptr) {
Почему нельзя просто обходить список с первого по последний элемент?

2024-10-14 06:35 UTC, EKATERINAelnova commented on Lab2CPP/lab2.cpp
> +        if (list_second_to_last(postfix) == nullptr) {
Изначально так и хотела, но видимо слишком увлеклась исполнением этой идеи. Исправлю.

2024-10-14 06:38 UTC, EKATERINAelnova commented on Lab2CPP/lab2.cpp
> +        case '+': return -1;
Что функцию эту не писать? Верно понимаю?

2024-10-14 14:24 UTC, EKATERINAelnova commented on Lab2CPP/lab2.cpp
> +        if (list_second_to_last(postfix) == nullptr) {
мне нужно проходить с конца до начала, потому что постфиксное выражение, записанное в списке, перевёрнуто. чтобы это сделать, требуются ссылка на предыдущий элемент.

2024-10-15 06:07 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +        case '+': return -1;
Ещё в остальных местах надо на именованные константы поменять.

2024-10-15 06:09 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +        if (list_second_to_last(postfix) == nullptr) {
Тогда разумнее будет использовать функцию list_insert_after, чтобы список не получался перевёрнутым.

2024-10-21 05:24 UTC, Dovgalyuk requested changes

2024-10-21 05:24 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +    if(op==-1 || op == -2) return blabla2;
Здесь нет именованных констант.

2024-10-21 05:24 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +        case -1:
Здесь тоже нет именованных констант.

2024-10-21 05:24 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +            stack_push(vals,left-right); break;
break лучше писать на отдельной строке, чтобы было ясно видно, что ветка прерывается.

2024-10-21 05:24 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +                while (!stack_empty(ops) && stack_get(ops) != -5) {
И здесь не используется именованная константа.

2024-10-21 05:24 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +        list_last(postfix) == nullptr ? list_insert(postfix, stack_get(ops)) : (list_insert_after(postfix, list_last(postfix), stack_get(ops)));
Лучше написать нормальный оператор if.
Ещё можно доработать list_insert_after для случая null и не писать здесь if вообще.

2024-10-22 05:37 UTC, Dovgalyuk requested changes

2024-10-23 07:39 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Задан ориентированный граф виде матрицы смежности. Написать программу для определения длины кратчайшего пути от одной вершины для другой. В первой строке входного файла записано количество вершин, номер стартовой вершины и номер финишной. В последующих строках идет описание матрицы смежности. Значения 0 в матрице обозначают отсутствие ребра. В выходной файл выводится длина кратчайшего пути. Если решения не существует – выводится IMPOSSIBLE. Программа должна использовать поиск в ширину на основе очереди.

Входные данные
```
4 1 4
0 1 1 0
0 0 0 0
0 1 0 1
0 0 1 0
```
Выходные данные
```
2
```

2024-10-23 07:39 UTC, closed without merging