lab2
Dovgalyuk/Algorithms pull request #943
Opened 2024-10-05 18:17 UTC by AverageCsEnjoyer

2024-10-07 05:03 UTC, Dovgalyuk requested changes

2024-10-07 05:03 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +        if (o == "bipush") {
Параметр bipush - это просто число, а не номер переменной.

2024-10-07 05:03 UTC, Dovgalyuk commented on LibraryCPP/stack.cpp
> +void imul(Stack* stack) {
Это всё должно быть не в стеке, а в основной программе.

2024-10-07 05:03 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    ListItem* pred = nullptr;
В задании односвязный список.

2024-10-07 10:58 UTC, AverageCsEnjoyer commented
Павел Михайлович, я правда не знаю, что именно исправлять во второй правке

2024-10-08 17:03 UTC, Dovgalyuk commented
Стек отдельно, 4 переменные отдельно. Push заносит данные в стек, а не в одну из этих переменных.

2024-10-09 09:48 UTC, Dovgalyuk requested changes

2024-10-09 09:48 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +        stack_push(stack, 0);
Это не нужно. Операции должны удалять из стека операнды.

2024-10-09 09:48 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +            is0 = stack_get(stack);
Почему тут 0, а не 3?

2024-10-09 09:48 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +void ilo(Stack* stack, int ind, int si) {
У "процессора" кроме стека есть 4 переменных. load просто кладёт в стек одну из них.

2024-10-10 10:06 UTC, Dovgalyuk requested changes

2024-10-10 10:06 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +void isub(Stack* stack) {
Разве оно посчитает разность?

2024-10-10 10:06 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +bool iand(Stack* stack) {
Тут должно быть побитовое "И", а не логическое.

2024-10-10 10:06 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +    while (true) {
while (!stack_empty(st))

2024-10-10 10:06 UTC, Dovgalyuk commented on LibraryCPP/stack.h
> +bool ixor(Stack* stack);
Эти функции не должны объявляться в заголовочном файле стека.

2024-10-11 08:08 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной - «#» или пустым пространством – «.». Стартовая позиция обозначается как X. Написать программу, считающую количество клеток, до которых можно найти из начальной, а также выводящую лабиринт с достижимыми клетками, отмеченными символом «x». За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди.

Входные данные
```
######
#...X#
#.####
#....#
######
```
Выходные данные
```
9
######
#xxxx#
#x####
#xxxx#
######
```

2024-10-11 08:08 UTC, closed without merging