lab1
Dovgalyuk/Algorithms pull request #945
Opened 2024-10-07 10:35 UTC by Ilya-Vdovskiy

Вдовский Илья 3093

2024-10-08 17:01 UTC, Dovgalyuk requested changes

2024-10-08 17:01 UTC, Dovgalyuk commented on Lab1CPP/lab1.cpp
> +        if (array_get(arr, i) % 2 == 0 && array_get(arr, i - 1) % 2 == 0) {
А если между двумя чётными элементами один нечётный?

2024-10-08 17:01 UTC, Dovgalyuk commented on LibraryCPP/array.h
> +struct InputData{
Эта структура не относится к массиву, здесь её описывать не нужно.

2024-10-08 20:28 UTC, Ilya-Vdovskiy commented on LibraryCPP/array.h
> +struct InputData{
все исправил, проверьте пожалуйста

2024-10-09 09:41 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
* Решить задачу, используя реализованный стек.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Реализовать интерпретатор подмножества языка Befunge: https://en.wikipedia.org/wiki/Befunge
Программа читает входную строку из следующих команд:
* 0-9 - заносит число в стек
* +-*/% - арифметические операции. Извлекают два числа из стека, а потом заносят туда результат
* ! - логическое "не". Извлекает значение с вершины стека и заносит туда 1, если это был 0. Иначе заносит в стек 0.
* ` - логическое "больше". Извлекает два значения из стека и заносит обратно 1, если первое больше второго и 0 в противном случае.
* : - дублирует значение на вершине стека.
* . - извлекает значение из стека и выводит его.
* & - запрашивает число с клавиатуры и заносит его в стек.

Входные данные
```
123...
```
Выходные данные
```
3
2
1
```

Входные данные
```
1:.2:.3:.++.
```
Выходные данные
```
1
2
3
6
```

2024-10-09 09:41 UTC, closed without merging