задание3 Чалый Сергей 9091
Dovgalyuk/Algorithms pull request #95
Opened 2020-10-26 09:31 UTC by sergeychaliy2

2020-10-26 11:35 UTC, Dovgalyuk requested changes

2020-10-26 11:35 UTC, Dovgalyuk commented on Task/main.cpp
> +		for (int i = 0; i < str.length() - str_push.length(); i++)
Какой смысл в этом цикле?

2020-10-26 11:35 UTC, Dovgalyuk commented on Task/main.cpp
> +				stack_push(stack, atoi(str_num.c_str()));
Как будет работать PUSH C, например?

2020-10-28 06:55 UTC, Dovgalyuk commented on Task/main.cpp
> +				stack_push(stack, atoi(str_num.c_str()));
Вопрос был про push.

2020-10-28 12:32 UTC, sergeychaliy2 commented on Task/main.cpp
> +				stack_push(stack, atoi(str_num.c_str()));
преобразую  строку в число, и потом её помещаю в stack

2020-10-29 05:35 UTC, Dovgalyuk commented on Task/main.cpp
> +				stack_push(stack, atoi(str_num.c_str()));
C - это не число.

2020-10-29 07:32 UTC, sergeychaliy2 commented on Task/main.cpp
> +				stack_push(stack, atoi(str_num.c_str()));
команды PUSH C по не должно быть. Только POP C, для того, чтобы достать значения и переместить его в регистр C

2020-10-29 08:13 UTC, Dovgalyuk commented on Task/main.cpp
> +				stack_push(stack, atoi(str_num.c_str()));
Должна быть, даже есть в примере к заданию.

2020-11-01 11:15 UTC, sergeychaliy2 commented
я исправил , вы были правы.

2020-11-02 05:50 UTC, Dovgalyuk commented
Ещё осталось временные файлы удалить. Я что-то пропустил когда они появились.

2020-11-02 08:31 UTC, sergeychaliy2 commented
подскажите пожалуйста , что конкретно там лишнее, у меня просто через консоль не получается сейчас залить, что то мешает.

2020-11-03 21:37 UTC, sergeychaliy2 commented
zadanie3 - получилось загрузить только нужные файлы

2020-11-05 07:03 UTC, Dovgalyuk commented
1. Реализовать в проекте Library очередь (модуль queue) с использованием двух стеков (модуль stack).
    2. Решить задачу, используя реализованную очередь.
Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной – «#» или пустым пространством – «.». Стартовая позиция обозначается как X, финишная как Y. Написать программу, находящую минимальный путь от стартовой до финишной клетки, если это возможно. За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди. Если решения нет, вывести IMPOSSIBLE.

Вход
```
######
#...X#
#.####
#...Y#
######
```
Выход
```
######
#xxxX#
#x####
#xxxY#
######

```

Вход
```
######
#...X#
######
#...Y#
######
```
Выход
`IMPOSSIBLE
`

2020-11-05 07:03 UTC, closed without merging