Lab2
Dovgalyuk/Algorithms pull request #951
Opened 2024-10-08 21:04 UTC by Dan-GH-str

Лабораторная работа 2: 
Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
Решить задачу, используя реализованный стек.
Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.
Преобразовать корректное арифметическое выражение, использующее операции сложения, вычитания, умножения и деления, в арифметическое выражение в обратной польской записи. Программа должна учитывать приоритет операторов умножения и деления и использовать стек. Операндами в выражении являются однобуквенные переменные.

2024-10-09 10:02 UTC, Dovgalyuk requested changes

2024-10-09 10:02 UTC, Dovgalyuk commented on LibraryCPPTemplate/vector.h
> +            }
А где тут default_value?

2024-10-09 10:02 UTC, Dovgalyuk commented on LibraryCPPTemplate/vector.h
> +            size_t new_capacity = (size_t)ceil(double(len) * 2);
Умножение на 2 уже есть в resize. Проще сделать здесь resize(len+1) и set.

2024-10-09 10:02 UTC, Dovgalyuk commented on LibraryCPPTemplate/vector.h
> +        }
resize же не умеет уменьшать capacity.

2024-10-09 21:07 UTC, Dan-GH-str commented on LibraryCPPTemplate/vector.h
> +            }
В данном случае я не заполнял новые элементы значениями по умолчанию, так как посчитал такие действия лишними операциями с расчетом на то, что при использовании resize пользователь захочет заполнять новые элементы своими значениями. Но если это важно для работы, то я могу заполнять все новые элементы определенными значениями по умолчанию, ведь это, в свою очередь, может предотвратить неопределенное поведение программы при обращении к этим элементам.

2024-10-10 10:09 UTC, Dovgalyuk commented on LibraryCPPTemplate/vector.h
> +        if (len == capacity) {
А если len < capacity?

2024-10-10 20:59 UTC, Dan-GH-str commented on LibraryCPPTemplate/vector.h
> +        if (len == capacity) {
Если len < capacity, значит есть уже зарезервированное место и им можно воспользоваться для вставки нового значения (с помощью функции set, 82-ая строка).

2024-10-11 08:10 UTC, Dovgalyuk commented on LibraryCPPTemplate/vector.h
> +        if (len == capacity) {
То, что set меняет длину - это неправильно. Ведь для этого предназначена функция push.

2024-10-11 08:45 UTC, Dan-GH-str commented on LibraryCPPTemplate/vector.h
> +        if (len == capacity) {
Понял, исправил

2024-10-14 05:15 UTC, Dovgalyuk commented on LibraryCPPTemplate/vector.h
> +        if (len == capacity) {
Сравнение всё ещё не имеет смысла. Можно просто вызывать resize, а не повторять часть её логики здесь.

2024-10-14 20:05 UTC, Dan-GH-str commented on LibraryCPPTemplate/vector.h
> +        if (len == capacity) {
Изменять длину вектора в методе push действительно бессмысленно, убрал лишнее сравнение.

2024-10-15 06:20 UTC, Dovgalyuk commented on LibraryCPPTemplate/vector.h
> +        if (len == capacity) {
Теперь осталось упростить pop.

2024-10-15 20:35 UTC, Dan-GH-str commented on LibraryCPPTemplate/vector.h
> +        if (len == capacity) {
Точно, перенес логику по уменьшению вместимости вектора в случае большого количества удаленных элементов из метода pop в метод resize. Теперь в pop достаточно вызывать resize с уменьшенным размером вектора.

2024-10-17 05:00 UTC, Dovgalyuk commented on LibraryCPPTemplate/vector.h
> +            capacity = new_size;
Так нельзя. Память-то не освободилась. Получается, она занята, но не может быть использована. Лучше вообще этот фрагмент удалить.

2024-10-18 04:57 UTC, closed without merging

2024-10-18 04:57 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library кольцевой двусвязный список (модуль list) и очередь на основе этого списка (модуль queue).
* Решить задачу, используя реализованную очередь.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

На шахматной доске построен лабиринт и задана позиция шахматного коня.
Найти кратчайший путь коня в целевую точку.

Позиция коня обозначена бувой 'K', выход буквой 'E', а препятствие символом '#'.
Вывести такую же доску с клетками, пронумерованными в порядке их посещения.

Входные данные
```
K.######
..#E....
..#.....
..#.###.
..#.....
.....###
.#####..
##......
```
Выходные данные
```
0.######
..#2....
.1#.....
..#.###.
..#.....
.....###
.#####..
##......
```