Lab1
Dovgalyuk/Algorithms pull request #953
Opened 2024-10-11 13:37 UTC by BRUHcha

2024-10-14 05:25 UTC, Dovgalyuk requested changes

2024-10-14 05:25 UTC, Dovgalyuk commented on Lab1CPP/lab1.h
> +#include "../LibraryCPP/array.h"
Пути стоило задать в CMakeLists.txt

2024-10-14 05:25 UTC, Dovgalyuk commented on LibraryCPP/Tests/MyArray.cpp
> +int main(int argc, char **argv)
Этот тест стоит разместить в каталоге с лабораторной, а не в библиотеке.

2024-10-14 11:08 UTC, BRUHcha commented on Lab1CPP/lab1.h
> +#include "../LibraryCPP/array.h"
исправил

2024-10-15 06:03 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library двусвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Написать программу, которая с помощью стека проверяет правильность последовательности из скобок вида (), [], {} и <>. В выходной файл напечатать YES, если последовательность правильная и NO, если неправильная.

Входные данные
```
([])<>
```
Выходные данные
```
YES
```

Входные данные
```
()>
```
Выходные данные
```
NO
```

2024-10-15 06:03 UTC, closed without merging