Lab2
Dovgalyuk/Algorithms pull request #955
Opened 2024-10-12 10:44 UTC by Dethord-hub

2024-10-14 05:34 UTC, Dovgalyuk requested changes

2024-10-14 05:34 UTC, Dovgalyuk commented on Lab2C/lab2.c
> +    Stack *stack = stack_create_from_file(input);
Лучше просто считывать по символу и сразу их обрабатывать, не используя промежуточное хранилище.

2024-10-14 05:34 UTC, Dovgalyuk commented on LibraryC/list.c
> +    ListItem *tail;
tail нигде не используется, его можно удалить.

2024-10-17 11:07 UTC, Dethord-hub commented on Lab2C/lab2.c
> +    Stack *stack = stack_create_from_file(input);
Сделано

2024-10-18 04:53 UTC, Dovgalyuk commented on LibraryC/list.c
> +    ListItem *tail;
Его наличие никак не влияет на внешних пользователей list, потому что никто не запрашивает tail у списка.

2024-10-24 06:08 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Задан список двунаправленных дорог, соединяющих города и названия городов между которыми нужно найти кратчайший путь. Написать программу, находящую кратчайший путь с помоью поиска в ширину и вывести в выходной файл список городов, которые нужно посетить, чтобы добраться из начального города в конечный.

Входные данные
```
City1 City2
City2 End
Start City1
Start End
```
Выходные данные
```
Start City1 City2 End
```

В примере задано 3 дороги: City1-City2, City2-End, Start-City1. Последние 2 города в списке – начальный и конечный города в искомом пути.

2024-10-24 06:08 UTC, closed without merging