ThirdTask
Dovgalyuk/Algorithms pull request #96
Opened 2020-10-26 22:04 UTC by 3minbb

2020-10-28 06:50 UTC, Dovgalyuk requested changes

2020-10-28 06:50 UTC, Dovgalyuk commented on papka/ThirdTask/StrTask.cpp
> +#include "..\..\..\..\Desktop\stack.h"
Пути должны настраиваться в CMakeLists.txt

2020-10-28 06:50 UTC, Dovgalyuk commented on papka/ThirdTask/StrTask.cpp
> +	Say(CheckRightStr("(]"));
Нужен ввод строки с клавиатуры или из файла.

2020-10-28 06:50 UTC, Dovgalyuk commented on papka/ThirdTask/StrTask.cpp
> +	Stack* stack = new Stack();
Память после работы со стеком не освобождается.

2020-10-28 06:50 UTC, Dovgalyuk commented on papka/ThirdTask/StrTask.cpp
> +}
Что выдаст функция для (][) ?

2020-10-28 06:50 UTC, Dovgalyuk commented on papka/ThirdTask/list.cpp
> +		if (toDelete->_next) item->_next = toDelete->_next;
если следующего элемента нет, то что произойдёт?

2020-10-28 06:50 UTC, Dovgalyuk commented on papka/ThirdTask/list.cpp
> +	if (head == nullptr)
Можно обойтись вообще без ветвления.

2020-10-28 06:50 UTC, Dovgalyuk commented on papka/ThirdTask/list.h
> +    Data _value;
_next и _value нужно спрятать в private.
Для доступа из класса List к ним можно написать friend class List;

2020-10-29 10:47 UTC, 3minbb commented on papka/ThirdTask/list.h
> +    Data _value;
Загрузил исправления

2020-10-30 08:48 UTC, Dovgalyuk requested changes
Не все замечания исправлены.

2020-11-20 08:57 UTC, Dovgalyuk requested changes

2020-11-20 08:57 UTC, Dovgalyuk commented on papka/ThirdTask/list.cpp
> +		else item->_next = nullptr;
Теперь снова можно обойтись без ветвления.
Стоит продумать и упростить всю функцию.

2020-11-20 08:57 UTC, Dovgalyuk commented on papka/ThirdTask/StrTask.cpp
> +}
Это тоже не исправлено.

2020-12-02 07:43 UTC, Dovgalyuk requested changes

2020-12-02 07:43 UTC, Dovgalyuk commented on papka/ThirdTask/list.cpp
> +	else head = toInsert;
Почему здесь надо заменять голову списка?

2020-12-02 07:43 UTC, Dovgalyuk commented on papka/ThirdTask/list.cpp
> +void List::Insert(Data value)
Зачем две функции list_insert и Insert?

2020-12-02 07:43 UTC, Dovgalyuk commented on papka/ThirdTask/list.cpp
> +	if (head->_next) head = head->_next;
Можно ли убрать условие?

2020-12-02 07:43 UTC, Dovgalyuk commented on papka/ThirdTask/StrTask.cpp
> +}
Вопрос открыт.

2020-12-14 05:53 UTC, Dovgalyuk commented
CMake Error at CMakeLists.txt:14 (add_subdirectory):
  The source directory

    /home/pasha/Novsu/tmp/papka

  does not contain a CMakeLists.txt file.

2020-12-15 19:22 UTC, 3minbb commented on papka/ThirdTask/list.cpp
> +	if (head->_next) head = head->_next;
Исправил последнюю ошибку

2020-12-16 05:32 UTC, Dovgalyuk commented
LibraryCPP/list.cpp:56:6: error: no declaration matches ‘void List::push_front(Data)’

2020-12-17 21:37 UTC, 3minbb commented on papka/ThirdTask/list.cpp
> +	if (head->_next) head = head->_next;
Исправил

2020-12-18 06:19 UTC, Dovgalyuk commented
LibraryCPP/list.h:30:1: error: version control conflict marker in file
   30 | <<<<<<< HEAD

2020-12-19 12:47 UTC, 3minbb commented
У меня сломалось все на гите вот этот же проект на гуглдиске (https://drive.google.com/file/d/1PLDJ5VPzgl0Smve3zuI1xO8oyiyXsJn8/view?usp=sharing)

2020-12-21 07:45 UTC, Dovgalyuk commented
Можно удалить репозиторий, сделать fork заново, а потом добавить туда файлы.

2020-12-22 10:32 UTC, closed without merging