Lab2
Dovgalyuk/Algorithms pull request #970
Opened 2024-10-24 02:35 UTC by BRUHcha

-  Реализовать в проекте Library двусвязный список (модуль list) и стек на основе этого списка (модуль stack).
  -  Решить задачу, используя реализованный стек.
  -  Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Написать программу, которая с помощью стека проверяет правильность последовательности из скобок вида (), [], {} и <>. В выходной файл напечатать YES, если последовательность правильная и NO, если неправильная.

2024-10-24 02:39 UTC, BRUHcha commented
Пока что не начинал делать задачу, просто хотел спросить, могу ли я в реализации списка изменить тип данных для решения задачи?

2024-10-24 06:11 UTC, Dovgalyuk commented
Да, типы данных менять можно. При необходимости также можно изменить тесты, чтобы они работали правильно.

2024-10-25 05:45 UTC, Dovgalyuk commented
Нужно разобраться с конфликтами.

2024-10-25 06:15 UTC, BRUHcha commented
есть контакт

2024-10-28 04:54 UTC, Dovgalyuk requested changes

2024-10-28 04:54 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +    if(!is_open(str[0])) return "NO";
Этот код ни к чему, ведь остальная часть программы всё равно обрабатывает такую ситуацию.

2024-10-28 04:54 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +            if(str[i] != stack_get(stack))
Тут не хватает проверки стека на пустоту.

2024-10-28 04:54 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +    else if(c == ']' || c == '}' || c == '>')
Для закрывающихся скобок эта функция не вызывается.

2024-10-28 04:54 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    ListItem *tail;
tail не нужен никому вне этого файла, поэтому его можно удалить.

2024-10-28 06:38 UTC, BRUHcha commented
вроде все подправил

2024-10-29 05:34 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Задано начальное вещество и список химических реакций, в которых оно превращается в другое вещество.  Написать программу, использующую поиск в ширину, и выводящую список веществ, которые можно получить из исходного.

Входные данные
```
A
A->B
B->C
D->E
```
Выходные данные
```
B
C
```

В примере из вещества A можно получить вещества B и C.

2024-10-29 05:34 UTC, closed without merging