lab_2
Dovgalyuk/Algorithms pull request #974
Opened 2024-10-24 20:35 UTC by Roman375757752

2024-10-25 05:44 UTC, Dovgalyuk commented
В задании односвязный список, а не вектор.

2024-10-28 05:17 UTC, Dovgalyuk requested changes

2024-10-28 05:17 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +    ifstream inputFile("input.txt");
Открывать нужно файл, переданный в качестве параметра.

2024-10-29 19:52 UTC, Roman375757752 commented on Lab2CPP/lab2.cpp
> +    ifstream inputFile("input.txt");
не особо понял, что именно нужно сделать?

2024-10-30 04:02 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +    ifstream inputFile("input.txt");
При запуске программы ей можно передать аргумент: program.exe file.txt
Должен открываться именно этот файл, а не всегда input.txt

2024-11-02 06:02 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
* Решить задачу, используя реализованную очередь.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Во входном файле записано количество вершин и матрица смежности ориентированного графа. Вывести в выходной файл список расстояний от первой вершины до всех остальных. Для вычисления расстояний использовать поиск в ширину.

Входные данные
```
4
0 1 0 0
0 0 1 1
1 0 0 1
0 1 0 0
```
Выходные данные
```
0
1
2
2
```

2024-11-02 06:02 UTC, closed without merging