lab2
Dovgalyuk/Algorithms pull request #975
Opened 2024-10-26 13:13 UTC by Ilya-Vdovskiy

Vdovskiy 3093

2024-10-28 05:25 UTC, Dovgalyuk requested changes

2024-10-28 05:25 UTC, Dovgalyuk commented on Lab2CPP/CMakeLists.txt
> +add_executable(TestTasks ../LibraryCPP/Tests/test_task2.cpp lab2.cpp)
Этот тест напрямую к библиотеке не относится, поэтому стоит поместить его в каталог с решением.

2024-10-28 05:25 UTC, Dovgalyuk commented on Lab2CPP/lab2.cpp
> +    if (stack_size(stack) >= 2) {
Не нужно узнавать весь размер, достаточно перед каждым извлечением числа проверять стек на пустоту.

2024-10-29 05:40 UTC, Dovgalyuk requested changes

2024-10-29 05:40 UTC, Dovgalyuk commented on Lab2CPP/CMakeLists.txt
> +add_executable(TestTasks ../LibraryCPP/Tests/test_task2.cpp lab2.cpp)
Это ещё осталось.

2024-10-29 07:06 UTC, Ilya-Vdovskiy commented on Lab2CPP/CMakeLists.txt
> +add_executable(TestTasks ../LibraryCPP/Tests/test_task2.cpp lab2.cpp)
Извините, не совсем понимаю что нужно сделать, в последних коммитах 
«fix Cmake and checks» и «fix stack.h» я убрал этот тест из каталога Lab2CPP и перенес его в Cmake всего решения. Его нужно в другое место перенести или совсем убрать?

2024-10-29 18:27 UTC, Ilya-Vdovskiy commented on Lab2CPP/CMakeLists.txt
> +add_executable(TestTasks ../LibraryCPP/Tests/test_task2.cpp lab2.cpp)
Вроде разобрался, исправил

2024-10-30 04:01 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library кольцевой двусвязный список (модуль list) и очередь на основе этого списка (модуль queue).
* Решить задачу, используя реализованную очередь.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Задан ориентированный граф виде матрицы смежности. Написать программу для определения длины кратчайшего пути от одной вершины для другой. В первой строке входного файла записано количество вершин, номер стартовой вершины и номер финишной. В последующих строках идет описание матрицы смежности. Значения 0 в матрице обозначают отсутствие ребра. В выходной файл выводится длина кратчайшего пути. Если решения не существует – выводится IMPOSSIBLE. Программа должна использовать поиск в ширину на основе очереди.

Входные данные
```
4 1 4
0 1 1 0
0 0 0 0
0 1 0 1
0 0 1 0
```
Выходные данные
```
2
```

2024-10-30 04:01 UTC, closed without merging