Lab_1
Dovgalyuk/Algorithms pull request #978
Opened 2024-10-27 15:10 UTC by wXwSmilewXw

Романов Дмитрий Александрович г.3093

P.S.
Если что-то поломал, пока пытался разобраться с гитом, приношу извинения (シ. .)シ (シ_ _)シ

2024-10-28 05:30 UTC, Dovgalyuk requested changes

2024-10-28 05:30 UTC, Dovgalyuk commented on Lab1C/lab1.c
> +#include "../LibraryC/array.h"
Этот путь уже прописан в CMakeLists.txt, здесь его указывать не нужно.

2024-10-28 13:41 UTC, wXwSmilewXw commented
Убрал путь, оставил только array.h, что делать дальше?

2024-10-29 05:36 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library модуль vector для массива переменного размера и стек на основе этого модуля (модуль stack).
* Решить задачу, используя реализованный стек.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Написать программу, работу процессора со стеком. Процессор имеет 4 регистра, обозначенных буквами A, B, C, D. Во входном файле присутствуют операции PUSH и POP. Операция PUSH может иметь в качестве параметра число или регистр. Операция POP в качестве параметра имеет регистр и считывает в него значение с вершины стека.

Также процессор поддерживает арифметические операции со стеком: ADD, MUL, SUB.
Каждая такая операция извлекает из стека два операнда и заносит результат в регистр.

После выполнения последовательности операций программа должна распечатать содержимое регистров.

Входные данные
```
PUSH 1
POP B
```
Выходные данные
```
A = 0
B = 1
C = 0
D = 0
```

Входные данные
```
PUSH 1
PUSH 2
POP B
POP C
PUSH C
POP D
```
Выходные данные
```
A = 0
B = 2
C = 1
D = 1
```

Входные данные
```
PUSH 1
PUSH 2
ADD B
```
Выходные данные
```
A = 0
B = 3
C = 0
D = 0
```

2024-10-29 05:36 UTC, closed without merging