Lab #2 First commit
Dovgalyuk/Algorithms pull request #98
Opened 2020-10-29 11:00 UTC by Znoleg

Случайно удалил стандартные файлы из LibraryCPP, позже всё верну

2020-10-30 08:46 UTC, Dovgalyuk requested changes

2020-10-30 08:46 UTC, Dovgalyuk commented on LibraryIndividual/Individual2.cpp
> +#include "..\..\..\..\..\..\Projects\Algorithms\LibraryCPP\stack.h"
Пути надо настраивать в CMakeLists.txt

2020-10-30 08:46 UTC, Dovgalyuk commented on LibraryIndividual/Individual2.cpp
> +	}
А если такой порядок частиц? + + - -

2020-11-02 05:39 UTC, Dovgalyuk requested changes

2020-11-02 05:39 UTC, Dovgalyuk commented on LibraryIndividual/Individual2.cpp
> +			if (!negative->Empty() && negative->Get() > current.coord)
Координаты упорядочены в файле, сравнивать их смысла нет.

2020-11-02 05:39 UTC, Dovgalyuk commented on LibraryIndividual/Individual2.cpp
> +	Stack* popped = new Stack();
Можно обойтись одним стеком, так как нам не нужны оставшиеся частицы, а интересуют только столкновения.

2020-11-16 09:54 UTC, Dovgalyuk requested changes

2020-11-16 09:54 UTC, Dovgalyuk commented on LibraryIndividual/Individual2.cpp
> +	bool wasPositive = false;
От этой переменной можно избавиться.

2020-11-16 09:54 UTC, Dovgalyuk commented on LibraryIndividual/Individual2.cpp
> +	for (int i = 0; i < n; i++)
Лучше счётчик j из предыдущего цикла взять вместо n.

2020-11-17 05:38 UTC, Dovgalyuk commented
Попробовал собрать:

CMake Error at LibraryIndividual/CMakeLists.txt:2 (add_executable):
  add_executable cannot create target "LibraryIndividual" because another
  target with the same name already exists.  The existing target is an
  executable created in source directory

2020-11-20 09:00 UTC, Dovgalyuk commented
CMake Error at LibraryCPP/CMakeLists.txt:1 (add_library):
  Cannot find source file:

    vector.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: Cannot determine link language for target "LibraryCPP".
CMake Error: CMake can not determine linker language for target: LibraryCPP

2020-11-23 06:40 UTC, Dovgalyuk commented
LibraryIndividual/Individual2.cpp:3:10: fatal error: stack.h: No such file or directory
    3 | #include "stack.h"
      |          ^~~~~~~~~
compilation terminated.

2020-11-30 10:30 UTC, Dovgalyuk commented
/usr/bin/ld: CMakeFiles/LibraryIndividual.dir/Individual2.cpp.o: in function `main':
Individual2.cpp:(.text+0x0): multiple definition of `main'; CMakeFiles/LibraryIndividual.dir/Individual.cpp.o:Individual.cpp:(.text+0x0): first defined here

2020-12-01 06:17 UTC, Dovgalyuk commented
/usr/bin/ld: CMakeFiles/LibraryIndividual.dir/Individual2.cpp.o: in function `main':

Individual2.cpp:(.text+0x81): undefined reference to `Stack::Stack()'

2020-12-01 10:46 UTC, Dovgalyuk commented
/usr/bin/ld: CMakeFiles/LibraryIndividual.dir/Individual2.cpp.o: in function `main':

Individual2.cpp:(.text+0x81): undefined reference to `Stack::Stack()'

2020-12-04 11:41 UTC, Dovgalyuk commented
Та же ошибка.

Стоит попробовать собрать самостоятельно.

2020-12-08 06:08 UTC, Dovgalyuk commented
Надо разобраться со всеми заголовочными файлами.

Пути должны быть в CMakeLists.txt. В .cpp файлах не нужно писать include с относительными путями "../../../ ..."

2020-12-09 10:46 UTC, Znoleg commented
> Надо разобраться со всеми заголовочными файлами.
> 
> Пути должны быть в CMakeLists.txt. В .cpp файлах не нужно писать include с относительными путями "../../../ ..."

Всё ещё не собирается? Всё проверил -  вроде нигде относительных путей нету
Можно ли пока что получить третью лабораторную работу пока разбираюсь со сборкой второй? а то теряется много времени

2020-12-09 11:35 UTC, Dovgalyuk commented
![image](https://user-images.githubusercontent.com/6038023/101624929-c222d700-3a2b-11eb-8f23-aad5f12ab950.png)

было нормально, стало плохо

2020-12-09 12:27 UTC, Dovgalyuk commented
/usr/bin/ld: CMakeFiles/TestStackC.dir/main.cpp.o: in function `main':
main.cpp:(.text+0x20): undefined reference to `Stack::Stack()'
/usr/bin/ld: main.cpp:(.text+0x35): undefined reference to `Stack::Push(int) const'

2020-12-14 05:40 UTC, Dovgalyuk commented
```
4
1 +
2 +
3 -
4 -
```

2020-12-15 05:36 UTC, Dovgalyuk commented
1. Реализовать в проекте Library односвязный список (модуль list) и очередь на основе этого списка (модуль queue).
    2. Решить задачу, используя реализованную очередь.
Во входном файле записан прямоугольный лабиринт. Каждая клетка лабиринта может быть стеной – «#» или пустым пространством – «.». Стартовая позиция обозначается как X, финишная как Y. Написать программу, находящую минимальный путь от стартовой до финишной клетки, если это возможно. За пределы лабиринта выходить нельзя. Использовать поиск в ширину (волновой алгоритм) с реализацией на основе очереди. Если решения нет, вывести IMPOSSIBLE.

Вход
```
######
#...X#
#.####
#...Y#
######
```

Выход
```
######
#xxxX#
#x####
#xxxY#
######
```

Вход
```
######
#...X#
######
#...Y#
######
```

Выход
```
IMPOSSIBLE
```

2020-12-15 05:36 UTC, closed without merging