Develop
Dovgalyuk/Algorithms pull request #982
Opened 2024-10-29 12:42 UTC by AleksArtemiy

Lab1

2024-10-30 03:46 UTC, Dovgalyuk commented
Сборка не проходит.

2024-11-05 09:04 UTC, AleksArtemiy commented
Не подскажите в чем проблема? Не могу разобраться. Пишет, что утечка памяти, но не могу понять где она. Пишет что в ваших тестах

2024-11-06 08:25 UTC, Dovgalyuk commented
Чтобы код можно было смотреть, нужно удалить временные файлы из репозитория.

2024-11-08 11:31 UTC, AleksArtemiy commented
Удалил временные файлы

2024-11-08 13:08 UTC, AleksArtemiy commented
Здравствуйте, можете пожалуйста подсказать, в чем заключается ошибка?

2024-11-11 07:51 UTC, Dovgalyuk requested changes

2024-11-11 07:51 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +        int curSum = (int)(array_get(arr, i) + array_get(arr, i + 1) + array_get(arr, i + 2) + array_get(arr, i + 3) + array_get(arr, i + 4));
Всю сумму нет смысла пересчитывать на каждой итерации. Можно хранить предыдущую сумму, а для получения новой вычитать один старый элемент и добавлять один новый.

2024-11-11 07:51 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +}
А куда девается результат?

2024-11-11 07:51 UTC, Dovgalyuk commented on LibraryCPP/array.cpp
> +    if (!arr) //Проверка на создание массива
new не может вернуть нулевой указатель.

2024-11-11 15:51 UTC, AleksArtemiy commented on LibraryCPP/array.cpp
> +    if (!arr) //Проверка на создание массива
удалил проверку

2024-11-11 15:51 UTC, AleksArtemiy commented on Lab1C/lab1.cpp
> +}
добавлен вывод результата

2024-11-11 15:52 UTC, AleksArtemiy commented on Lab1C/lab1.cpp
> +        int curSum = (int)(array_get(arr, i) + array_get(arr, i + 1) + array_get(arr, i + 2) + array_get(arr, i + 3) + array_get(arr, i + 4));
переделана функция вычисления суммы

2024-11-12 06:53 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +        curSum = curSum - array_get(arr, i - 5) + array_get(arr, i);
На первой итерации будет обращение к -1 элементу массива.

2024-11-12 06:53 UTC, Dovgalyuk commented on LibraryCPP/array.cpp
>      if (!arr->data) { //Проверка на создание даты
Здесь тоже не может быть нулевого указателя.

2024-11-12 09:51 UTC, AleksArtemiy commented on LibraryCPP/array.cpp
>      if (!arr->data) { //Проверка на создание даты
Удалил проверку на нулевой размер

2024-11-15 04:33 UTC, Dovgalyuk commented on LibraryCPP/array.cpp
>      if (!arr->data) { //Проверка на создание даты
Проверка осталась.

2024-11-15 04:34 UTC, Dovgalyuk commented on LibraryCPP/array.cpp
>      if (!arr->data) { //Проверка на создание даты
Всё ещё осталась.

2024-11-15 04:34 UTC, Dovgalyuk commented on Lab1C/lab1.cpp
> +}
Пример:
1 1 1 1 1 2 2 2 2 2

2024-11-18 11:57 UTC, AleksArtemiy commented on Lab1C/lab1.cpp
> +}
Исправил количество проверяемых элементов в цикле

2024-11-19 04:25 UTC, Dovgalyuk commented
Принято.

* Реализовать в проекте Library односвязный список (модуль list) и стек на основе этого списка (модуль stack).
* Решить задачу, используя реализованный стек.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Реализовать интерпретатор подмножества языка Befunge: https://en.wikipedia.org/wiki/Befunge
Программа читает входную строку из следующих команд:
* 0-9 - заносит число в стек
* +-*/% - арифметические операции. Извлекают два числа из стека, а потом заносят туда результат
* ! - логическое "не". Извлекает значение с вершины стека и заносит туда 1, если это был 0. Иначе заносит в стек 0.
* ` - логическое "больше". Извлекает два значения из стека и заносит обратно 1, если первое больше второго и 0 в противном случае.
* : - дублирует значение на вершине стека.
* . - извлекает значение из стека и выводит его.
* & - запрашивает число с клавиатуры и заносит его в стек.

Входные данные
```
123...
```
Выходные данные
```
3
2
1
```

Входные данные
```
1:.2:.3:.++.
```
Выходные данные
```
1
2
3
6
```

2024-11-19 04:25 UTC, closed without merging