Lab3
Dovgalyuk/Algorithms pull request #983
Opened 2024-10-29 15:32 UTC by BRUHcha

Принято.

-    Реализовать в проекте Library модуль vector для массива переменного размера и очередь на основе этого модуля (модуль queue). Массив расширяется, если в очереди становится слишком много элементов.
-    Решить задачу, используя реализованную очередь.
-    Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.

Задано начальное вещество и список химических реакций, в которых оно превращается в другое вещество. Написать программу, использующую поиск в ширину, и выводящую список веществ, которые можно получить из исходного.

2024-10-29 15:37 UTC, BRUHcha commented
что в голове было написал в векторе, не совсем понимаю как можно сделать так чтобы resize работал O(1) и при этом новые элементы были заполнены нормально без мусора

2024-10-30 03:56 UTC, Dovgalyuk commented
Вот тут есть разбор: https://ru.algorithmica.org/cs/basic-structures/vector/

2024-12-19 05:58 UTC, Dovgalyuk commented on CMakeLists.txt
> +add_subdirectory(Lab2CPP)
Нужно добавить сборку и тестирование 3 работы.

2024-12-20 06:24 UTC, Dovgalyuk requested changes

2024-12-20 06:24 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +    vector_resize(queue->vector, vector_size(queue->vector) + 1);
Нужно реализовать кольцевой буфер. resize не нужен, когда в начале массива уже освободилось место.

2024-12-23 09:18 UTC, Dovgalyuk requested changes

2024-12-23 09:18 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +vector<Data> bfs(Data start, unordered_map<Data, vector<Data>>& graph) {
typedef для неоднократно используемых типов всё ещё нужны.

2024-12-23 09:18 UTC, Dovgalyuk commented on LibraryCPP/queue.cpp
> +    size_t last;
last можно вычислять на основе first и size.

2024-12-25 05:44 UTC, Dovgalyuk commented on Lab3CPP/lab3.cpp
> +vector<Data> bfs(Data start, Graph& graph) {
```vector<Data>``` тоже несколько раз используется

2024-12-26 06:18 UTC, Dovgalyuk commented on Lab3CPP/lab3.h
>  vector<char> task(ifstream& input, int reactions);
А тут почему другие типы?

2025-01-20 06:04 UTC, Dovgalyuk commented
Принято.

2025-01-20 06:04 UTC, closed without merging