Lab3
Dovgalyuk/Algorithms pull request #992
Opened 2024-11-02 11:31 UTC by larkes-cyber

2024-11-05 05:26 UTC, Dovgalyuk commented
А где тест для списка?

2024-11-06 07:54 UTC, Dovgalyuk requested changes

2024-11-06 07:54 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +struct ListItem {
Это не кольцевой двусвязный список.

2024-11-07 05:32 UTC, Dovgalyuk requested changes

2024-11-07 05:32 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    if (item == list->head)
Логично поставить это в начало функции.

2024-11-08 05:54 UTC, Dovgalyuk requested changes

2024-11-08 05:54 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    ListItem* new_item = new ListItem;
Тут будет утечка памяти, если список пустой.

2024-11-11 05:38 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    if (!list->head){
Эта проверка никогда не сработает.

2024-11-12 06:43 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    ListItem* new_item = new ListItem;
Это замечание осталось.

2024-11-12 17:49 UTC, larkes-cyber commented
в последнем комите скорее всего пофиксил, проблема была в инициализации ListItem даже при пустом списке

2024-11-13 11:45 UTC, Dovgalyuk commented on LibraryCPP/list.cpp
> +    if(!list->head){
Чему будет равен item, если head==nullptr?

2024-11-14 06:09 UTC, Dovgalyuk commented
Временные файлы не нужно добавлять в репозиторий.

2024-11-15 04:38 UTC, Dovgalyuk commented
Принято.
Следующее задание после защиты.

2024-11-15 04:38 UTC, closed without merging

2024-11-20 05:58 UTC, larkes-cyber commented
Можно следующее задание?

2024-11-20 07:13 UTC, Dovgalyuk commented
Принято.

* Разработать программный интерфейс модуля (заголовки функций) библиотеки LibraryCPPTemplate для работы с ориентированными графами. Граф должен инициализироваться количеством вершин. В нем должна быть поддержка следующих операций: добавить вершину, добавить ребро (между заданными вершинами), удалить вершину, удалить ребро, проверить существует ли ребро между вершинами, задать/считать пометку для ребра, задать/считать пометку для вершины,
получить пометки всех вершин в виде вектора.
* Должна быть реализована структура-итератор для поддержки перебора всех соседей заданной вершины.
* Реализовать в библиотеке Library модуль поддержки графов с разработанным интерфейсом. Связи должны храниться в виде списков смежности в контейнере List библиотеки LibraryCPPTemplate.
* Разработать и добавить в проект LibraryCPPTemplate программу, тестирующую работу библиотеки для графа.
* Добавить в решение проект, использующий графы. Программа должна считывать параметры графа и искать для него все длины кратчайших путей алгоритмом Флойда.
* Добавить пример входных данных и описать тест в CMakeLists.txt, который запускает разработанную программу и использует входные данные.